### ISSUE TITLE
Error When downloading chain: Async operation failed

### ISSUE THREAD

**Issue by eum602** [hyperledger/besu#1053]
### Description
I am trying to synchronize a new node (besu 1.4.4) in a long working IBFT network . For some reason the synchronization starts to fail at some block number (9701521). This node behavior does not affect the network. When I checked the content on that block I saw it looks as any other block. nothing special. I have tried on different instance machines but the error persist.
This issue is similar to #992 but after checking the printed logs I see the cause of  this issue is different.

### Steps to Reproduce (Bug)
1. synchronize a new node using Besu 1.4.4

**Actual behavior:

**Frequency:
Always when trying to synchronize from the first block.

### Versions (Add all that apply)
* Software version: 1.4.4, 1.4.1
* Java version: 11
* OS Name & Version: Ubuntu 18.04
* Kernel Version: 5.0.0-1025-gcp

### Additional Information
_**Info messages shows the node stack trying to download the chain:**_
Info messages:
2020-06-05T16:29:01.178+0000 INFO Found common ancestor with peer 0x55296094e38b96070d... at block 9701521
2020-06-05T16:29:28.944+0000 INFO Found common ancestor with peer 0x55296094e38b96070d... at block 9701521
2020-06-05T16:29:56.459+0000 INFO Found common ancestor with peer 0xeda7578e00354b3d19... at block 9701521

**_Info in trace:_**
2020-06-05T15:41:05.487+0000 TRACE Writing org.hyperledger.besu.ethereum.p2p.rlpx.wire.messages.PongMessage@27a881bf to PeerInfo{version=5, clientId='pantheon/v1.2.0/linux-x86_64/oracle-java-11', capabilities=[eth/62, eth/63, IBF/1], port=60606, nodeId=0x5c9f15c4a4f57eeb1dc8472875545f6bf2da37ca632c9b21895b355eb92f2322c627676aba31aa9bdad64b42c74611a943e2b16030e44bf012a100066e99738e} via protocol null
2020-06-05T15:41:05.500+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.504+0000 TRACE Process message eth/64, 7
2020-06-05T15:41:05.505+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.505+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.507+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.511+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.513+0000 TRACE Process message eth/64, 7
2020-06-05T15:41:05.514+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.529+0000 TRACE Process message eth/64, 7
2020-06-05T15:41:05.551+0000 TRACE Process message eth/64, 7
2020-06-05T15:41:05.553+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.556+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.566+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.569+0000 TRACE Process message eth/64, 7
2020-06-05T15:41:05.572+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.574+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.576+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.585+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.617+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.622+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.659+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.659+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.661+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.675+0000 TRACE Process message eth/63, 4
2020-06-05T15:41:05.676+0000 TRACE **Interrupted while waiting for processing to complete
java.lang.InterruptedException: null**
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.processNextInput(AsyncOperationProcessor.java:64) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-06-05T15:41:05.731+0000 TRACE Process message eth/63, 4
2020-06-05T15:41:05.737+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.737+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.738+0000 TRACE Writing org.hyperledger.besu.ethereum.eth.messages.GetBlockHeadersMessage@7b46759e to PeerInfo{version=5, clientId='besu/v1.4.1/linux-x86_64/oracle-java-11', capabilities=[eth/62, eth/63, eth/64, IBF/1], port=60606, nodeId=0x34f9c86d2b2563ccd10adf73a09a368bc12fd39bac4a24794ac644b33bff2a6e05e50fc757b75b0058b0ced49e097acafe7e6fcfe5596e4ab1a4a44b90f96c9e} via protocol eth/64
2020-06-05T15:41:05.758+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:05.790+0000 TRACE Process message eth/64, 4
2020-06-05T15:41:05.791+0000 TRACE Interrupted while waiting for processing to complete
java.lang.InterruptedException: null
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.processNextInput(AsyncOperationProcessor.java:64) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-06-05T15:41:06.008+0000 TRACE Process message eth/63, 4
2020-06-05T15:41:06.013+0000 TRACE Process message eth/63, 7
2020-06-05T15:41:06.014+0000 TRACE Writing org.hyperledger.besu.ethereum.eth.messages.GetBlockHeadersMessage@2dd17cba to PeerInfo{version=5, clientId='besu/v1.4.1/linux-x86_64/oracle-java-11', capabilities=[eth/62, eth/63, eth/64, IBF/1], port=60606, nodeId=0x30d446025516c6f016b578f89a4024a37a9da98f671470b0b281c8bfab1ebfac327d615cd998a95682830d15dbc736a1e367e132c6d988b28c2208575893b241} via protocol eth/64

...
...

2020-06-05T17:25:51.967+0000 **TRACE Interrupted while waiting to add to output
java.lang.InterruptedException: null**
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
	at java.util.concurrent.ArrayBlockingQueue.offer(ArrayBlockingQueue.java:393) ~[?:?]
	at org.hyperledger.besu.services.pipeline.Pipe.put(Pipe.java:129) ~[besu-pipeline-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.services.pipeline.IteratorSourceStage.run(IteratorSourceStage.java:35) ~[besu-pipeline-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.4.jar:1.4.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**_Info on Debug_**

Idle connection detected, sending Wire PING to peer.
2020-06-05T15:53:45.610+0000 DEBUG Received Wire PONG
2020-06-05T15:53:46.857+0000 DEBUG **Timed out while waiting for response from peer 0x26c79b1c307a40b14f...**
2020-06-05T15:53:46.858+0000 DEBUG Disconnection triggered by repeated timeouts
2020-06-05T15:53:46.858+0000 DEBUG Disconnecting (0x0b TIMEOUT) from PeerInfo{version=5, clientId='besu/v1.4.4/linux-x86_64/oracle-java-11', capabilities=[eth/62, eth/63, eth/64, IBF/1], port=60606, nodeId=0x26c79b1c307a40b14f86a020590703aa60ecd20c5faca9ddfc2a2513a25c1976c3fb37dadecc18162134e408d17ae9421b22dd30f09600f288a1ce8cc37a7b29}
2020-06-05T15:53:46.858+0000 DEBUG **Disconnecting from peer (0x0b TIMEOUT), 36 peers left:** EthPeers{connections=0xf5914e42ca15720bfd...,0x3fdbade61613b09a57...,0x97739e4076548d3c46...,0xbab57c4deb7c9ec3ac...,0xcb24877f329e0e3fff...,0x5db9a9089653b81622...,0x12517e300824d5b39d...,0xf40953a282f0da4ba0...,0xbaba6273a695ee3583...,0x08d08462047df9655e...,0x34f9c86d2b2563ccd1...,0xda81e2bfa67574b075...,0x916b8cc76db4a19035...,0x3632c7f222fcb4af11...,0x5c9f15c4a4f57eeb1d...,0x96e6c5d10b044361da...,0xfa83941b3a21b2288d...,0x8635fd0a08fd9721ae...,0x0cc0df50c350c8b8b6...,0x2c98c25d95c8354a05...,0x30d446025516c6f016...,0xfead4eeea1f1cce8bf...,0x681b635336ad10ad2e...,0xccfe32fc60a8584316...,0xffbb4795b564348fb4...,0x8a9ae10f01e212d98c...,0x3fdf2cc9c08dc4cd8a...,0x55296094e38b96070d...,0x2e84e50c18ccc4e7fd...,0xb436cbdfd9242859e1...,0xeda7578e00354b3d19...,0x8e16519f6b4645520b...,0xc992a0d9009454b9a3...,0x2ca1d413d5ebc055e0...,0x4cd3c6452ce1d5ef5a...,0xd9bb698a2b56909f3e...}
2020-06-05T15:53:46.858+0000 DEBUG **Retrying after recoverable failure from peer task CompleteBlocksTask: Timeout after 5000 MILLISECONDS**

....
....

2020-06-05T15:57:04.366+0000 DEBUG **Disconnecting (0x10 SUBPROTOCOL_TRIGGERED)** from PeerInfo{version=5, clientId='besu/v1.4.4/linux-x86_64/openjdk-java-11', capabilities=[eth/62, eth/63, eth/64, IBF/1], port=60606, nodeId=0xcd62282fde774af30fe1de20826fe017121d1e1173a1749b73d38e943821d3e22dcd2f7e52fbfc33992b2e077f0191552cb33ec3cbca28283ae80c1c84ad3ea1}
2020-06-05T15:57:04.366+0000 DEBUG Disconnecting from peer (0x10 SUBPROTOCOL_TRIGGERED), 36 peers left: EthPeers{connections=0xf5914e42ca15720bfd...,0x3fdbade61613b09a57...,0x97739e4076548d3c46...,0xbab57c4deb7c9ec3ac...,0x26c79b1c307a40b14f...,0xcb24877f329e0e3fff...,0x8e16519f6b4645520b...,0x12517e300824d5b39d...,0xeda7578e00354b3d19...,0xbaba6273a695ee3583...,0xc992a0d9009454b9a3...,0xf40953a282f0da4ba0...,0x08d08462047df9655e...,0x34f9c86d2b2563ccd1...,0x916b8cc76db4a19035...,0x3632c7f222fcb4af11...,0x5c9f15c4a4f57eeb1d...,0x96e6c5d10b044361da...,0xd9bb698a2b56909f3e...,0xfa83941b3a21b2288d...,0x8635fd0a08fd9721ae...,0x2c98c25d95c8354a05...,0x30d446025516c6f016...,0x55296094e38b96070d...,0xfead4eeea1f1cce8bf...,0x681b635336ad10ad2e...,0xccfe32fc60a8584316...,0xffbb4795b564348fb4...,0x8a9ae10f01e212d98c...,0x3fdf2cc9c08dc4cd8a...,0x2e84e50c18ccc4e7fd...,0xb436cbdfd9242859e1...,0x0cc0df50c350c8b8b6...,0x2ca1d413d5ebc055e0...,0x4cd3c6452ce1d5ef5a...,0xda81e2bfa67574b075...}
2020-06-05T15:57:04.367+0000 DEBUG Received Wire DISCONNECT (SUBPROTOCOL_TRIGGERED) from peer: PeerInfo{version=5, clientId='besu/v1.4.4/linux-x86_64/openjdk-java-11', capabilities=[eth/62, eth/63, eth/64, IBF/1], port=60606, nodeId=0xcd62282fde774af30fe1de20826fe017121d1e1173a1749b73d38e943821d3e22dcd2f7e52fbfc33992b2e077f0191552cb33ec3cbca28283ae80c1c84ad3ea1}

....
....

2020-06-05T16:01:40.718+0000 DEBUG Timed out while waiting for response from peer 0xfead4eeea1f1cce8bf...
2020-06-05T16:01:40.718+0000 DEBUG Retrying after recoverable failure from peer task CompleteBlocksTask: Timeout after 5000 MILLISECONDS
2020-06-05T16:01:41.718+0000 DEBUG Unhandled exception in pipeline. Aborting.
java.lang.RuntimeException: **Async operation failed.** org.hyperledger.besu.ethereum.eth.manager.exceptions.**MaxRetriesReachedException**: Task failed: MAX_RETRIES_REACHED
	at org.hyperledger.besu.services.pipeline.**AsyncOperationProcessor.outputNextCompletedTask**(AsyncOperationProcessor.java:86) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.processNextInput(AsyncOperationProcessor.java:64) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
**Caused by: java.util.concurrent.ExecutionException:** org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: **Task failed: MAX_RETRIES_REACHED**
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81) ~[besu-pipeline-1.4.1.jar:1.4.1]
	... 8 more
Caused by: org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractRetryingPeerTask.executeTask(AbstractRetryingPeerTask.java:81) ~[besu-eth-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:155) ~[besu-eth-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleFutureTask$4(EthScheduler.java:152) ~[besu-eth-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	... 3 more
2020-06-05T16:01:41.719+0000 DEBUG **Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Async operation failed.** org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: **Task failed: MAX_RETRIES_REACHED**
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: Async operation failed. org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:86) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.processNextInput(AsyncOperationProcessor.java:64) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.1.jar:1.4.1]
	... 5 more
Caused by: java.util.concurrent.ExecutionException: org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~[?:?]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.processNextInput(AsyncOperationProcessor.java:64) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38) ~[besu-pipeline-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130) ~[besu-pipeline-1.4.1.jar:1.4.1]
	... 5 more
Caused by: org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractRetryingPeerTask.executeTask(AbstractRetryingPeerTask.java:81) ~[besu-eth-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:155) ~[besu-eth-1.4.1.jar:1.4.1]
	at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleFutureTask$4(EthScheduler.java:152) ~[besu-eth-1.4.1.jar:1.4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	... 3 more
2020-06-05T16:01:43.721+0000 DEBUG Searching for common ancestor with 0x0cc0df50c350c8b8b6... between 0 and 9701521
2020-06-05T16:01:43.721+0000 DEBUG Requesting 200 headers from peer 0x0cc0df50c350c8b8b6....

**Comment by shemnon** [comment]
LACChain correct?  We will need to get a second peer added to try and do deep debugging.  I'm concerned the bug may be on the peer side not the local side.  Either that header causes weird things in the wire protocol or generation of the message for that header has issues.

**Comment by eum602** [comment]
Sure @shemnon please let me know when you are ready to add your node to  the permissioning network. Or any help you need.

**Comment by eum602** [comment]
I have just confirmed the issue is also happening in past versions like 1.3.6. Also The problem happens around 9701xxx and not specifically at some block. IMO it is independent of the version.

**Comment by eum602** [comment]
After many hours of looping in errors the node suddenly started to synchronize. I don't think the problem is solved, just want to add more details about this issue.

**2020-06-07T02:26**:40.280+0000 INFO Found common ancestor with peer 0x3632c7f222fcb4af11... at block 9701534
...
...
**2020-06-07T11:53**:03.626+0000 INFO Found common ancestor with peer 0x26c79b1c307a40b14f... at block 9701534
...
...
**2020-06-07T12:54**:54.491+0000 INFO Found common ancestor with peer 0x9636ad55b62cd519bc... at block 9701534
2020-06-07T12:55:11.754+0000 **INFO Import reached block** 9701600
2020-06-07T12:55:20.379+0000 INFO Import reached block 9701800

...

**Comment by matkt** [comment]
We have just added a fix to solve the issue and we tested it on the LACChain network. You can now synchronize completely with the version of Besu available in the master. Or you can wait for the next release which will integrate it. Feel free to reopen the ticket if you still have the issue
