### ISSUE TITLE
Error message when trying to use port that is already in use

### ISSUE THREAD

**Issue by MariusVanDerWijden** [hyperledger/besu#1064]
### Description
As a User I want to see an appropriate error message so that I can act on it 

### Acceptance Criteria
* Error message is understandable when starting a node while the port 30303 is already in use.

### Steps to Reproduce (Bug)
1. ./bin/besu  --network=YOLO_V1 --Xberlin-enabled=true in one terminal
2. ./bin/besu  --network=YOLO_V1 --Xberlin-enabled=true in second terminal

**Expected behavior:** 
Produce an error message that explains that I'm trying to use a port twice and how I could change the listening port.
**Actual behavior:** [What actually happens]
```
2020-06-10 12:36:41.583+02:00 | nioEventLoopGroup-2-1 | ERROR | RlpxAgent | Failed to start P2P RLPx agent.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unable start listening on 0.0.0.0:30303. Check for port conflicts.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.NettyConnectionInitializer.lambda$start$0(NettyConnectionInitializer.java:117) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalStateException: Unable start listening on 0.0.0.0:30303. Check for port conflicts.
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.NettyConnectionInitializer.lambda$start$0(NettyConnectionInitializer.java:118) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	... 21 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:479) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:468) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220) ~[?:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	... 13 more
2020-06-10 12:36:41.595+02:00 | main | ERROR | Runner | Startup failed
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unable start listening on 0.0.0.0:30303. Check for port conflicts.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.NettyConnectionInitializer.lambda$start$0(NettyConnectionInitializer.java:117) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
Caused by: java.lang.IllegalStateException: Unable start listening on 0.0.0.0:30303. Check for port conflicts.
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.NettyConnectionInitializer.lambda$start$0(NettyConnectionInitializer.java:118) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	... 21 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:479) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:468) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220) ~[?:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	... 13 more
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unable start listening on 0.0.0.0:30303. Check for port conflicts.

To display full help:
besu [COMMAND] --help
2020-06-10 12:37:11.602+02:00 | Thread-1 | ERROR | AbstractMinerExecutor | Failed to shutdown CliqueMinerExecutor.
2020-06-10 12:37:11.604+02:00 | Thread-1 | INFO  | NetworkRunner | Stopping Network.
2020-06-10 12:37:11.614+02:00 | Thread-1 | ERROR | rejectedExecution | Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:981) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:388) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:381) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:880) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.NettyConnectionInitializer.stop(NettyConnectionInitializer.java:142) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at org.hyperledger.besu.ethereum.p2p.rlpx.RlpxAgent.stop(RlpxAgent.java:148) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at org.hyperledger.besu.ethereum.p2p.network.DefaultP2PNetwork.stop(DefaultP2PNetwork.java:240) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.stop(NetworkRunner.java:89) ~[besu-p2p-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at org.hyperledger.besu.Runner.stop(Runner.java:145) ~[besu-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at org.hyperledger.besu.Runner.close(Runner.java:166) ~[besu-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at org.hyperledger.besu.cli.BesuCommand.lambda$addShutdownHook$9(BesuCommand.java:1971) ~[besu-1.4.7-SNAPSHOT.jar:1.4.7-dev-4523d591]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2020-06-10 12:37:11.616+02:00 | Thread-1 | INFO  | EthProtocolManager | Stopping eth Subprotocol.
2020-06-10 12:38:11.617+02:00 | Thread-1 | ERROR | DefaultP2PNetwork | DefaultP2PNetwork did not shutdown cleanly: some internal services failed to fully terminate.
2020-06-10 12:38:11.618+02:00 | Thread-1 | INFO  | EthProtocolManager | eth Subprotocol stopped.
2020-06-10 12:38:11.618+02:00 | Thread-1 | INFO  | NetworkRunner | Network stopped.
2020-06-10 12:38:11.618+02:00 | Thread-1 | INFO  | AutoTransactionLogBloomCachingService | Shutting down Auto transaction logs caching service.
2020-06-10 12:38:11.619+02:00 | Thread-1 | INFO  | NatService | No NAT environment detected so no service could be stopped
```
**Frequency:** Always

### Versions (Add all that apply)
* Software version: develop
* Java version: jdk-14-openjdk

**Comment by jaeheonshim** [comment]
I can tackle this tomorrow in the morning

**Comment by MadelineMurray** [comment]
@MariusVanDerWijden - this should be resolved by #1160.  Let me know if you're still seeing this issue otherwise I'll close this issue at the end of the week.

**Comment by MariusVanDerWijden** [comment]
Looks good, thanks!

**Comment by TrishamBP** [comment]
Hi, where was this issue solved and how can we fix it?

**Comment by macfarla** [comment]
👋  @TrishamBP the logging was clarified in https://github.com/hyperledger/besu/pull/1160
Hopefully that helps if you've got conflicts in your port setup! If you're having issues, please open a new github issue or ask questions in https://chat.hyperledger.org/channel/besu
