### ISSUE TITLE
eth_getLogs rejecting integer parameters

### ISSUE THREAD

**Issue by epiccoolguy** [hyperledger/besu#1088]
### Description
The RPC call `eth_getLogs` should accept integer values for parameter `fromBlock` (and `toBlock`) as defined here: https://eth.wiki/json-rpc/API#eth_getlogs

`eth_getLogs` currently returns "Invalid Params" using both ws and http with fromBlock as integer. Casting the integer value to string returns the logs as expected.

I came across this issue when web3.js [automatically retrieved past events](https://github.com/ethereum/web3.js/blob/bd37b9171889c2c2d9789134598f3d1777a92560/packages/web3-core-subscriptions/src/subscription.js#L241) on event subscription creation with a given (integer) fromBlock.

### Acceptance Criteria
* `eth_getLogs` accepts integer type parameters where appropriate.

### Steps to Reproduce (Bug)
WebSockets using [wscat](https://github.com/websockets/wscat):
```
miguel@Miguels-MBP ~ % npx wscat --connect localhost:8546
npx: installed 11 in 0.852s
Connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","id":220,"method":"eth_getLogs","params":[{"address":"0xaa8194af7c69df638a5ea7e82c4421b49223c821","topics":[],"fromBlock":1168}]}
< {"jsonrpc":"2.0","id":220,"error":{"code":-32602,"message":"Invalid params"}}
> {"jsonrpc":"2.0","id":220,"method":"eth_getLogs","params":[{"address":"0xaa8194af7c69df638a5ea7e82c4421b49223c821","topics":[],"fromBlock":"1168"}]}
< {"jsonrpc":"2.0","id":220,"result":[{"logIndex":"0x0","removed":false,"blockNumber":"0x1c1d3","blockHash":"0xbfd6b14ed90eb206b3b7bdc8fa49a3695148861b06e0c5b97631466 ...
```
Using the Postman collection gives the same results on HTTP: https://besu.hyperledger.org/en/stable/Reference/API-Methods/

**Expected behavior:**
Logs (or empty array) to be returned.

**Actual behavior:**
Error response:
```
{"jsonrpc":"2.0","id":220,"error":{"code":-32602,"message":"Invalid params"}}
```
Relevant logs on DEBUG level:
```
2020-06-16 12:47:30.941+00:00 | vert.x-eventloop-thread-0 | DEBUG | WebSocketService | Received Websocket request {"jsonrpc":"2.0","id":220,"method":"eth_getLogs","params":[{"address":"0xaa8194af7c69df638a5ea7e82c4421b49223c821","topics":[],"fromBlock":1168}]} (host=10.24.0.22, port=59958)
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-13 | DEBUG | WebSocketRequestHandler | WS-RPC request -> eth_unsubscribe
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-7 | DEBUG | SubscriptionManager | Subscribe request SubscribeRequest{subscriptionType=LOGS, includeTransaction=null, filterParameter=FilterParameter{fromBlock=BlockParameter{type=LATEST, number=OptionalLong.empty}, toBlock=BlockParameter{type=LATEST, number=OptionalLong.empty}, addresses=[0x9e9ae90b6cd198de531a8ddf5edbefb57af96c57], topics=[], blockHash=Optional.empty}, connectionId=__vertx.ws.d3415f5d-fc0a-4ef9-8b94-ee8b285ef3a6}
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-13 | DEBUG | SubscriptionManager | Unsubscribe request subscriptionId = 2640
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-19 | DEBUG | WebSocketRequestHandler | WS-RPC request -> eth_getLogs
2020-06-16 12:47:30.941+00:00 | vert.x-eventloop-thread-0 | DEBUG | WebSocketService | Received Websocket request {"jsonrpc":"2.0","id":221,"method":"eth_subscribe","params":["logs",{"address":"0xaa8194af7c69df638a5ea7e82c4421b49223c821","topics":[]}]} (host=10.24.0.22, port=59958)
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-5 | DEBUG | WebSocketRequestHandler | WS-RPC request -> eth_subscribe
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-5 | DEBUG | SubscriptionManager | Subscribe request SubscribeRequest{subscriptionType=LOGS, includeTransaction=null, filterParameter=FilterParameter{fromBlock=BlockParameter{type=LATEST, number=OptionalLong.empty}, toBlock=BlockParameter{type=LATEST, number=OptionalLong.empty}, addresses=[0xaa8194af7c69df638a5ea7e82c4421b49223c821], topics=[], blockHash=Optional.empty}, connectionId=__vertx.ws.d3415f5d-fc0a-4ef9-8b94-ee8b285ef3a6}
2020-06-16 12:47:30.941+00:00 | vert.x-worker-thread-19 | DEBUG | WebSocketRequestHandler | Invalid Params
org.hyperledger.besu.ethereum.api.jsonrpc.internal.exception.InvalidJsonRpcParameters: Invalid json rpc parameter at index 0
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter.optional(JsonRpcParameter.java:74) ~[besu-api-1.4.5.jar:1.4.5]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter.required(JsonRpcParameter.java:39) ~[besu-api-1.4.5.jar:1.4.5]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.JsonRpcRequest.getRequiredParameter(JsonRpcRequest.java:133) ~[besu-api-1.4.5.jar:1.4.5]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.JsonRpcRequestContext.getRequiredParameter(JsonRpcRequestContext.java:49) ~[besu-api-1.4.5.jar:1.4.5]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:45) ~[besu-api-1.4.5.jar:1.4.5]
	at org.hyperledger.besu.ethereum.api.jsonrpc.websocket.WebSocketRequestHandler.lambda$handle$0(WebSocketRequestHandler.java:82) ~[besu-api-1.4.5.jar:1.4.5]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.BlockParameter` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1168)
 at [Source: (String)"{"address":"0xaa8194af7c69df638a5ea7e82c4421b49223c821","topics":[],"fromBlock":1168}"; line: 1, column: 81] (through reference chain: org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.FilterParameter["fromBlock"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1451) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1081) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:262) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:356) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1347) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1310) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4482) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434) ~[jackson-databind-2.11.0.jar:2.11.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3402) ~[jackson-databind-2.11.0.jar:2.11.0]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter.optional(JsonRpcParameter.java:72) ~[besu-api-1.4.5.jar:1.4.5]
	... 10 more
```

**Frequency:**
100%

### Versions
* Software version:
```
besu/v1.4.5/linux-x86_64/oracle_openjdk-java-11
```
* Java version:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode, sharing)
```
* OS Name & Version:
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
* Kernel Version:
```Linux blockchain-6df777585c-rwjq5 4.19.107 #1 SMP Thu May 28 15:07:17 PDT 2020 x86_64 GNU/Linux
```
* Virtual Machine software & version:
```
hyperkit: 0.20200224
minikube: v1.11.0
kubernetes v1.18.3
```
* Docker Version:
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Additional Information

Haven't encountered this on other Ethereum clients.

**Comment by RatanRSur** [comment]
Unless I'm misreading it, I don't believe the spec calls for support for numbers in the form `1111` (implying decimal) but only for `Quantity`s of the form `0x457`

**Comment by RatanRSur** [comment]
Unless I'm reading the spec wrong, I believe you need to use numerals formatted as hex `Quantity`s. `0x` prefixed.

**Comment by epiccoolguy** [comment]
Hi @RatanRSur, thanks for the quick reply! Just read the part you mentioned 😅 : https://eth.wiki/json-rpc/API#hex-value-encoding

This seems like something that's usually formatted by web3.js, but isn't happening in this case. Will have a closer look at their implementation to see what's going on.

**Comment by RatanRSur** [comment]
No problem :) Closing for now, feel free to reopen if it's something deeper than that.
