### ISSUE TITLE
Threads blocked on `org.rocksdb.RocksDB.get(Native Method)`

### ISSUE THREAD

**Issue by roderik** [hyperledger/besu#1114]
### Description

I'm running an ibft network (started at v 1.4.2, upgraded to 1.4.6) on with nodes in GKE and AKS. 
In each cloud provider, we run 1 validator, and 2 rpc nodes.

<details>
<summary>Network config:</summary>
```
{
  "alloc": {
    "0x41bEA720b87EE046F9B8d7eEc737ca702e3073e7": {
      "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "chainId": 45124,
    "constantinoplefixblock": 0,
    "contractSizeLimit": 2147483647,
    "evmStackSize": 2048,
    "ibft2": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 10
    }
  },
  "difficulty": "0x1",
  "extraData": "0xf83ea00000000000000000000000000000000000000000000000000000000000000000d59441bea720b87ee046f9b8d7eec737ca702e3073e7808400000000c0",
  "gasLimit": "0x1fffffffffffff",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "nonce": "0x0",
  "timestamp": "0x0"
}
```
</details>

We sent a bunch of transactions and overloaded the rpc nodes in some way. 
We saw OOM errors (both in Besu and in k8s) so we increased memory (5g) and cpu limits (4cpu) and the Xmx and Xms settings to 4g.

The validators never failed in any way.

On some nodes we deleted the DB and synced again, on others de did not.

All nodes after a restart/recreate boot, resync and follow the chain for a short while. Then they start failing with: 

```
2020-06-18T15:24:33.675489427Z 2020-06-18 15:24:33.673+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-19,5,main]=Thread[vert.x-worker-thread-19,5,main] has been blocked for 805883 ms, time limit is 60000 ms
2020-06-18T15:24:33.675525157Z io.vertx.core.VertxException: Thread blocked
2020-06-18T15:24:33.675532272Z 	at org.rocksdb.RocksDB.get(Native Method) ~[rocksdbjni-6.4.6.jar:?]
2020-06-18T15:24:33.675538854Z 	at org.rocksdb.RocksDB.get(RocksDB.java:1721) ~[rocksdbjni-6.4.6.jar:?]
2020-06-18T15:24:33.675544948Z 	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:155) ~[besu-plugin-rocksdb-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675551439Z 	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:62) ~[besu-plugin-rocksdb-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.67555785Z 	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.get(SegmentedKeyValueStorageAdapter.java:50) ~[besu-kvstore-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.67556437Z 	at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage.getTrieNode(WorldStateKeyValueStorage.java:69) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675570524Z 	at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage.getAccountStorageTrieNode(WorldStateKeyValueStorage.java:62) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.67557631Z 	at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState$$Lambda$1165/0x0000000840663040.getNode(Unknown Source) ~[?:?]
2020-06-18T15:24:33.675581786Z 	at org.hyperledger.besu.ethereum.trie.StoredNodeFactory.retrieve(StoredNodeFactory.java:95) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675587366Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:106) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675592804Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:50) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675598964Z 	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675604822Z 	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675610835Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675617724Z 	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675634108Z 	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675639709Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675653645Z 	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675659094Z 	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675664492Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675669787Z 	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.67567489Z 	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675680098Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675685196Z 	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675690655Z 	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675695989Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675701366Z 	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675706494Z 	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675711589Z 	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675717025Z 	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:80) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675722474Z 	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:35) ~[besu-trie-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675727717Z 	at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState$WorldStateAccount.getStorageValue(DefaultMutableWorldState.java:292) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675733122Z 	at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater$UpdateTrackingAccount.getStorageValue(AbstractWorldUpdater.java:340) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675738191Z 	at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater$UpdateTrackingAccount.getStorageValue(AbstractWorldUpdater.java:340) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675742887Z 	at org.hyperledger.besu.ethereum.core.AbstractWorldUpdater$UpdateTrackingAccount.getStorageValue(AbstractWorldUpdater.java:340) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.67574801Z 	at org.hyperledger.besu.ethereum.vm.operations.SLoadOperation.execute(SLoadOperation.java:44) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675758046Z 	at org.hyperledger.besu.ethereum.vm.EVM.lambda$executeNextOperation$0(EVM.java:82) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675763052Z 	at org.hyperledger.besu.ethereum.vm.EVM$$Lambda$1162/0x0000000840664440.execute(Unknown Source) ~[?:?]
2020-06-18T15:24:33.675768075Z 	at org.hyperledger.besu.ethereum.vm.OperationTracer.lambda$static$0(OperationTracer.java:27) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675773259Z 	at org.hyperledger.besu.ethereum.vm.OperationTracer$$Lambda$1156/0x0000000840665c40.traceExecution(Unknown Source) ~[?:?]
2020-06-18T15:24:33.675793183Z 	at org.hyperledger.besu.ethereum.vm.EVM.executeNextOperation(EVM.java:75) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675800948Z 	at org.hyperledger.besu.ethereum.vm.EVM.runToHalt(EVM.java:51) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675806202Z 	at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:157) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675811742Z 	at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:171) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675817634Z 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:407) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675822754Z 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:330) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675828222Z 	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:47) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675834952Z 	at org.hyperledger.besu.ethereum.mainnet.TransactionProcessor.processTransaction(TransactionProcessor.java:182) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675839778Z 	at org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:131) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675844511Z 	at org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:84) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675849252Z 	at org.hyperledger.besu.ethereum.transaction.TransactionSimulator.process(TransactionSimulator.java:76) ~[besu-core-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675854476Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthCall.resultByBlockNumber(EthCall.java:56) ~[besu-api-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675859413Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.latestResult(AbstractBlockParameterMethod.java:55) ~[besu-api-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675864825Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:66) ~[besu-api-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.67587043Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthCall.response(EthCall.java:78) ~[besu-api-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675875959Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:599) ~[besu-api-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675886846Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:472) ~[besu-api-1.4.6.jar:1.4.6]
2020-06-18T15:24:33.675892384Z 	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService$$Lambda$1106/0x000000084063dc40.handle(Unknown Source) ~[?:?]
2020-06-18T15:24:33.67589828Z 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[vertx-core-3.8.5.jar:3.8.5]
2020-06-18T15:24:33.675903583Z 	at io.vertx.core.impl.ContextImpl$$Lambda$795/0x0000000840562440.run(Unknown Source) ~[?:?]
2020-06-18T15:24:33.675908506Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
2020-06-18T15:24:33.67591333Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
2020-06-18T15:24:33.675918327Z 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.42.Final.jar:4.1.42.Final]
2020-06-18T15:24:33.675923754Z 	at java.lang.Thread.run(Thread.java:834) ~[?:?]
```

[Full log from startup to failure](https://github.com/hyperledger/besu/files/4799486/validators.log)

At that point in time, they keep running, but stop interacting with the network. Running at 1 full CPU and a rising memory graph until they restart due to memory limits (at 5gb...)

![image](https://user-images.githubusercontent.com/16780/85040247-e55d7f80-b188-11ea-9b5d-c6167bb656d9.png)

**Frequency:** [What percentage of the time does it occur?]

100% of the time

### Versions (Add all that apply)

We run out of the official docker container

* Software version: [`besu --version`] 

besu/v1.4.6/linux-x86_64/oracle_openjdk-java-11

* Java version: [`java -version`] 

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode, sharing)

* OS Name & Version: [`cat /etc/*release`]

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

* Kernel Version: [`uname -a`]

Linux besu-edge-1-peach-aardwolf-0 4.14.138+ #1 SMP Tue Sep 3 02:58:08 PDT 2019 x86_64 GNU/Linux

* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]

k8s - 1.14.10-gke.36

* Cloud VM, type, size: [Amazon Web Services I3-large]

4 x n1-standard-2

### Additional info

DB size, 1.5gb

```
90M     000043.log
58M     000045.log
58M     000047.log
60M     000049.log
68M     000051.log
63M     000057.log
71M     000059.log
1008K   000065.log
71M     000087.log
65M     000100.sst
65M     000103.sst
4.0K    000111.log
156K    000128.log
71M     000145.log
4.0K    000161.log
71M     000178.log
4.0K    000200.log
928K    000217.log
71M     000234.log
65M     000250.sst
65M     000251.sst
49M     000252.sst
71M     000257.log
65M     000261.sst
65M     000273.sst
65M     000274.sst
16K     000275.sst
320K    000278.sst
660K    000280.log
304K    000295.sst
71M     000297.log
276K    000312.sst
71M     000314.log
65M     000324.sst
4.0K    CURRENT
4.0K    IDENTITY
0       LOCK
256K    LOG
772K    LOG.old.1592485304454240
256K    LOG.old.1592485822129207
256K    LOG.old.1592485870423897
128K    LOG.old.1592485922244741
256K    LOG.old.1592486102069536
256K    LOG.old.1592486147831992
256K    LOG.old.1592486187278630
388K    LOG.old.1592489180764970
256K    LOG.old.1592489269440959
256K    LOG.old.1592490017001269
256K    LOG.old.1592490425812230
256K    LOG.old.1592491729755350
256K    LOG.old.1592492974804448
256K    LOG.old.1592494089862828
4.0M    MANIFEST-000311
20K     OPTIONS-000327
20K     OPTIONS-000329
1.5G    total
```

**Comment by roderik** [comment]
We have the sneaking suspicion that a user pushed a large value in a contract, and the errors are coming from trying to get these values out of the jsonrpc interface.

The error we currently get in our code, which correlates roughly to the errors in the Besu logs

```
The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825795
```

**Comment by shemnon** [comment]
It looks like the eth_call rpc is indeed taking too much time.  My gut is that it is related to the number of sload operations and not the single large value.  Is the particular contract available for us to examine?

**Comment by sambacha** [comment]
This reminds me of the contracted that violated state, , 0x03 out of gas

**Comment by roderik** [comment]
After a lot of debugging I've got some more info:

Essentially the contract:
```
pragma solidity ^0.6.4;
pragma experimental ABIEncoderV2;

contract PD {

  struct ReceivedPalletData {
    string did;
    string receivedPalletSsccCode;
    string receivedPalletSsccStatusCode;
    string receivedPalletBarcode;
    string receivedPalletQuantitySu;
    string receivedPalletBestBeforDate;
    string goodsReceiptMessage;
  }

  ReceivedPalletData[] internal _receivedPalletDataRegistry;

  function getContents() public view override returns (ReceivedPalletData[] memory) {
    return _receivedPalletDataRegistry;
  }

}
```

The problem is I cannot tell you how much is in the array since it is hard to get out. But I cannot find any information on there being limits to get data out.

Some random things:
- My nodes return data, albeit slowly, with -Xms4g -Xmx4g, but they get killed by hitting the 5gb Kubernetes limit I've set. But Xmx is max VM size, so I thought it would stay at max 4
- I had to increase the Ethers timeout (2min) to a lot higher to get it to wait long enough for the response. 

Some things I've been thinking about:

- the db is stored on a regular persistent disk in google cloud, you can also create ssd persistent disks, that might speed up rocksdb queries?

**Comment by roderik** [comment]
It takes at least 220 seconds, this is the last message I see before everything returns to normal because the request dies with a `504 Gateway timeout`

```
 2020-06-19 16:45:29.538+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-11,5,main]=Thread[vert.x-worker-thread-11,5,main] has been blocked for 219643 ms, time limit is 60000 ms 
```

**Comment by shemnon** [comment]
I would recommend a paginated variant of getContents where either an explicit sub-range of the array is returned.

**Comment by roderik** [comment]
I upgraded to bigger machines and SSD disks, but the query keeps being 300+ seconds long. On an infrastructure level, there is nothing more I can do.

Will implement the pagination next unless anyone has a better idea?

**Comment by shemnon** [comment]
What is the scale of the response?  i.e.How many items are in that array?  We are considering some radical DB changes on the back end so that number would be helpful in determining if this is an issue of trie-climbing to get all the values or some other problem.

**Comment by roderik** [comment]
Sorry, I missed this question. I do not have exact numbers anymore, but it was about 2000 items and serialized as JSON they went over the 16MB MongoDB document limit. So I only know more then 2k and together more than 16mb in space (in one response, so this was a bad query / implementation anyway from my side)

**Comment by forkwatch-ninja** [comment]
I'm running into the same issue @shemnon

I am running a public Hyperledger Besu RPC endpoint which means others would be using it to deploy their smart contracts, and I see this in the log repeatedly:

```
# Besu Buggs	
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs$$Lambda$858/0x0000000801072440.get(Unknown Source)                                                                                                       [300/1896]
        at java.base@14/java.util.Optional.orElseGet(Optional.java:362)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:59)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:614)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:476)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService$$Lambda$753/0x000000080102b440.handle(Unknown Source)
        at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at app//io.vertx.core.impl.ContextImpl$$Lambda$587/0x0000000800f8d040.run(Unknown Source)
        at java.base@14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base@14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@14/java.lang.Thread.run(Thread.java:832)

2020-11-07 20:47:46.848+00:00 | vert.x-worker-thread-19 | WARN  | BackendQuery | Zombie backend query detected [ unnamed ], aborting process.
2020-11-07 20:47:46.852+00:00 | vert.x-worker-thread-19 | ERROR | BlockchainQueries | Error retrieving matching logs
org.hyperledger.besu.ethereum.api.handlers.RpcMethodTimeoutException: Timeout expired
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:46)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:31)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.stopIfExpired(BackendQuery.java:52)
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogs(BlockchainQueries.java:560)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.lambda$response$1(EthGetLogs.java:64)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:59)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:614)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:476)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-11-07 20:47:46.857+00:00 | vert.x-worker-thread-19 | ERROR | JsonRpcHttpService | Error processing JSON-RPC requestBody
org.hyperledger.besu.ethereum.api.handlers.RpcMethodTimeoutException: Timeout expired
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:46)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:31)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.stopIfExpired(BackendQuery.java:52)
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogs(BlockchainQueries.java:560)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.lambda$response$1(EthGetLogs.java:64)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:59)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:614)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:476)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-11-07 20:47:47.428+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-8,5,main]=Thread[vert.x-worker-thread-8,5,main] has been blocked for 78205 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
        at app//org.rocksdb.RocksDB.get(Native Method)
        at app//org.rocksdb.RocksDB.get(RocksDB.java:1886)
        at app//org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:155)
        at app//org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:62)
        at app//org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.get(SegmentedKeyValueStorageAdapter.java:50)
        at app//org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage.get(KeyValueStoragePrefixedKeyBlockchainStorage.java:122)
        at app//org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage.getBlockHeader(KeyValueStoragePrefixedKeyBlockchainStorage.java:77)
        at app//org.hyperledger.besu.ethereum.chain.DefaultBlockchain$$Lambda$833/0x0000000801067c40.apply(Unknown Source)
        at java.base@14/java.util.Optional.flatMap(Optional.java:287)
        at app//org.hyperledger.besu.ethereum.chain.DefaultBlockchain.getBlockHeader(DefaultBlockchain.java:186)
        at app//org.hyperledger.besu.ethereum.api.query.BlockchainQueries$$Lambda$869/0x0000000801079440.apply(Unknown Source)
        at java.base@14/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
        at java.base@14/java.util.stream.Streams$RangeLongSpliterator.tryAdvance(Streams.java:207)
        at java.base@14/java.util.stream.LongPipeline.forEachWithCancel(LongPipeline.java:161)
        at java.base@14/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
```

I'm running this command:
```
besu --network=classic --data-path=~/besu-dir --node-private-key-file=~/besu-dir/keys --rpc-http-enabled --rpc-ws-enabled --host-whitelist=* --rpc-http-cors-origins=* --p2p-host=<IP> --p2p-port=30303 --rpc-http-host=0.0.0.0 --rpc-http-port=8545 --sync-mode=FULL --rpc-http-api=web3,net,eth,trace,txpool --rpc-ws-api=web3,net,eth,trace,txpool --rpc-ws-host=0.0.0.0
```

**Comment by shemnon** [comment]
@forkwatch-ninja the stacks indicate you are causing this via a different means than roderik is.  Can you post this in a separate bug?

Also, can you post the RPC calls triggering it?  How large is the getLogsQuery you are polling?  How big is the block range, what are the filters, and how much data are you expecting to get?  Add this to the new bug because that will be my first thing to look at.

**Comment by vmichalik** [comment]
Hi @roderik, are you still experiencing this issue? If not, I'll go ahead and close it!

**Comment by roderik** [comment]
Nope, all good here!
