### ISSUE TITLE
shouldFailConnectingToNodeWithWsRpcDisabled Failed in Acceptance Test

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#1168]
it seems to be a flaky test. After relaunching it was ok

>org.hyperledger.besu.tests.acceptance.RpcApisTogglesAcceptanceTest > 
shouldFailConnectingToNodeWithWsRpcDisabled failed on a CI build

````
org.hyperledger.besu.tests.acceptance.RpcApisTogglesAcceptanceTest > shouldFailConnectingToNodeWithWsRpcDisabled FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.hyperledger.besu.tests.acceptance.dsl.condition.net.AwaitNetPeerCount 
    Expecting:
     <1>
    to be equal to:
     <2>
    but was not within 30 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
        at org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:24)
        at org.hyperledger.besu.tests.acceptance.dsl.condition.net.AwaitNetPeerCount.verify(AwaitNetPeerCount.java:39)
        at org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.verify(BesuNode.java:673)
        at org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.awaitPeerDiscovery(BesuNode.java:459)
        at org.hyperledger.besu.tests.acceptance.dsl.node.cluster.Cluster.start(Cluster.java:96)
        at org.hyperledger.besu.tests.acceptance.dsl.node.cluster.Cluster.start(Cluster.java:67)
        at org.hyperledger.besu.tests.acceptance.RpcApisTogglesAcceptanceTest.before(RpcApisTogglesAcceptanceTest.java:39)

        Caused by:
        org.opentest4j.AssertionFailedError: 
        Expecting:
         <1>
        to be equal to:
         <2>
        but was not.
            at jdk.internal.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at org.hyperledger.besu.tests.acceptance.dsl.condition.net.AwaitNetPeerCount.lambda$verify$0(AwaitNetPeerCount.java:39)
            at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
            at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
            at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
````

https://app.circleci.com/pipelines/github/hyperledger/besu/4647/workflows/0ac0b2cb-3705-47fc-93ea-c6954397cdde/jobs/21941/steps

**Comment by vmichalik** [comment]
we haven't seen this again recently, right? let's close for now if you agree @matkt

**Comment by matkt** [comment]
yes we can close this one. thanks
