### ISSUE TITLE
Merkle. Trie. Exception.

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1324]
### Description
As a developer, I want to never see a `MerkleTrieException` so that I can sleep at night. Here's an example of one of my nightmares:

```
2020-08-20 12:19:34.017-05:00 | EthScheduler-Transactions-1 | ERROR | Besu | Uncaught exception in thread "EthScheduler-Transactions-1"
org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xc565b6f9e357f4c1111e790c5f90d2ee41a2f48c212f4bb88935e5b409977abe
	at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:108)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:107)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:50)
	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46)
	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51)
	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46)
	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51)
	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46)
	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:63)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:51)
	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:80)
	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:35)
	at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState.get(DefaultMutableWorldState.java:111)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.lambda$validateTransaction$2(TransactionPool.java:272)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateTransaction(TransactionPool.java:270)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.addRemoteTransactions(TransactionPool.java:198)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:82)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:67)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageHandler.lambda$exec$0(TransactionsMessageHandler.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

That means that the node in the state/storage trie with the hash `0xc565b6f9e357f4c1111e790c5f90d2ee41a2f48c212f4bb88935e5b409977abe` was swept even thought it shouldn't have been.
The good news is that there were 5 more exceptions of this kind thrown simultaneously . Why is that good news? Because it means that things have gone horribly wrong and we're not searching for a node serial killer and not a node assassin. The former is much sloppier.

This all happened right before these block import failures.

```
2020-08-20 12:19:40.401-05:00 | EthScheduler-Services-23 (importBlock) | WARN  | MainnetBlockBodyValidator | Invalid block: receipts root mismatch (expected=0x701d274f98107d52c20070bc0d834770b882a897ba0fd7f048b99b31e6584289, actual=0x34affcf1e0dda56cfebba75487fe88fed9606367536c85bbdb4d6c3e8ab8abfe)
2020-08-20 12:19:40.401-05:00 | EthScheduler-Services-23 (importBlock) | WARN  | PipelineChainDownloader | Invalid block detected.  Disconnecting from sync target. Failed to import block: Invalid block at #510987 (0x68d320222d203a54215f3e4fce972b71847c8367caf8cc01cb7ec469e11392bc)
2020-08-20 12:19:40.406-05:00 | EthScheduler-Services-23 (importBlock) | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
2020-08-20 12:19:40.407-05:00 | EthScheduler-Services-23 (importBlock) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #510987 (0x68d320222d203a54215f3e4fce972b71847c8367caf8cc01cb7ec469e11392bc)
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:152)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #510987 (0x68d320222d203a54215f3e4fce972b71847c8367caf8cc01cb7ec469e11392bc)
	at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:57)
	at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:30)
	at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:130)
	... 5 more
```

### Steps to Reproduce (Bug)
1. Start a fresh **full** sync and pruning enabled.
2. Pray.
3. If step 2 didn't work, switch to another testnet and repeat. Or try using `pruning-block-confirmations=0` and `pruning-blocks-retained=1` or some other low numbers.

### Versions (Add all that apply)
* Software version: `1.5.3`

### Additional Information
When I encountered this bug, I also had multiple pruning machines running on completed mainnet fast syncs, walking over the entire huge trie as of block ~10,500,000 and those worked fine. I suspect it has something to do with the rapid marking and sweeping that happens when running a full sync from scratch and pruning _or_ because of peculiaries of contracts early in the history of the chain. For example take a look at a previous bug I fixed, #760

**Comment by vmichalik** [comment]
@RatanRSur might I guess that you haven't run into this again? If not, I'll close this for now

**Comment by RatanRSur** [comment]
Closing because of Bonsai Tries
