### ISSUE TITLE
Flakey test - neighborsPacketLimited - org.hyperledger.besu.ethereum.p2p.discovery.PeerDiscoveryAgentTest

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1490]
unit test neighborsPacketLimited - org.hyperledger.besu.ethereum.p2p.discovery.PeerDiscoveryAgentTest was flakey on the CI server

**Comment by shemnon** [comment]
https://app.circleci.com/pipelines/github/hyperledger/besu/5821/workflows/72016b15-631f-418c-aeb6-6862ad1ee598/jobs/28085

23 Oct 2020 ~18:00 UTC

```
java.lang.AssertionError: 
Expecting ListFromStream:
 <[DiscoveryPeer{status=bonded, enode=enode://c94ef9dd8a23f6a21f81e539e7b21afe3c14290e461ef1879bfe7a1614adaa99028934c5fd06ef57c0ca02f9dfee2cf860983b0e3444e62c8016eecd1fd045cc@127.0.0.1:37?discport=36, firstDiscovered=1603473750976, lastContacted=1603473750980, lastSeen=1603473750980},
    DiscoveryPeer{status=bonded, enode=enode://f042f21321c41218adc0121607b625b016f79d381d22093d91212832d1ed5e5497e56dab8ae4df0b1b136ae17f9fcc93d04ffe2a81227e0232c20f622508d23a@127.0.0.1:21?discport=20, firstDiscovered=1603473750996, lastContacted=1603473751001, lastSeen=1603473751001},
    DiscoveryPeer{status=bonded, enode=enode://2aeefc36a2b5cf0970855536b1d4012e95b02aec185f717664eb331fa9c3ff3cb89545c0d4a69ed5cc5c24ed04ed94383f118f391d15384d30a5f47c1829fb39@127.0.0.1:29?discport=28, firstDiscovered=1603473750941, lastContacted=1603473750945, lastSeen=1603473750945},
    DiscoveryPeer{status=bonded, enode=enode://fad089df1bb8cb5dad992572be4931663308ecbff1168f4df2070164153d8a345148df7e7be46f6096207d7999a4dc1f742077777e952e19ed27ced01e60518e@127.0.0.1:11?discport=10, firstDiscovered=1603473751001, lastContacted=1603473751004, lastSeen=1603473751004},
    DiscoveryPeer{status=bonded, enode=enode://df90d0aee80f40a377640622c0784af1b41a4c27fee64bdff769857f157c79cbd3a8613a921259e2ec776c113fa7ea1cc56513c0bcdd31e19fb691b1c55451af@127.0.0.1:9?discport=8, firstDiscovered=1603473750992, lastContacted=1603473750996, lastSeen=1603473750996},
    DiscoveryPeer{status=bonded, enode=enode://ddcd4ff6fdc6f5ba27146f8e5e463fa1d77c52215a13900dd70450397b194ac6c6f403dd4249b7a5436af7324049f4353e802fbd4e602e9afc8bce88219d79bf@127.0.0.1:3?discport=2, firstDiscovered=1603473750988, lastContacted=1603473750992, lastSeen=1603473750992},
    DiscoveryPeer{status=bonded, enode=enode://db89a030aa322197274ec0e9beb7217e140cacde58eeedde3d7b1f6caab5481f1c213802a48b3a330f0cdcf7638993333a29d79dff9611d7ac4ebb180435d0e6@127.0.0.1:35?discport=34, firstDiscovered=1603473750983, lastContacted=1603473750988, lastSeen=1603473750988},
    DiscoveryPeer{status=bonded, enode=enode://d4f52dcc44e826e793f51d1adb73fc6121f55a57fcf62d31bc553f70c91f1fdcc4a0114700ae6ba175a9d7729375ffc7885702a1f785c9e86508312e4c592c1e@127.0.0.1:19?discport=18, firstDiscovered=1603473750980, lastContacted=1603473750983, lastSeen=1603473750983},
    DiscoveryPeer{status=bonded, enode=enode://c52c0ab7b165e25dbecadcb72a9bf57aa63658691dfba0db18021a927b9d850e6d51f0e8d39b4c5c6151f081affad8c79356fa605db65e36d39b6b7b04d244d2@127.0.0.1:15?discport=14, firstDiscovered=1603473750972, lastContacted=1603473750976, lastSeen=1603473750976},
    DiscoveryPeer{status=bonded, enode=enode://9e7f7c46eea046796d8a41ede1de968c304eb9025d73a12f23b5adeda83ee4141c4cebccb7435e256b68a2a6814bcfab6bf3a05c9bd9731ab5f12f933007dc7c@127.0.0.1:27?discport=26, firstDiscovered=1603473750968, lastContacted=1603473750972, lastSeen=1603473750972},
    DiscoveryPeer{status=bonded, enode=enode://99026fab50cdc87af333f9b4c8cdd65716a76cab5a2aac6bf66292dbafc3430a0d4322c93f74e961300c046a8f6ecf1e80f1ea5f650d734e11701462aeae7413@127.0.0.1:7?discport=6, firstDiscovered=1603473750964, lastContacted=1603473750968, lastSeen=1603473750968},
    DiscoveryPeer{status=bonded, enode=enode://7f90074e597b828905c343e06b765fde106070fe2bd945833f0111d0437259083bdfa6ecc19c13b324d9e40d4c48df6f4341c45084e6676e447ec92ad30811a9@127.0.0.1:41?discport=40, firstDiscovered=1603473750959, lastContacted=1603473750964, lastSeen=1603473750964},
    DiscoveryPeer{status=bonded, enode=enode://7ddb740f445b3046eec6cfe527e52111bd7af2bdc1324dac3908ec81ee15bb559f7ba0afc44c65c2e726b6ab0169a335bf124fc245500d205746db3ee77b662f@127.0.0.1:13?discport=12, firstDiscovered=1603473750954, lastContacted=1603473750959, lastSeen=1603473750959},
    DiscoveryPeer{status=bonded, enode=enode://6e33ad4ced64ffcea3cd253954c50bb5bf260dee521520ffc7adbbee227a1795c669b056e464ee2c30f7becd7f501449f57e1d6f77c27af179366de193924065@127.0.0.1:33?discport=32, firstDiscovered=1603473750949, lastContacted=1603473750954, lastSeen=1603473750954},
    DiscoveryPeer{status=bonded, enode=enode://4ea4f12f43cecfafc3cae986a2f5c5a74b3b7ab452c9bc6190486f57902a0c65d1345ac0aee615b19edbf8858d0e7bbd5d45240ac924e5773a3d14f26f912205@127.0.0.1:39?discport=38, firstDiscovered=1603473750945, lastContacted=1603473750949, lastSeen=1603473750949},
    DiscoveryPeer{status=bonded, enode=enode://28b26656fd9b6320ea305afc23708384a064dab689c8ef5ff0bd97fd923ac930f215c3a45bcaad42e585d22520fd0c7567464e90753036c04d1242630d3b4f8a@127.0.0.1:23?discport=22, firstDiscovered=1603473750937, lastContacted=1603473750941, lastSeen=1603473750941},
    DiscoveryPeer{status=bonded, enode=enode://16b1a0e0e3c8f6234a09bd1e482833fa20482055b7773577798d1b29063605f457a82990d0ea16fece42c195b2a20a1488a22c9730327a28e22353724f5427f7@127.0.0.1:5?discport=4, firstDiscovered=1603473750934, lastContacted=1603473750937, lastSeen=1603473750937},
    DiscoveryPeer{status=bonded, enode=enode://145f39d273ef710e6ee9e237ae66fc338ef73c75ba23afd8adf15b78550a5c9ebc0779444911eac5b8f3d89c762096dcf0d0f6e651f0c28cd4caaad0725f9ce9@127.0.0.1:31?discport=30, firstDiscovered=1603473750931, lastContacted=1603473750934, lastSeen=1603473750934},
    DiscoveryPeer{status=bonded, enode=enode://04628e66627fc8b38ec360cd40e9a18ad01d62e4b12db25de278fbb14baf630e7c71c84944623a735f8c65143bbb2fafd7ed6bde085a8e41a1f547004803baab@127.0.0.1:17?discport=16, firstDiscovered=1603473750927, lastContacted=1603473750931, lastSeen=1603473750931}]>
to contain:
 <[DiscoveryPeer{status=known, enode=enode://ddcd4ff6fdc6f5ba27146f8e5e463fa1d77c52215a13900dd70450397b194ac6c6f403dd4249b7a5436af7324049f4353e802fbd4e602e9afc8bce88219d79bf@127.0.0.1:3?discport=2, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://16b1a0e0e3c8f6234a09bd1e482833fa20482055b7773577798d1b29063605f457a82990d0ea16fece42c195b2a20a1488a22c9730327a28e22353724f5427f7@127.0.0.1:5?discport=4, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://99026fab50cdc87af333f9b4c8cdd65716a76cab5a2aac6bf66292dbafc3430a0d4322c93f74e961300c046a8f6ecf1e80f1ea5f650d734e11701462aeae7413@127.0.0.1:7?discport=6, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://df90d0aee80f40a377640622c0784af1b41a4c27fee64bdff769857f157c79cbd3a8613a921259e2ec776c113fa7ea1cc56513c0bcdd31e19fb691b1c55451af@127.0.0.1:9?discport=8, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://fad089df1bb8cb5dad992572be4931663308ecbff1168f4df2070164153d8a345148df7e7be46f6096207d7999a4dc1f742077777e952e19ed27ced01e60518e@127.0.0.1:11?discport=10, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://7ddb740f445b3046eec6cfe527e52111bd7af2bdc1324dac3908ec81ee15bb559f7ba0afc44c65c2e726b6ab0169a335bf124fc245500d205746db3ee77b662f@127.0.0.1:13?discport=12, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://c52c0ab7b165e25dbecadcb72a9bf57aa63658691dfba0db18021a927b9d850e6d51f0e8d39b4c5c6151f081affad8c79356fa605db65e36d39b6b7b04d244d2@127.0.0.1:15?discport=14, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://04628e66627fc8b38ec360cd40e9a18ad01d62e4b12db25de278fbb14baf630e7c71c84944623a735f8c65143bbb2fafd7ed6bde085a8e41a1f547004803baab@127.0.0.1:17?discport=16, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://d4f52dcc44e826e793f51d1adb73fc6121f55a57fcf62d31bc553f70c91f1fdcc4a0114700ae6ba175a9d7729375ffc7885702a1f785c9e86508312e4c592c1e@127.0.0.1:19?discport=18, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://f042f21321c41218adc0121607b625b016f79d381d22093d91212832d1ed5e5497e56dab8ae4df0b1b136ae17f9fcc93d04ffe2a81227e0232c20f622508d23a@127.0.0.1:21?discport=20, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://28b26656fd9b6320ea305afc23708384a064dab689c8ef5ff0bd97fd923ac930f215c3a45bcaad42e585d22520fd0c7567464e90753036c04d1242630d3b4f8a@127.0.0.1:23?discport=22, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://03c1acdb962a722ff3366055935e645e09c14a5c27abe7e64d20ff403883d5cb22489ef677b72151572c27209caa4cd45726f1315bf7e848ab12e22c82147bfd@127.0.0.1:25?discport=24, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://9e7f7c46eea046796d8a41ede1de968c304eb9025d73a12f23b5adeda83ee4141c4cebccb7435e256b68a2a6814bcfab6bf3a05c9bd9731ab5f12f933007dc7c@127.0.0.1:27?discport=26, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://2aeefc36a2b5cf0970855536b1d4012e95b02aec185f717664eb331fa9c3ff3cb89545c0d4a69ed5cc5c24ed04ed94383f118f391d15384d30a5f47c1829fb39@127.0.0.1:29?discport=28, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://145f39d273ef710e6ee9e237ae66fc338ef73c75ba23afd8adf15b78550a5c9ebc0779444911eac5b8f3d89c762096dcf0d0f6e651f0c28cd4caaad0725f9ce9@127.0.0.1:31?discport=30, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://6e33ad4ced64ffcea3cd253954c50bb5bf260dee521520ffc7adbbee227a1795c669b056e464ee2c30f7becd7f501449f57e1d6f77c27af179366de193924065@127.0.0.1:33?discport=32, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://db89a030aa322197274ec0e9beb7217e140cacde58eeedde3d7b1f6caab5481f1c213802a48b3a330f0cdcf7638993333a29d79dff9611d7ac4ebb180435d0e6@127.0.0.1:35?discport=34, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://c94ef9dd8a23f6a21f81e539e7b21afe3c14290e461ef1879bfe7a1614adaa99028934c5fd06ef57c0ca02f9dfee2cf860983b0e3444e62c8016eecd1fd045cc@127.0.0.1:37?discport=36, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://4ea4f12f43cecfafc3cae986a2f5c5a74b3b7ab452c9bc6190486f57902a0c65d1345ac0aee615b19edbf8858d0e7bbd5d45240ac924e5773a3d14f26f912205@127.0.0.1:39?discport=38, firstDiscovered=0, lastContacted=0, lastSeen=0},
    DiscoveryPeer{status=known, enode=enode://7f90074e597b828905c343e06b765fde106070fe2bd945833f0111d0437259083bdfa6ecc19c13b324d9e40d4c48df6f4341c45084e6676e447ec92ad30811a9@127.0.0.1:41?discport=40, firstDiscovered=0, lastContacted=0, lastSeen=0}]>
but could not find the following element(s):
 <[DiscoveryPeer{status=known, enode=enode://03c1acdb962a722ff3366055935e645e09c14a5c27abe7e64d20ff403883d5cb22489ef677b72151572c27209caa4cd45726f1315bf7e848ab12e22c82147bfd@127.0.0.1:25?discport=24, firstDiscovered=0, lastContacted=0, lastSeen=0}]>

	at org.hyperledger.besu.ethereum.p2p.discovery.PeerDiscoveryAgentTest.neighborsPacketLimited(PeerDiscoveryAgentTest.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
