### ISSUE TITLE
Cannot connect tp IPv6 peers

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#1495]
While running Yolov2 in a docker container I saw this error complaining about ipv6 addresses.  Not sure if it's a Besu bug or a docker limitation.  Note the IPv6 address in the enode.

``` 
2020-10-26 06:00:06.493+00:00 | vert.x-eventloop-thread-1 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, enode=enode://6f75a5f729bc23884961fcdd9002d40fe2cb555636f35c57198100533100e64d08666e48d5bd928e16b6600615920e564dd2317eae3c78996d1ffb5e319154c6@[2400:8901::f03c:91ff:feb6:c94a]:30303, firstDiscovered=1603691980123, lastContacted=0, lastSeen=0} failed, packet: 0x08a9399e6df78f1be6078569c704a31df6504bb4d7ab4133887c8b346e455452d975bf1eb81c8a3f382f2033faa5d0623beae18f0ad0f883389dc34126f74dc50f449cf5dda47b0da00ff670eb0831bbac09bbfcec8348667eca569041705b6a0001ea05cb847f00000182765f82765fd7902400890100000000f03c91fffeb6c94a82765f82765f845f966622
java.nio.channels.UnsupportedAddressTypeException
	at java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
	at java.base/sun.nio.ch.DatagramChannelImpl.send(Unknown Source)
	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:295)
	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:280)
	at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:268)
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:88)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

  

### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by leontastic** [comment]
This causes fast sync to hang when I try syncing for the first time in a docker image on the `ropsten` chain. IPv6 peers are pretty common too so it's really hard to get a node syncing as a result.

**Comment by macfarla** [comment]
assigning this one to you too @frankisawesome - think this should be cleared up by your changes

**Comment by frankisawesome** [comment]
So this is a docker config issue - docker doesn't have ipv6 enabled by default.
There will be three steps to this:
1. https://github.com/hyperledger/besu/pull/2970 hide full stacktrace to TRACE level
2. Update troubleshooting section in besu-docs
3. Potentially update the quickstart guides in besu-docs with instructions to enable ipv6
