### ISSUE TITLE
JsonRpcHttpService Error processing JSON-RPC requestBody and vertx-blocked-thread-checker warn in logs

### ISSUE THREAD

**Issue by forkwatch-ninja** [hyperledger/besu#1539]
I'm running into the same issue @shemnon as https://github.com/hyperledger/besu/issues/1114
Where threads are blocked.

I am running a public Hyperledger Besu RPC endpoint which means others would be using it to deploy their smart contracts, and I see this in the log repeatedly:
```
# Besu Buggs	
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs$$Lambda$858/0x0000000801072440.get(Unknown Source)                                                                                                       [300/1896]
        at java.base@14/java.util.Optional.orElseGet(Optional.java:362)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:59)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:614)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:476)
        at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService$$Lambda$753/0x000000080102b440.handle(Unknown Source)
        at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at app//io.vertx.core.impl.ContextImpl$$Lambda$587/0x0000000800f8d040.run(Unknown Source)
        at java.base@14/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base@14/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@14/java.lang.Thread.run(Thread.java:832)

2020-11-07 20:47:46.848+00:00 | vert.x-worker-thread-19 | WARN  | BackendQuery | Zombie backend query detected [ unnamed ], aborting process.
2020-11-07 20:47:46.852+00:00 | vert.x-worker-thread-19 | ERROR | BlockchainQueries | Error retrieving matching logs
org.hyperledger.besu.ethereum.api.handlers.RpcMethodTimeoutException: Timeout expired
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:46)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:31)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.stopIfExpired(BackendQuery.java:52)
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogs(BlockchainQueries.java:560)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.lambda$response$1(EthGetLogs.java:64)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:59)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:614)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:476)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-11-07 20:47:46.857+00:00 | vert.x-worker-thread-19 | ERROR | JsonRpcHttpService | Error processing JSON-RPC requestBody
org.hyperledger.besu.ethereum.api.handlers.RpcMethodTimeoutException: Timeout expired
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:46)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.runIfAlive(BackendQuery.java:31)
        at org.hyperledger.besu.ethereum.api.query.BackendQuery.stopIfExpired(BackendQuery.java:52)
        at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogs(BlockchainQueries.java:560)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.lambda$response$1(EthGetLogs.java:64)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:59)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:614)
        at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$10(JsonRpcHttpService.java:476)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
2020-11-07 20:47:47.428+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-8,5,main]=Thread[vert.x-worker-thread-8,5,main] has been blocked for 78205 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
        at app//org.rocksdb.RocksDB.get(Native Method)
        at app//org.rocksdb.RocksDB.get(RocksDB.java:1886)
        at app//org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:155)
        at app//org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:62)
        at app//org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.get(SegmentedKeyValueStorageAdapter.java:50)
        at app//org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage.get(KeyValueStoragePrefixedKeyBlockchainStorage.java:122)
        at app//org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage.getBlockHeader(KeyValueStoragePrefixedKeyBlockchainStorage.java:77)
        at app//org.hyperledger.besu.ethereum.chain.DefaultBlockchain$$Lambda$833/0x0000000801067c40.apply(Unknown Source)
        at java.base@14/java.util.Optional.flatMap(Optional.java:287)
        at app//org.hyperledger.besu.ethereum.chain.DefaultBlockchain.getBlockHeader(DefaultBlockchain.java:186)
        at app//org.hyperledger.besu.ethereum.api.query.BlockchainQueries$$Lambda$869/0x0000000801079440.apply(Unknown Source)
        at java.base@14/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
        at java.base@14/java.util.stream.Streams$RangeLongSpliterator.tryAdvance(Streams.java:207)
        at java.base@14/java.util.stream.LongPipeline.forEachWithCancel(LongPipeline.java:161)
        at java.base@14/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
```
I'm running this command:
```
besu --network=classic --data-path=~/besu-dir --node-private-key-file=~/besu-dir/keys --rpc-http-enabled --rpc-ws-enabled --host-whitelist=* --rpc-http-cors-origins=* --p2p-host=<IP> --p2p-port=30303 --rpc-http-host=0.0.0.0 --rpc-http-port=8545 --sync-mode=FULL --rpc-http-api=web3,net,eth,trace,txpool --rpc-ws-api=web3,net,eth,trace,txpool --rpc-ws-host=0.0.0.0
```

@shemnon  I'm connecting it to blockscout used by the public and providing the RPC endpoint to the public as well. I can share traffic data to the RPC, but for specific RPC calls triggering it, I can't really say, it's mostly Blockscout and a public RPC endpoint. How do you advise me to look into the RPC calls hitting the Besu node and how large the getLogsQuery being polled. Are there docs to allow me to debug this to provide the data for you?

**Comment by macfarla** [comment]
@forkwatch-ninja sorry about the delay - is this still a problem for you? And if so, can you provide any more data - besu logs will show all RPC calls if you set log level to TRACE

**Comment by vmichalik** [comment]
Hi @forkwatch-ninja, closing this for now as we haven't been able to recreate this issue, if you're still having problems please feel free to reopen!
