### ISSUE TITLE
Flaky test - onlyTrustStaticNodesWhileOutOfSync - org.hyperledger.besu.tests.acceptance.permissioning.NodesSmartContractPermissioningStaticNodesAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#1630]
onlyTrustStaticNodesWhileOutOfSync - org.hyperledger.besu.tests.acceptance.permissioning.NodesSmartContractPermissioningStaticNodesAcceptanceTest

https://app.circleci.com/pipelines/github/hyperledger/besu/6282/workflows/a5c68080-35bd-4a8e-b943-9219cdb0505a/jobs/30354

org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.hyperledger.besu.tests.acceptance.dsl.AcceptanceTestBase 
Expecting:
 <0>
to be greater than or equal to:
 <50>  within 2 minutes.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
	at org.hyperledger.besu.tests.acceptance.dsl.AcceptanceTestBase.waitForBlockHeight(AcceptanceTestBase.java:224)
	at org.hyperledger.besu.tests.acceptance.permissioning.NodesSmartContractPermissioningStaticNodesAcceptanceTest.onlyTrustStaticNodesWhileOutOfSync(NodesSmartContractPermissioningStaticNodesAcceptanceTest.java:54)

**Comment by macfarla** [comment]
and again https://app.circleci.com/pipelines/github/hyperledger/besu/6309/workflows/42ad34eb-074c-45d9-953c-0444e2f3e605/jobs/30487

**Comment by matkt** [comment]
Again https://app.circleci.com/pipelines/github/hyperledger/besu/6320/workflows/72d7f0b0-8617-4a45-936d-c3af81303b4f/jobs/30562

**Comment by macfarla** [comment]
This one I also updated to reduce 50 to a more sensible number
