### ISSUE TITLE
Uncaught DNS exception, redux

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#1839]
### Description

Besu 20.10.4, using published docker images and running on Goerli, got this exception shortly after starting:

```
eth1_1    | 2021-01-26 14:43:10.994+00:00 | nioEventLoopGroup-3-4 | INFO  | WaitForPeersTask | Waiting for 4 peers to connect.
eth1_1    | 2021-01-26 14:43:15.767+00:00 | nioEventLoopGroup-3-5 | INFO  | WaitForPeersTask | Waiting for 3 peers to connect.
eth1_1    | 2021-01-26 14:43:23.632+00:00 | Timer-0 | ERROR | Besu | Uncaught exception in thread "Timer-0"
eth1_1    | java.io.EOFException
eth1_1    |     at org.xbill.DNS.NioTcpClient$ChannelState.processRead(NioTcpClient.java:180)
eth1_1    |     at org.xbill.DNS.NioTcpClient$ChannelState.processReadyKey(NioTcpClient.java:138)
eth1_1    |     at org.xbill.DNS.Client.processReadyKeys(Client.java:79)
eth1_1    |     at org.xbill.DNS.Client.runSelector(Client.java:62)
eth1_1    |     at java.base/java.lang.Thread.run(Unknown Source)
eth1_1    | 2021-01-26 14:45:47.529+00:00 | nioEventLoopGroup-3-10 | INFO  | WaitForPeersTask | Waiting for 1 peers to connect.
```

Like #1648 it references DNS, but the specifics of the exception are different.

I have not attempted to reproduce this behavior.

**Comment by atoulme** [comment]
We should expect the same fix as soon as the next Apache Tuweni release is out. Feel free to report there and participate on the Tuweni list to raise this issue.
