### ISSUE TITLE
NullPointerException during initial mainnet sync.

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#1850]
### Description

NullPointerException during initial mainnet sync. Sync does continue after it. Besu 20.10.4 on Ubuntu 20.04, using official docker image.

```
eth1_1    | 2021-01-28 13:41:04.192+00:00 | nioEventLoopGroup-3-3 | ERROR | Subscribers | Error in callback:
eth1_1    | java.lang.NullPointerException
eth1_1    |     at java.base/java.util.ArrayList.removeIf(Unknown Source)
eth1_1    |     at java.base/java.util.ArrayList.removeIf(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.EthPeers.reattemptPendingPeerRequests(EthPeers.java:119)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.EthPeers.dispatchMessage(EthPeers.java:113)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:264)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
eth1_1    |     at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
eth1_1    |     at java.base/java.lang.Iterable.forEach(Unknown Source)
eth1_1    |     at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:99)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:33)
eth1_1    |     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
eth1_1    |     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
eth1_1    |     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
eth1_1    |     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
eth1_1    |     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
eth1_1    |     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
eth1_1    |     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
eth1_1    |     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
eth1_1    |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
eth1_1    |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
eth1_1    |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
eth1_1    |     at java.base/java.lang.Thread.run(Unknown Source)
eth1_1    | 2021-01-28 13:41:05.433+00:00 | EthScheduler-Services-8 (importBlock) | INFO  | FastImportBlocksStep | Completed importing chain segment 9670290 to 9670489, Peers: 2
```

**Comment by iamhsk** [comment]
Closing this issue since it did not affect the sync. Let us know if you notice the same problem!😊
