### ISSUE TITLE
CompletionException when stopping besu during sync

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#1851]
### Description

CompletionException when stopping Besu during initial mainnet sync. Besu 20.10.4 on Ubuntu 20.04, using official docker images.

```
eth1_1    | 2021-01-28 13:35:08.974+00:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 11744551: 0x044b2d195389a31564dc78f56a94aac1f2fe7417e4e56c8b543ba9d15eeb9526
eth1_1    | 2021-01-28 13:35:08.976+00:00 | nioEventLoopGroup-3-4 | ERROR | FastSyncDownloader | Encountered an unexpected error during fast sync. Restarting fast sync in PT5S seconds.
eth1_1    | java.util.concurrent.CompletionException: java.util.concurrent.CancellationException: FastSyncDownloader stopped
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.sync.fastsync.PivotBlockRetriever.handleConfirmationResult(PivotBlockRetriever.java:141)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.sync.fastsync.PivotBlockConfirmer.processReceivedHeader(PivotBlockConfirmer.java:132)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
eth1_1    |     at org.hyperledger.besu.util.FutureUtils.lambda$propagateResult$1(FutureUtils.java:74)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
eth1_1    |     at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:69)
eth1_1    |     at org.hyperledger.besu.util.FutureUtils.lambda$exceptionallyCompose$0(FutureUtils.java:48)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.sync.tasks.RetryingGetHeaderFromPeerByNumberTask.lambda$executePeerTask$0(RetryingGetHeaderFromPeerByNumberTask.java:72)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$2(AbstractPeerRequestTask.java:83)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
eth1_1    |     at java.base/java.util.Optional.ifPresent(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.handleMessage(AbstractPeerRequestTask.java:104)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$0(AbstractPeerRequestTask.java:67)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.dispatchBufferedResponses(RequestManager.java:171)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.processMessage(RequestManager.java:162)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.RequestManager.lambda$dispatchResponse$0(RequestManager.java:55)
eth1_1    |     at java.base/java.util.ArrayList.forEach(Unknown Source)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.RequestManager.dispatchResponse(RequestManager.java:55)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.EthPeer.dispatch(EthPeer.java:268)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.EthPeers.dispatchMessage(EthPeers.java:111)
eth1_1    |     at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:264)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
eth1_1    |     at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
eth1_1    |     at java.base/java.lang.Iterable.forEach(Unknown Source)
eth1_1    |     at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:99)
eth1_1    |     at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:33)
eth1_1    |     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
eth1_1    |     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
eth1_1    |     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
eth1_1    |     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
eth1_1    |     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
eth1_1    |     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
eth1_1    |     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
eth1_1    |     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
eth1_1    |     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
eth1_1    |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
eth1_1    |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
eth1_1    |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
eth1_1    |     at java.base/java.lang.Thread.run(Unknown Source)
eth1_1    | Caused by: java.util.concurrent.CancellationException: FastSyncDownloader stopped
eth1_1    |     at org.hyperledger.besu.ethereum.eth.sync.fastsync.FastSyncDownloader.downloadChainAndWorldState(FastSyncDownloader.java:153)
eth1_1    |     ... 78 more
eth1_1    | 2021-01-28 13:35:13.728+00:00 | Thread-1 | ERROR | Pruner | Failed to shutdown Pruner executor service.
eth1_1    | 2021-01-28 13:35:13.728+00:00 | Thread-1 | INFO  | NetworkRunner | Stopping Network.
eth1_1    | 2021-01-28 13:35:13.754+00:00 | Thread-1 | INFO  | EthProtocolManager | Stopping eth Subprotocol.
```

**Comment by RatanRSur** [comment]
Thanks for reporting this. There are a couple of instance where this happens but it's typically not indicative of something actually going wrong in the shutdown process. Can you confirm that everything was alright when you restarted the node?

**Comment by yorickdowne** [comment]
Everything was fine when I restarted the node. I am reporting these only because I was encouraged to on the Besu discord, along the lines of “Besu should catch all exceptions”. I haven’t had any issues with Besu corrupting data or refusing to sync, so far.

**Comment by RatanRSur** [comment]
Ok cool, yes, we welcome the issue! We'll get around to tidying this up someday.
