### ISSUE TITLE
DeleteRangeCF error when enabling pruning

### ISSUE THREAD

**Issue by 3nprob** [hyperledger/besu#1913]
### Description
As a user, I want to have the node open up the http rpc interface once synced 

### Acceptance Criteria
* Service listening on specified port

### Steps to Reproduce (Bug)
1. Start full pruned sync on Rinkeby testnet
2. Wait until caught up with current head
3. Attempt to connect to RPC interface. 

**Expected behavior:**
Connection opens

**Actual behavior:**
Connection refused

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: [`besu/v21.1.0-RC2/linux-x86_64/oracle_openjdk-java-15`]
* Java version: [`OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)`]
* OS Name & Version: Docker, host is Debian 10 / Debian 11
* Kernel Version: [`Linux 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 x86_64 GNU/Linux`]
* Docker Version: [`20.10.2`]

### Additional Information

Running on self-managed hardware/OS (not cloud/vm) in docker. Local DNS is working. State is stored on a local zfs volume.

There seems to be some issue with the node not being able to tranbsition to stynced state once caught up, it throws some errors and then continues to download and sync new blocks, with the number of connected peers increasing as expected and by the looks of it, it's keeping up with current head of chain.

```
main | INFO  | AbstractAltBnPrecompiledContract | Using LibEthPairings native alt bn128
main | INFO  | SECP256K1 | Using native secp256k1
main | INFO  | Besu | Starting Besu version: besu/v21.1.0-RC2/linux-x86_64/oracle_openjdk-java-15
main | INFO  | Besu | Static Nodes file = /besu/data/static-nodes.json
main | INFO  | StaticNodesParser | StaticNodes file /besu/data/static-nodes.json does not exist, no static connections will be created.
main | INFO  | Besu | Connecting to 0 static nodes.
main | INFO  | Besu | Security Module: localfile
main | INFO  | KeyPairUtil | Loaded public key REDACTED from /besu/data/key
main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /besu/data
main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /besu/data. Version 1
main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Frontier: 0, Homestead: 1, TangerineWhistle: 2, SpuriousDragon: 3, Byzantium: 1035301, Constantinople: 3660663, Petersburg: 4321234, Istanbul: 5435345]
main | INFO  | FastDownloaderFactory | Fast sync was requested, but cannot be enabled because the local blockchain is not empty.
main | INFO  | RunnerBuilder | Detecting NAT service.
main | INFO  | Runner | Starting Ethereum main loop ...
main | INFO  | NatService | No NAT environment detected so no service could be started
main | INFO  | NetworkRunner | Starting Network.
main | INFO  | DefaultP2PNetwork | Starting DNS discovery with URL enrtree://REDACTED@all.rinkeby.ethdisco.net
nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0.0.0.0:REDACTED.
main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=REDACTED
vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0.0.0.0 and port=REDACTED
vert.x-eventloop-thread-1 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0.0.0.0:REDACTED
main | INFO  | DefaultP2PNetwork | Enode URL enode://REDACTED@REDACTED
main | INFO  | DefaultP2PNetwork | Node address REDACTED
main | INFO  | DefaultSynchronizer | Starting synchronizer.
StatePruning-0 | INFO  | Pruner | Starting Pruner.
main | INFO  | FullSyncDownloader | Starting full sync.
main | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
main | INFO  | Runner | Ethereum main loop is up.
StatePruning-0 | ERROR | Besu | Uncaught exception in thread "StatePruning-0"
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:211)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:62)
        at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.clear(SegmentedKeyValueStorageAdapter.java:40)
        at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.clearMarks(MarkSweepPruner.java:228)
        at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.prepare(MarkSweepPruner.java:123)
        at org.hyperledger.besu.ethereum.worldstate.Pruner.lambda$start$0(Pruner.java:97)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
        at org.rocksdb.RocksDB.deleteRange(Native Method)
        at org.rocksdb.RocksDB.deleteRange(RocksDB.java:1493)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:206)
        ... 8 more
main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
main | INFO  | LogBloomCacheMetadata | Lookup cache metadata file in data directory: /besu/data/caches
nioEventLoopGroup-3-1 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
Timer-0 | ERROR | Besu | Uncaught exception in thread "Timer-0"
java.net.SocketTimeoutException
        at org.xbill.DNS.Resolver.send(Resolver.java:157)
        at org.apache.tuweni.discovery.DNSResolver.resolveRecordRaw(DNSResolver.kt:149)
        at org.apache.tuweni.discovery.DNSResolver.resolveRecord(DNSResolver.kt:72)
        at org.apache.tuweni.discovery.DNSResolver.visitTree(DNSResolver.kt:114)
        at org.apache.tuweni.discovery.DNSResolver.visitTree(DNSResolver.kt:105)
        at org.apache.tuweni.discovery.DNSResolver.collectAll(DNSResolver.kt:94)
        at org.apache.tuweni.discovery.DNSTimerTask.run(DNSDaemon.kt:70)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
nioEventLoopGroup-3-3 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 1
nioEventLoopGroup-3-3 | INFO  | SyncTargetManager | Found common ancestor with peer REDACTED... at block 8076206
EthScheduler-Workers-2 | INFO  | PersistBlockTask | Imported #8,076,208 / 15 tx / 0 om / 2,260,911 (22.6%) gas / (0xdda7250c3bacf9809521b66b9c548b8df6640bdc94d9a7a04a2a698671ca5032) in 0.149s. Peers: 1
EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #8,076,209 / 10 tx / 0 om / 1,312,420 (13.1%) gas / (0xb86fa09ddd4b194635ae992fd83927c966630efa213b2abe593e7c89dc3af8b0) in 0.089s. Peers: 1
```

### Environment variables:

```
BESU_DATA_PATH=/besu/data
BESU_GRAPHQL_HTTP_HOST=0.0.0.0
BESU_METRICS_PORT=25943
BESU_NAT_METHOD=NONE
BESU_NETWORK=rinkeby
BESU_P2P_HOST=REDACTED
BESU_P2P_INTERFACE=0.0.0.0
BESU_P2P_PORT=REDACTED
BESU_PID_PATH=/tmp/pid
BESU_PRUNING_BLOCKS_RETAINED=10000
BESU_PRUNING_ENABLED=true
BESU_RPC_HTTP_HOST=0.0.0.0
BESU_RPC_HTTP_PORT=26695
BESU_RPC_WS_HOST=0.0.0.0
BESU_RPC_WS_PORT=8546
BESU_SYNC_MODE=FAST
```

```
# netstat -tanpu | grep LISTEN
tcp        0      0 0.0.0.0:$P2P_PORT           0.0.0.0:*               LISTEN      -
```

**Comment by 3nprob** [comment]
The error, if related, seems to come from here:  https://github.com/facebook/rocksdb/blob/master/include/rocksdb/write_batch.h#L226

**Comment by shemnon** [comment]
Set `BESU_RPC_HTTP_ENABLED=true`

**Comment by 3nprob** [comment]
Thanks @shemnon , that was it for the RPC :flushed: 

The DeleteRangeCF error seems related to pruning - it disappears if I disable pruning, so seems like that's not functional.

**Comment by shemnon** [comment]
I've flagged it internally.  It's curious because all our local pruning nodes never complained.  Seems to be related to column families.

**Comment by 3nprob** [comment]
Let me know if there's anything I can do to help with debugging. For the time being I have the space to spare.

**Comment by yorickdowne** [comment]
Started a fresh mainnet full sync with `--pruning-enabled=true` and `--sync-mode=FULL`, same error after the first 1000 blocks:

```
eth1_1    | 2021-03-17 13:28:51.135+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 1000 (0x5b45..5d58), - Mg/s, Peers: 4
eth1_1    | 2021-03-17 13:28:54.782+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | Pruner | Begin sweeping unused nodes for pruning. Keeping full state for blocks 1 to 1025
eth1_1    | 2021-03-17 13:28:55.143+00:00 | StatePruning-2 | ERROR | Besu | Uncaught exception in thread "StatePruning-2"
eth1_1    | org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
eth1_1    |     at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:211)
eth1_1    |     at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:62)
eth1_1    |     at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.clear(SegmentedKeyValueStorageAdapter.java:40)
eth1_1    |     at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.clearMarks(MarkSweepPruner.java:229)
eth1_1    |     at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.sweepBefore(MarkSweepPruner.java:219)
eth1_1    |     at org.hyperledger.besu.ethereum.worldstate.Pruner.lambda$sweep$2(Pruner.java:159)
eth1_1    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
eth1_1    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
eth1_1    |     at java.base/java.lang.Thread.run(Unknown Source)
eth1_1    | Caused by: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
eth1_1    |     at org.rocksdb.RocksDB.deleteRange(Native Method)
eth1_1    |     at org.rocksdb.RocksDB.deleteRange(RocksDB.java:1493)
eth1_1    |     at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:206)
eth1_1    |     ... 8 more
```

**Comment by RatanRSur** [comment]
We're working on an overhaul to how we structure our database that should make pruning like this a thing of the past. I haven't looked into this but I'm assuming this could be a zfs issue? I recommend turning pruning off for the time being.

**Comment by yorickdowne** [comment]
I can’t see this being a ZFS issue. DeleteRangeCF is a DB function isn’t it?

Plus, I think I tested it on a VPS, no ZFS there. The file system is just a file system, standard Linux fare.

**Comment by RatanRSur** [comment]
Perhaps you're right but I jumped to that being the likely case since delete range has never given us issues and it sounds like it might be because there's some non-standard call that perhaps zfs doesn't implement so rocksdb then says it's not implemented. Again, perhaps you're right but since our new Bonsai Tries database format is our main focus right now, there might not be a fix to this until that becomes production ready.

**Comment by jondoe1337** [comment]
Same problem here with:
```
      - "--sync-mode=FAST"
      - "--pruning-enabled=true"
      - "--pruning-blocks-retained=1024"
```

Resulting during startup with:
```
2021-07-05 12:10:30.342+00:00 | StatePruning-0 | INFO  | Pruner | Starting Pruner.
2021-07-05 12:10:30.342+00:00 | main | INFO  | FullSyncDownloader | Starting full sync.
2021-07-05 12:10:30.360+00:00 | main | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-07-05 12:10:30.397+00:00 | main | INFO  | JsonRpcHttpService | Starting JSON-RPC service on 0.0.0.0:8545
2021-07-05 12:10:30.387+00:00 | StatePruning-0 | ERROR | Besu | Uncaught exception in thread "StatePruning-0"
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:211)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:62)
	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.clear(SegmentedKeyValueStorageAdapter.java:40)
	at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.clearMarks(MarkSweepPruner.java:229)
	at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.prepare(MarkSweepPruner.java:124)
	at org.hyperledger.besu.ethereum.worldstate.Pruner.lambda$start$0(Pruner.java:97)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
	at org.rocksdb.RocksDB.deleteRange(Native Method)
	at org.rocksdb.RocksDB.deleteRange(RocksDB.java:1493)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:206)
	... 8 more
```

The node was previously configured with 2048 retained blocks, reduced that to 1024.

The disk usage is still 1.4TB - obviously the pruning does not work at all!? 🤔

**Comment by jcodic** [comment]
Build from source v 21.7.3.
--network=mainnet --sync-mode=FAST --pruning-enabled=true
Get same error always when restarting besu.

**Comment by non-fungible-nelson** [comment]
Closing due to bonsai
