### ISSUE TITLE
NullpointerException during mainnet full synchronization (with experimental bonsai trie storage mode)

### ISSUE THREAD

**Issue by matkt** [hyperledger/besu#1939]
### Description

An error appeared during mainnet full synchronization. This doesn't seem to be related to fastsync and it stops synchronization on Block **11 905 272**

https://grafana-metrics-ohio.ops.pegasys.tech/d/5S-6O8VZk/besu-overview?var-system=dev-besu-ohio-mainnet-karim-bonsai-trie-test-fast-final

### Steps to Reproduce (Bug)
Run a mainnet synchronisation

**Expected behavior:** Import the block correctly

**Actual behavior:** Throw an exception

`{"timestamp":"2021-02-22T06:38:36,407","level":"ERROR","thread":"EthScheduler-Workers-2","class":"MainnetTransactionProcessor","message":"Critical Exception Processing Transaction","throwable":" java.lang.NullPointerException\n\tat java.base/java.util.Objects.requireNonNull(Objects.java:221)\n\tat java.base/java.util.Optional.<init>(Optional.java:107)\n\tat java.base/java.util.Optional.of(Optional.java:120)\n\tat org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValueBySlotHash(BonsaiWorldStateUpdater.java:297)\n\tat org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValue(BonsaiWorldStateUpdater.java:288)\n\tat org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.getStorageValue(BonsaiAccount.java:242)\n\tat org.hyperledger.besu.ethereum.core.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:217)\n\tat org.hyperledger.besu.ethereum.core.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:217)\n\tat org.hyperledger.besu.ethereum.core.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:217)\n\tat org.hyperledger.besu.ethereum.core.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:217)\n\tat org.hyperledger.besu.ethereum.mainnet.IstanbulGasCalculator.calculateStorageCost(IstanbulGasCalculator.java:72)\n\tat org.hyperledger.besu.ethereum.vm.operations.SStoreOperation.execute(SStoreOperation.java:66)\n\tat org.hyperledger.besu.ethereum.vm.EVM.lambda$executeNextOperation$0(EVM.java:82)\n\tat org.hyperledger.besu.ethereum.vm.OperationTracer.lambda$static$0(OperationTracer.java:26)\n\tat org.hyperledger.besu.ethereum.vm.EVM.executeNextOperation(EVM.java:77)\n\tat org.hyperledger.besu.ethereum.vm.EVM.runToHalt(EVM.java:55)\n\tat org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:155)\n\tat org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:167)\n\tat org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:446)\n\tat org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:360)\n\tat org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:147)\n\tat org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:43)\n\tat org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:65)\n\tat org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:135)\n\tat org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:108)\n\tat org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)\n\tat org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)\n\tat org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.executeTask(PersistBlockTask.java:199)\n\tat org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)\n\tat org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.run(AbstractEthTask.java:75)\n\tat org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.runImportTask(BlockPropagationManager.java:347)\n\tat org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.validateAndProcessPendingBlock(BlockPropagationManager.java:325)\n\tat org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.lambda$importOrSavePendingBlock$5(BlockPropagationManager.java:313)\n\tat org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:97)\n\tat org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleSyncWorkerTask$0(EthScheduler.java:108)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"}
`

**Comment by shemnon** [comment]
I think the fix is to make BonsaiWorldStateUpdater.java:297 an Optional.ofNullable.  The updated portion of the value can validly be null (indicating it was deleted), and that translates downstream into a zero.  The call a few steps down deals with an empty optional.

**Comment by shemnon** [comment]
Simple fix result in this stack trace - 
{"timestamp":"2021-02-23T19:27:20,265","level":"ERROR","thread":"EthScheduler-Services-5 (importBlock)","class":"PipelineChainDownloader","message":"Chain download failed. Restarting after short delay.","throwable":" java.util.concurrent.CompletionException: java.lang.RuntimeException: World State Root does not match expected value, header 0xfee64192f1b5c0dbfadacfaf08aca66313c83aca99f7a19190cbd95f9d265f87 calculated 0x9b45a625b3ae077f7e3c879e51b1c1cbb170c4a7e0bc6caa246cffebf46b7fb5
at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:179)
at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:158)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: java.lang.RuntimeException: World State Root does not match expected value, header 0xfee64192f1b5c0dbfadacfaf08aca66313c83aca99f7a19190cbd95f9d265f87 calculated 0x9b45a625b3ae077f7e3c879e51b1c1cbb170c4a7e0bc6caa246cffebf46b7fb5
at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.persist(BonsaiPersistedWorldState.java:244)
at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:208)
at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:44)
at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:75)
at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:152)
at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:110)
at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)
at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:59)
at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:151)\n\t... 5 more\n"}

**Comment by shemnon** [comment]
Some more detail.  Looks like it's 2/3 tx combo.

First, we need to have a call that creates a new contract, that writes to it's contract storage, then self destructs.  It needs to not exist in the world state prior to the block being processed.

Next, we have a second TX, that also create a contract at the same address, and then writes to a field that is the same value that the field had prior to reaching self-destruct.

I think I need to add a special case for deleted accounts that when the account didn't exist prior to the block we remove the bonsaivalue from the trie log instead of setting the updated to null.  Or something else....
