### ISSUE TITLE
besu blocks export subcommand fails

### ISSUE THREAD

**Issue by b-rohit** [hyperledger/besu#1997]
### Steps to Reproduce (Bug)
1. besu --data-path=/opt/besu/data/ blocks export --start-block=2 --end-block=3 --to=/home/exportblock.bin

**Expected behavior:** [What you expect to happen]
it should export the blocks in the given file in the RLP format

**Actual behavior:** [What actually happens]
```
2021-03-10 12:26:17.013+00:00 | main | INFO  | BlocksSubCommand | Export RLP block data to file /home/exportblock.bin
2021-03-10 12:26:19.444+00:00 | main | INFO  | KeyPairUtil | Loaded key 0x642147e9304f8237f7195c3dc125b5e485b7615948fa96a61e8dbfe554a891d7a0244222050785d0663c1a42d085fa266479867f12ef666a93106eb70fab99ed from /opt/besu/data/key
2021-03-10 12:26:19.548+00:00 | main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /opt/besu/data
2021-03-10 12:26:19.679+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /opt/besu/data. Version 1
picocli.CommandLine$ExecutionException: org.rocksdb.RocksDBException: While lock file: /opt/besu/data/database/LOCK: Resource temporarily unavailable
        at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:1222)
        at org.hyperledger.besu.cli.subcommands.blocks.BlocksSubCommand$ExportSubCommand.createBesuController(BlocksSubCommand.java:309)
        at org.hyperledger.besu.cli.subcommands.blocks.BlocksSubCommand$ExportSubCommand.run(BlocksSubCommand.java:292)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2322)
        at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:61)
        at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:31)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2322)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1053)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:922)
        at org.hyperledger.besu.Besu.main(Besu.java:49)
Caused by: org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: While lock file: /opt/besu/data/database/LOCK: Resource temporarily unavailable
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.<init>(RocksDBColumnarKeyValueStorage.java:133)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBKeyValueStorageFactory.create(RocksDBKeyValueStorageFactory.java:118)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProviderBuilder.build(KeyValueStorageProviderBuilder.java:64)
        at org.hyperledger.besu.cli.BesuCommand.keyStorageProvider(BesuCommand.java:1695)
        at org.hyperledger.besu.cli.BesuCommand.getControllerBuilder(BesuCommand.java:1251)
        at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:1220)
        ... 15 more
Caused by: org.rocksdb.RocksDBException: While lock file: /opt/besu/data/database/LOCK: Resource temporarily unavailable
        at org.rocksdb.TransactionDB.open(Native Method)
        at org.rocksdb.TransactionDB.open(TransactionDB.java:90)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.<init>(RocksDBColumnarKeyValueStorage.java:109)
        ... 20 more
```

**Frequency:** [What percentage of the time does it occur?]
Every time

### Versions (Add all that apply)
* Software version: [`besu --version`]
`besu/v1.4.3/linux-x86_64/oracle_openjdk-java-11`
* Java version: [`java -version`]
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode, sharing)
```
* OS Name & Version: [`cat /etc/*release`]
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Docker Version: [`docker version`]
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```
* Cloud VM, type, size: [Amazon Web Services I3-large]
Google cloud VM instance

**Comment by macfarla** [comment]
@b-rohit This error means the exporter can't get a lock on the db. This would be explained by Besu still running. Can you try to run the export command after stopping Besu?

**Comment by RatanRSur** [comment]
@b-rohit Closing this assuming that the lock file was indeed the issue. Feel free to reopen if not.
