### ISSUE TITLE
RocksDBException (LockTimeout) during state pruning

### ISSUE THREAD

**Issue by adetante** [hyperledger/besu#2056]
### Description
An RocksDBException exception occurs randomly (after several days) on validator nodes with pruning enabled.  
From that moment on, state pruning is no longer performed on this node until the next restart.

Error trace:

```
Uncaught exception in thread "StatePruning-3608"
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: TimedOut(LockTimeout)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.tryDelete(RocksDBColumnarKeyValueStorage.java:186)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.tryDelete(RocksDBColumnarKeyValueStorage.java:62)
	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.tryDelete(SegmentedKeyValueStorageAdapter.java:65)
	at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage.lambda$prune$0(WorldStateKeyValueStorage.java:102)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage.prune(WorldStateKeyValueStorage.java:98)
	at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.sweepBefore(MarkSweepPruner.java:216)
	at org.hyperledger.besu.ethereum.worldstate.Pruner.lambda$sweep$2(Pruner.java:159)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.rocksdb.RocksDBException: TimedOut(LockTimeout)
	at org.rocksdb.RocksDB.delete(Native Method)
	at org.rocksdb.RocksDB.delete(RocksDB.java:1046)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.tryDelete(RocksDBColumnarKeyValueStorage.java:180)
	... 12 more
```

### Versions
* Docker image: `hyperledger/besu:20.10.1`
* Cloud VM, type, size: GCP Kubernetes Engine with SSD disks

**Comment by RatanRSur** [comment]
We might get to this but our state control story going forward is to double down on Bonsai Tries, which will allow us to keep the state at under 100gbs. For now I'd recommend restarting the node and if you see the lock again, to disable pruning.
