### ISSUE TITLE
Run web3js-eea examples with Besu <> Tessera network

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#2071]
Run web3js-eea examples with Besu <> Tessera network
Besu with --privacy-enabled
Tessera with mode=orion
- [x] accessPublicState
- [x] concurrentPrivateTransactions
- [x] eventLogs
- [x] multiNodeExample
- [x] multiNodeExamplePrivacyGroup
- [x] multiNodeExamplePrivateCall
- [x] privacyGroupManagement

- [x] multiTenancy
- [x] multiTenancyExampleOnchainPrivacyEventLogs
- [ ] multiTenancyExamplePrivateCall
- [x] onChainPrivacy

**Comment by macfarla** [comment]
onchainPrivacy examples work if 3 besu nodes are running, otherwise the scripts hang - suspect this is the same with Besu/Orion

**Comment by macfarla** [comment]
note for password-protected keys, I had to generate new ones for tessera https://docs.tessera.consensys.net/en/latest/HowTo/Generate-Keys/File-Stored-Keys/

**Comment by macfarla** [comment]
multiTenancyExamplePrivateCall

```
➜  multiTenancyExamplePrivateCall git:(deploy-contract-size-bug) ✗ node deployContract.js
creating privacy group
(node:32708) UnhandledPromiseRejectionWarning: Error: Returned error: Unable to determine nonce for account in group.
    at Object.ErrorResponse (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/sallymacfarlane/workspace/web3js-eea/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/web3-providers-http/src/index.js:110:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
```
Besu shows this error
```
2021-03-26 14:43:55.420+10:00 | vert.x-worker-thread-8 | ERROR | PrivGetTransactionCount | Privacy group Id[J6uZHKOrVqDe4djJuR3ejJtYgtAzfja8wMssoNzLm4U=] not found
org.hyperledger.besu.enclave.EnclaveClientException: Privacy group Id[J6uZHKOrVqDe4djJuR3ejJtYgtAzfja8wMssoNzLm4U=] not found
	at org.hyperledger.besu.enclave.Enclave.parseResponse(Enclave.java:173)
	at org.hyperledger.besu.enclave.Enclave.handleJsonResponse(Enclave.java:159)
	at org.hyperledger.besu.enclave.Enclave.lambda$retrievePrivacyGroup$7(Enclave.java:135)
```
and it doesn't seem to be sending the privacygroup to tessera

**Comment by macfarla** [comment]
but the multiNodeExamplePrivateCall works fine - so is this to do with multi-tenancy setup?
```
➜  multiNodeExamplePrivateCall git:(deploy-contract-size-bug) ✗ node deployContract.js
The privacy group created is: Rch1DQZfWN5twvKIN7poE0ofYx7ZjxZZEX/XB+8HUcM=
got privacy group id Rch1DQZfWN5twvKIN7poE0ofYx7ZjxZZEX/XB+8HUcM=
Transaction Hash  0xc5f907bae5a8a94a37b4e6f5abfd503fe7db3dd57c11a986590a094efb649a9f
Waiting for transaction to be mined ...
Private Transaction Receipt
 {
  contractAddress: '0x4de2f71ab6705efc8a26f330abd4b0a73eec526a',
  from: '0xfe3b557e8fb62b89f4916b721be55ceb828dbd73',
```
and I can see tessera creating the group
```
2021-03-26 15:18:02.151 [pool-2-thread-1] INFO  c.q.t.p.p.PartyInfoBroadcaster - Finished PartyInfo polling round
2021-03-26 15:18:05.207 [qtp414978148-41] INFO  c.q.tessera.q2t.PrivacyGroupResource - Enter Request : POST : /createPrivacyGroup
2021-03-26 15:18:05.211 [pool-10-thread-1] INFO  c.q.t.q2t.RestPrivacyGroupPublisher - Publishing privacy group to http://localhost:8082/
2021-03-26 15:18:05.228 [pool-10-thread-1] INFO  c.q.t.q2t.RestPrivacyGroupPublisher - Published privacy group to http://localhost:8082/
2021-03-26 15:18:05.230 [qtp414978148-41] INFO  c.q.tessera.q2t.PrivacyGroupResource - Exit Request : POST : /createPrivacyGroup
2021-03-26 15:18:05.230 [qtp414978148-41] INFO  c.q.tessera.q2t.PrivacyGroupResource - Response for createPrivacyGroup : 200 OK
2021-03-26 15:18:05.283 [qtp414978148-85] INFO  c.q.tessera.q2t.PrivacyGroupResource - Enter Request : POST : /retrievePrivacyGroup
2021-03-26 15:18:05.292 [qtp414978148-85] INFO  c.q.tessera.q2t.PrivacyGroupResource - Exit Request : POST : /retrievePrivacyGroup
2021-03-26 15:18:05.293 [qtp414978148-85] INFO  c.q.tessera.q2t.PrivacyGroupResource - Response for retrievePrivacyGroup : 200 OK
2021-03-26 15:18:05.302 [qtp414978148-87] INFO  c.q.t.q2t.BesuTransactionResource - Enter Request : POST : /send
2021-03-26 15:18:05.362 [pool-5-thread-1] INFO  c.q.tessera.q2t.RestPayloadPublisher - Publishing message to http://localhost:8082/
2021-03-26 15:18:05.382 [pool-5-thread-1] INFO  c.q.tessera.q2t.RestPayloadPublisher - Published to http://localhost:8082/
2021-03-26 15:18:05.384 [qtp414978148-87] INFO  c.q.t.q2t.BesuTransactionResource - Exit Request : POST : /send
2021-03-26 15:18:05.384 [qtp414978148-87] INFO  c.q.t.q2t.BesuTransactionResource - Response for send : 200 OK
2021-03-26 15:18:06.316 [qtp414978148-85] INFO  c.q.t.q2t.BesuTransactionResource - Enter Request : POST : /receive
```

**Comment by macfarla** [comment]
ok this is working now, starting with an empty db

```
2021-03-29 08:59:14.773 [qtp414978148-104] INFO  c.q.tessera.q2t.PrivacyGroupResource - Enter Request : POST : /createPrivacyGroup
2021-03-29 08:59:14.846 [pool-10-thread-1] INFO  c.q.t.q2t.RestPrivacyGroupPublisher - Publishing privacy group to http://localhost:8082/
2021-03-29 08:59:14.903 [pool-10-thread-1] INFO  c.q.t.q2t.RestPrivacyGroupPublisher - Published privacy group to http://localhost:8082/
2021-03-29 08:59:14.905 [qtp414978148-104] INFO  c.q.tessera.q2t.PrivacyGroupResource - Exit Request : POST : /createPrivacyGroup
2021-03-29 08:59:14.905 [qtp414978148-104] INFO  c.q.tessera.q2t.PrivacyGroupResource - Response for createPrivacyGroup : 200 OK
2021-03-29 08:59:14.969 [qtp414978148-41] INFO  c.q.tessera.q2t.PrivacyGroupResource - Enter Request : POST : /retrievePrivacyGroup
2021-03-29 08:59:14.981 [qtp414978148-41] INFO  c.q.tessera.q2t.PrivacyGroupResource - Exit Request : POST : /retrievePrivacyGroup
2021-03-29 08:59:14.981 [qtp414978148-41] INFO  c.q.tessera.q2t.PrivacyGroupResource - Response for retrievePrivacyGroup : 200 OK
2021-03-29 08:59:14.994 [qtp414978148-102] INFO  c.q.t.q2t.BesuTransactionResource - Enter Request : POST : /send
2021-03-29 08:59:15.067 [pool-5-thread-1] INFO  c.q.tessera.q2t.RestPayloadPublisher - Publishing message to http://localhost:8082/
2021-03-29 08:59:15.102 [pool-5-thread-1] INFO  c.q.tessera.q2t.RestPayloadPublisher - Published to http://localhost:8082/
2021-03-29 08:59:15.105 [qtp414978148-102] INFO  c.q.t.q2t.BesuTransactionResource - Exit Request : POST : /send
2021-03-29 08:59:15.105 [qtp414978148-102] INFO  c.q.t.q2t.BesuTransactionResource - Response for send : 200 OK
2021-03-29 08:59:16.127 [qtp414978148-104] INFO  c.q.t.q2t.BesuTransactionResource - Enter Request : POST : /receive
2021-03-29 08:59:16.134 [qtp414978148-104] INFO  c.q.t.t.TransactionManagerImpl - Lookup transaction UuNvcecFhXxlMMdMCrgcRwr+jmS7tKdJtWXeTRtl4SY=
2021-03-29 08:59:16.160 [qtp414978148-104] INFO  c.q.t.q2t.BesuTransactionResource - Exit Request : POST : /receive
2021-03-29 08:59:16.160 [qtp414978148-104] INFO  c.q.t.q2t.BesuTransactionResource - Response for receive : 200 OK
2021-03-29 08:59:16.168 [qtp414978148-102] INFO  c.q.tessera.q2t.PrivacyGroupResource - Enter Request : POST : /retrievePrivacyGroup
2021-03-29 08:59:16.169 [qtp414978148-102] INFO  c.q.tessera.q2t.PrivacyGroupResource - Exit Request : POST : /retrievePrivacyGroup
2021-03-29 08:59:16.169 [qtp414978148-102] INFO  c.q.tessera.q2t.PrivacyGroupResource - Response for retrievePrivacyGroup : 200 OK
2021-03-29 08:59:17.158 [qtp414978148-104] INFO  c.q.t.q2t.BesuTransactionResource - Enter Request : POST : /receive
2021-03-29 08:59:17.158 [qtp414978148-104] INFO  c.q.t.t.TransactionManagerImpl - Lookup transaction UuNvcecFhXxlMMdMCrgcRwr+jmS7tKdJtWXeTRtl4SY=
2021-03-29 08:59:17.176 [qtp414978148-104] INFO  c.q.t.q2t.BesuTransactionResource - Exit Request : POST : /receive
2021-03-29 08:59:17.176 [qtp414978148-104] INFO  c.q.t.q2t.BesuTransactionResource - Response for receive : 200 OK
2021-03-29 08:59:18.834 [pool-2-thread-1] INFO  c.q.t.p.p.PartyInfoBroadcaster - Started PartyInfo polling round
2021-03-29 08:59:18.836 [pool-2-thread-1] INFO  c.q.t.p.p.PartyInfoBroadcaster - Finished PartyInfo polling round
```

**Comment by macfarla** [comment]
Thought this was working but it isn't. Same thing is happening with Besu/Orion though.  With onchain groups turned on, 

```
creating ONCHAIN privacy group from=AwEia3o72fIT9YV+Aya0auIahYRUlev9faAvubHQFzw= with participants x6q2llVYRizI6n93OUu0Q5JlYmYDxlnPqx33Qb/Hizs= and KkOjNLmCI6r+mICrC6l+XuEDjFEzQllaMQMpWLl4y1s=
generated privacyGroupId o0HHO/OEI4FacH0jRoFClXWXYerX1yqwJmhz4zX0wJk=
func 0xb4926e2500000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002c7aab6965558462cc8ea7f77394bb4439265626603c659cfab1df741bfc78b3b2a43a334b98223aafe9880ab0ba97e5ee1038c513342595a31032958b978cb5b
Waiting for transaction to be mined ...
Created privacy group
{
  from: '0xfe3b557e8fb62b89f4916b721be55ceb828dbd73',
  to: '0x000000000000000000000000000000000000007c',
  output: '0x',
  commitmentHash: '0xa03f9f867d5135b4230e3d3bc2d945811538cb2acc7c3260d968f82fc2abbd2a',
  transactionHash: '0xdccc41153f7976daf0e2cda384ca2b344d5d376c5f8e892f58818fee326f4a98',
  privateFrom: 'AwEia3o72fIT9YV+Aya0auIahYRUlev9faAvubHQFzw=',
  privacyGroupId: 'o0HHO/OEI4FacH0jRoFClXWXYerX1yqwJmhz4zX0wJk=',
  status: '0x0',
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  blockHash: '0x76a8491d9e0b999c70ed01b891228d03e181a9eef1886cb3dd60efac0d359498',
  blockNumber: '0xd23',
  transactionIndex: '0x0'
}
eea.sendRawTransaction with 0x608060405234801561001057600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550610221806100606000396000f300608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680633fa4f2451461005c5780636057361d1461008757806367e404ce146100b4575b600080fd5b34801561006857600080fd5b5061007161010b565b6040518082815260200191505060405180910390f35b34801561009357600080fd5b506100b260048036038101908080359060200190929190505050610115565b005b3480156100c057600080fd5b506100c96101cb565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6000600254905090565b7fc9db20adedc6cf2b5d25252b101ab03e124902a73fcb12b753f3d1aaa2d8f9f53382604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020018281526020019250505060405180910390a18060028190555033600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b6000600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff169050905600a165627a7a723058208efaf938851fb2d235f8bf9a9685f149129a30fe0f4b20a6c1885dc02f639eba0029
privateFrom AwEia3o72fIT9YV+Aya0auIahYRUlev9faAvubHQFzw=
privacyGroupId o0HHO/OEI4FacH0jRoFClXWXYerX1yqwJmhz4zX0wJk=
privateKey 8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63
(node:48104) UnhandledPromiseRejectionWarning: Error: Returned error: Onchain Privacy group does not exist.
```
and with onchain groups turned off,
```➜  multiTenancyExamplePrivateCall git:(deploy-contract-size-bug) ✗ node deployContract.js
creating ONCHAIN privacy group from=GGilEkXLaQ9yhhtbpBT03Me9iYa7U/mWXxrJhnbl1XY= with participants JhOQwapQgv36ENsICu4K21YoeU+vFLvEU/Hnt/Fcoxc= and KkOjNLmCI6r+mICrC6l+XuEDjFEzQllaMQMpWLl4y1s=
generated privacyGroupId IjBO/YPePdZfrnuioucctraGh7P/cJzV2U4qSeKh1+w=
func 0xb4926e2500000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002261390c1aa5082fdfa10db080aee0adb5628794faf14bbc453f1e7b7f15ca3172a43a334b98223aafe9880ab0ba97e5ee1038c513342595a31032958b978cb5b
(node:49509) UnhandledPromiseRejectionWarning: Error: Returned error: Unable to determine nonce for account in group.
    at Object.ErrorResponse (/Users/sallymacfarlane/workspace/web3js-eea/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/sallymacfarlane/workspace/web3js-eea/node_modules/web3-core-requestmanager/src/index.js:140:36
```

**Comment by macfarla** [comment]
Have logged a bug for the example that isn't working
