### ISSUE TITLE
legacy privacy groups are created with duplicate members

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2081]
This might be an issue with Besu, or with Orion,

Running the web3js-eea/concurrentPrivateTransactions - a privacy group is created with "one" member but they are in there twice - privateFrom = privateFor

```
// options used to create a privacy group with only one member
const privacyOptions = {
  privateFrom: orion.node1.publicKey,
  privateFor: [orion.node1.publicKey],
  privateKey: besu.node1.privateKey
};
```

as in, if I run it with Besu/Orion, and then do
```
{
    "jsonrpc": "2.0",
    "method": "priv_findPrivacyGroup",
    "params": [
        [
            "GGilEkXLaQ9yhhtbpBT03Me9iYa7U/mWXxrJhnbl1XY="
        ]
    ],
    "id": 1
}
```

the result is a privacy group with the same member in there twice
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "privacyGroupId": "MC4aHjApHsGb0j5glU2iAj5KcR5LId52S0BU9mtdeuY=",
            "name": "legacy",
            "description": "Privacy groups to support the creation of groups by privateFor and privateFrom",
            "type": "LEGACY",
            "members": [
                "GGilEkXLaQ9yhhtbpBT03Me9iYa7U/mWXxrJhnbl1XY=",
                "GGilEkXLaQ9yhhtbpBT03Me9iYa7U/mWXxrJhnbl1XY="
            ]
        }
    ]
}
```

**Comment by macfarla** [comment]
Orion accepts these privacy groups but Tessera rejecting in migration (PK violation)
```
2021-03-25 13:53:05.790+10:00 | vert.x-worker-thread-13 | ERROR | DefaultPrivacyController | Failed to store private transaction in enclave
org.hyperledger.besu.enclave.EnclaveClientException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_6 ON PUBLIC.PRIVACY_GROUP(ID) VALUES 4"; SQL statement:
INSERT INTO PRIVACY_GROUP (ID, DATA, LOOKUP_ID, TIMESTAMP) VALUES (?, ?, ?, ?) [23505-200]
	at org.hyperledger.besu.enclave.Enclave.parseResponse(Enclave.java:173)
	at org.hyperledger.besu.enclave.Enclave.handleJsonResponse(Enclave.java:162)
	at org.hyperledger.besu.enclave.Enclave.lambda$send$0(Enclave.java:66)
	at org.hyperledger.besu.enclave.VertxRequestTransmitter.lambda$handleResponse$2(VertxRequestTransmitter.java:100)
```

**Comment by vmichalik** [comment]
If this issue only occurs in the Besu<>Orion mode I think we should wait to revisit if it causes a problem

**Comment by non-fungible-nelson** [comment]
@macfarla is this still an issue on latest and with Tessera?

**Comment by macfarla** [comment]
closing. it's only an issue w Orion which is long deprecated
