### ISSUE TITLE
NullPointerException in `updateNodeRecord` when mining milestone block

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#2115]
besu version: `21.1.3`

```
2021-04-06 16:24:38.165+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #17,619 / 0 tx / 0 om / 0 (0.0%) gas / (0x33f23515d643f6f63c61eb1fc556bf212e04de2fc8b27ddb841ab62d9e9dd65e) in 0.082s. Peers: 3
2021-04-06 16:24:43.182+00:00 | pool-7-thread-2 | ERROR | BlockMiner | Block mining threw an unhandled exception.
java.lang.NullPointerException
        at com.google.common.net.InetAddresses.ipStringToBytes(InetAddresses.java:169)
        at com.google.common.net.InetAddresses.forString(InetAddresses.java:142)
        at org.hyperledger.besu.ethereum.p2p.discovery.PeerDiscoveryAgent.updateNodeRecord(PeerDiscoveryAgent.java:189)
        at org.hyperledger.besu.ethereum.p2p.network.DefaultP2PNetwork.updateNodeRecord(DefaultP2PNetwork.java:435)
        at org.hyperledger.besu.RunnerBuilder.lambda$build$6(RunnerBuilder.java:459)
        at org.hyperledger.besu.RunnerBuilder$$Lambda$516/000000006A0FDFF0.onBlockAdded(Unknown Source)
        at org.hyperledger.besu.ethereum.chain.DefaultBlockchain.lambda$appendBlock$8(DefaultBlockchain.java:242)
        at org.hyperledger.besu.ethereum.chain.DefaultBlockchain$$Lambda$858/00000000C089F6F0.accept(Unknown Source)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
        at org.hyperledger.besu.util.Subscribers$$Lambda$384/0000000069FC9DD0.accept(Unknown Source)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
        at org.hyperledger.besu.ethereum.chain.DefaultBlockchain.appendBlock(DefaultBlockchain.java:242)
        at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.lambda$importBlock$0(MainnetBlockImporter.java:50)
        at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter$$Lambda$850/00000000C0876EC0.accept(Unknown Source)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:48)
        at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.mineBlock(BlockMiner.java:131)
        at org.hyperledger.besu.consensus.clique.blockcreation.CliqueBlockMiner.mineBlock(CliqueBlockMiner.java:49)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.run(BlockMiner.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
```
> admin.nodeInfo
{
  enode: "enode://95fbe5135415caf11e56fb75950db7ebbc3acbe9e604d5b81b9e644e3906aa955adb0400af8cf48bb81c18fe20320cedc4a27d2e56a784075640e2fff91c4305@0.0.0.0:30303?discport=0",
  id: "95fbe5135415caf11e56fb75950db7ebbc3acbe9e604d5b81b9e644e3906aa955adb0400af8cf48bb81c18fe20320cedc4a27d2e56a784075640e2fff91c4305",
  ip: "0.0.0.0",
  listenAddr: "0.0.0.0:30303",
  name: "besu/v21.1.3/linux-x86_64/openj9-java-11",
  po21.1.3rts: {
    listener: 30303
  },
  protocols: {
    eth: {
      config: {
        byzantiumBlock: 0,
        chainId: 644457192,
        clique: {...},
        eip150Block: 0,
        eip158Block: 0,
        homesteadBlock: 0,
        istanbulBlock: 17620,
        muirGlacierBlock: 17620,
        petersburgBlock: 0
      },
```

**Comment by vdamle** [comment]
[besu-restart-21.1.3.log](https://github.com/hyperledger/besu/files/6272717/besu-restart-21.1.3.log)

@RatanRSur Attaching logs from the node here.

One thing I see, now that I looked at the logs following the NPE (since I bumped up the level to `debug` after), is that there are `Duplicate Peer` messages and the output seems to show 5 peers. The number of nodes in the chain is 3. Not sure if this has anything to do with the error. As background, in Kaleido, we run private chains with a set of static nodes (which could change over time when nodes are added/removed from the chain). Since Besu did not have support for providing a static nodes file as a startup argument until recently, we orchestrate calling `admin_addPeer` on nodes.

**Comment by RatanRSur** [comment]
Can you provide your configuration? The `.toml` file and any command line flags you used as overrides to the `.toml`

**Comment by vdamle** [comment]
The command line args are (we aren't using a `.toml` file yet):

```
--data-path=/<path>/ethereum --node-private-key-file /<path>/ethereum/nodekey --discovery-enabled=false --max-peers=200 --p2p-port=30303 --p2p-host=0.0.0.0 --rpc-http-enabled --rpc-http-host=0.0.0.0 --rpc-http-port=8555 --rpc-ws-enabled --rpc-ws-host=0.0.0.0 --rpc-ws-port=8556 --rpc-http-api=ETH,NET,WEB3,DEBUG,MINER,ADMIN,TXPOOL,PERM,EEA,PRIV,CLIQUE --rpc-ws-api=ETH,NET,WEB3,DEBUG,MINER,ADMIN,TXPOOL,PERM,EEA,PRIV,CLIQUE --rpc-http-cors-origins='*' --host-whitelist='*' --network-id=644457192 --privacy-enabled --privacy-url=http://127.0.0.1:8888 --privacy-public-key-file=/<path>/orion/orion.pub --privacy-enable-database-migration --min-gas-price=0 --logging=INFO --genesis-file=/<path>/ethereum/genesis.json
```

The genesis config is:

```
{
  "alloc": {
    "ca8e94f9482bfd7dd0845fa67d9c3e804f71f49b": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinoplefixblock": 0,
    "clique": {
      "blockperiodseconds": 5,
      "epochlength": 30000
    },
    "chainId": 644457192,
    "istanbulBlock": 17620,
    "muirGlacierBlock": 17620
  },
  "nonce": "0x0",
  "timestamp": "0x58ee40ba",
  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000000f99f3979dfde1dd3cfadb60c23e9dd845b58e210000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x2FEFD800",
  "contractSizeLimit": 2147483647,
  "difficulty": "0x1",
  "number": "0x0",
  "gasUsed": "0x0",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```
