### ISSUE TITLE
Uncaught exception on first start for fresh sync: `java.net.SocketTimeoutException`

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#2288]
### Description

This is a cosmetic bug, of the "we should really catch all expected exceptions" variety.

On a fresh fast bonsai mainnet sync, this uncaught `java.net.SocketTimeoutException` exception is displayed in logs.

```
Attaching to besu-main_eth1_1
eth1_1  | Setting logging level to INFO
eth1_1  | 2021-05-17 11:21:23.300+00:00 | main | INFO  | AbstractAltBnPrecompiledContract | Using LibEthPairings native alt bn128
eth1_1  | 2021-05-17 11:21:23.318+00:00 | main | INFO  | SECP256K1 | Using native secp256k1
eth1_1  | 2021-05-17 11:21:23.322+00:00 | main | INFO  | Besu | Starting Besu version: besu/v21.1.6-dev-57f6cf55/linux-x86_64/oracle_openjdk-java-15
eth1_1  | 2021-05-17 11:21:23.495+00:00 | main | INFO  | Besu | Static Nodes file = /var/lib/besu/static-nodes.json
eth1_1  | 2021-05-17 11:21:23.497+00:00 | main | INFO  | StaticNodesParser | StaticNodes file /var/lib/besu/static-nodes.json does not exist, no static connections will be created.
eth1_1  | 2021-05-17 11:21:23.497+00:00 | main | INFO  | Besu | Connecting to 0 static nodes.
eth1_1  | 2021-05-17 11:21:23.501+00:00 | main | INFO  | Besu | Security Module: localfile
eth1_1  | 2021-05-17 11:21:23.515+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | No existing database detected at /var/lib/besu. Using version 2
eth1_1  | 2021-05-17 11:21:24.596+00:00 | main | INFO  | KeyPairUtil | Generated new public key 0xb35e5d7a31c95b0630cd19cae80cba21eb22380e81e3cbe94b266ddaaf3dec8af9689ad3d51ffd8f470a478de014ba9297cdd300ca1e8cd58531d13a8a62dfeb and stored it to /var/lib/besu/key
eth1_1  | 2021-05-17 11:21:24.759+00:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Frontier: 0, Homestead: 1150000, DaoRecoveryInit: 1920000, DaoRecoveryTransition: 1920001, Homestead: 1920010, TangerineWhistle: 2463000, SpuriousDragon: 2675000, Byzantium: 4370000, Petersburg: 7280000, Istanbul: 9069000, MuirGlacier: 9200000, Berlin: 12244000]
eth1_1  | 2021-05-17 11:21:26.005+00:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
eth1_1  | 2021-05-17 11:21:26.132+00:00 | main | INFO  | Runner | Starting Ethereum main loop ...
eth1_1  | 2021-05-17 11:21:26.132+00:00 | main | INFO  | DockerNatManager | Starting docker NAT manager.
eth1_1  | 2021-05-17 11:21:26.148+00:00 | main | INFO  | NetworkRunner | Starting Network.
eth1_1  | 2021-05-17 11:21:26.151+00:00 | main | INFO  | DefaultP2PNetwork | Starting DNS discovery with URL enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
eth1_1  | 2021-05-17 11:21:26.378+00:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0.0.0.0:30313.
eth1_1  | 2021-05-17 11:21:26.378+00:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30313
eth1_1  | 2021-05-17 11:21:26.443+00:00 | vert.x-eventloop-thread-2 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0.0.0.0 and port=30313
eth1_1  | 2021-05-17 11:21:26.444+00:00 | vert.x-eventloop-thread-2 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0.0.0.0:30313
eth1_1  | 2021-05-17 11:21:26.488+00:00 | vert.x-eventloop-thread-2 | INFO  | PeerDiscoveryAgent | Writing node record to disk. NodeRecord{seq=1, publicKey=0x03b35e5d7a31c95b0630cd19cae80cba21eb22380e81e3cbe94b266ddaaf3dec8a, udpAddress=Optional[/127.0.0.1:30313], tcpAddress=Optional[/127.0.0.1:30313], asBase64=-Jq4QELpKnULAYa0sRq_AlJYA_tX9puQQ41l-uPq4omiWolFASdcQ0Jlc9eRMAiwSIkd_0RoFXuQHZmfirCJv1PmCHYBg2V0aMrJhPxk7ASDEYwwgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQOzXl16MclbBjDNGcroDLoh6yI4DoHjy-lLJm3arz3sioN0Y3CCdmmDdWRwgnZp, nodeId=0xf154424ac21b8605578b554bdd8fbde4302d2d7a945653ca98816ad60f20fd2c}
eth1_1  | 2021-05-17 11:21:26.733+00:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://b35e5d7a31c95b0630cd19cae80cba21eb22380e81e3cbe94b266ddaaf3dec8af9689ad3d51ffd8f470a478de014ba9297cdd300ca1e8cd58531d13a8a62dfeb@127.0.0.1:30313
eth1_1  | 2021-05-17 11:21:26.734+00:00 | main | INFO  | DefaultP2PNetwork | Node address 0xdd8fbde4302d2d7a945653ca98816ad60f20fd2c
eth1_1  | 2021-05-17 11:21:26.748+00:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
eth1_1  | 2021-05-17 11:21:26.752+00:00 | main | INFO  | FastSyncDownloader | Starting fast sync.
eth1_1  | 2021-05-17 11:21:26.758+00:00 | main | INFO  | WaitForPeersTask | Waiting for 5 peers to connect. 0 peers currently connected.
eth1_1  | 2021-05-17 11:21:26.770+00:00 | main | INFO  | JsonRpcHttpService | Starting JSON-RPC service on 0.0.0.0:8547
eth1_1  | 2021-05-17 11:21:26.827+00:00 | vert.x-eventloop-thread-6 | INFO  | JsonRpcHttpService | JSON-RPC service started and listening on 0.0.0.0:8547
eth1_1  | 2021-05-17 11:21:26.829+00:00 | main | INFO  | WebSocketService | Starting Websocket service on 0.0.0.0:8548
eth1_1  | 2021-05-17 11:21:26.837+00:00 | vert.x-eventloop-thread-0 | INFO  | WebSocketService | Websocket service started and listening on 0.0.0.0:8548
eth1_1  | 2021-05-17 11:21:26.840+00:00 | main | INFO  | Runner | Ethereum main loop is up.
eth1_1  | 2021-05-17 11:21:26.851+00:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
eth1_1  | 2021-05-17 11:21:26.852+00:00 | main | INFO  | LogBloomCacheMetadata | Lookup cache metadata file in data directory: /var/lib/besu/caches
eth1_1  | 2021-05-17 11:21:27.659+00:00 | nioEventLoopGroup-3-4 | INFO  | WaitForPeersTask | Waiting for 4 peers to connect.
eth1_1  | 2021-05-17 11:21:33.246+00:00 | nioEventLoopGroup-3-4 | INFO  | WaitForPeersTask | Waiting for 1 peers to connect.
eth1_1  | 2021-05-17 11:21:43.520+00:00 | Timer-0 | ERROR | Besu | Uncaught exception in thread "Timer-0"
eth1_1  | java.net.SocketTimeoutException
eth1_1  |       at org.xbill.DNS.Resolver.send(Resolver.java:157)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.resolveRecordRaw(DNSResolver.kt:149)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.resolveRecord(DNSResolver.kt:72)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:166)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.internalVisit(DNSResolver.kt:175)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.visitTree(DNSResolver.kt:129)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.visitTree(DNSResolver.kt:105)
eth1_1  |       at org.apache.tuweni.discovery.DNSResolver.collectAll(DNSResolver.kt:94)
eth1_1  |       at org.apache.tuweni.discovery.DNSTimerTask.run(DNSDaemon.kt:70)
eth1_1  |       at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
eth1_1  |       at java.base/java.util.TimerThread.run(Timer.java:506)
eth1_1  | 2021-05-17 11:21:45.249+00:00 | nioEventLoopGroup-3-7 | INFO  | WaitForPeersTask | Waiting for 3 peers to connect.
eth1_1  | 2021-05-17 11:21:46.659+00:00 | nioEventLoopGroup-3-3 | INFO  | WaitForPeersTask | Waiting for 3 peers to connect.
eth1_1  | 2021-05-17 11:21:51.386+00:00 | nioEventLoopGroup-3-2 | INFO  | WaitForPeersTask | Waiting for 3 peers to connect.
```

**Expected behavior:** 

Exception is caught and handled by Besu

### Versions (Add all that apply)
* Software version: `besu/v21.1.6-dev-57f6cf55/linux-x86_64/oracle_openjdk-java-15`
* Java version: 15
* OS Name & Version: Ubuntu 20.04

**Comment by atoulme** [comment]
This issue occurs while Besu tries to connect via DNS over TCP for dns discovery.

It will be better handled once Tuweni 1.4 is out. In the meantime, this won’t break the client. The task will try to run again.
