### ISSUE TITLE
EthByzantiumJsonRpcHttpBySpecTest jsonRPCCallWithSpecFile[0: eth_call_revert.json] assertion error

### ISSUE THREAD

**Issue by perusworld** [hyperledger/besu#2332]
### Description
As an developer, I want build to pass. 

### Steps to Reproduce (Bug)
1. Sync to master
2. run ./gradlew clean spotlessApply build distDocker installDist

**Expected behavior:** Build to pass

**Actual behavior:** Build fails with 
<pre><b>&gt; Task :ethereum:api:test</b>

org.hyperledger.besu.ethereum.api.jsonrpc.bonsai.EthByzantiumJsonRpcHttpBySpecTest &gt; jsonRPCCallWithSpecFile[0: eth_call_revert.json] <font color="#CC0000">FAILED</font>
    java.lang.AssertionError at AbstractJsonRpcHttpBySpecTest.java:179

1874 tests completed, 1 failed

<font color="#CC0000"><b>&gt; Task :ethereum:api:test</b></font><font color="#CC0000"> FAILED</font>

<font color="#CC0000">FAILURE: Build failed with an exception.</font>
</pre>

**Frequency:** Always

### Versions (Add all that apply)
* Software version: 21.1.7-SNAPSHOT
* Java version: openjdk 11.0.11
* OS Name & Version: Ubuntu 20.04.2 LTS
* Kernel Version: 5.8.0-53-generic
### Additional Information
Error Log
`java.lang.AssertionError: 
Expecting value to be true but was false
	at org.hyperledger.besu.ethereum.api.jsonrpc.AbstractJsonRpcHttpBySpecTest.checkResponse(AbstractJsonRpcHttpBySpecTest.java:179)
	at org.hyperledger.besu.ethereum.api.jsonrpc.AbstractJsonRpcHttpBySpecTest.jsonRPCCall(AbstractJsonRpcHttpBySpecTest.java:128)
	at org.hyperledger.besu.ethereum.api.jsonrpc.AbstractJsonRpcHttpBySpecTest.jsonRPCCallWithSpecFile(AbstractJsonRpcHttpBySpecTest.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)`

**Comment by perusworld** [comment]
As a work around i had to add locally 
`test {
  ignoreFailures = true
}
` to ethereum/api/build.gradle

**Comment by vmichalik** [comment]
@perusworld has this issue resolved itself?

**Comment by perusworld** [comment]
> @perusworld has this issue resolved itself?

yes, i don't see this issue any more. i will close the ticket. thanks
