### ISSUE TITLE
Suppress StackTrace and add logging when pub key can't be recovered

### ISSUE THREAD

**Issue by jamartinez-aubay** [hyperledger/besu#2402]
Hello ... sometimes we saw in logs the next error

vert.x-eventloop-thread-1 | ERROR | VertxPeerDiscoveryAgent | Encountered error while handling packet
java.lang.IllegalArgumentException: Could not recover public key
	at org.hyperledger.besu.crypto.SECP256K1.recoverFromSignatureNative(SECP256K1.java:495)
	at org.hyperledger.besu.crypto.SECP256K1.recoverPublicKeyFromSignature(SECP256K1.java:370)
	at org.hyperledger.besu.ethereum.p2p.discovery.internal.Packet.<init>(Packet.java:90)
	at org.hyperledger.besu.ethereum.p2p.discovery.internal.Packet.decode(Packet.java:126)
	at org.hyperledger.besu.ethereum.p2p.discovery.VertxPeerDiscoveryAgent.lambda$handlePacket$6(VertxPeerDiscoveryAgent.java:221)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

This traces appears a lot of time and very quickly, but later dissapears and Besu back to works well. Any idea about this trace?

**Comment by atoulme** [comment]
This means that Besu failed to make sense of a message from a remote peer during discovery. The remote peer is incompatible. Besu itself is fine and will keep on discovering new peers.

**Comment by sajz** [comment]
We think we fixed this with a released version, re-open if it's not working.
https://github.com/hyperledger/besu/issues/2143
