### ISSUE TITLE
java.lang.NullPointerException in trace_block method

### ISSUE THREAD

**Issue by centromere** [hyperledger/besu#2628]
### Steps to Reproduce (Bug)

```
curl -H 'Content-Type: application/json' http://localhost:8545 -d '{"jsonrpc":"2.0","params":["0xcae8c8"],"method":"trace_block","id":"1"}'
```

**Actual behavior:**
```
{
  "jsonrpc" : "2.0",
  "id" : "1",
  "error" : {
    "code" : -32603,
    "message" : "Internal error"
  }
}
```

```
2021-08-12 18:20:52.989+00:00 | vert.x-worker-thread-9 | ERROR | JsonRpcHttpService | Error processing JSON-RPC requestBody
java.lang.NullPointerException
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.handleHalt(FlatTraceGenerator.java:471)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.generateFromTransactionTrace(FlatTraceGenerator.java:198)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.generateFromTransactionTraceAndBlock(FlatTraceGenerator.java:245)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.lambda$generateTracesFromTransactionTraceAndBlock$1(TraceBlock.java:104)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.generateTracesFromTransactionTraceAndBlock(TraceBlock.java:102)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.lambda$traceBlock$0(TraceBlock.java:89)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.traceBlock(TraceBlock.java:87)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.resultByBlockNumber(TraceBlock.java:73)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:65)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.response(AbstractBlockParameterMethod.java:78)
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:725)
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$13(JsonRpcHttpService.java:579)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: `besu/v21.1.7/linux-x86_64/openjdk-java-11`
* Java version:
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

**Comment by vmichalik** [comment]
Hey @centromere, thanks for flagging! Can you share your Besu config?

**Comment by centromere** [comment]
@vmichalik 
```
      --network=classic
      --sync-mode=FAST
      --data-path=/opt/data
      --host-allowlist=*
      --p2p-host=0.0.0.0
      --p2p-port=30304
      --pruning-enabled=true
      --pruning-blocks-retained=100000
      --Xsynchronizer-fast-sync-pivot-distance=50000
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api ETH,NET,TRACE,WEB3
```

I am unable to replicate the issue with 21.7.0, so the issue may be closed if you feel it is proper.

**Comment by vmichalik** [comment]
ok! please reopen if you see it again 🙏
