### ISSUE TITLE
SECP256R1 unit tests failing on MacOS

### ISSUE THREAD

**Issue by lucassaldanha** [hyperledger/besu#2665]
### Description
Some tests on `SECP256R1Test` are failing when running on MacOS. This was likely introduced in https://github.com/hyperledger/besu/pull/2630.

The tests are working fine on a Linux machine and on the CircleCI build.

The native libraries are from https://github.com/hyperledger/besu-native

Test **​org.hyperledger.besu.crypto.SECP256R1Test#signatureGenerationAndVerification:**
```
dlopen(/Users/lucas/Library/Caches/JNA/temp/jna17785093207262039815.tmp, 9): Library not loaded: /usr/local/lib/libcrypto.3.dylib
  Referenced from: /Users/lucas/Library/Caches/JNA/temp/jna17785093207262039815.tmp
  Reason: image not found
java.lang.UnsatisfiedLinkError: dlopen(/Users/lucas/Library/Caches/JNA/temp/jna17785093207262039815.tmp, 9): Library not loaded: /usr/local/lib/libcrypto.3.dylib
  Referenced from: /Users/lucas/Library/Caches/JNA/temp/jna17785093207262039815.tmp
  Reason: image not found
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at org.hyperledger.besu.nativelib.secp256r1.besuNativeEC.BesuNativeEC.<clinit>(BesuNativeEC.java:23)
	at org.hyperledger.besu.nativelib.secp256r1.LibSECP256R1.sign(LibSECP256R1.java:35)
	at org.hyperledger.besu.crypto.SECP256R1.signNative(SECP256R1.java:94)
	at org.hyperledger.besu.crypto.SECP256R1.sign(SECP256R1.java:67)
	at org.hyperledger.besu.crypto.SECP256R1Test.lambda$signatureGenerationAndVerification$0(SECP256R1Test.java:156)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.hyperledger.besu.crypto.SECP256R1Test.signatureGenerationAndVerification(SECP256R1Test.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Test **org.hyperledger.besu.crypto.SECP256R1Test#recoverPublicKeyFromSignature**
```
Could not initialize class org.hyperledger.besu.nativelib.secp256r1.besuNativeEC.BesuNativeEC
java.lang.NoClassDefFoundError: Could not initialize class org.hyperledger.besu.nativelib.secp256r1.besuNativeEC.BesuNativeEC
	at org.hyperledger.besu.nativelib.secp256r1.LibSECP256R1.sign(LibSECP256R1.java:35)
	at org.hyperledger.besu.crypto.SECP256R1.signNative(SECP256R1.java:94)
	at org.hyperledger.besu.crypto.SECP256R1.sign(SECP256R1.java:67)
	at org.hyperledger.besu.crypto.SECP256R1Test.recoverPublicKeyFromSignature(SECP256R1Test.java:137)
```

### Acceptance Criteria
* Test success should be independent of the platform

### Steps to Reproduce (Bug)
1. Run `./gradlew :crypto:test` on a MacOS machine

**Expected behavior:** All tests passing

**Actual behavior:** Some tests in SECP256R1 class are failing

**Frequency:** Always

### Versions (Add all that apply)
* Software version: Commit 0b2b2bacd210f5b30665eb6febb907e28f159817 onwards
* Java version: openjdk 11.0.2 2019-01-15
* OS Name & Version: MacOS Big Sur 11.5.2

### Additional Information

If this is blocking someone, you can exclude the test from the crypto package:
```
./gradlew build -x :crypto:test
```

**Comment by lucassaldanha** [comment]
We are looking at this issue. Starting with https://github.com/ConsenSys/besu-native-ec/pull/17
