### ISSUE TITLE
21.7.3 mainnet stops syncing with "Attempting to update buffer with 213 byte(s) but there is -213 byte(s) left to fill"

### ISSUE THREAD

**Issue by leontastic** [hyperledger/besu#2776]
### Description

I want to besu stay synced without getting stuck.

I encountered this issue on two nodes syncing with *mainnet*.

### Acceptance Criteria

Should not get stuck

### Steps to Reproduce (Bug)

Run a synced besu node on 21.7.3

**Expected behavior:** 

Should work

**Actual behavior:** [What actually happens]

Observe log `Attempting to update buffer with 213 byte(s) but there is -213 byte(s) left to fill`. Besu will fail to accept that block and get stuck.

The node stops syncing, but there are still many peers connected (25).

**Frequency:**

I ran two nodes that stopped syncing on the same block.

Seems to resolve itself after recreating the container. I notice this error happens again with other byte values (e.g. `Attempting to update buffer with 213 byte(s) but there is 0 byte(s) left to fill`) but this doesn't seem to cause the node to get stuck.

### Versions (Add all that apply)

* Software version: 21.7.3
* Java version:
    ```
    openjdk 11.0.12 2021-07-20
    OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
    OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)
    ```
* OS Name & Version: Debian GNU/Linux 10 (buster)
* Kernel Version: x86_64 GNU/Linux
* Cloud VM, type, size: GCP n1-standard-2

### Additional Information

Logs:
```
2021-09-16 21:04:29.972+00:00 | nioEventLoopGroup-3-5 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x2295bf19ca8f8e934c... at block 13238964
2021-09-16 21:04:36.328+00:00 | EthScheduler-Services-6920 (importBlock) | ERROR | MainnetTransactionProcessor | Critical Exception Processing Transaction
java.lang.IllegalArgumentException: Attempting to update buffer with 213 byte(s) but there is -213 byte(s) left to fill
	at org.hyperledger.besu.crypto.Blake2bfMessageDigest$Blake2bfDigest.update(Blake2bfMessageDigest.java:152)
	at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineUpdate(Unknown Source)
	at java.base/java.security.MessageDigest.update(Unknown Source)
	at org.apache.tuweni.bytes.ArrayWrappingBytes.update(ArrayWrappingBytes.java:115)
	at org.hyperledger.besu.crypto.Hash.digestUsingAlgorithm(Hash.java:62)
	at org.hyperledger.besu.crypto.Hash.blake2bf(Hash.java:106)
	at org.hyperledger.besu.ethereum.mainnet.precompiles.BLAKE2BFPrecompileContract.compute(BLAKE2BFPrecompileContract.java:69)
	at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.executePrecompile(MainnetMessageCallProcessor.java:131)
	at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.start(MainnetMessageCallProcessor.java:60)
	at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:163)
	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:454)
	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:361)
	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:161)
	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:42)
	at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:75)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:150)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:108)
	at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)
	at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
	at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:54)
	at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
	at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-16 21:04:36.329+00:00 | EthScheduler-Services-6920 (importBlock) | INFO  | AbstractBlockProcessor | Block processing error: transaction invalid 'INTERNAL_ERROR'. Block 0xb738c748d52d0c2f1a66a2306078a763ee99ad3d9a126c250036a43e91b539e9 Transaction 0xfc55eac21b7803e27d65ad9146b606b206cc0aa830a06d117baf2a2e82fa055c
2021-09-16 21:04:36.330+00:00 | EthScheduler-Services-6920 (importBlock) | WARN  | PipelineChainDownloader | Invalid block detected.  Disconnecting from sync target. Failed to import block: Invalid block at #13238965 (0xb738c748d52d0c2f1a66a2306078a763ee99ad3d9a126c250036a43e91b539e9)
2021-09-16 21:04:36.330+00:00 | EthScheduler-Services-6920 (importBlock) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #13238965 (0xb738c748d52d0c2f1a66a2306078a763ee99ad3d9a126c250036a43e91b539e9)
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #13238965 (0xb738c748d52d0c2f1a66a2306078a763ee99ad3d9a126c250036a43e91b539e9)
	at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:55)
	at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
	at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
	... 5 more
2021-09-16 21:07:55.851+00:00 | nioEventLoopGroup-3-3 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xeaa7bc9bd297c70f79... at block 13238964
2021-09-16 21:07:56.066+00:00 | EthScheduler-Services-6921 (downloadBodies) | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 25
2021-09-16 21:10:20.339+00:00 | nioEventLoopGroup-3-3 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xbd71c6b2d202b8faf6... at block 13238964
2021-09-16 21:10:20.370+00:00 | EthScheduler-Services-6926 (downloadBodies) | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 25
2021-09-16 21:10:25.646+00:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 25
2021-09-16 21:10:30.890+00:00 | nioEventLoopGroup-3-3 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 25
```

**Comment by atoulme** [comment]
Please indicate which network or chain you were syncing. Please provide information on your OS and machine architecture. Please let us know if native bindings were loaded on startup (looking for the first 100 lines of your log at startup time).

Thank you for your report.

**Comment by leontastic** [comment]
@atoulme Thanks for looking at this.

<details>
<summary>Startup logs</summary>
<pre>
2021-09-16 21:44:48.090+00:00 | main | INFO  | Besu | Using LibEthPairings native alt bn128
2021-09-16 21:44:48.094+00:00 | main | INFO  | Besu | Using the native implementation of the signature algorithm
2021-09-16 21:44:48.100+00:00 | main | INFO  | Besu | Starting Besu version: besu/v21.7.3/linux-x86_64/oracle_openjdk-java-11
2021-09-16 21:44:48.378+00:00 | main | INFO  | Besu | Static Nodes file = /data/static-nodes.json
2021-09-16 21:44:48.380+00:00 | main | INFO  | StaticNodesParser | StaticNodes file /data/static-nodes.json does not exist, no static connections will be created.
2021-09-16 21:44:48.381+00:00 | main | INFO  | Besu | Connecting to 0 static nodes.
2021-09-16 21:44:48.384+00:00 | main | INFO  | Besu | Security Module: localfile
2021-09-16 21:44:48.407+00:00 | main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /data
2021-09-16 21:44:48.493+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /data. Version 1
2021-09-16 21:44:50.584+00:00 | main | INFO  | KeyPairUtil | Loaded public key 0x017cb427027149128597e841b79c76a29b2ce4aa5dadb3d289370eea79a98a144080b319da0c9a6163240d204c42eab907a4000870c4438f116c65308e9b57c1 from /data/key
2021-09-16 21:44:50.721+00:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Frontier: 0, Homestead: 1150000, DaoRecoveryInit: 1920000, DaoRecoveryTransition: 1920001, Homestead: 1920010, TangerineWhistle: 2463000, SpuriousDragon: 2675000, Byzantium: 4370000, Petersburg: 7280000, Istanbul: 9069000, MuirGlacier: 9200000, Berlin: 12244000, London: 12965000]
2021-09-16 21:44:51.448+00:00 | main | INFO  | FastDownloaderFactory | Fast sync was requested, but cannot be enabled because the local blockchain is not empty.
2021-09-16 21:44:51.468+00:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2021-09-16 21:44:51.618+00:00 | main | INFO  | Runner | Starting Ethereum main loop ...
2021-09-16 21:44:51.618+00:00 | main | INFO  | MetricsHttpService | Starting metrics http service on 127.0.0.1:9094
2021-09-16 21:44:51.799+00:00 | main | INFO  | KubernetesNatManager | Starting kubernetes NAT manager.
2021-09-16 21:44:51.799+00:00 | vert.x-eventloop-thread-3 | INFO  | MetricsHttpService | Metrics service started and listening on 9094:9094
ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.8SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/besu/lib/log4j-slf4j-impl-2.14.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/besu/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2021-09-16 21:44:52.160+00:00 | main | INFO  | NetworkRunner | Starting Network.
2021-09-16 21:44:52.163+00:00 | main | INFO  | DefaultP2PNetwork | Starting DNS discovery with URL enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
2021-09-16 21:44:52.225+00:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0.0.0.0:30303.
2021-09-16 21:44:52.226+00:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2021-09-16 21:44:52.243+00:00 | vert.x-eventloop-thread-4 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0.0.0.0 and port=30303
2021-09-16 21:44:52.244+00:00 | vert.x-eventloop-thread-4 | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0.0.0.0:30303
2021-09-16 21:44:52.295+00:00 | vert.x-eventloop-thread-4 | INFO  | PeerDiscoveryAgent | Writing node record to disk. NodeRecord{seq=74, publicKey=0x03017cb427027149128597e841b79c76a29b2ce4aa5dadb3d289370eea79a98a14, udpAddress=Optional[/127.0.0.1:30303], tcpAddress=Optional[/127.0.0.1:30303], asBase64=-Je4QJWTEcqUmqW1gE_rOk5DMa0dxzIzE6VITdTkAeQi96Pzb5nJ41spP_zxk48TWZUfX7j8oX5s7mrf8CyK_mRAKwtKg2V0aMfGhLcVB32AgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQMBfLQnAnFJEoWX6EG3nHaimyzkql2ts9KJNw7qeamKFIN0Y3CCdl-DdWRwgnZf, nodeId=0x3163108181fdee800ddd854ba1ba49093909e29bb4fdfa524634f6735c1ee460, customFields={tcp=30303, udp=30303, ip=0x7f000001, eth=[[0xb715077d, 0x]], id=V4, secp256k1=0x03017cb427027149128597e841b79c76a29b2ce4aa5dadb3d289370eea79a98a14}}
2021-09-16 21:44:52.372+00:00 | main | INFO  | DefaultP2PNetwork | Enode URL enode://017cb427027149128597e841b79c76a29b2ce4aa5dadb3d289370eea79a98a144080b319da0c9a6163240d204c42eab907a4000870c4438f116c65308e9b57c1@127.0.0.1:30303
2021-09-16 21:44:52.373+00:00 | main | INFO  | DefaultP2PNetwork | Node address 0xa1ba49093909e29bb4fdfa524634f6735c1ee460
2021-09-16 21:44:52.378+00:00 | main | INFO  | DefaultSynchronizer | Starting synchronizer.
2021-09-16 21:44:52.380+00:00 | main | INFO  | FullSyncDownloader | Starting full sync.
2021-09-16 21:44:52.381+00:00 | StatePruning-0 | INFO  | Pruner | Starting Pruner.
2021-09-16 21:44:52.382+00:00 | main | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-09-16 21:44:52.394+00:00 | main | INFO  | JsonRpcHttpService | Starting JSON-RPC service on 0.0.0.0:9091
2021-09-16 21:44:52.393+00:00 | StatePruning-0 | ERROR | Besu | Uncaught exception in thread "StatePruning-0"
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:211)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:62)
        at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.clear(SegmentedKeyValueStorageAdapter.java:40)
        at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.clearMarks(MarkSweepPruner.java:229)
        at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.prepare(MarkSweepPruner.java:124)
        at org.hyperledger.besu.ethereum.worldstate.Pruner.lambda$start$0(Pruner.java:97)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.rocksdb.RocksDBException: DeleteRangeCF not implemented
        at org.rocksdb.RocksDB.deleteRange(Native Method)
        at org.rocksdb.RocksDB.deleteRange(RocksDB.java:1493)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:206)
        ... 8 more
2021-09-16 21:44:52.422+00:00 | vert.x-eventloop-thread-8 | INFO  | JsonRpcHttpService | JSON-RPC service started and listening on 0.0.0.0:9091
2021-09-16 21:44:52.424+00:00 | main | INFO  | WebSocketService | Starting Websocket service on 0.0.0.0:9092
2021-09-16 21:44:52.434+00:00 | vert.x-eventloop-thread-10 | INFO  | WebSocketService | Websocket service started and listening on 0.0.0.0:9092
2021-09-16 21:44:52.436+00:00 | main | INFO  | Runner | Ethereum main loop is up.
</pre>
</details>

Maybe it was just a bad peer or something. I felt this needed a report because the server would get stuck for many blocks without restarting. Besu's liveness is very valuable.

**Comment by atoulme** [comment]
Are you unblocked now?

**Comment by macfarla** [comment]
Hi @leontastic - realise it's been a while but we have made some improvements in peering and syncing (eg 22.1.0 had fast sync optimisations). Additionally we are beginning a holistic assessment of peering behavior including any outstanding issues. So we're hoping that either those changes have it fixed already, or that you're able to give us an update if you're still having related issues?
