### ISSUE TITLE
Stratum mining is broken since 21.7.3

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#2921]
### Description
since 21.7.3, when stratum mining is enabled we get a divide by zero error when trying to submit mining jobs:
```
2021-10-18 21:49:04.497+00:00 | pool-7-thread-1 | DEBUG | Stratum1Protocol | Sending new work to miners: PoWSolverInputs{target=0x000012c7f3a2cde3ba652cb294eb0f66a10477cf870029282ce7c5300b77b6f3, prePowHash=0x91cf633f75576c444484aa121ade6057cc217ee1c4f194a862eaea3fbcd320e9, blockNumber=32799}
2021-10-18 21:49:04.497+00:00 | pool-7-thread-1 | ERROR | BlockMiner | Block mining threw an unhandled exception.
java.lang.ArithmeticException: divide by zero
        at org.apache.tuweni.units.bigints.UInt256.divide(UInt256.java:425)
        at org.hyperledger.besu.ethereum.stratum.StratumServer.newJob(StratumServer.java:162)
        at org.hyperledger.besu.ethereum.mainnet.PoWSolver.lambda$solveFor$1(PoWSolver.java:113)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
        at org.hyperledger.besu.ethereum.mainnet.PoWSolver.solveFor(PoWSolver.java:113)
        at org.hyperledger.besu.ethereum.blockcreation.PoWBlockCreator.createFinalBlockHeader(PoWBlockCreator.java:73)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:185)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:126)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.mineBlock(BlockMiner.java:123)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.run(BlockMiner.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is presumably related to the upgrade to tuweni-2.0

### Acceptance Criteria
* stratum mining should work

**Comment by atoulme** [comment]
No, this was broken by https://github.com/hyperledger/besu/commit/670a19e7d8a2bb5ed585cc9bbd65642f3f12b127 because of `DIFFICULTY_1_TARGET = UInt256.valueOf(2).pow(256)` shifts too much left and equals zero :(
I guess I meant 255, not 256.
