### ISSUE TITLE
java.net.SocketException: Operation not permitted

### ISSUE THREAD

**Issue by one-three-three-seven** [hyperledger/besu#2982]
### Description
As a node operator, I want logging that it is not flooded by unnecessary error messages.

### Steps to Reproduce (Bug)
1. Add a firewall rule to block unroutable outgoing traffic like `ufw deny out to 100.64.0.0/10`.
2. Start Besu and wait till it tries to connect to a `100.64.0.0/10` ip.

**Expected behavior:** [What you expect to happen]
1. Less verbose or even no logging of this expected behaviour.

**Actual behavior:** [What actually happens]

```
Oct 31 23:45:19 dakara docker[807879]: 2021-10-31 22:45:19.561+00:00 | vert.x-eventloop-thread-1 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, enode=enode://3b8cde6fd28498b922c46fa340696a809cdba1f53d2830a90492edd60480fb57bd0a2b2c537fffaa6582b39ecc8d2732a54967da805f46740f0d0e46c32d7f35@100.64.229.95:10104, firstDiscovered=1635720310059, lastContacted=0, lastSeen=0} failed, packet: 0xbed75c82206fe0ce8d26e55e6d414cb7171017a8d206d333d7b32101ec2af0b25a2041718b5a0719d6c21b5547f9242ce633099e5550f0176e2741ef6156b2f65bef963ce1f1d33ad0d46baac84c82c4e2e688eafbeb1fe8a5455a89ec2da10b0101df05cb844115596382765f82765fcb846440e55f82277882277884617f1cbb0f
Oct 31 23:45:19 dakara docker[807879]: java.net.SocketException: Operation not permitted
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:901)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:863)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:821)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:296)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:913)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:280)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:268)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:88)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
Oct 31 23:45:19 dakara docker[807879]:         at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Oct 31 23:45:19 dakara docker[807879]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Oct 31 23:45:19 dakara docker[807879]:         at java.base/java.lang.Thread.run(Thread.java:833)
```

**Frequency:** [What percentage of the time does it occur?]

100%

### Versions (Add all that apply)
* Software version: `besu/v21.10.0-RC4/linux-x86_64/oracle_openjdk-java-17`
* Docker Version: `20.10.5+dfsg1` (running with `--network host`)
* OS: Debian Bullseye

### Additional Information

Some hosting providers do not allow to send local and/or unrouteable traffic.

https://github.com/openethereum/parity-ethereum/issues/2478
https://github.com/ethereum/go-ethereum/issues/15957
https://community.hetzner.com/tutorials/block-outgoing-traffic-to-private-networks

**Comment by macfarla** [comment]
Actions
- change stack trace to TRACE level but keep the top level error msg
- add something to Besu docs (P2P networks section) about what the error means (you need to set up your routing rules correctly). We can't prevent Besu from sending traffic to private IP addresses.

**Comment by frankisawesome** [comment]
Wanted to clarify - this is currently at WARN level, is it worth changing it all the way down to TRACE or is DEBUG more approriate?
Thoughts @macfarla and @one-three-three-seven ?

**Comment by one-three-three-seven** [comment]
I would expect it to be DEBUG, but I'm fine with both.

**Comment by macfarla** [comment]
Agree DEBUG seems appropriate

**Comment by macfarla** [comment]
hey @one-three-three-seven the PR has been merged in - can you update and let us know if you're still having issues!

**Comment by one-three-three-seven** [comment]
Hey, I updated about 12 hours ago and just looked at the logfile, the error message is gone.

Thanks for the fix, this makes running Besu a lot nicer. 👍

**Comment by macfarla** [comment]
Awesome! Thanks for the feedback @one-three-three-seven 🚀
