### ISSUE TITLE
Bonsai mainnet sync shows ` World State Root does not match expected value`

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#3007]
### Description

Syncing mainnet with bonsai trie and the recent fix, the sync shows an error after importing world states.

Pivot block information:
```
ubuntu@eth-testing:~$ grep -i pivot besu-logs
2021-10-31 12:27:19.426+01:00 | EthScheduler-Timer-0 | INFO  | FastSyncActions | Selecting block number 13524471 as fast sync pivot block.
2021-10-31 12:27:19.428+01:00 | EthScheduler-Timer-0 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2021-10-31 12:27:19.429+01:00 | EthScheduler-Timer-0 | INFO  | PivotBlockConfirmer | Confirm pivot block 13524471 with at least 5 peers.
2021-10-31 12:27:19.437+01:00 | nioEventLoopGroup-3-5 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 13524471: 0xdcfcf866c1b714f594957b92c71ab102e5432b4913f71f8d946a17ab903bd101
2021-10-31 12:27:19.472+01:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 13524471: 0xdcfcf866c1b714f594957b92c71ab102e5432b4913f71f8d946a17ab903bd101
2021-10-31 12:27:19.525+01:00 | nioEventLoopGroup-3-8 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 13524471: 0xdcfcf866c1b714f594957b92c71ab102e5432b4913f71f8d946a17ab903bd101
2021-10-31 12:27:19.543+01:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 13524471: 0xdcfcf866c1b714f594957b92c71ab102e5432b4913f71f8d946a17ab903bd101
2021-10-31 12:27:19.548+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 13524471: 0xdcfcf866c1b714f594957b92c71ab102e5432b4913f71f8d946a17ab903bd101
2021-11-01 05:32:01.335+01:00 | nioEventLoopGroup-3-2 | INFO  | FastSyncDownloader | Re-pivoting to newer block.
2021-11-01 05:32:01.387+01:00 | nioEventLoopGroup-3-2 | INFO  | FastSyncActions | Selecting block number 13529038 as fast sync pivot block.
2021-11-01 05:32:01.387+01:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2021-11-01 05:32:01.388+01:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirm pivot block 13529038 with at least 5 peers.
2021-11-01 05:32:01.391+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 13529038: 0xbf3c6eb4857543c8c97852591e7b1a4683f98d2ff2f140da050591f274b4a329
2021-11-01 05:32:01.393+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 13529038: 0xbf3c6eb4857543c8c97852591e7b1a4683f98d2ff2f140da050591f274b4a329
2021-11-01 05:32:01.394+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 13529038: 0xbf3c6eb4857543c8c97852591e7b1a4683f98d2ff2f140da050591f274b4a329
2021-11-01 05:32:01.416+01:00 | nioEventLoopGroup-3-5 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 13529038: 0xbf3c6eb4857543c8c97852591e7b1a4683f98d2ff2f140da050591f274b4a329
2021-11-01 05:32:01.464+01:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 13529038: 0xbf3c6eb4857543c8c97852591e7b1a4683f98d2ff2f140da050591f274b4a329
2021-11-02 06:36:46.457+01:00 | nioEventLoopGroup-3-8 | INFO  | FastSyncDownloader | Re-pivoting to newer block.
2021-11-02 06:36:46.699+01:00 | nioEventLoopGroup-3-8 | INFO  | FastSyncActions | Selecting block number 13535721 as fast sync pivot block.
2021-11-02 06:36:46.699+01:00 | nioEventLoopGroup-3-8 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2021-11-02 06:36:46.699+01:00 | nioEventLoopGroup-3-8 | INFO  | PivotBlockConfirmer | Confirm pivot block 13535721 with at least 5 peers.
2021-11-02 06:36:46.703+01:00 | nioEventLoopGroup-3-10 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 13535721: 0xf0316ce9d063e5f1c4fdbd3831f9a3263787cca05dd5e43eeee4a166cbc601f2
2021-11-02 06:36:46.724+01:00 | nioEventLoopGroup-3-8 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 13535721: 0xf0316ce9d063e5f1c4fdbd3831f9a3263787cca05dd5e43eeee4a166cbc601f2
2021-11-02 06:36:46.857+01:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 13535721: 0xf0316ce9d063e5f1c4fdbd3831f9a3263787cca05dd5e43eeee4a166cbc601f2
2021-11-02 06:36:46.985+01:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 13535721: 0xf0316ce9d063e5f1c4fdbd3831f9a3263787cca05dd5e43eeee4a166cbc601f2
2021-11-02 06:36:46.986+01:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 13535721: 0xf0316ce9d063e5f1c4fdbd3831f9a3263787cca05dd5e43eeee4a166cbc601f2
2021-11-03 06:56:15.208+01:00 | nioEventLoopGroup-3-4 | INFO  | FastSyncDownloader | Re-pivoting to newer block.
2021-11-03 06:56:42.484+01:00 | nioEventLoopGroup-3-4 | INFO  | FastSyncActions | Selecting block number 13542125 as fast sync pivot block.
2021-11-03 06:56:42.484+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2021-11-03 06:56:42.484+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Confirm pivot block 13542125 with at least 5 peers.
2021-11-03 06:56:42.488+01:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 13542125: 0x3afdf2208391a258d3ab16a53f145fa1bcc48a990e033f8038c49c577dd2b9fa
2021-11-03 06:56:42.502+01:00 | nioEventLoopGroup-3-9 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 13542125: 0x3afdf2208391a258d3ab16a53f145fa1bcc48a990e033f8038c49c577dd2b9fa
2021-11-03 06:56:42.519+01:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 13542125: 0x3afdf2208391a258d3ab16a53f145fa1bcc48a990e033f8038c49c577dd2b9fa
2021-11-03 06:56:42.535+01:00 | nioEventLoopGroup-3-4 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 13542125: 0x3afdf2208391a258d3ab16a53f145fa1bcc48a990e033f8038c49c577dd2b9fa
2021-11-03 06:57:20.803+01:00 | nioEventLoopGroup-3-9 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 13542125: 0x3afdf2208391a258d3ab16a53f145fa1bcc48a990e033f8038c49c577dd2b9fa
2021-11-03 23:12:34.128+01:00 | nioEventLoopGroup-3-6 | INFO  | FastSyncDownloader | Re-pivoting to newer block.
2021-11-03 23:12:34.155+01:00 | nioEventLoopGroup-3-6 | INFO  | FastSyncActions | Selecting block number 13546439 as fast sync pivot block.
2021-11-03 23:12:34.155+01:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2021-11-03 23:12:34.156+01:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockConfirmer | Confirm pivot block 13546439 with at least 5 peers.
2021-11-03 23:12:34.194+01:00 | nioEventLoopGroup-3-3 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 13546439: 0x457a39280e3fa9db5b421b26f76864e13fb6a8ebdb1412224aee7a24c3498ef1
2021-11-03 23:12:34.220+01:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 13546439: 0x457a39280e3fa9db5b421b26f76864e13fb6a8ebdb1412224aee7a24c3498ef1
2021-11-03 23:12:34.264+01:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 13546439: 0x457a39280e3fa9db5b421b26f76864e13fb6a8ebdb1412224aee7a24c3498ef1
2021-11-03 23:12:34.282+01:00 | nioEventLoopGroup-3-6 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 13546439: 0x457a39280e3fa9db5b421b26f76864e13fb6a8ebdb1412224aee7a24c3498ef1
2021-11-03 23:12:34.368+01:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 13546439: 0x457a39280e3fa9db5b421b26f76864e13fb6a8ebdb1412224aee7a24c3498ef1
2021-11-04 15:59:44.001+01:00 | EthScheduler-Services-10 (requestCompleteTask) | INFO  | DefaultSynchronizer | Fast sync completed successfully with pivot block 13546439
```

Error logs once fast sync completes, ongoing `Import reached block` logs every few minutes after this:

```
execution_1  | 2021-11-04 17:20:01.499+01:00 | EthScheduler-Services-133 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13549800 (0x2ae8c67497bdb8e4a9e9a9989c17a9d6106775b28d2f52d0f36a172fceb54c47), 11.550 Mg/s, Peers: 25
execution_1  | 2021-11-04 17:24:30.481+01:00 | EthScheduler-Services-133 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13550000 (0x73d39c9ab8401d771d64a138a4bfb71514dd08b8ea8a620f7856fb10a6eeaf4e), 11.555 Mg/s, Peers: 25
execution_1  | 2021-11-04 17:24:35.289+01:00 | EthScheduler-Services-133 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
execution_1  | java.util.concurrent.CompletionException: java.lang.RuntimeException: World State Root does not match expected value, header 0xb9f7b6ac1f6185aa5cd1990bb1e4111587999632568ac7751d67fdd1f04e881c calculated 0x6209a3c82e5bd7a49ec88507528dbb79490f21b9a730eb3ca80938c6a07f9dea
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
execution_1  |  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
execution_1  |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
execution_1  |  at java.base/java.lang.Thread.run(Thread.java:833)
execution_1  | Caused by: java.lang.RuntimeException: World State Root does not match expected value, header 0xb9f7b6ac1f6185aa5cd1990bb1e4111587999632568ac7751d67fdd1f04e881c calculated 0x6209a3c82e5bd7a49ec88507528dbb79490f21b9a730eb3ca80938c6a07f9dea
execution_1  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.persist(BonsaiPersistedWorldState.java:264)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:202)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:42)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:75)
execution_1  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:150)
execution_1  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:108)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)
execution_1  |  at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:54)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
execution_1  |  at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
execution_1  |  ... 5 more
execution_1  | 2021-11-04 17:24:37.336+01:00 | nioEventLoopGroup-3-2 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x717d2edf75ea523c8f... at block 13550002
execution_1  | 2021-11-04 17:29:06.498+01:00 | EthScheduler-Services-137 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13550200 (0x41d70acf950ff5103aa1125f5ea451c8e096574cd603cbdfb734d9f43b82df29), - Mg/s, Peers: 25
execution_1  | 2021-11-04 17:33:13.021+01:00 | EthScheduler-Services-137 (importBlock) | INFO  | FullImportBlockStep | Import reached block 13550400 (0xdce40a87e21ffeb58ae01c864683fd602dbb6291a15625678c5d78d90d60f0e1), 12.505 Mg/s, Peers: 25
```

### Versions

Besu: `besu/v21.10.1-dev-93b556aa/linux-x86_64/openjdk-java-17`
OS: Ubuntu 20.04

**Comment by yorickdowne** [comment]
Despite this scary-looking error message, sync does complete. Currently showing the below, which looks like Besu keeping up with head to me.

```
execution_1  | 2021-11-04 19:33:05.284+01:00 | EthScheduler-Workers-2 | INFO  | PersistBlockTask | Imported #13,551,830 / 103 tx / 0 om / 6,050,593 (20.1%) gas / (0xe892e4995556f5c5a9a297ee51ee2ca61009faf9d9c1c37f39f1f7631c8dee70) in 0.395s. Peers: 25
execution_1  | 2021-11-04 19:33:10.757+01:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #13,551,831 / 54 tx / 0 om / 3,182,253 (10.6%) gas / (0x2828c5ad8dee1f6d9d699a98ef86dfee17212236cb80f72d6bbad1c45e5cb7c7) in 0.194s. Peers: 25
```

**Comment by yorickdowne** [comment]
This can also occur while keeping up with head, for example:

```
execution_1  | 2021-11-04 18:15:13.334+01:00 | EthScheduler-Workers-3 | INFO  | BlockPropagationManager | Imported 1 pending blocks
execution_1  | 2021-11-04 18:15:24.327+01:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #13,551,501 / 253 tx / 0 om / 29,980,142 (99.9%) gas / (0x738dd109657f88735d7c7afeeed08372cf1f63f079e46b3a18170b38beedc557) in 2.823s. Peers: 25
execution_1  | 2021-11-04 18:15:31.249+01:00 | nioEventLoopGroup-3-7 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x9a487d7b7b5fe27833... at block 13551501
execution_1  | 2021-11-04 18:15:31.279+01:00 | EthScheduler-Services-157 (downloadHeaders) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
execution_1  | java.util.concurrent.CompletionException: java.lang.RuntimeException: Async operation failed. java.lang.IllegalArgumentException: Must have at least one header to import
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1097)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
execution_1  |  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
execution_1  |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
execution_1  |  at java.base/java.lang.Thread.run(Thread.java:833)
execution_1  | Caused by: java.lang.RuntimeException: Async operation failed. java.lang.IllegalArgumentException: Must have at least one header to import
execution_1  |  at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:86)
execution_1  |  at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.attemptFinalization(AsyncOperationProcessor.java:70)
execution_1  |  at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:43)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
execution_1  |  ... 5 more
execution_1  | Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Must have at least one header to import
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
execution_1  |  at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94)
execution_1  |  at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81)
execution_1  |  ... 8 more
execution_1  | Caused by: java.lang.IllegalArgumentException: Must have at least one header to import
execution_1  |  at com.google.common.base.Preconditions.checkArgument(Preconditions.java:144)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.CheckpointRangeHeaders.<init>(CheckpointRangeHeaders.java:32)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.DownloadHeadersStep.processHeaders(DownloadHeadersStep.java:118)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.DownloadHeadersStep.lambda$apply$0(DownloadHeadersStep.java:67)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$2(AbstractPeerRequestTask.java:83)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
execution_1  |  at java.base/java.util.Optional.ifPresent(Optional.java:178)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.handleMessage(AbstractPeerRequestTask.java:104)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$0(AbstractPeerRequestTask.java:67)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.dispatchBufferedResponses(RequestManager.java:185)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.processMessage(RequestManager.java:176)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.RequestManager.lambda$dispatchResponse$2(RequestManager.java:73)
execution_1  |  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.RequestManager.dispatchResponse(RequestManager.java:73)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.EthPeer.dispatch(EthPeer.java:294)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.EthPeers.dispatchMessage(EthPeers.java:131)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:275)
execution_1  |  at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
execution_1  |  at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
execution_1  |  at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
execution_1  |  at java.base/java.lang.Iterable.forEach(Iterable.java:75)
execution_1  |  at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
execution_1  |  at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
execution_1  |  at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:99)
execution_1  |  at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:33)
execution_1  |  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
execution_1  |  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
execution_1  |  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
execution_1  |  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
execution_1  |  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
execution_1  |  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
execution_1  |  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
execution_1  |  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
execution_1  |  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
execution_1  |  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
execution_1  |  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
execution_1  |  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
execution_1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
execution_1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
execution_1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
execution_1  |  ... 1 more
execution_1  | 2021-11-04 18:15:33.373+01:00 | nioEventLoopGroup-3-7 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x9a487d7b7b5fe27833... at block 13551501
execution_1  | 2021-11-04 18:15:33.956+01:00 | EthScheduler-Workers-2 | INFO  | PersistBlockTask | Imported #13,551,502 / 349 tx / 0 om / 29,971,658 (99.8%) gas / (0x05e25c7f9ea7f496aca60ca2a5b6e6a4e0c552da62917f02c5f7a9ee07809568) in 2.868s. Peers: 25
```

Which then begs the question: Is this normal? And if so, could the exception be caught so it looks a little less scary?

**Comment by matkt** [comment]
I'll check the hash of the block that caused the problem in the first log tomorrow. But I think it's just that the peer wasn't giving out valid blocks. So it's a normal but scary log
The second block it's more a logging issue I will check that. But looking at your logs indeed your node is well synchronized and continues to import without problem. We will rework the logs

**Comment by matt-nelson-csi** [comment]
closed for consensus fixes.
