### ISSUE TITLE
java.lang.IllegalArgumentException & java.nio.channels.UnsupportedAddressTypeException

### ISSUE THREAD

**Issue by DRIgnazGortngschirl** [hyperledger/besu#3053]
### Steps to Reproduce (Bug)
1. Use Version v21.10.0 in Docker
2. Use Ethereum Classic Chain
3. Full Sync

**Actual behavior:**

````
besu_1           | 2021-11-12 19:11:02.631+00:00 | nioEventLoopGroup-3-2 | ERROR | Subscribers | Error in callback:
besu_1           | java.lang.IllegalArgumentException: Comparison method violates its general contract!
besu_1           |      at java.base/java.util.TimSort.mergeHi(Unknown Source)
besu_1           |      at java.base/java.util.TimSort.mergeAt(Unknown Source)
besu_1           |      at java.base/java.util.TimSort.mergeForceCollapse(Unknown Source)
besu_1           |      at java.base/java.util.TimSort.sort(Unknown Source)
besu_1           |      at java.base/java.util.Arrays.sort(Unknown Source)
besu_1           |      at java.base/java.util.ArrayList.sort(Unknown Source)
besu_1           |      at java.base/java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
besu_1           |      at java.base/java.util.stream.Sink$ChainedReference.end(Unknown Source)
besu_1           |      at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
besu_1           |      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
besu_1           |      at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
besu_1           |      at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
besu_1           |      at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
besu_1           |      at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.handleNewBlockHashesFromNetwork(BlockPropagationManager.java:260)
besu_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthMessages.lambda$dispatch$0(EthMessages.java:36)
besu_1           |      at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
besu_1           |      at java.base/java.lang.Iterable.forEach(Unknown Source)
besu_1           |      at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
besu_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthMessages.lambda$dispatch$1(EthMessages.java:36)
besu_1           |      at java.base/java.util.Optional.ifPresent(Unknown Source)
besu_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthMessages.dispatch(EthMessages.java:35)
besu_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:290)
besu_1           |      at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
besu_1           |      at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
besu_1           |      at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
besu_1           |      at java.base/java.lang.Iterable.forEach(Unknown Source)
besu_1           |      at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
besu_1           |      at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
besu_1           |      at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:99)
besu_1           |      at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:33)
besu_1           |      at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
besu_1           |      at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
besu_1           |      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
besu_1           |      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
besu_1           |      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
besu_1           |      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
besu_1           |      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
besu_1           |      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
besu_1           |      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
besu_1           |      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
besu_1           |      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
besu_1           |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
besu_1           |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
besu_1           |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
besu_1           |      at java.base/java.lang.Thread.run(Unknown Source)

`````
&
`````
besu_1           | 2021-11-12 19:16:15.445+00:00 | vert.x-eventloop-thread-4 | WARN  | PeerDiscoveryAgent | Sending to peer DiscoveryPeer{status=bonding, enode=enode://bd170ae95e175a4f50211156a00f7173844841433d7baa1aa950441fd41e6a94ab8724fce8aebc67021b897d4984d5e9a7ca77730aa1ea98e128f1edc816690a@[2a01:4f8:1c17:c48f::1]:30303, firstDiscovered=1636744549062, lastContacted=0, lastSeen=0} failed, packet: 0x0cd6c81cf8c5b89bee76283579139bbafa75adb85bab1d07445904dfde0c247bd89afc0f031b3e0e2aa245fc9d9fa4f18ea389f43a299dced07e604ca4ea89423d62a55c897806f6587048c1179dab25c7ce364e6b876d0f28fe03ea71cc32a90101eb05cb847f00000182765f82765fd7902a0104f81c17c48f000000000000000182765f82765f84618ebdbb56
besu_1           | java.nio.channels.UnsupportedAddressTypeException
besu_1           |      at java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
besu_1           |      at java.base/sun.nio.ch.DatagramChannelImpl.send(Unknown Source)
besu_1           |      at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:296)
besu_1           |      at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
besu_1           |      at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949)
besu_1           |      at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
besu_1           |      at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:913)
besu_1           |      at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
besu_1           |      at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
besu_1           |      at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
besu_1           |      at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
besu_1           |      at io.vertx.core.datagram.impl.DatagramSocketImpl.doSend(DatagramSocketImpl.java:280)
besu_1           |      at io.vertx.core.datagram.impl.DatagramSocketImpl.lambda$send$2(DatagramSocketImpl.java:268)
besu_1           |      at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:88)
besu_1           |      at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
besu_1           |      at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
besu_1           |      at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
besu_1           |      at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
besu_1           |      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
besu_1           |      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
besu_1           |      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
besu_1           |      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
besu_1           |      at java.base/java.lang.Thread.run(Unknown Source)
`````

**Frequency:** often, but does not crash besu

### Versions (Add all that apply)
* Docker Version:  Tag:v21.10.0

### Additional Information

Full log; https://txt.mariomichel.com/?36efa66e1c3ef09c#68nd9nC9BD8wnrCRRYkGzPafStkihTZqpJzyQSQEhWX1

**Comment by MrMarioMichel** [comment]
Update: Also occur in v21.10.2 release

**Comment by gezero** [comment]
My suspicion is that we get the first exception when we [sort the stream of Peers](            ethContext.getEthPeers().streamBestPeers().collect(Collectors.toList());) we use volatile fields. I suspect that one of the fields that was used might got changed in the middle of the sort and therefore caused the exception.

**Comment by macfarla** [comment]
@MrMarioMichel I think the `java.nio.channels.UnsupportedAddressTypeException` should be fixed in latest besu - see https://github.com/hyperledger/besu/pull/2970

Are you still getting the IllegalArgumentException?

**Comment by MrMarioMichel** [comment]
@macfarla 

I didn't get any ```java.nio.channels.UnsupportedAddressTypeException``` yet (upgraded yesterday to latest v21.10.18)

But I do still get ```IllegalArgumentException``` errors. Do you need some more logs of that ?

**Comment by macfarla** [comment]
@MrMarioMichel if you have any extra info to add that would be useful. Also are you still on besu 21.10.0?

**Comment by MrMarioMichel** [comment]
@macfarla Sorry I meant 21.10 8 not .18

**Comment by DRIgnazGortngschirl** [comment]
I think it's solved in the recent releases. Never saw that error again after upgrading.
