### ISSUE TITLE
Invalid negative value -2 for scalar encoding (Hive)

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#3155]
This started happening somewhat recently. From a hive run on november 7: 
https://hivetests.ethdevops.io/viewer.html?file=results/besu/client-55d64ffb21b4cce22cc751f63ed534eb9553e924824d65771ad039844e99ed7e.log

Previously, around 30 consensus tests failed, but now it's in the 200 range instead. Error: 
```


  | 2021-12-07 12:33:55.179+00:00 \| main \| INFO  \| ProtocolScheduleBuilder \| Protocol schedule created with milestones: [Byzantium: 0, London: 2000]
-- | --
  | picocli.CommandLine$ExecutionException: Invalid negative value -2 for scalar encoding
  | at org.hyperledger.besu.cli.subcommands.blocks.BlocksSubCommand$ImportSubCommand.createController(BlocksSubCommand.java:253)
  | at org.hyperledger.besu.cli.subcommands.blocks.BlocksSubCommand$ImportSubCommand.run(BlocksSubCommand.java:200)
  | at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
  | at picocli.CommandLine.access$1300(CommandLine.java:145)
  | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
  | at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
  | at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
  | at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
  | at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
  | at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:54)
  | at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:31)
  | at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
  | at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
  | at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1408)
  | at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1226)
  | at org.hyperledger.besu.Besu.main(Besu.java:50)
  | Caused by: java.lang.IllegalArgumentException: Invalid negative value -2 for scalar encoding
  | at com.google.common.base.Preconditions.checkArgument(Preconditions.java:205)
  | at org.hyperledger.besu.ethereum.rlp.RLPOutput.writeLongScalar(RLPOutput.java:110)
  | at org.hyperledger.besu.ethereum.worldstate.StateTrieAccountValue.writeTo(StateTrieAccountValue.java:100)
  | at org.hyperledger.besu.ethereum.rlp.RLP.encode(RLP.java:85)
  | at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState.serializeAccount(DefaultMutableWorldState.java:139)
  | at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState$Updater.commit(DefaultMutableWorldState.java:435)
  | at org.hyperledger.besu.ethereum.chain.GenesisState.writeAccountsTo(GenesisState.java:120)
  | at org.hyperledger.besu.ethereum.chain.GenesisState.calculateGenesisStateHash(GenesisState.java:131)
  | at org.hyperledger.besu.ethereum.chain.GenesisState.fromConfig(GenesisState.java:89)
  | at org.hyperledger.besu.controller.BesuControllerBuilder.build(BesuControllerBuilder.java:256)
  | at org.hyperledger.besu.cli.subcommands.blocks.BlocksSubCommand$ImportSubCommand.createController(BlocksSubCommand.java:251)


```

**Comment by matkt** [comment]
Thanks , do you have the Besu version you are using ?

**Comment by macfarla** [comment]
@holiman what Besu version are you running?

**Comment by holiman** [comment]
Sorry, missed the first question. So, for the future. if you go to https://hivetests.ethdevops.io/, and click "Load" on one of the tests with Besu, you see the version. The latest results are using 
`besu/v22.1.0-RC2-dev-25a2af08/linux-x86_64/openjdk-java-11`
The latest 'consensus' tests are here: https://hivetests.ethdevops.io/?page=v-pills-results-tab&suite=1642293029-d334e9e5c1adbdcf51c43ab4ecd5e22d.json  , using `    besu/v22.1.0-RC2-dev-25a2af08/linux-x86_64/openjdk-java-11`. and they have the same problem: https://hivetests.ethdevops.io/viewer.html?file=results/besu/client-58189ab6c260110914b13d1de4ab0d5262dfb95b5b98a9436e64fd24c171efc2.log

**Comment by matkt** [comment]
fixed by #3835
