### ISSUE TITLE
New node joining an IBFT2 network with R1 and TLS fails to join the network after any blocks are created

### ISSUE THREAD

**Issue by joshuafernandes** [hyperledger/besu#3208]
### Description
As a node operator I would like to add new nodes to my network, eg as RPC nodes supporting API calls/blockscout etc

### Acceptance Criteria
Adding new nodes to an existing network with R1 and TLS would work as expected.

### Steps to Reproduce (Bug)
See the attached zip file
1. Use the attached zip file and extract
2. In the docker-compose file comment out members2 and 3
3. Run it with `./run.sh`
4. Give it a couple of mins for blocks to be created
5.  In the docker-compose file uncomment members2 and 3 and bring them back
6. Start members2 and 3 with `docker-compose up -d member2` and the same for member3 respectiely
7. Check the logs with `docker logs quorum_dev_quickstart-member2_1` (check the name for your setup)

**Expected behavior:** [What you expect to happen]
Nodes would just join the network and import blocks

**Actual behavior:** [What actually happens]
Nodes sit there hanging on peers=0 and no blocks are imported
```
(0xd10269b1f116dc1f8baa8960782ece8ed97abd5fe9797db029053985ce6fbaf8) for future import","throwable":""}
{"timestamp":"2021-12-20T03:20:33,600","container":"c2c56abf2179","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 1","throwable":""}
{"timestamp":"2021-12-20T03:20:38,602","container":"c2c56abf2179","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 1","throwable":""}
{"timestamp":"2021-12-20T03:20:40,459","container":"c2c56abf2179","level":"INFO","thread":"nioEventLoopGroup-3-9","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:20:41,370","container":"c2c56abf2179","level":"INFO","thread":"nioEventLoopGroup-3-10","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:20:42,166","container":"c2c56abf2179","level":"INFO","thread":"nioEventLoopGroup-3-1","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:20:43,603","container":"c2c56abf2179","level":"INFO","thread":"EthScheduler-Timer-0","class":"FullSyncTargetManager","message":"No sync target, waiting for peers: 1","throwable":""}
{"timestamp":"2021-12-20T03:20:44,677","container":"c2c56abf2179","level":"INFO","thread":"nioEventLoopGroup-3-2","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
{"timestamp":"2021-12-20T03:20:45,198","container":"c2c56abf2179","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"TLSContextFactory","message":"Initializing SSL Context using JKS keystore.","throwable":""}
```

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: [`besu --version`] 21.10.2
* Java version: [`java -version`] jsk11
* OS Name & Version: [`cat /etc/*release`] ubuntu 20.04 lts
* Kernel Version: [`uname -a`] 5.11
* Virtual Machine software & version: [`vmware -v`] n/a
* Docker Version: [`docker version`] 20.11.10
* Cloud VM, type, size: [Amazon Web Services I3-large] n/a

### Additional Information
[quorum-test-network-R1.tar.gz](https://github.com/hyperledger/besu/files/7742509/quorum-test-network-R1.tar.gz)

**Comment by joshuafernandes** [comment]
Update for networks with K1 (in place of R1) and all else the same:

- on doing a restart where there is existing data is appears to work
- on adding a fresh node in we saw 2 errors on different machines:
```
2021-12-21 00:21:15.031+00:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saving announced block 26 (0x797c80479996163a5406faddd65f3ec402c67015210b99af1f6d2b6d9492b52c) for future import
2021-12-21 00:21:16.736+00:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x09f5652362f09fa567... at block 0
2021-12-21 00:21:16.746+00:00 | EthScheduler-Services-2 (downloadHeaders) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Async operation failed. java.lang.IllegalArgumentException: Must have at least one header to import
        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
        at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Async operation failed. java.lang.IllegalArgumentException: Must have at least one header to import
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:86)
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.attemptFinalization(AsyncOperationProcessor.java:70)
        at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:43)
        at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
        ... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Must have at least one header to import
        at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94)
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Must have at least one header to import
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:144)
        at org.hyperledger.besu.ethereum.eth.sync.CheckpointRangeHeaders.<init>(CheckpointRangeHeaders.java:32)
        at org.hyperledger.besu.ethereum.eth.sync.DownloadHeadersStep.processHeaders(DownloadHeadersStep.java:118)
        at org.hyperledger.besu.ethereum.eth.sync.DownloadHeadersStep.lambda$apply$0(DownloadHeadersStep.java:67)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$2(AbstractPeerRequestTask.java:83)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.handleMessage(AbstractPeerRequestTask.java:104)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$0(AbstractPeerRequestTask.java:67)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.dispatchBufferedResponses(RequestManager.java:185)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.close(RequestManager.java:164)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager.closeOutstandingStreams(RequestManager.java:93)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager.close(RequestManager.java:82)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeer.handleDisconnect(EthPeer.java:318)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeers.registerDisconnect(EthPeers.java:96)
        at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.handleDisconnect(EthProtocolManager.java:343)
        at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$2(NetworkRunner.java:157)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchDisconnect$0(PeerConnectionEvents.java:55)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchDisconnect(PeerConnectionEvents.java:55)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.AbstractPeerConnection.disconnect(AbstractPeerConnection.java:159)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.DeFramer.exceptionCaught(DeFramer.java:221)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1374)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1237)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
2021-12-21 00:21:18.488+00:00 | nioEventLoopGroup-3-7 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:18.747+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-12-21 00:21:21.733+00:00 | nioEventLoopGroup-3-8 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:22.239+00:00 | nioEventLoopGroup-3-9 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:23.747+00:00 | nioEventLoopGroup-3-10 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:23.748+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-12-21 00:21:28.748+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-12-21 00:21:28.836+00:00 | nioEventLoopGroup-3-1 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:30.849+00:00 | nioEventLoopGroup-3-2 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:31.187+00:00 | nioEventLoopGroup-3-3 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:33.222+00:00 | nioEventLoopGroup-3-4 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:33.749+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-12-21 00:21:37.237+00:00 | nioEventLoopGroup-3-5 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:38.503+00:00 | nioEventLoopGroup-3-6 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:38.750+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers: 0
2021-12-21 00:21:40.551+00:00 | nioEventLoopGroup-3-7 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:21:43.750+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for pe
```
and
```
021-12-21 00:23:29.981+00:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0x8d08ae416c0789faeb... at block 0
2021-12-21 00:23:29.990+00:00 | EthScheduler-Services-5 (downloadHeaders) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Async operation failed. java.lang.IllegalArgumentException: Must have at least one header to import
        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
        at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
        at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Async operation failed. java.lang.IllegalArgumentException: Must have at least one header to import
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:86)
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.attemptFinalization(AsyncOperationProcessor.java:70)
        at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:43)
        at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
        ... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Must have at least one header to import
        at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.waitForAnyFutureToComplete(AsyncOperationProcessor.java:94)
        at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:81)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Must have at least one header to import
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:144)
        at org.hyperledger.besu.ethereum.eth.sync.CheckpointRangeHeaders.<init>(CheckpointRangeHeaders.java:32)
        at org.hyperledger.besu.ethereum.eth.sync.DownloadHeadersStep.processHeaders(DownloadHeadersStep.java:118)
        at org.hyperledger.besu.ethereum.eth.sync.DownloadHeadersStep.lambda$apply$0(DownloadHeadersStep.java:67)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$2(AbstractPeerRequestTask.java:83)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.handleMessage(AbstractPeerRequestTask.java:104)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$0(AbstractPeerRequestTask.java:67)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.dispatchBufferedResponses(RequestManager.java:185)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.close(RequestManager.java:164)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager.closeOutstandingStreams(RequestManager.java:93)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager.close(RequestManager.java:82)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeer.handleDisconnect(EthPeer.java:318)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeers.registerDisconnect(EthPeers.java:96)
        at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.handleDisconnect(EthProtocolManager.java:343)
        at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$2(NetworkRunner.java:157)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchDisconnect$0(PeerConnectionEvents.java:55)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchDisconnect(PeerConnectionEvents.java:55)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.AbstractPeerConnection.disconnect(AbstractPeerConnection.java:159)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.DeFramer.exceptionCaught(DeFramer.java:221)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1374)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1237)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        ... 1 more
2021-12-21 00:23:30.859+00:00 | nioEventLoopGroup-3-9 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:23:31.190+00:00 | nioEventLoopGroup-3-10 | INFO  | TLSContextFactory | Initializing SSL Context using JKS keystore.
2021-12-21 00:23:31.992+00:00 | EthScheduler-Timer-0 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xf737b9b69613d4aacf... at block 0
2021-12-21 00:23:32.002+00:00 | EthScheduler-Services-2 (downloadHeaders) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.


```

**Comment by siladu** [comment]
Most likely same issue as https://github.com/hyperledger/besu/issues/3207 so we will test this scenario once that is fixed.

**Comment by lucassaldanha** [comment]
We have confirmed that this is related to https://github.com/hyperledger/besu/issues/3254. Please follow #3254 for tracking this bug.
