### ISSUE TITLE
Low disk space left node in unusuable state

### ISSUE THREAD

**Issue by MariusVanDerWijden** [hyperledger/besu#3228]
During fuzzing the engine api, my disk ran full. 
Besu correctly saw that and tried to shut down. However something broke and the node kept repeating the following logs:
I could not shut besu down afterwards (not with ctrl+d,c) and had to manually kill the process with a SIGKILL,
```
2022-01-04 13:34:14.621+01:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-8,5,main]=Thread[vert.x-worker-thread-8,5,main] has been blocked for 396794 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	at java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	at java.base@17.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.response(ExecutionEngineJsonRpcMethod.java:83)
	at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:744)
	at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$14(JsonRpcHttpService.java:598)
	at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService$$Lambda$868/0x00000008005b5cd8.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$870/0x00000008005b6128.run(Unknown Source)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRun
```
Version: 
```
commit 02d52ea133f3bd8777be949f0bec99606ba9fd70 (HEAD -> merge, origin/merge)
Author: garyschulte <garyschulte@gmail.com>
Date:   Tue Dec 21 14:04:45 2021 -0800

    backport changes from merge to main of engine_executePayload
    
    Signed-off-by: garyschulte <garyschulte@gmail.com>
```

**Comment by jflo** [comment]
sorry fren, cannot reproduce.
