### ISSUE TITLE
admin_addPeer RPC error

### ISSUE THREAD

**Issue by RP27** [hyperledger/besu#3294]
### Description
As a Besu Dev, I want to be able to make a JSON-RPC API call for admin_addPeer so that I can add a peer to an IBFT 2.0 network. 

### Steps to Reproduce (Bug)
1. Run Besu
2. Try the following RPC call
`{
    "jsonrpc": "2.0",
    "method": "admin_addPeer",
    "params": [
        "enode://04adacdd1b35190519d972dacda5a2178fd104898539fc2cd9dd8d659c60bb5e71e72f67be0f42fdddd4d91320ad1eb93bccaee38341149bf018327ac4b217f7@127.0.0.1:30304"
    ],
    "id": 1
}`

**Expected behavior:** admin_addPeer should allow a new peer to be added to the IBFT network

**Actual behavior** 

_Response:_ Internal Server Error

_Stack Trace:_
`2022-01-18 10:32:28.728+10:00 | vert.x-eventloop-thread-1 | ERROR | RoutingContext | Unhandled exception in router
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "io.vertx.ext.web.RoutingContext.getBodyAsString()" is null
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.handleJsonRPCRequest(JsonRpcHttpService.java:572)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:117)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at org.hyperledger.besu.ethereum.api.handlers.TimeoutHandler.processHandler(TimeoutHandler.java:75)
	at org.hyperledger.besu.ethereum.api.handlers.TimeoutHandler.lambda$handler$0(TimeoutHandler.java:40)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1128)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:154)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:290)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:86)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:561)
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:544)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:71)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:163)
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:191)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:147)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:156)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: [besu/v21.10.8/osx-x86_64/oracle_openjdk-java-17]
* Java version: [openjdk version "17.0.1" 2021-10-19]
* OS Name & Version: [Monterey Version 12.0 21A344 ]
* Kernel Version: [Darwin 192.168.20.18 21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 arm64]

### Additional Information
Other RPC calls appear to work normally.

**Comment by macfarla** [comment]
Hey @RP27 I note you've got besu 21.10.3 - can you try with latest master and see if the behaviour is different? The error is coming from vert.x and we have updated vert.x in between

**Comment by RP27** [comment]
@macfarla I have tried it again with 21.10.8, but I've still obtained the same issue. Have updated my version in the issue above as well.

**Comment by macfarla** [comment]
also can you try this on the cmd line (eliminating postman) 
`
curl -X POST --data '{"jsonrpc":"2.0","method":"admin_addPeer","params":["enode://04adacdd1b35190519d972dacda5a2178fd104898539fc2cd9dd8d659c60bb5e71e72f67be0f42fdddd4d91320ad1eb93bccaee38341149bf018327ac4b217f7@127.0.0.1:30304"],"id":51}' http://localhost:8545
`

**Comment by RP27** [comment]
@macfarla That seems to work

**Comment by macfarla** [comment]
Is there something different with how you're sending that request in postman vs others that are working? headers maybe?

**Comment by RP27** [comment]
Ah, you were right, it seems the headers were different, though I don't remember ever changing them. Seems to work now!

Should I close the issue?

**Comment by macfarla** [comment]
I think we should still handle NPE in that scenario - but at least we know why it's happening!

**Comment by macfarla** [comment]
I can reproduce this if I uncheck the content-length or host headers
