### ISSUE TITLE
Besu in docker loses sync and does not recover

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#3300]
### Description

On Ethereum mainnet, Besu v21.10.7/linux-x86_64/openjdk-java-11, inside a docker volume. No IPv6 enabled inside docker.

Besu loses sync, does not recover without a restart. This might be related to encountering IPv6 peers? See also PR #2883 

IPv6 being the culprit is conjecture, since it's the only other error message I saw around the time this happened.

```
execution_1  | 2022-01-16 09:02:57.813+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015604 (0x0b181636cd08ae2c56a3952d20558cab61f5d0d565cda77789c01a4173adadb2) for future import
execution_1  | 2022-01-16 09:03:16.299+00:00 | nioEventLoopGroup-3-9 | INFO  | BlockPropagationManager | Saving announced block 14015605 (0x87fecf94d51ed2f96a29ce518cfe2692e7125e04285b0879a17455eba00d2cf6) for future import
execution_1  | 2022-01-16 09:03:16.614+00:00 | nioEventLoopGroup-3-6 | INFO  | GetBlockFromPeerTask | Failed to download block 0x87fecf94d51ed2f96a29ce518cfe2692e7125e04285b0879a17455eba00d2cf6 from peer Peer 0x5bdae2119793434f48....
execution_1  | 2022-01-16 09:03:16.691+00:00 | nioEventLoopGroup-3-3 | INFO  | GetBlockFromPeerTask | Failed to download block 0x87fecf94d51ed2f96a29ce518cfe2692e7125e04285b0879a17455eba00d2cf6 from peer Peer 0x1242de91f43cbf7f21....
execution_1  | 2022-01-16 09:03:21.199+00:00 | nioEventLoopGroup-3-5 | INFO  | GetBlockFromPeerTask | Failed to download block 0x87fecf94d51ed2f96a29ce518cfe2692e7125e04285b0879a17455eba00d2cf6 from peer Peer 0x0502b874b046e5a892....
execution_1  | 2022-01-16 09:03:21.199+00:00 | nioEventLoopGroup-3-5 | INFO  | GetBlockFromPeerTask | Failed to download block 0x87fecf94d51ed2f96a29ce518cfe2692e7125e04285b0879a17455eba00d2cf6 from peer Peer 0x5c22800f3912ba14c0....
execution_1  | 2022-01-16 09:03:28.298+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015606 (0xe01af85e6383cf8b82e361c756546ae122cb3b61f3240e97845ca9d6a76748fa) for future import
execution_1  | 2022-01-16 09:03:31.546+00:00 | nioEventLoopGroup-3-9 | INFO  | BlockPropagationManager | Saving announced block 14015607 (0xbb0d1bc59cd26241e6657a99bb296ae1af35ddc33247ef52285043d609611a03) for future import
execution_1  | 2022-01-16 09:03:44.822+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015608 (0xc208ff8cf3a368d81b063e89ac857ded691bebcc5422a28b78177c5296cf9581) for future import
execution_1  | 2022-01-16 09:03:57.754+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015609 (0x1feee3a41d82542f1f4f32e421240ac864f6c679e6563d72078275723326a44c) for future import
execution_1  | 2022-01-16 09:04:03.610+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015610 (0xbd1067c61cb80c15c18edd3e5440cb32d973578bf8d42e5fd5ab060f81c07de1) for future import
execution_1  | 2022-01-16 09:04:13.469+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015612 (0x1060ea3553a905f8abbc3632e52464e8cdad26939c566514de61e8fe9f084171) for future import
execution_1  | 2022-01-16 09:04:14.124+00:00 | nioEventLoopGroup-3-5 | INFO  | BlockPropagationManager | Saving announced block 14015611 (0x77ae1f0f8b88598ad8be1f3383da7e0698b95e20009c3349f80d98d547454fd2) for future import
execution_1  | 2022-01-16 09:04:23.560+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015613 (0xf2069d30ea28a7416f5befd5c5d26d39c0d1121dcc2e8cc78b7ceb68b13b9026) for future import
execution_1  | 2022-01-16 09:04:23.644+00:00 | nioEventLoopGroup-3-5 | INFO  | GetBlockFromPeerTask | Failed to download block 0xf2069d30ea28a7416f5befd5c5d26d39c0d1121dcc2e8cc78b7ceb68b13b9026 from peer Peer 0x0502b874b046e5a892....
execution_1  | 2022-01-16 09:04:25.059+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14015614 (0xfc9384a2092e6d14931034c47d391a2abd5428bc303a3ff99cbda82f17f1230f) for future import
execution_1  | 2022-01-16 09:04:30.863+00:00 | nioEventLoopGroup-3-5 | INFO  | BlockPropagationManager | Saving announced block 14015615 (0x62b15e80c1148f7172518ed1e143c6d035dc72c44f95d6c83455b6ec5da2ed8d) for future import
execution_1  | 2022-01-16 09:04:31.921+00:00 | nioEventLoopGroup-3-6 | INFO  | BlockPropagationManager | Saving announced block 14015616 (0x6e02c478b14bba6168b46aad565e445423e1f8c22ce9878dde2bbfadae628bdf) for future import
execution_1  | 2022-01-16 09:33:49.719+00:00 | vert.x-eventloop-thread-3 | WARN  | PeerDiscoveryAgent | Unsupported address type exception when connecting to peer DiscoveryPeer{status=bonding, enode=enode://949423caff724a5e787b5c3622fe6f20635a9228d68aa90ac926b5859c04d6a8fbc26963314108243c591a867a294fc778bfb45b9ce16902ce958619bf85570f@[2a01:7a7:2:1467:ec4:7aff:fee2:568e]:30303, firstDiscovered=1642325629718, lastContacted=0, lastSeen=0}, this is likely due to ipv6 not being enabled at runtime. Set logging level to TRACE to see full stacktrace
```

Note it stopped importing 2022-01-16. It did not recover from this; on 2022-01-18 I restarted it and it picked back up where it lost sync:

```
execution_1  | 2022-01-18 19:32:49.999+00:00 | nioEventLoopGroup-3-3 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xc40b2405ed046daa34... at block 14015586
execution_1  | 2022-01-18 19:33:18.809+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 14015600 (0x4abe25626fb6807eecad725cc36a6e2b5b372ebf0f057a03a4fbb7e919bf3081), - Mg/s, Peers: 15
execution_1  | 2022-01-18 19:36:16.505+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 14015800 (0x5a9a2270a0151216561c7469a77ee8a4b67f92e2e407379ddb57492692261cea), 17.447 Mg/s, Peers: 23
execution_1  | 2022-01-18 19:38:51.245+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 14016000 (0xdb06cddfcebf8cdca5683087b9b6f6b2c1f0e5558e182559ad8f1992ff25d2c1), 20.059 Mg/s, Peers: 25
execution_1  | 2022-01-18 19:41:30.309+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | FullImportBlockStep | Import reached block 14016200 (0x05f4f1987971f00dcbc00d01ce5bc7be16c95b807b694b46155bbb4c5f2714a1), 19.238 Mg/s, Peers: 25
```

**Comment by yorickdowne** [comment]
This might just be good old DB corruption.

It's on a host that ran a Geth just fine, and Heco, and has ECC RAM and mirrored drives, so I am not suspecting hardware right away.

```
execution_1  | 2022-01-18 20:04:55.658+00:00 | EthScheduler-Services-5 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
execution_1  | java.util.concurrent.CompletionException: java.lang.RuntimeException: World State Root does not match expected value, header 0x44d6b43e092ae0e3873d237a32c97dd8c4c7824ca00509da400fab3a52c52130 calculated 0x6e969bdffa60d541cfcecfbed3dda1e8d360a88a097e9f39363d8c0417535e5d
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
execution_1  |  at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)
execution_1  |  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
execution_1  |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
execution_1  |  at java.base/java.lang.Thread.run(Thread.java:829)
execution_1  | Caused by: java.lang.RuntimeException: World State Root does not match expected value, header 0x44d6b43e092ae0e3873d237a32c97dd8c4c7824ca00509da400fab3a52c52130 calculated 0x6e969bdffa60d541cfcecfbed3dda1e8d360a88a097e9f39363d8c0417535e5d
execution_1  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.persist(BonsaiPersistedWorldState.java:264)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:202)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:42)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:75)
execution_1  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:150)
execution_1  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:108)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)
execution_1  |  at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:54)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)
execution_1  |  at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
execution_1  |  at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
execution_1  |  ... 5 more
```

**Comment by yorickdowne** [comment]
I can leave this up for a little while for troubleshooting, maybe a day or two. It uses Bonsai tries.

**Comment by macfarla** [comment]
If it's related to #2883, that change is not in 21.10.7 (it will be in the 22.1.0-RC)
https://github.com/hyperledger/besu/blob/1104f1b3ed85f26002dabd313c5a2c856dd27c37/ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/discovery/PeerDiscoveryAgent.java

If it's a possibility to enable IPv6 on docker that might make your life easier!

**Comment by yorickdowne** [comment]
I do not know that it’s related to IPv6 at all. Docker and IPv6 are not a love affair, it’s a bit of a mess actually. The goal for me is to have a stable Besu in a docker environment, IPv4 only. Occasional error messages about v6 are okay, as long as they don’t stop sync.

**Comment by yorickdowne** [comment]
Restarting Besu allowed it to catch up again and it's been keeping up with head, will monitor. I am quite worried about the fact it lost sync and needed a restart. Root cause TBD, that's what this issue is for. It may be necessary to sync Bonsai trie Besu from scratch on mainnet multiple times to find the culprit.

The high-level background is that I am attempting to move away from my Geth monoculture. To do that, I need to gain confidence in alternatives, such as Besu.

**Comment by macfarla** [comment]
@yorickdowne you're right, ipv6 peers is probably a red herring, even though we made a change to improve the logging situation to make it clearer. Are you using full sync or fast sync? We're working on improvements to fast sync which are in the current RC release

Can you share your besu config?

**Comment by yorickdowne** [comment]
I am using fast sync. This is the config.

```
      - /opt/besu/bin/besu
      - --data-path
      - /var/lib/besu
      - --p2p-port
      - ${EC_P2P_PORT}
      - --rpc-http-enabled
      - --rpc-http-api
      - "WEB3,ETH,NET"
      - --rpc-http-host
      - 0.0.0.0
      - --rpc-http-port
      - ${EC_RPC_PORT}
      - --rpc-http-cors-origins=*
      - --rpc-ws-enabled
      - --rpc-ws-api
      - "WEB3,ETH,NET"
      - --rpc-ws-host
      - 0.0.0.0
      - --rpc-ws-port
      - ${EC_WS_PORT}
      - --host-allowlist=*
      - --logging
      - ${LOG_LEVEL}
      - --network
      - ${EC_NETWORK}
      - --metrics-enabled
      - --metrics-host
      - 0.0.0.0
      - --Xdata-storage-format=BONSAI
```

**Comment by fab-10** [comment]
@yorickdowne we are investigation this issue, since it seldom happens to us as well, so collecting data is very useful in this phase, could you share, could you share the resources allocated to Besu, like cpu, memory, free disk space and verify if there are incoming peers?

**Comment by yorickdowne** [comment]
@fab-10 Besu uses 1 to 2 cores on a 6-core, 12-thread machine. It uses 10 GiB of memory out of 32, total in use with other processes 24.5 GiB. There are ~700 GiB free on the NVMe.

I'm on debug logging right now and grepped for incoming, looks like yes, as expected, incoming works fine: `Too many peers. Disconnect incoming connection`

If there's a way to query number of outgoing and incoming (established) peer connections, please share, I'll run it.

**Comment by yorickdowne** [comment]
Yep confirmed. This is right after restart, needed to enable the admin RPC space.

```
curl -s -X POST --data '{"jsonrpc":"2.0","method":"admin_peers","params":[],"id":1}' https://besu.example.com | grep localAddress | grep 30303
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      "localAddress" : "172.19.0.6:30303",
      ```

**Comment by fab-10** [comment]
On main (22.1.0-RC4-SNAPSHOT version) there are more sync fixes, that we are currently testing, with good results, if you want to give it a try.
