### ISSUE TITLE
Besu 22.1.0-RC4 loses ability to respond to websocket

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#3381]
### Description

Besu v22.1.0-RC4 loses the ability to respond to websocket connections. Eventually it will start displaying blocked thread messages in a continuous loop. Restart resolves it, until it re-occurs.

This is while using Bonsai tries.

I had this issue with the current GA release as well and tried 22.1.0-RC4 for the sync fixes. This issue here does not appear related to sync at all: Besu does not have to do a lengthy catchup after restart.

```
execution_1  | 2022-02-06 14:04:21.783+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 80305521 ms, time limit is 2000 ms
execution_1  | io.vertx.core.VertxException: Thread blocked
execution_1  |  at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
execution_1  |  at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
execution_1  |  at java.base@11.0.13/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
execution_1  |  at java.base@11.0.13/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
execution_1  |  at java.base@11.0.13/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
execution_1  |  at java.base@11.0.13/java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
execution_1  |  at app//org.hyperledger.besu.ethereum.api.jsonrpc.websocket.JsonResponseStreamer.writeFrame(JsonResponseStreamer.java:63)
execution_1  |  at app//org.hyperledger.besu.ethereum.api.jsonrpc.websocket.JsonResponseStreamer.write(JsonResponseStreamer.java:51)
execution_1  |  at app//com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171)
execution_1  |  at app//com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:515)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serializeContents(ObjectArraySerializer.java:253)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:214)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.std.ObjectArraySerializer.serialize(ObjectArraySerializer.java:23)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
execution_1  |  at app//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
execution_1  |  at app//com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
execution_1  |  at app//com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1219)
execution_1  |  at app//com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1044)
execution_1  |  at app//org.hyperledger.besu.ethereum.api.jsonrpc.websocket.WebSocketRequestHandler.replyToClient(WebSocketRequestHandler.java:229)
execution_1  |  at app//org.hyperledger.besu.ethereum.api.jsonrpc.websocket.WebSocketRequestHandler.lambda$handleJsonBatchRequest$4(WebSocketRequestHandler.java:209)
execution_1  |  at app//org.hyperledger.besu.ethereum.api.jsonrpc.websocket.WebSocketRequestHandler$$Lambda$1579/0x0000000840765040.handle(Unknown Source)
execution_1  |  at app//io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
execution_1  |  at app//io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
execution_1  |  at app//io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
execution_1  |  at app//io.vertx.core.impl.future.CompositeFutureImpl.trySucceed(CompositeFutureImpl.java:163)
execution_1  |  at app//io.vertx.core.impl.future.CompositeFutureImpl.lambda$all$0(CompositeFutureImpl.java:38)
execution_1  |  at app//io.vertx.core.impl.future.CompositeFutureImpl$$Lambda$1577/0x0000000840764840.handle(Unknown Source)
execution_1  |  at app//io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
execution_1  |  at app//io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
execution_1  |  at app//io.vertx.core.impl.future.FutureBase$$Lambda$625/0x0000000840482c40.run(Unknown Source)
execution_1  |  at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
execution_1  |  at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
execution_1  |  at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
execution_1  |  at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
execution_1  |  at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
execution_1  |  at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
execution_1  |  at java.base@11.0.13/java.lang.Thread.run(Thread.java:829)
```

When this happens, Besu does not respond gracefully to SIGTERM.

**Frequency:**

Reproducible by using Besu as the WS target of a chainlink node

### Versions
* Software version: besu/v22.1.0-RC4/linux-x86_64/openjdk-java-11
* OS Name & Version: Ubuntu 20.04
* Docker Version: 20.10.7

Besu is configured with `--Xdata-storage-format=BONSAI`

### System

6-core, 32 GiB RAM, 1.9TB NVMe

**Comment by garyschulte** [comment]
Do you have reason to believe this is specific to bonsai?  What web socket client are you using, nimbus?

**Comment by yorickdowne** [comment]
I have no reason to believe this is in any way related to Bonsai.

The websocket client is a chainlink node.

**Comment by yorickdowne** [comment]
I've added `-XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/lib/besu/jvm.log` to `JAVA_OPTS` and will `kill -3` Besu when this happens again.

**Comment by fab-10** [comment]
thanks for the logs @yorickdowne, we will review them.
To help us reproducing this problem, do you which kind of requests, and the how many in parallel, Chainlink submits to Besu?

**Comment by yorickdowne** [comment]
Let me try something - I can point chainlink at Infura (the horror!) and see what gets recorded.

**Comment by yorickdowne** [comment]
Roughly 10 minutes worth of requests. The bulk appears to be `eth_call`

![image](https://user-images.githubusercontent.com/71337066/153013961-15608b02-ec8e-40bb-92d8-996b9fa56852.png)

**Comment by fab-10** [comment]
I think I am now able to reproduce this issue, and I am working for a fix
