### ISSUE TITLE
ConcurrentModificationException in Subscribers class

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#3491]
### Description
Subscribers class thrown this exception

```
java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CopyOnWriteArrayList.bulkRemove(CopyOnWriteArrayList.java:855)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.bulkRemove(CopyOnWriteArrayList.java:833)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.removeIf(CopyOnWriteArrayList.java:816)
	at org.hyperledger.besu.ethereum.eth.manager.EthPeers.reattemptPendingPeerRequests(EthPeers.java:151)
	at org.hyperledger.besu.ethereum.eth.manager.EthPeers.dispatchMessage(EthPeers.java:141)
	at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:275)
	at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
	at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:99)
	at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:33)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Versions (Add all that apply)
* Software version: 22.1.0
* Java version: Java11

**Comment by sharad-develop** [comment]
@fab-10 can you provide steps to reproduce

**Comment by fab-10** [comment]
@sharad-develop unfortunately this kind of exception is very rare, it was collected by our alerting rules on one of our canary nodes, so there is not a deterministic way to reproduce it yet. Opening this issue is more a way to keep track of it and see if others are having the same.
My approach to this kind of issues, would be to do a code analisys to spot potential concurrency issues, but this could be time consuming, and since it is occuring rarely, putting effort on this depends on other priorities

**Comment by daniellehrner** [comment]
A user on Discord has the same issue: https://discord.com/channels/697535391594446898/888098626264502302/994181378860126269

The desciption of his setup is:
```
Version: besu/v22.4.3/linux-x86_64/openjdk-java-11
I'm connecting to a VPN network using OpenVpn (that is because my ISP seems to throttle p2p bandwidth)
I'm using bonsai storage
I'm using default sync mode
```

**Comment by iamhsk** [comment]
From another user:  stack trace here: https://pastebin.com/2zaa4JEd
Logs: https://pastebin.com/64LBAv6s
Discord message: https://discord.com/channels/905194001349627914/938504958909747250/1001287161007571035
