### ISSUE TITLE
Getting Error : Private Marker Transaction failed due to intrinsic gas exceeding the limit

### ISSUE THREAD

**Issue by jann2005** [hyperledger/besu#3498]
### Description
I wanted to create a privacy group with two participants and do a private transaction between these two .

Steps to re-produce - 
a. I have created 3 Besu nodes with privacy enabled.
b. Each node is running a tressera node inside.
c. Using IBFT consensus
d. Created Privacy group with 2 participants 
e . Sending Ether within 2 participants member 

Getting Error :  Private Marker Transaction failed due to intrinsic gas exceeding the limit

## Getting Privacy Group ID -
             node1 = Besu.build(new HttpService("http://localhost:8545"));
            List<Base64String> participants = new ArrayList<Base64String>();
            participants.add(Base64String.wrap("KXJmOY+SyjGoPgZmA7itpSu4W6wxWFCWz+4HQGvZ600="));
            participants.add(Base64String.wrap("sOkbkOhXVBzhOzYX7qSy0AqIhvdBO1g5nG9ytFfrARI="));
            Base64String privacyGrpIdBase64 = node1
                    .privCreatePrivacyGroup(participants, "network_1", "Network 1 privacy group")
                    .send()
                    .getPrivacyGroupId();
            privacyGrpId = privacyGrpIdBase64.toString();

## Sending Ether - 
         TransactionManager transactionManager = new BesuPrivateTransactionManager(besu,
                new BesuPrivacyGasProvider(DefaultGasProvider.GAS_PRICE, DefaultGasProvider.GAS_LIMIT), credentials, CHAIN_ID, privateForm, privacyGroupId);
        Transfer transfer = new Transfer(web3j, transactionManager);
        TransactionReceipt transactionReceipt = transfer.sendFunds(toAddress, value, Convert.Unit.ETHER).send();

### Stacktrace 

2022-02-25 14:47:51.247 ERROR 47917 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Error processing transaction request: Private Marker Transaction failed due to intrinsic gas exceeding the limit. Gas limit used from the Private Transaction.] with root cause

java.lang.RuntimeException: Error processing transaction request: Private Marker Transaction failed due to intrinsic gas exceeding the limit. Gas limit used from the Private Transaction.
        at org.web3j.tx.PrivateTransactionManager.processResponse(PrivateTransactionManager.java:250) ~[besu-5.0.0.jar:na]
        at org.web3j.tx.PrivateTransactionManager.executeTransaction(PrivateTransactionManager.java:109) ~[besu-5.0.0.jar:na]
        at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:102) ~[core-5.0.0.jar:na]
        at org.web3j.tx.Transfer.send(Transfer.java:79) ~[core-5.0.0.jar:na]
        at org.web3j.tx.Transfer.send(Transfer.java:55) ~[core-5.0.0.jar:na]
        at org.web3j.tx.Transfer.lambda$sendFunds$1(Transfer.java:107) ~[core-5.0.0.jar:na]
        at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42) ~[core-5.0.0.jar:na]
.....

### Versions
Besu Version - 22.1.0
web3j Lib - 5.0.0
Jopen JDK 11

**Comment by MadelineMurray** [comment]
Thanks for providing these details @jann2005.  The team will have a look this week.

**Comment by pinges** [comment]
Hi @jann2005, I've had a look what is happening here. The error happens, because Besu uses the gas_limit from from the private transaction (as well as the gas_cost) that you are sending for the private marker transaction. If you are using the Transfer class from web3j to send the transaction the gas_limit used in the private transaction is 21000 (cost for a value transfer), which is below the intrinsic cost for the PMT. The minimum cost for the PMT is 21128 (tx base cost of 21000 plus 32 * 4, for 32 byte payload times 4, which is the cost for a zero byte, more for a non zero byte).

**Comment by pinges** [comment]
The PrivateTransactionManager in web3j could check whether the gas_limit used in the private transaction is greater than the intrinsic gas for the PMT.  The sendTransaction() method could then fail early, or could fix the gas_limit.

**Comment by jann2005** [comment]
@pinges  - I am setting  DefaultGasProvider.GAS_LIMIT . The value is below by default. This should be sufficient as per your logic. Is not it?
public static final BigInteger GAS_LIMIT = BigInteger.valueOf(9_000_000);

But still I am getting this issue. Please comment if I am missing something.

**Comment by macfarla** [comment]
Can you share the code you're using and the error you're getting?

**Comment by iamhsk** [comment]
Closing this issue since no activity in the past 30 days. Feel free to reopen if further help is needed 😊

**Comment by notAhacker13** [comment]
Hi, I have been trying to deploy a smart contract on my private permissioned network created using besu.

I am getting the error " reason: 'Intrinsic gas exceeds gas limit " , below is my code and genesis

import { Web3 } from 'web3';
import { resolve } from 'path';
import { readFileSync } from 'fs';

import { Common, Hardfork } from '@ethereumjs/common'
import { LegacyTransaction } from '@ethereumjs/tx'

const web3 = new Web3("http://127.0.0.1:8545/");
// use an existing account, or make an account
// const privateKey = "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63";
// const account = Web3.eth.accounts.privateKeyToAccount(privateKey);

// const acc = "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73";
const privateKey = "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63";

const privateKeyBuffer = Buffer.from(privateKey, 'hex');

const acc = web3.eth.accounts.privateKeyToAccount("0x8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63");

// read in the contracts
const contractJsonPath = resolve(process.cwd(), "SimpleStorage.json");
const contractJson = JSON.parse(readFileSync(contractJsonPath));
const contractAbi = contractJson.abi;
const contractBinPath = resolve(process.cwd(), "SimpleStorage.bin");
const contractBin = readFileSync(contractBinPath);

// initialize the default constructor with a value `47 = 0x2F`; this value is appended to the bytecode
const contractConstructorInit =
  "000000000000000000000000000000000000000000000000000000000000002F";

  const contractBinHex = contractBin.toString('hex'); // Convert buffer to hexadecimal string
  const data1 = `0x${contractBinHex}${contractConstructorInit}`; // Concatenate  

// get txnCount for the nonce value
const txnCount = await web3.eth.getTransactionCount(acc.address);

const rawTxOptions = {
  nonce: web3.utils.numberToHex(txnCount),
  from: acc.address,
  to: null,
  value: "0x00",
  data: data1,
//   data: "0x" + contractBin + contractConstructorInit, // contract binary appended with initialization value
//   gasPrice: 100, //ETH per unit of gas
  gasPrice: 500,
   gas: 500000000,
  chainId: 1337 //max number of gas units the tx is allowed to use
};

// const gasEstimate = await web3.eth.estimateGas({
//     from: acc.address,
//     data: data1
// });
// console.log("gas estimate -->", gasEstimate);

console.log("Creating transaction...");

const common = Common.custom({ chainId: 6990 },{ hardfork: Hardfork.Berlin })

// const tx = new Tx(rawTxOptions);

const tx = LegacyTransaction.fromTxData(rawTxOptions, { common })

console.log("Signing transaction...");
console.log("Length:", privateKey.length);
const signedtx = tx.sign(privateKeyBuffer);
console.log("Sending transaction...");
var serializedTx = signedtx.serialize();
console.log("reached here...")

console.log('Serialized Transaction:', serializedTx);

// const pTx = await web3.eth.sendSignedTransaction(
//   "0x" + serializedTx.toString("hex"),
// );

try {
    const pTx = await web3.eth.sendSignedTransaction(
      "0x" + Buffer.from(serializedTx).toString('hex')
    );
    console.log('Transaction Hash:', pTx);
  } catch (error) {
    console.error('Error sending transaction:', error);
  }
  
Genesis:-

{
  "config" : {
    "chainId" : 6990,
    "berlinBlock" : 0,
    "ibft2" : {
      "blockperiodseconds" : 2,
      "epochlength" : 30000,
      "requesttimeoutseconds" : 4
    }
  },
  "nonce" : "0x0",
  "timestamp" : "0x58ee40ba",
  "gasLimit" : "0x47b760",
  "difficulty" : "0x1",
  "mixHash" : "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "coinbase" : "0x0000000000000000000000000000000000000000",
  "alloc" : {
    "0x086Ed7A43049c0A2a428884E69ec298dC215Fa61" : {
      "privateKey" : "98237264cbac8630421c10ef99521102f3c720bcb341591067dd45c1e1b6b5a6",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    },
    "fe3b557e8fb62b89f4916b721be55ceb828dbd73" : {
      "privateKey" : "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "0xad78ebc5ac6200000"
    },
    "627306090abaB3A6e1400e9345bC60c78a8BEf57" : {
      "privateKey" : "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    },
    "f17f52151EbEF6C7334FAD080c5704D77216b732" : {
      "privateKey" : "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
      "comment" : "private key and this comment are ignored.  In a real chain, the private key should NOT be stored",
      "balance" : "90000000000000000000000"
    }
  },
  "extraData" : "0xf87ea00000000000000000000000000000000000000000000000000000000000000000f8549499793e1a679672b9ec70b77976f7270cbf15d5e2941e0e19a96d2beff77a0721251c5cdb7ee8297dbb942ea65fb755dc807cf94c2c79e9d030e6aab370ae940f98db1b38140dd682c78b79bade89dc7f0983ff808400000000c0"
}
