### ISSUE TITLE
Noisy unhandled exception on interrupted mining

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3627]
### Description
As an operator, I don't want a common task like mining interruption to be logged like an error.

### Acceptance Criteria
Mining being interrupted when a block arrives should only be visible at debug logging level.

### Steps to Reproduce (Bug)
1. Set up 2 besu miners.
2. When one receives the new block while it is still mining, observe the ERROR message and stack trace in the logs.

**Expected behavior:** [What you expect to happen]
Notification of interruption should only display when DEBUG is enabled.

**Actual behavior:** [What actually happens]
```
2022-03-23 17:22:30.511+00:00 | pool-7-thread-217 | ERROR | BlockMiner | Block mining threw an unhandled exception.
java.lang.IllegalStateException: Attempt to create block was interrupted
        at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:212)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:143)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractBlockCreator.createBlock(AbstractBlockCreator.java:129)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.mineBlock(BlockMiner.java:136)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.run(BlockMiner.java:83)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.CancellationException
        at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2396)
        at org.hyperledger.besu.ethereum.mainnet.PoWSolver$PoWSolverJob.cancel(PoWSolver.java:65)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.hyperledger.besu.ethereum.mainnet.PoWSolver.cancel(PoWSolver.java:149)
        at org.hyperledger.besu.ethereum.blockcreation.PoWBlockCreator.cancel(PoWBlockCreator.java:113)
        at org.hyperledger.besu.ethereum.blockcreation.BlockMiner.cancel(BlockMiner.java:166)
        at org.hyperledger.besu.ethereum.blockcreation.PoWMiningCoordinator.haltMiner(PoWMiningCoordinator.java:137)
        at org.hyperledger.besu.ethereum.blockcreation.PoWMiningCoordinator.haltMiner(PoWMiningCoordinator.java:38)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractMiningCoordinator.lambda$haltCurrentMiningOperation$0(AbstractMiningCoordinator.java:164)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractMiningCoordinator.haltCurrentMiningOperation(AbstractMiningCoordinator.java:162)
        at org.hyperledger.besu.ethereum.blockcreation.AbstractMiningCoordinator.onBlockAdded(AbstractMiningCoordinator.java:180)
        at org.hyperledger.besu.ethereum.chain.DefaultBlockchain.lambda$appendBlock$9(DefaultBlockchain.java:290)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
```

**Frequency:** [What percentage of the time does it occur?]
Every block.

**Comment by alexheat** [comment]
I just setup my node and am trying to verify if it is working correctly. If I get this error, does it mean that the mining is working correctly and this error just means that I didn't mine that block and it is time to move on to the next block?

**Comment by lucassaldanha** [comment]
> does it mean that the mining is working correctly and this error just means that I didn't mine that block and it is time to move on to the next block? 

Correct! Whenever a newer block arrives, we interrupt the mining thread so it can start trying to mine the next block.

**Comment by wcgcyx** [comment]
@jflo Hi, it seems like this has already been fixed in your PR: https://github.com/hyperledger/besu/pull/3840 
Should we close this issue?
