### ISSUE TITLE
Thread blocked - "thread":"vertx-blocked-thread-checker","class":"BlockedThreadChecker"

### ISSUE THREAD

**Issue by rinor** [hyperledger/besu#3732]
### Steps to Reproduce (Bug)
Have yet to track down the exact request causing this, but it's happening when we attach an explorer to the node (Blockscout)

**Expected behavior:** - no thread blocked

**Actual behavior:**
```log
2022-04-15 11:28:54,632 main INFO Registered Log4j as the java.util.logging.LogManager.
Setting logging level to INFO
{"timestamp":"2022-04-15T11:28:56,094","container":"ip-x","level":"INFO","thread":"main","class":"Besu","message":"Using LibEthPairings native alt bn128","throwable":""}
{"timestamp":"2022-04-15T11:28:56,097","container":"ip-x","level":"INFO","thread":"main","class":"Besu","message":"Using the native implementation of the signature algorithm","throwable":""}
{"timestamp":"2022-04-15T11:28:56,102","container":"ip-x","level":"INFO","thread":"main","class":"Besu","message":"Starting Besu version: besu/v22.1.3/linux-x86_64/openjdk-java-11","throwable":""}
{"timestamp":"2022-04-15T11:28:56,341","container":"ip-x","level":"WARN","thread":"main","class":"Besu","message":"--tx-pool-hashes-max-size has been deprecated and is now useless, remove it.","throwable":""}
{"timestamp":"2022-04-15T11:28:56,580","container":"ip-x","level":"WARN","thread":"main","class":"Besu","message":"Permissions are disabled. Cannot enable PERM APIs when not using Permissions.","throwable":""}
{"timestamp":"2022-04-15T11:28:56,581","container":"ip-x","level":"INFO","thread":"main","class":"Besu","message":"Static Nodes file = /config/static-nodes.json","throwable":""}
{"timestamp":"2022-04-15T11:28:56,621","container":"ip-x","level":"INFO","thread":"main","class":"Besu","message":"Connecting to 6 static nodes.","throwable":""}
{"timestamp":"2022-04-15T11:28:56,625","container":"ip-x","level":"INFO","thread":"main","class":"Besu","message":"Security Module: localfile","throwable":""}
{"timestamp":"2022-04-15T11:28:56,646","container":"ip-x","level":"INFO","thread":"main","class":"DatabaseMetadata","message":"Lookup database metadata file in data directory: /opt/besu/data","throwable":""}
{"timestamp":"2022-04-15T11:28:56,703","container":"ip-x","level":"INFO","thread":"main","class":"RocksDBKeyValueStorageFactory","message":"Existing database detected at /opt/besu/data. Version 1","throwable":""}
{"timestamp":"2022-04-15T11:28:57,126","container":"ip-x","level":"INFO","thread":"main","class":"KeyPairUtil","message":"Loaded public key 0xcc221c7ca2670b0e39eeaeae645b813e517f31c4c4c1d28c496b80534277d372959d2af4be4cb169dce0e018c025dfb39428b8ffb80cec564d471e1c897ec6a5 from /opt/besu/keys/besu.key","throwable":""}
{"timestamp":"2022-04-15T11:28:57,289","container":"ip-x","level":"INFO","thread":"main","class":"ProtocolScheduleBuilder","message":"Protocol schedule created with milestones: [Berlin: 0, Berlin: 1934001]","throwable":""}
{"timestamp":"2022-04-15T11:28:57,446","container":"ip-x","level":"INFO","thread":"main","class":"RunnerBuilder","message":"Detecting NAT service.","throwable":""}
{"timestamp":"2022-04-15T11:28:57,611","container":"ip-x","level":"INFO","thread":"main","class":"Runner","message":"Starting external services ... ","throwable":""}
{"timestamp":"2022-04-15T11:28:57,612","container":"ip-x","level":"INFO","thread":"main","class":"MetricsHttpService","message":"Starting metrics http service on 0.0.0.0:9545","throwable":""}
{"timestamp":"2022-04-15T11:28:57,731","container":"ip-x","level":"INFO","thread":"main","class":"JsonRpcHttpService","message":"Starting JSON-RPC service on 0.0.0.0:8545","throwable":""}
{"timestamp":"2022-04-15T11:28:57,731","container":"ip-x","level":"INFO","thread":"vert.x-eventloop-thread-1","class":"MetricsHttpService","message":"Metrics service started and listening on 9545:9545","throwable":""}
{"timestamp":"2022-04-15T11:28:57,747","container":"ip-x","level":"INFO","thread":"vert.x-eventloop-thread-1","class":"JsonRpcHttpService","message":"JSON-RPC service started and listening on 0.0.0.0:8545","throwable":""}
{"timestamp":"2022-04-15T11:28:57,749","container":"ip-x","level":"INFO","thread":"main","class":"WebSocketService","message":"Starting Websocket service on 0.0.0.0:8546","throwable":""}
{"timestamp":"2022-04-15T11:28:57,773","container":"ip-x","level":"INFO","thread":"vert.x-eventloop-thread-1","class":"WebSocketService","message":"Websocket service started and listening on 0.0.0.0:8546","throwable":""}
{"timestamp":"2022-04-15T11:28:57,776","container":"ip-x","level":"INFO","thread":"main","class":"AutoTransactionLogBloomCachingService","message":"Starting auto transaction log bloom caching service.","throwable":""}
{"timestamp":"2022-04-15T11:28:57,777","container":"ip-x","level":"INFO","thread":"main","class":"LogBloomCacheMetadata","message":"Lookup cache metadata file in data directory: /opt/besu/data/caches","throwable":""}
{"timestamp":"2022-04-15T11:28:57,784","container":"ip-x","level":"INFO","thread":"main","class":"Runner","message":"Starting Ethereum main loop ... ","throwable":""}
{"timestamp":"2022-04-15T11:28:57,784","container":"ip-x","level":"INFO","thread":"main","class":"NatService","message":"No NAT environment detected so no service could be started","throwable":""}
{"timestamp":"2022-04-15T11:28:57,784","container":"ip-x","level":"INFO","thread":"main","class":"NetworkRunner","message":"Starting Network.","throwable":""}
{"timestamp":"2022-04-15T11:28:57,790","container":"ip-x","level":"INFO","thread":"nioEventLoopGroup-2-1","class":"RlpxAgent","message":"P2P RLPx agent started and listening on /0:0:0:0:0:0:0:0:30303.","throwable":""}
{"timestamp":"2022-04-15T11:28:57,793","container":"ip-x","level":"INFO","thread":"main","class":"DefaultP2PNetwork","message":"Enode URL enode://cc221c7ca2670b0e39eeaeae645b813e517f31c4c4c1d28c496b80534277d372959d2af4be4cb169dce0e018c025dfb39428b8ffb80cec564d471e1c897ec6a5@x:30303?discport=0","throwable":""}
{"timestamp":"2022-04-15T11:28:57,793","container":"ip-x","level":"INFO","thread":"main","class":"DefaultP2PNetwork","message":"Node address 0xc46004160a9f0f4090293bdc9dcd2525c9923aea","throwable":""}
{"timestamp":"2022-04-15T11:28:57,795","container":"ip-x","level":"INFO","thread":"main","class":"DefaultSynchronizer","message":"Starting synchronizer.","throwable":""}
{"timestamp":"2022-04-15T11:28:57,797","container":"ip-x","level":"INFO","thread":"main","class":"FullSyncDownloader","message":"Starting full sync.","throwable":""}
{"timestamp":"2022-04-15T11:28:57,798","container":"ip-x","level":"INFO","thread":"main","class":"FullSyncTargetManager","message":"No sync target, waiting for peers. Current peers: 0","throwable":""}
{"timestamp":"2022-04-15T11:28:59,222","container":"ip-x","level":"INFO","thread":"main","class":"Runner","message":"Ethereum main loop is up.","throwable":""}
{"timestamp":"2022-04-15T11:28:59,620","container":"ip-x","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"FullSyncTargetManager","message":"No sync target, waiting for peers. Current peers: 1","throwable":""}
{"timestamp":"2022-04-15T11:29:00,170","container":"ip-x","level":"INFO","thread":"nioEventLoopGroup-3-3","class":"SyncTargetManager","message":"Found common ancestor with peer Peer 0xbce1621b839ad9696e... at block 3439355","throwable":""}
{"timestamp":"2022-04-15T11:29:01,288","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #3,439,396 / 0 tx / 0 om / 0 (0.0%) gas / (0x35b663ed21960ee72cbf1a0bcb4210e66e673a125dad29a511bc662dc01616d9) in 0.004s. Peers: 8","throwable":""}
{"timestamp":"2022-04-15T11:29:05,246","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-2","class":"PersistBlockTask","message":"Imported #3,439,397 / 0 tx / 0 om / 0 (0.0%) gas / (0xee7a4e559b37fe5627cfc8ab65a07cd034b5fbce4bbfe0c2dbd7f0a0b40e51c1) in 0.002s. Peers: 8","throwable":""}
{"timestamp":"2022-04-15T11:29:09,216","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #3,439,398 / 0 tx / 0 om / 0 (0.0%) gas / (0x2d75fa33313196efbb9bcaf503a2c2940b5885b307dfd781583ca1b8956d0d0b) in 0.002s. Peers: 8","throwable":""}
{"timestamp":"2022-04-15T11:29:13,229","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-3","class":"PersistBlockTask","message":"Imported #3,439,399 / 0 tx / 0 om / 0 (0.0%) gas / (0xc9b5ba2cd65ea9ae07318d88baa7f673801a82935c90a4b76aeab96c2fea2412) in 0.002s. Peers: 8","throwable":""}
{"timestamp":"2022-04-15T11:29:17,250","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #3,439,400 / 0 tx / 0 om / 0 (0.0%) gas / (0x76dba5cb431046817c41002553fbd45f0a4aa70e353a4d0e8b7067dd22f125a9) in 0.004s. Peers: 9","throwable":""}
{"timestamp":"2022-04-15T11:29:21,269","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-2","class":"PersistBlockTask","message":"Imported #3,439,401 / 0 tx / 0 om / 0 (0.0%) gas / (0xbfca22ff79167154b1ab3c339eed489e87d74b903026db2b386799f8644f1845) in 0.002s. Peers: 9","throwable":""}
{"timestamp":"2022-04-15T11:29:25,272","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #3,439,402 / 0 tx / 0 om / 0 (0.0%) gas / (0xb8d11271e474470bf3ec185546f78d97e0385ae5eb932eca985f676290c45a22) in 0.002s. Peers: 9","throwable":""}
{"timestamp":"2022-04-15T11:29:29,245","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-3","class":"PersistBlockTask","message":"Imported #3,439,403 / 0 tx / 0 om / 0 (0.0%) gas / (0xfa48ea4b16493ace2b9f232aff6e8e5709e7a3066562e4a535292967bc766e36) in 0.002s. Peers: 9","throwable":""}
{"timestamp":"2022-04-15T11:29:33,215","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #3,439,404 / 0 tx / 0 om / 0 (0.0%) gas / (0xc7ae2bea6bc825b27b952a282946a3373fab46c4334b148e41e470f144abebf4) in 0.002s. Peers: 10","throwable":""}
{"timestamp":"2022-04-15T11:29:37,463","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-2","class":"PersistBlockTask","message":"Imported #3,439,405 / 0 tx / 0 om / 0 (0.0%) gas / (0xd966a6b6f46a0cc69c450ded16fe4adf4c6ff69ee911d567e58b0504d2703902) in 0.002s. Peers: 10","throwable":""}
{"timestamp":"2022-04-15T11:29:41,247","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #3,439,406 / 0 tx / 0 om / 0 (0.0%) gas / (0xd6be2653b85df90f7f2b882fe13a0f7f9da96121df4342a446a878875d6ead69) in 0.001s. Peers: 10","throwable":""}
{"timestamp":"2022-04-15T11:29:45,269","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-3","class":"PersistBlockTask","message":"Imported #3,439,407 / 0 tx / 0 om / 0 (0.0%) gas / (0x74aca27de2d928e7379e456f69e14313cdf32efcd30282e7983e08f490cd030d) in 0.002s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:29:49,272","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #3,439,408 / 0 tx / 0 om / 0 (0.0%) gas / (0xfbfd2124a07f4cb61e03fc1a18b0814a9165fa30454cae792153896ddb0f2371) in 0.002s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:29:53,246","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-2","class":"PersistBlockTask","message":"Imported #3,439,409 / 0 tx / 0 om / 0 (0.0%) gas / (0x6f3a70669e407f43290e44c9e2edd08d9b18a7fde269393a6fb8da2643fe7f63) in 0.001s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:29:57,214","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #3,439,410 / 0 tx / 0 om / 0 (0.0%) gas / (0xa0ae75ca4d82211dd5257cca546dcbcbbffc9ebaf2ad2afc2d67aef510512bad) in 0.001s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:30:01,227","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-3","class":"PersistBlockTask","message":"Imported #3,439,411 / 0 tx / 0 om / 0 (0.0%) gas / (0x621cb7dec63c8d2572a022b063f99d61d3c106431e37d4c7afd986df8947f543) in 0.001s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:30:05,245","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-0","class":"PersistBlockTask","message":"Imported #3,439,412 / 0 tx / 0 om / 0 (0.0%) gas / (0x6bbff1d47f89a2668bd80a35f94b319107e345004a7a293643eb2245f4fe3387) in 0.001s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:30:09,268","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-2","class":"PersistBlockTask","message":"Imported #3,439,413 / 0 tx / 0 om / 0 (0.0%) gas / (0x647ca215bf1bcc7c3ea06a885f0716937adbfb40c078bc0e46ebdb47f78d8f12) in 0.001s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:30:13,271","container":"ip-x","level":"INFO","thread":"EthScheduler-Workers-1","class":"PersistBlockTask","message":"Imported #3,439,414 / 0 tx / 0 om / 0 (0.0%) gas / (0xceb5e21d2406805918d35ac1a0c986656a73055d37d4b47c3bce708652e01528) in 0.001s. Peers: 11","throwable":""}
{"timestamp":"2022-04-15T11:30:14,966","container":"ip-x","level":"WARN","thread":"vertx-blocked-thread-checker","class":"BlockedThreadChecker","message":"Thread Thread[vert.x-worker-thread-19,5,main] has been blocked for 60621 ms, time limit is 60000 ms","throwable":" io.vertx.core.VertxException: Thread blocked
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.hasRevertInSubCall(FlatTraceGenerator.java:531)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.lambda$handleCall$7(FlatTraceGenerator.java:303)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator$$Lambda$1230/0x00007f44d864e8b0.accept(Unknown Source)
                at java.base@11.0.14.1/java.util.Optional.ifPresent(Optional.java:183)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.handleCall(FlatTraceGenerator.java:301)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.generateFromTransactionTrace(FlatTraceGenerator.java:148)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.generateFromTransactionTrace(FlatTraceGenerator.java:234)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.tracing.flat.FlatTraceGenerator.generateFromTransactionTrace(FlatTraceGenerator.java:224)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$1215/0x00007f44d862fc40.format(Unknown Source)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.generateTracesFromTransactionTrace(TraceReplayBlockTransactions.java:195)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.handleTransactionTrace(TraceReplayBlockTransactions.java:163)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.lambda$generateTracesFromTransactionTrace$2(TraceReplayBlockTransactions.java:133)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$1209/0x00007f44d8628db0.accept(Unknown Source)
                at java.base@11.0.14.1/java.util.ArrayList.forEach(ArrayList.java:1541)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.generateTracesFromTransactionTrace(TraceReplayBlockTransactions.java:131)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.lambda$traceBlock$1(TraceReplayBlockTransactions.java:120)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$1208/0x00007f44d8628108.apply(Unknown Source)
                at java.base@11.0.14.1/java.util.Optional.map(Optional.java:265)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.traceBlock(TraceReplayBlockTransactions.java:120)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.lambda$resultByBlockNumber$0(TraceReplayBlockTransactions.java:102)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$1193/0x00007f44d85950b0.apply(Unknown Source)
                at java.base@11.0.14.1/java.util.Optional.map(Optional.java:265)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.resultByBlockNumber(TraceReplayBlockTransactions.java:102)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:66)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.response(AbstractBlockParameterMethod.java:79)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:770)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonBatchRequest$16(JsonRpcHttpService.java:691)
                at app//org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService$$Lambda$1180/0x00007f44d8df0960.handle(Unknown Source)
                at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
                at app//io.vertx.core.impl.ContextImpl$$Lambda$833/0x00007f4588cfbcb0.handle(Unknown Source)
                at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
                at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
                at app//io.vertx.core.impl.ContextImpl$$Lambda$832/0x00007f4588cfa968.run(Unknown Source)
                at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
                at app//io.vertx.core.impl.TaskQueue$$Lambda$646/0x00007f45b43dd040.run(Unknown Source)
                at java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base@11.0.14.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
                "}
```

**Frequency:** [`100%`]
 - we have the same setup in 2 different networks, but are experiencing with 100% frequency in one of the networks only so it may be related to some specific block/content/state, but haven't been able to narrow it down yet

### Versions (Add all that apply)
* Software version: [`22.1.3 - official docker image`]
* Java version: [`java -version`]
* OS Name & Version: [`Ubuntu 20.04.4 LTS`]
* Kernel Version: [`Linux ip-10-42-20-178 5.13.0-1021-aws #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`]
* Docker Version: [`Docker Engine - Community - 20.10.14`]
* Cloud VM, type, size: [`Amazon Web Services - m5.4xlarge`]

### Additional Information (Add any of the following or anything else that may be relevant)
* System info - memory - 64GiB, CPU - 16 vCPU

**Comment by frankisawesome** [comment]
Hey @rinor are you able to provide more information on the network setup, genesis file used, nodes in the network etc?

**Comment by rinor** [comment]
- genesis - https://github.com/dcSpark/milkomeda-evm-passive/blob/main/c1-devnet/config/genesis.json
- config - https://github.com/dcSpark/milkomeda-evm-passive/blob/main/c1-devnet/config/config.toml
- explorer/passive/rpc node (the node in question) - `cc221c7ca2670b0e39eeaeae645b813e517f31c4c4c1d28c496b80534277d372959d2af4be4cb169dce0e018c025dfb39428b8ffb80cec564d471e1c897ec6a5`
- 6 validators

all connected through `static-nodes-file`

```json
[
  "enode://93ed276b4cecfe0bc4fb2b33f80a0822920ff438853161f3eb2d234e20860f607ffc63f38e2c03455748f1157e39fce778c666778faf58dc50f79fb37dced0e2@a:30303",
  "enode://640a9dca825965f448b03d6030d66259b53bb4ec14769c20ae8e0ce976c1c612b4fa0a33e6f90dd1cd72dd345047684cbe2087b1e92df801b03872c718e326ae@b:30303",
  "enode://1340659f084bfc21c208f0b552b62e6b46eed4f6dc8172595e035956b18be94e53aec9bb9d0b0b849f03ab249d91d83fd5f1a0873b2171b86541fb7dc61a0508@c:30303",
  "enode://8f4570aefa03b8fc5abf513d0b8e2bcaf4ad865dfc36469c92a1c82eb92c9664e18139f83ce738e9b8fb0912ae30d2b3d59e0a44db5624cdf2dcc56dd497bb10@d:30303",
  "enode://2dd01d4bfec677a67fd4658447ed834e9e62eefd086e7327837d58823a98df447d8ad824dfd58d929f3f286c9c4525269ebe037ffcf67202b092936be6971163@e:30303",
  "enode://1959e3ead5ea3f46846605a6e75c75d7e7501301f5203f19e75c283ffd0be0d6095b89027d9e95782dc73c0713509ebbf1868565bb3ae17204412daa3957f57e@f:30303"
]
```

**Comment by frankisawesome** [comment]
I'm unassingning myself and putting this one in the backlog, thanks for the info @rinor

**Comment by macfarla** [comment]
Are you seeing this blocked thread logs on one node only? Is it stopping blocks from being produced or other function of the node?

**Comment by rinor** [comment]
> Are you seeing this blocked thread logs on one node only? Is it stopping blocks from being produced or other function of the node?

The node in question is not a block producer node, just a passive one.
The logs are on the same node that the requester (blockscout explorer in this case) is pointed to and the state afaict right now:
- block propagation is fine
- http rpc interface responds ok
- ws rpc interface has issues/timeouts

Will check again to get more details, but also if there is smth specific you want us to check, please let us know and will provide that information.

**Comment by macfarla** [comment]
If it's not affecting node operation, we are deprioritizing this for the time being. Please let us know if it does start affecting node operation.

**Comment by rinor** [comment]
> If it's not affecting node operation, we are deprioritizing this for the time being. Please let us know if it does start affecting node operation.

the side-effect of this is tha all requests http/ws for historical data fail with timeout hence no operations involving those data can be completed making it impossible to use for explorers or any other application that requires such information. While the node may be operational on its own is mostly unusable for any other operation.

It looks like there is some lock/contention on the storage (no proof though). If you have any suspicion and/or hint where/how to check please let us know so we can investigate further. Thank you

**Comment by rinor** [comment]
We will test with the latest master again since there are a lot of changes from the latest stable release used and will provide feedback with the results.

**Comment by rinor** [comment]
`"Besu version: besu/v22.4.0-RC2/linux-x86_64/openjdk-java-11"` (using `hyperledger/besu:22.4.0-RC2 docker images` ) - same behavior.

**Comment by macfarla** [comment]
Hmmm ok so sounds like it is affecting node operation in a way. 
Blockscout is known to be pretty resource hungry, could it be that it is affecting things? Is it possible to separate the ws rpc interface from where blockscout is running?

**Comment by rinor** [comment]
> Hmmm ok so sounds like it is affecting node operation in a way. Blockscout is known to be pretty resource hungry, could it be that it is affecting things? Is it possible to separate the ws rpc interface from where blockscout is running?

It is and we tried that, same result. Went even further and lowered the concurrency of blockscout and the batch request sizes just to test.

Will check again that separated setup with the latest version and report back.

also https://github.com/hyperledger/besu/issues/3786 could be related (no OOM in our case since we pushed a lot more  resources)

**Comment by macfarla** [comment]
#3786  is related to trace_replayBlockTransactions - are you using that API?

**Comment by iamhsk** [comment]
Closing this issue since no activity in the past 30 days. Feel free to reopen if further help is needed 😊

**Comment by nwasiqUC** [comment]
I'm having this same issue. Connect blockscout to my hyperledger besu deployment and the node isn't able to handle it.

Even reduced the number of concurrent requests in the fetcher but no luck. @rinor were you able to find a fix for this?

**Comment by macfarla** [comment]
@nwasiqUC can you try with the latest version of besu 22.7.0 - and if still having an issue, can you file a new issue with your specific environment and setup details?
