### ISSUE TITLE
Duplicate metrics registered during snap sync

### ISSUE THREAD

**Issue by ajsutton** [hyperledger/besu#3779]
### Description
Snap sync hit an error and then failed to recover, just entering a loop of the sequence below:

```
<previous failure>
2022-05-03 08:38:39.938+00:00 | EthScheduler-Timer-0 | INFO  | SnapSyncDownloader | Starting snap sync.
2022-05-03 08:38:39.938+00:00 | EthScheduler-Timer-0 | INFO  | TransitionPivotSelector | Chain has not yet reached TTD, best peer has estimated difficulty 0x000000000000000000000000000000000000000000000a27ee16b4451
ba6d368, select pivot from peers
2022-05-03 08:38:39.938+00:00 | EthScheduler-Timer-0 | INFO  | PivotSelectorFromPeers | Selecting block number 14703590 as fast sync pivot block.
2022-05-03 08:38:39.938+00:00 | EthScheduler-Timer-0 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 5 peers.
2022-05-03 08:38:39.938+00:00 | EthScheduler-Timer-0 | INFO  | PivotBlockConfirmer | Confirm pivot block 14703590 with at least 5 peers.
2022-05-03 08:38:39.993+00:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Received 1 confirmation(s) for pivot block header 14703590: 0xbec4c3a82938cf56a54b0e70391733002f897b344c8ed05b6634942204f0dd9d
2022-05-03 08:38:39.994+00:00 | nioEventLoopGroup-3-5 | INFO  | PivotBlockConfirmer | Received 2 confirmation(s) for pivot block header 14703590: 0xbec4c3a82938cf56a54b0e70391733002f897b344c8ed05b6634942204f0dd9d
2022-05-03 08:38:40.023+00:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Received 3 confirmation(s) for pivot block header 14703590: 0xbec4c3a82938cf56a54b0e70391733002f897b344c8ed05b6634942204f0dd9d
2022-05-03 08:38:40.158+00:00 | nioEventLoopGroup-3-3 | INFO  | PivotBlockConfirmer | Received 4 confirmation(s) for pivot block header 14703590: 0xbec4c3a82938cf56a54b0e70391733002f897b344c8ed05b6634942204f0dd9d
2022-05-03 08:38:40.173+00:00 | nioEventLoopGroup-3-8 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 14703590: 0xbec4c3a82938cf56a54b0e70391733002f897b344c8ed05b6634942204f0dd9d
2022-05-03 08:38:40.174+00:00 | nioEventLoopGroup-3-8 | INFO  | SnapWorldStateDownloader | Downloading world state from peers for block 14703590 (0xbec4c3a82938cf56a54b0e70391733002f897b344c8ed05b6634942204f0dd9d).
 State root 0xbea6f4c2ffe2a322bc516f09051b17b9ab9701ee4ff08b3448a68026e0256882 pending request 0
2022-05-03 08:38:40.174+00:00 | nioEventLoopGroup-3-8 | ERROR | FastSyncDownloader | Encountered an unexpected error during fast sync. Restarting fast sync in PT5S seconds.
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Collector already registered that provides name: besu_synchronizer_snap_world_state_pending_account_requests_current
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hyperledger.besu.ethereum.eth.sync.fastsync.PivotBlockRetriever.handleConfirmationResult(PivotBlockRetriever.java:141)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hyperledger.besu.ethereum.eth.sync.fastsync.PivotBlockConfirmer.processReceivedHeader(PivotBlockConfirmer.java:131)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hyperledger.besu.util.FutureUtils.lambda$propagateResult$1(FutureUtils.java:74)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:144)
        at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:69)
        at org.hyperledger.besu.util.FutureUtils.lambda$exceptionallyCompose$0(FutureUtils.java:48)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hyperledger.besu.ethereum.eth.sync.tasks.RetryingGetHeaderFromPeerByNumberTask.lambda$executePeerTask$0(RetryingGetHeaderFromPeerByNumberTask.java:72)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$2(AbstractPeerRequestTask.java:83)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.handleMessage(AbstractPeerRequestTask.java:104)
        at org.hyperledger.besu.ethereum.eth.manager.task.AbstractPeerRequestTask.lambda$executeTask$0(AbstractPeerRequestTask.java:67)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.dispatchBufferedResponses(RequestManager.java:191)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager$ResponseStream.processMessage(RequestManager.java:182)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager.lambda$dispatchResponse$0(RequestManager.java:74)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
        at org.hyperledger.besu.ethereum.eth.manager.RequestManager.dispatchResponse(RequestManager.java:73)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeer.lambda$dispatch$7(EthPeer.java:367)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeer.dispatch(EthPeer.java:366)
        at org.hyperledger.besu.ethereum.eth.manager.EthPeers.dispatchMessage(EthPeers.java:139)
        at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:275)
        at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
        at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:99)
        at org.hyperledger.besu.ethereum.p2p.rlpx.connections.netty.ApiHandler.channelRead0(ApiHandler.java:33)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Collector already registered that provides name: besu_synchronizer_snap_world_state_pending_account_requests_current
        at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
        at io.prometheus.client.Collector.register(Collector.java:139)
        at org.hyperledger.besu.metrics.prometheus.PrometheusMetricsSystem.addCollectorUnchecked(PrometheusMetricsSystem.java:168)
        at org.hyperledger.besu.metrics.prometheus.PrometheusMetricsSystem.createGauge(PrometheusMetricsSystem.java:141)
        at org.hyperledger.besu.plugin.services.MetricsSystem.createLongGauge(MetricsSystem.java:132)
        at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldDownloadState.<init>(SnapWorldDownloadState.java:102)
        at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloader.run(SnapWorldStateDownloader.java:123)
        at org.hyperledger.besu.ethereum.eth.sync.fastsync.FastSyncDownloader.downloadChainAndWorldState(FastSyncDownloader.java:176)
        at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapSyncDownloader.lambda$start$0(SnapSyncDownloader.java:57)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        ... 79 more
```

**Comment by ajsutton** [comment]
For the record the first failure was:
```
2022-05-03 05:25:05.696+00:00 | EthScheduler-Services-28 (requestCompleteTask) | INFO  | WorldDownloadState | World state download failed.
java.lang.NullPointerException: Cannot invoke "org.apache.tuweni.bytes.Bytes.toArrayUnsafe()" because "node" is null
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage$Updater.saveWorldState(BonsaiWorldStateKeyValueStorage.java:276)
        at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldDownloadState.checkCompletion(SnapWorldDownloadState.java:153)
        at org.hyperledger.besu.ethereum.eth.sync.snapsync.CompleteTaskStep.markAsCompleteOrFailed(CompleteTaskStep.java:50)
        at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloadProcess$Builder.lambda$build$0(SnapWorldStateDownloadProcess.java:218)
        at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
        at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I'm not sure if that's the same issue I hit last time I tried snap sync or not. 

Besu version is: besu/v22.4.0-RC3-dev-9ef9ff49/linux-x86_64/corretto-java-17

**Comment by matkt** [comment]
> For the record the first failure was:
> 
> ```
> 2022-05-03 05:25:05.696+00:00 | EthScheduler-Services-28 (requestCompleteTask) | INFO  | WorldDownloadState | World state download failed.
> java.lang.NullPointerException: Cannot invoke "org.apache.tuweni.bytes.Bytes.toArrayUnsafe()" because "node" is null
>         at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage$Updater.saveWorldState(BonsaiWorldStateKeyValueStorage.java:276)
>         at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldDownloadState.checkCompletion(SnapWorldDownloadState.java:153)
>         at org.hyperledger.besu.ethereum.eth.sync.snapsync.CompleteTaskStep.markAsCompleteOrFailed(CompleteTaskStep.java:50)
>         at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloadProcess$Builder.lambda$build$0(SnapWorldStateDownloadProcess.java:218)
>         at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)
>         at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> ```
> 
> I'm not sure if that's the same issue I hit last time I tried snap sync or not.
> 
> Besu version is: besu/v22.4.0-RC3-dev-9ef9ff49/linux-x86_64/corretto-java-17

the nullpointer is fixed here https://github.com/hyperledger/besu/commit/beb4e3baa32b7a918e84343b1ef08b098698ce3d

I will check for the duplicate metrics

**Comment by non-fungible-nelson** [comment]
Are we still noticing this @ajsutton ?

**Comment by ajsutton** [comment]
I haven't seen it again but I'm not sure if that's because the original exception was fixed and so it hasn't had to restart which is what triggered the duplicate metric error. I'm not against closing this if we can't see a reason the metric would be registered twice now though.

**Comment by non-fungible-nelson** [comment]
Report from Rocketpool over the weekend - 
[fast-sync-metric-boom.txt](https://github.com/hyperledger/besu/files/10005543/fast-sync-metric-boom.txt)
