### ISSUE TITLE
OutOfMemoryError on JSON RPC method trace_replayBlockTransactions

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#3786]
### Description
As an Besu, I want to get block transactions traces when I call JSON RPC method trace_replayBlockTransactions on blocks with big transactions (> 20M Gas)

### Acceptance Criteria
* trace_replayBlockTransactions JSON RPC call displays block transactions traces

### Steps to Reproduce (Bug)
1. Create a private network of Besu nodes, set for each node these java options -Xms2G -Xmx2G (BESU_OPTS)
2. Send a huge transaction 25M Gas 
3. Call JSON RPC method trace_replayBlockTransactions with the  block number of the transaction sent in 2. as parameter

**Expected behavior:** 
Return the block transactions traces, we can see below the json result template
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result":[ 
      { 
        "output":"0x",
        "vmTrace":{
          "code":"0x7f3940be4289e4c3587d88c1856cc95352461992db0a584c281226faefe560b3016000527f14c4d2c102bdeb2354bfc3dc96a95e4512cf3a8461e0560e2272dbf884ef3905601052600851",
          "ops":[ 
            { 
              "cost":3,
              "ex":{ 
                "mem":null,
                "push":[ 
                  "0x8"
                ],
                "store":null,
                "used":16756175
              },
              "pc":72,
              "sub":null
            },
            ...
          ]
        },
        "trace":[ 
          { 
            "action":{ 
              "callType":"call",
              "from":"0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
              "gas":"0xffadea",
              "input":"0x",
              "to":"0x0100000000000000000000000000000000000000",
              "value":"0x0"
            },
            "result":{ 
              "gasUsed":"0x1e",
              "output":"0x"
            },
            "subtraces":0,
            "traceAddress":[      
            ],
            "type":"call"
          }
        ],
        "stateDiff":{
          "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73":{ 
            "balance":{ 
              "*":{ 
                "from":"0xffffffffffffffffffffffffffffffffc3e12a20b",
                "to":"0xffffffffffffffffffffffffffffffffc3dc5f091"
              }
            },
            "code":"=",
            "nonce":{ 
              "*":{ 
                "from":"0x14",
                "to":"0x15"
              }
            },
            "storage":{              
            }
          }
        },
        "transactionHash":"0x2a5079cc535c429f668f13a7fb9a28bdba6831b5462bd04f781777b332a8fcbd",
      },
      {...}
    ]
}
```
**Actual behavior:** 
java.lang.OutOfMemoryError: Java heap space
```
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base/java.util.ArrayList.grow(ArrayList.java:238)
        at java.base/java.util.ArrayList.grow(ArrayList.java:243)
        at java.base/java.util.ArrayList.add(ArrayList.java:486)
        at java.base/java.util.ArrayList.add(ArrayList.java:499)
        at org.hyperledger.besu.ethereum.vm.DebugOperationTracer.traceExecution(DebugOperationTracer.java:97)
        at org.hyperledger.besu.evm.EVM.executeNextOperation(EVM.java:81)
        at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:74)
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:161)
        at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:173)
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:485)
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:397)
        at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:181)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.lambda$prepareReplayAction$0(BlockTracer.java:60)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer$$Lambda$1375/0x00000008407b5040.performAction(Unknown Source)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$0(BlockReplay.java:60)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay$$Lambda$1377/0x00000008407b5840.apply(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$1(BlockReplay.java:66)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay$$Lambda$1376/0x00000008407b5440.perform(Unknown Source)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.performActionWithBlock(BlockReplay.java:155)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.block(BlockReplay.java:52)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.trace(BlockTracer.java:45)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.traceBlock(TraceReplayBlockTransactions.java:118)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.lambda$resultByBlockNumber$0(TraceReplayBlockTransactions.java:102)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$1373/0x00000008407b4840.apply(Unknown Source)
```
**Frequency:** 
100% 

### Versions
* Software version: besu/v22.4.0-RC2-dev-898ce928/linux-x86_64/corretto-java-17
* Java version: openjdk version "17.0.2" 2022-01-18 LTS
* OS Name & Version: NAME="Amazon Linux", VERSION="2", ID="amzn", ID_LIKE="centos rhel fedora", VERSION_ID="2", PRETTY_NAME="Amazon Linux 2", ANSI_COLOR="0;33", CPE_NAME="cpe:2.3: o:amazon:amazon_linux:2", HOME_URL="https://amazonlinux.com/", Amazon Linux release 2 (Karoo)
* Kernel Version: Linux ip-172-31-14-96.us-east-2.compute.internal 4.14.181-140.257.amzn2.x86_64 1 SMP Wed May 27 02:17:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud VM, type, size: i3.2xlarge

**Comment by ahamlat** [comment]
Top components :
```
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:     146572886     9400658032  [B (java.base@17.0.2)
   2:     146445748     4686263936  org.apache.tuweni.bytes.MutableArrayWrappingBytes32
   3:       6083127     1300789808  [Lorg.apache.tuweni.bytes.Bytes32;
   4:       3041563      389320064  org.hyperledger.besu.ethereum.debug.TraceFrame
```

**Comment by soragXYZ** [comment]
Hi! Any updates ?

**Comment by iamhsk** [comment]
Hi @soragXYZ, thank you for following up on this. The maintainers will prioritize this and work on it in the near future. 

Adding our discord conversations for reference here: 

- https://discord.com/channels/905194001349627914/938504958909747250/969536062047256620

- https://discord.com/channels/905194001349627914/938504958909747250/970674116766101534

**Comment by macfarla** [comment]
I seem to get different behaviour:
besu/v22.4.3-dev-1c7c9ed1/osx-x86_64/openjdk-java-11
JAVA_OPTS="-Xms2G -Xmx2G" besu --config-file config/besu/besu1.conf

```
{
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [{
  	"from": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
  	"data": "608060405234801561001057600080fd5b50610274806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b27b880414610030575b600080fd5b61004a60048036038101906100459190610108565b61004c565b005b60606000806000604051935036600085376000803686885af490503d9150816000853e806000811461007d57610093565b60008311156100925761012085019350836040525b5b5060008114156100ec578473ffffffffffffffffffffffffffffffffffffffff167f410d96db3f80b0f89b36888c4d8a94004268f8d42309ac39b7bcba706293e099856040516100e3919061016e565b60405180910390a25b5050505050565b60008135905061010281610227565b92915050565b60006020828403121561011e5761011d610211565b5b600061012c848285016100f3565b91505092915050565b600061014082610190565b61014a818561019b565b935061015a8185602086016101de565b61016381610216565b840191505092915050565b600060208201905081810360008301526101888184610135565b905092915050565b600081519050919050565b600082825260208201905092915050565b60006101b7826101be565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60005b838110156101fc5780820151818401526020810190506101e1565b8381111561020b576000848401525b50505050565b600080fd5b6000601f19601f8301169050919050565b610230816101ac565b811461023b57600080fd5b5056fea2646970667358221220fdfb5c371055342507b8fb9ca7b0c234f79819bd5cb05c0d467fb605de979eb564736f6c63430008060033",
  	"gas": "0xfffffffffffff"
  }],
  "id": 1
}
```
...
blockNumber 0xfd1
```
{
    "jsonrpc": "2.0",
    "method": "trace_replayBlockTransactions",
    "params": [
        "0xfd1", [ "vmTrace"]
    ],
    "id": 1
}
```
Response:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "output": "0x608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b27b880414610030575b600080fd5b61004a60048036038101906100459190610108565b61004c565b005b60606000806000604051935036600085376000803686885af490503d9150816000853e806000811461007d57610093565b60008311156100925761012085019350836040525b5b5060008114156100ec578473ffffffffffffffffffffffffffffffffffffffff167f410d96db3f80b0f89b36888c4d8a94004268f8d42309ac39b7bcba706293e099856040516100e3919061016e565b60405180910390a25b5050505050565b60008135905061010281610227565b92915050565b60006020828403121561011e5761011d610211565b5b600061012c848285016100f3565b91505092915050565b600061014082610190565b61014a818561019b565b935061015a8185602086016101de565b61016381610216565b840191505092915050565b600060208201905081810360008301526101888184610135565b905092915050565b600081519050919050565b600082825260208201905092915050565b60006101b7826101be565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60005b838110156101fc5780820151818401526020810190506101e1565b8381111561020b576000848401525b50505050565b600080fd5b6000601f19601f8301169050919050565b610230816101ac565b811461023b57600080fd5b5056fea2646970667358221220fdfb5c371055342507b8fb9ca7b0c234f79819bd5cb05c0d467fb605de979eb564736f6c63430008060033",
            "stateDiff": null,
            "trace": [],
            "transactionHash": "0x6448270c8211215465a209177e9c0ca0e4b32d0398e36f6a146e4e27b0d6c206",
            "vmTrace": {
                "code": "0x608060405234801561001057600080fd5b50610274806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b27b880414610030575b600080fd5b61004a60048036038101906100459190610108565b61004c565b005b60606000806000604051935036600085376000803686885af490503d9150816000853e806000811461007d57610093565b60008311156100925761012085019350836040525b5b5060008114156100ec578473ffffffffffffffffffffffffffffffffffffffff167f410d96db3f80b0f89b36888c4d8a94004268f8d42309ac39b7bcba706293e099856040516100e3919061016e565b60405180910390a25b5050505050565b60008135905061010281610227565b92915050565b60006020828403121561011e5761011d610211565b5b600061012c848285016100f3565b91505092915050565b600061014082610190565b61014a818561019b565b935061015a8185602086016101de565b61016381610216565b840191505092915050565b600060208201905081810360008301526101888184610135565b905092915050565b600081519050919050565b600082825260208201905092915050565b60006101b7826101be565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60005b838110156101fc5780820151818401526020810190506101e1565b8381111561020b576000848401525b50505050565b600080fd5b6000601f19601f8301169050919050565b610230816101ac565b811461023b57600080fd5b5056fea2646970667358221220fdfb5c371055342507b8fb9ca7b0c234f79819bd5cb05c0d467fb605de979eb564736f6c63430008060033",
                "ops": [
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x80"
                            ],
                            "store": null,
                            "used": 4503599627307496
                        },
                        "pc": 0,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x40"
                            ],
                            "store": null,
                            "used": 4503599627307493
                        },
                        "pc": 2,
                        "sub": null
                    },
                    {
                        "cost": 12,
                        "ex": {
                            "mem": {
                                "data": "0x0000000000000000000000000000000000000000000000000000000000000080",
                                "off": 64
                            },
                            "push": [],
                            "store": null,
                            "used": 4503599627307481
                        },
                        "pc": 4,
                        "sub": null
                    },
                    {
                        "cost": 2,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x0"
                            ],
                            "store": null,
                            "used": 4503599627307479
                        },
                        "pc": 5,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x0",
                                "0x0"
                            ],
                            "store": null,
                            "used": 4503599627307476
                        },
                        "pc": 6,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x1"
                            ],
                            "store": null,
                            "used": 4503599627307473
                        },
                        "pc": 7,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x10"
                            ],
                            "store": null,
                            "used": 4503599627307470
                        },
                        "pc": 8,
                        "sub": null
                    },
                    {
                        "cost": 10,
                        "ex": {
                            "mem": null,
                            "push": [],
                            "store": null,
                            "used": 4503599627307460
                        },
                        "pc": 11,
                        "sub": null
                    },
                    {
                        "cost": 1,
                        "ex": {
                            "mem": null,
                            "push": [],
                            "store": null,
                            "used": 4503599627307459
                        },
                        "pc": 16,
                        "sub": null
                    },
                    {
                        "cost": 2,
                        "ex": {
                            "mem": null,
                            "push": [],
                            "store": null,
                            "used": 4503599627307457
                        },
                        "pc": 17,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x274"
                            ],
                            "store": null,
                            "used": 4503599627307454
                        },
                        "pc": 18,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x274",
                                "0x274"
                            ],
                            "store": null,
                            "used": 4503599627307451
                        },
                        "pc": 21,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x20"
                            ],
                            "store": null,
                            "used": 4503599627307448
                        },
                        "pc": 22,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x0"
                            ],
                            "store": null,
                            "used": 4503599627307445
                        },
                        "pc": 25,
                        "sub": null
                    },
                    {
                        "cost": 114,
                        "ex": {
                            "mem": {
                                "data": "0x608060405234801561001057600080fd5b506004361061002b5760003560e01c8063b27b880414610030575b600080fd5b61004a60048036038101906100459190610108565b61004c565b005b60606000806000604051935036600085376000803686885af490503d9150816000853e806000811461007d57610093565b60008311156100925761012085019350836040525b5b5060008114156100ec578473ffffffffffffffffffffffffffffffffffffffff167f410d96db3f80b0f89b36888c4d8a94004268f8d42309ac39b7bcba706293e099856040516100e3919061016e565b60405180910390a25b5050505050565b60008135905061010281610227565b92915050565b60006020828403121561011e5761011d610211565b5b600061012c848285016100f3565b91505092915050565b600061014082610190565b61014a818561019b565b935061015a8185602086016101de565b61016381610216565b840191505092915050565b600060208201905081810360008301526101888184610135565b905092915050565b600081519050919050565b600082825260208201905092915050565b60006101b7826101be565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60005b838110156101fc5780820151818401526020810190506101e1565b8381111561020b576000848401525b50505050565b600080fd5b6000601f19601f8301169050919050565b610230816101ac565b811461023b57600080fd5b5056fea2646970667358221220fdfb5c371055342507b8fb9ca7b0c234f79819bd5cb05c0d467fb605de979eb564736f6c63430008060033",
                                "off": 0
                            },
                            "push": [],
                            "store": null,
                            "used": 4503599627307331
                        },
                        "pc": 27,
                        "sub": null
                    },
                    {
                        "cost": 3,
                        "ex": {
                            "mem": null,
                            "push": [
                                "0x0"
                            ],
                            "store": null,
                            "used": 4503599627307328
                        },
                        "pc": 28,
                        "sub": null
                    },
                    {
                        "cost": 0,
                        "ex": {
                            "mem": null,
                            "push": [],
                            "store": null,
                            "used": 4503599627307328
                        },
                        "pc": 30,
                        "sub": null
                    }
                ]
            }
        }
    ]
}
```

**Comment by macfarla** [comment]
I don't get OOM. looking at heap dump
jcmd pid GC.heap_dump ~/besu-heapdump0.hprof
I've got heap size 67,634,206 B - so 67M.

**Comment by macfarla** [comment]
@ahamlat @soragXYZ is it just the gas supplied for the transaction or is there something specific about the transaction you submitted?

**Comment by ahamlat** [comment]
@macfarla : to reproduce, you have to call trace_replayBlockTransactions on a block that contains one or several huge transactions. @matkt was able to reproduce on Ropsten.

**Comment by GrzegorzDrozda** [comment]
Hi, I hit same bug:
```
$ curl -v -XPOST --data '{"id":0,"jsonrpc":"2.0","method":"trace_block","params":["0x5D5E43"]}' http://localhost:8545
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8545...
* Connected to localhost (127.0.0.1) port 8545 (#0)
> POST / HTTP/1.1
> Host: localhost:8545
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 69
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< vary: origin
< Content-Type: application/json
< content-length: 21
< 
* Connection #0 to host localhost left intact
Internal Server Error
```
Actually another method is affected as well:
```
$ curl -v -XPOST --data '{"id":0,"jsonrpc":"2.0","method":"trace_replayBlockTransactions","params":["0x5D5E43",["trace"]]}'  Note: 
Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8545...
* Connected to localhost (127.0.0.1) port 8545 (#0)
> POST / HTTP/1.1
> Host: localhost:8545
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 97
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< vary: origin
< Content-Type: application/json
< content-length: 21
< 
* Connection #0 to host localhost left intact
Internal Server Error
```
On besu site: 
```
"level":"ERROR","thread":"vert.x-eventloop-thread-1","class":"RoutingContext","message":"Unhandled exception in router","throwable":" java.lang.OutOfMemoryError: Java heap space\n"
```
In both cases - block which is causing this problem has `34,287,831 | 52.8%` Gas Used

**Comment by non-fungible-nelson** [comment]
@daniellehrner - status?

**Comment by daniellehrner** [comment]
> @daniellehrner - status?

I am still working on this one.

**Comment by dhallatmaine** [comment]
Hello, we have been using Besu successfully in production for a few months. Recently, we have noticed the reader node that our block explorer connects to has been running into this issue. For more information, we are running BlockScout and BlockScout relies on the `trace_replayBlockTransactions` endpoint in order to index our chain. The issue seems to be loading into memory all of the TraceFrame's for all transactions within a block. With our specific use case, we have the need for some large transactions with high gas fees.

In order to reproduce this, I ran 3 nodes locally built off of main. In the genesis.json file, I specified a large gasLimit:
`"gasLimit" : "0x38D7EA4C67FFF",`

I ran the following contract:
```// SPDX-License-Identifier: MIT
pragma solidity >=0.4.22 <0.9.0;
contract GasHog {
  mapping(uint => string) public hogSomeGas1;
  mapping(uint => string) public hogSomeGas2;
  mapping(uint => string) public hogSomeGas3;
  mapping(uint => string) public hogSomeGas4;
  mapping(uint => string) public hogSomeGas5;
  mapping(uint => string) public hogSomeGas6;
  mapping(uint => string) public hogSomeGas7;
  mapping(uint => string) public hogSomeGas8;
  mapping(uint => string) public hogSomeGas9;
  mapping(uint => string) public hogSomeGas10;
  mapping(uint => string) public hogSomeGas11;
  mapping(uint => string) public hogSomeGas12;
  mapping(uint => string) public hogSomeGas13;
  function hogMeSomeGas(uint amount) public {
    for (uint i=0; i < amount; i++) {
      hogSomeGas1[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas2[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas3[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas4[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas5[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas6[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas7[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas8[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas9[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas10[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas11[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas12[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
      hogSomeGas13[i] = "LoremIpsumissimplydummytextoftheprintingandtypesettingindustry.LoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500s,whenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbook.Ithassurvivednotonlyfivecenturies,butalsotheleapintoelectronictypesetting,remainingessentiallyunchanged.Itwaspopularisedinthe1960swiththereleaseofLetrasetsheetscontainingLoremIpsumpassages,andmorerecentlywithdesktoppublishingsoftwarelikeAldusPageMakerincludingversionsofLoremIpsum";
    }
  }
}
```

This was deployed via truffle with the following script:
```
const GasHog = artifacts.require("GasHog");
module.exports = async function (deployer, network, accounts) {
  await deployer.deploy(GasHog);
  let contract = await GasHog.deployed();
  for (i = 0; i < 20; i++) {
    contract.hogMeSomeGas(20, { gas: 50000000000, gasPrice: 5000000000000 })
  }
}
```

Please note this uses around 300M gas for a single block.

I then curled the block and this triggered the out of memory successfully.

`curl -v -XPOST --data '{"id":0,"jsonrpc":"2.0","method":"trace_replayBlockTransactions","params":["0x4",["trace"]]}' http://localhost:8542`
I believe we have successfully implemented a fix for this issue and would like to get some community feedback on getting this or something similar to this in.
https://github.com/dhallatmaine/besu/commit/af5ecc5f424acf6c5536c6805f37bc792e46ef16

**Comment by macfarla** [comment]
@daniellehrner can you take a look at this proposed fix - using streams instead of lists - https://github.com/dhallatmaine/besu/commit/af5ecc5f424acf6c5536c6805f37bc792e46ef16

**Comment by daniellehrner** [comment]
@dhallatmaine Your fix looks good to me. We would need to measure performance and memory consumption, but if it fixes the problem for you I guess those measurements should definitely show an improvement.

Could you please open a PR with your changes? Then we could run the additional tests and I would like to get a review from other Besu contributors as well.
