### ISSUE TITLE
Besu does not complete snap sync, w/ bonsai tries

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#3909]
### Description

Sometimes, Besu when synced from scratch on Ethereum mainnet will not succeed and then just show "Refreshing DNS record" over and over.

Some logs. I'll try this again with debug logs enabled, but chances are it'll work, as this issue is sporadic.

```
execution_1  | 2022-05-27 02:33:35.842+00:00 | EthScheduler-Workers-2 | INFO  | PersistBlockTask | Imported #14,851,594 / 37 tx / 0 om / 3,564,864 (11.9%) gas / (0xcbf7a67bc90fde71ec737f34057bf3fd55d0f331ebeea1da8aff2e394b29533a) in 0.745s. Peers: 28
execution_1  | 2022-05-27 02:33:57.891+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1  | 2022-05-27 02:34:06.680+00:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #14,851,595 / 356 tx / 0 om / 29,896,466 (99.9%) gas / (0x1b8dac724d376aeee51baa1ee21eebc2996114f1cce3aeb22cbe5505f3fe6bef) in 3.126s. Peers: 28
execution_1  | 2022-05-27 02:34:14.261+00:00 | EthScheduler-Workers-1 | ERROR | AbstractBlockProcessor | failed persisting block
execution_1  | java.lang.RuntimeException: World State Root does not match expected value, header 0xdf77b524913391500fe2140e5d709aa82921a0190c7407f3afb6937af761c694 calculated 0x91b90ceb9c6e4b03e710864588f9cf0832b620e21e897c4a9df40be104d6b4af
execution_1  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.persist(BonsaiPersistedWorldState.java:264)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:203)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:42)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:75)
execution_1  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:146)
execution_1  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
execution_1  |  at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:44)
execution_1  |  at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:44)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.executeTask(PersistBlockTask.java:201)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.run(AbstractEthTask.java:75)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.runImportTask(BlockPropagationManager.java:487)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.validateAndProcessPendingBlock(BlockPropagationManager.java:468)
execution_1  |  at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.lambda$importOrSavePendingBlock$17(BlockPropagationManager.java:456)
execution_1  |  at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:97)
execution_1  |  at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleSyncWorkerTask$0(EthScheduler.java:108)
execution_1  |  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
execution_1  |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
execution_1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
execution_1  |  at java.base/java.lang.Thread.run(Thread.java:829)
execution_1  | 2022-05-27 02:34:14.269+00:00 | EthScheduler-Workers-1 | ERROR | MainnetBlockValidator | Error processing block. Block 14851596 (0x1f2e6e2bfcd344940dc6c8156ed1452d8b029839cd9168e812756ad5c75df116)
execution_1  | 2022-05-27 02:34:14.269+00:00 | EthScheduler-Workers-1 | WARN  | BlockPropagationManager | Failed to import announced block 14851596 (0x1f2e6e2bfcd344940dc6c8156ed1452d8b029839cd9168e812756ad5c75df116)
execution_1  | 2022-05-27 02:34:22.349+00:00 | nioEventLoopGroup-3-4 | INFO  | BlockPropagationManager | Saving announced block 14851597 (0x8a51245bd3dfd195c1c86fafdfbefbf393f8b09de21a44cd0df7bc00199ee1e3) for future import
execution_1  | 2022-05-27 02:34:38.266+00:00 | nioEventLoopGroup-3-9 | INFO  | BlockPropagationManager | Saving announced block 14851598 (0x0076d0f765ca520819b3e15f5fff8908954f13538ee04fe5163e82e76d531182) for future import
execution_1  | 2022-05-27 02:34:42.578+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 14851599 (0xbad1a802e549c9188c88b424c466d0d92e18642e3427d56245f69167fc767569) for future import
execution_1  | 2022-05-27 02:34:50.365+00:00 | nioEventLoopGroup-3-8 | INFO  | BlockPropagationManager | Saving announced block 14851600 (0xde61936299e3165a50da2fa453d1c50234f69f1b94de8251ffa3c0a8f15c7772) for future import
execution_1  | 2022-05-27 02:34:53.913+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 14851601 (0x67e10e75e9fae7ceab9f6d2adb465136192838e9d44ac90c6dfc46babff1925c) for future import
execution_1  | 2022-05-27 02:34:57.891+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1  | 2022-05-27 02:34:57.961+00:00 | nioEventLoopGroup-3-6 | INFO  | BlockPropagationManager | Saving announced block 14851602 (0x2ac6f4c66c61eeec90afb0ee3401c0c9a1caa7d9d33623056b55b1a7e8afa431) for future import
execution_1  | 2022-05-27 02:34:59.759+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851603 (0xca142a5261a6532dce0eba546a01ef93f3ec5963b77aade5ef02942afe570cc5) for future import
execution_1  | 2022-05-27 02:35:52.810+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851604 (0x062739cd9e7cd62c81c2d95e31534b9e1f298224ed6b81305c621aab62fa378d) for future import
execution_1  | 2022-05-27 02:35:57.891+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1  | 2022-05-27 02:36:00.804+00:00 | nioEventLoopGroup-3-8 | INFO  | BlockPropagationManager | Saving announced block 14851605 (0xd5ea97133df0181d7265a82a07dadecea9528ab65eb35e54ddd7f43e063bd27f) for future import
execution_1  | 2022-05-27 02:36:05.546+00:00 | nioEventLoopGroup-3-6 | INFO  | BlockPropagationManager | Saving announced block 14851606 (0xde4c34b862f2c26740b7af0e861b0d7bb4c0b405432db2afcddacac07f04df8b) for future import
execution_1  | 2022-05-27 02:36:16.054+00:00 | nioEventLoopGroup-3-6 | INFO  | BlockPropagationManager | Saving announced block 14851607 (0x68578c9ec737e64ffb361d5739a2cfcc862fac32e8d34874d0d392fdc82e1153) for future import
execution_1  | 2022-05-27 02:36:20.123+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 14851608 (0x5670bb6ebcb32dd3b76a8ee6be9a69703f7cf54a2648c6f06fbba17c9b442df4) for future import
execution_1  | 2022-05-27 02:36:21.563+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851609 (0xcc2a8447ac70df7cfabd958d396f05801ccdd17910dc765b8d7d40a552ba1600) for future import
execution_1  | 2022-05-27 02:36:29.087+00:00 | nioEventLoopGroup-3-8 | INFO  | BlockPropagationManager | Saving announced block 14851610 (0x27099eca58e3f5b1b44c58e3aa06028b2e28d19ce9e6ec3f9d722802f437e8c8) for future import
execution_1  | 2022-05-27 02:36:31.023+00:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saving announced block 14851611 (0xad24049e97b3df52275a1a5d0cc0e196977fa8c87f80d7f9542476a41b94d2c3) for future import
execution_1  | 2022-05-27 02:36:49.462+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851612 (0x260703ac2bf0fd55b2bfdcea3e1409108c23991b2a8e073ab029c81b2df385b6) for future import
execution_1  | 2022-05-27 02:36:57.891+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1  | 2022-05-27 02:37:26.879+00:00 | nioEventLoopGroup-3-1 | INFO  | BlockPropagationManager | Saving announced block 14851613 (0xd4969a6e3782ad23ee5ba43c3ae51a9f70115a71a8c9735709532354475d160c) for future import
execution_1  | 2022-05-27 02:37:32.622+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851614 (0x04d83a130c949ee7e2462d0ba5e54cf1bedc7233fda54726bdd7b9be94637002) for future import
execution_1  | 2022-05-27 02:37:40.491+00:00 | nioEventLoopGroup-3-4 | INFO  | BlockPropagationManager | Saving announced block 14851615 (0x55a052beaebfee21ae69f2f8b06272191cd676a73d522c5e6efc0caa15d6917d) for future import
execution_1  | 2022-05-27 02:37:57.891+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1  | 2022-05-27 02:37:58.326+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851616 (0xcf8d1f900d0f1d6abbb3811dea9ca47dabee2a934bab037c2c0e851bec59cb0b) for future import
execution_1  | 2022-05-27 02:38:09.034+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851616 (0xeec5efdd1c06de854c0728d949583f4fd84240afca03b05e696cde494c4798b2) for future import
execution_1  | 2022-05-27 02:38:11.724+00:00 | nioEventLoopGroup-3-6 | INFO  | BlockPropagationManager | Saving announced block 14851617 (0x7d1d60ecf8d6c364c0817124946154d4bb3ebebfec3c9a0c881ec44a1eb3d649) for future import
execution_1  | 2022-05-27 02:38:15.727+00:00 | nioEventLoopGroup-3-4 | INFO  | BlockPropagationManager | Saving announced block 14851618 (0x944123c446b351e1084aa194d6928c28d11702d6e84d42dda868c2893dca02c6) for future import
execution_1  | 2022-05-27 02:38:34.910+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 14851619 (0xc1e7e4a2de602456e1825df832b82d4d1d0d406fbf8e780b36c484775904c320) for future import
execution_1  | 2022-05-27 02:38:51.940+00:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saving announced block 14851620 (0xc5a5062cf4127f539d1481c44c4c6450e79edd5817bbb07100c6c685f6864df6) for future import
execution_1  | 2022-05-27 02:38:57.891+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
execution_1  | 2022-05-27 02:39:15.021+00:00 | nioEventLoopGroup-3-4 | INFO  | BlockPropagationManager | Saving announced block 14851621 (0xd36a9d4465e70734d306d959bfdcba0e17efbbd9d1e47a0984a86797418132b1) for future import
execution_1  | 2022-05-27 02:39:20.744+00:00 | nioEventLoopGroup-3-6 | INFO  | BlockPropagationManager | Saving announced block 14851622 (0xd54bafc8c7a4c247f087560b94538d35629354a505f6cbc62e9bb9d10a028a5b) for future import
execution_1  | 2022-05-27 02:39:23.640+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 14851623 (0xd2a2445183465755616ea2a534134855bc82af82beee75152bfa8be3c2227c7f) for future import
execution_1  | 2022-05-27 02:39:24.798+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851624 (0x7cf1360c6c65f9fe4f06b184a071ed8a9470d2cd1db2522a221aef5d2495d97d) for future import
execution_1  | 2022-05-27 02:39:48.840+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 14851625 (0x67eb4538282ee4960dddab1ec27d443528913e522e66a2216d7bc6b7515e7e57) for future import
execution_1  | 2022-05-27 02:39:49.780+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saving announced block 14851625 (0xb756ccc8439a5e5626e38217f05ac034787da2695b4d2dfa4b5283b0c5c9373d) for future import
execution_1  | 2022-05-27 02:39:57.892+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
```

After this point `Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net` repeats for hours, with no other logs.

### Versions (Add all that apply)
* Software version: besu/v22.4.1/linux-x86_64/openjdk-java-11
* OS Name & Version: Ubuntu 20.04
* Docker Version: 20.10.12
* Cloud VM, type, size: Baremetal, 6 cores, 32 GiB RAM

**Comment by yorickdowne** [comment]
After restart, Besu did complete the sync. Attaching debug logs for that run.
[besu-sync-restart-dbg.log.gz](https://github.com/hyperledger/besu/files/8786649/besu-sync-restart-dbg.log.gz)

**Comment by fornax2** [comment]
Also faced this issue (with a few more Rocket Pool node operators) where after the initial sync, some block couldn't be imported and Besu start to lag behind saving blocks for future import. Only a restart managed to fix this.

**Comment by matkt** [comment]
We just merged a fix for that. thanks for your issue
