### ISSUE TITLE
[SPIKE] Investigate GitHub Actions for calling Sonar

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3928]
Sonar via CircleCI required this setting in CI: `Pass secrets to builds from forked pull requests` which is recommend disabled for security reasons. Hence Sonar temporarily disabled 
https://github.com/hyperledger/besu/pull/3922

Can we use GHA to pass the specific credentials required to run sonar?

**Comment by macfarla** [comment]
there are 3 test failures with ClassCastException
```

RunnerTest > fastSyncFromGenesis FAILED
    java.lang.ClassCastException: class org.hyperledger.besu.ethereum.blockcreation.PoWMiningCoordinator cannot be cast to class org.hyperledger.besu.consensus.merge.blockcreation.MergeMiningCoordinator (org.hyperledger.besu.ethereum.blockcreation.PoWMiningCoordinator and org.hyperledger.besu.consensus.merge.blockcreation.MergeMiningCoordinator are in unnamed module of loader 'app')
        at org.hyperledger.besu.ethereum.api.jsonrpc.methods.ExecutionEngineJsonRpcMethods.<init>(ExecutionEngineJsonRpcMethods.java:42)
        at org.hyperledger.besu.ethereum.api.jsonrpc.methods.JsonRpcMethodsFactory.methods(JsonRpcMethodsFactory.java:131)
        at org.hyperledger.besu.RunnerBuilder.jsonRpcMethods(RunnerBuilder.java:984)
        at org.hyperledger.besu.RunnerBuilder.build(RunnerBuilder.java:591)
        at org.hyperledger.besu.RunnerTest.syncFromGenesis(RunnerTest.java:237)
        at org.hyperledger.besu.RunnerTest.fastSyncFromGenesis(RunnerTest.java:148)
RunnerTest > fullSyncFromGenesis FAILED
    java.lang.ClassCastException: class org.hyperledger.besu.ethereum.blockcreation.PoWMiningCoordinator cannot be cast to class org.hyperledger.besu.consensus.merge.blockcreation.MergeMiningCoordinator (org.hyperledger.besu.ethereum.blockcreation.PoWMiningCoordinator and org.hyperledger.besu.consensus.merge.blockcreation.MergeMiningCoordinator are in unnamed module of loader 'app')
        at org.hyperledger.besu.ethereum.api.jsonrpc.methods.ExecutionEngineJsonRpcMethods.<init>(ExecutionEngineJsonRpcMethods.java:42)
        at org.hyperledger.besu.ethereum.api.jsonrpc.methods.JsonRpcMethodsFactory.methods(JsonRpcMethodsFactory.java:131)
        at org.hyperledger.besu.RunnerBuilder.jsonRpcMethods(RunnerBuilder.java:984)
        at org.hyperledger.besu.RunnerBuilder.build(RunnerBuilder.java:591)
        at org.hyperledger.besu.RunnerTest.syncFromGenesis(RunnerTest.java:237)
        at org.hyperledger.besu.RunnerTest.fullSyncFromGenesis(RunnerTest.java:143)
RlpBlockImporterTest > blockImportRejectsBadPow FAILED
    java.lang.AssertionError: [Invalid header at block number 2.] 
    Expecting code to raise a throwable.
        at org.hyperledger.besu.chainimport.RlpBlockImporterTest.blockImportRejectsBadPow(RlpBlockImporterTest.java:111)
```

**Comment by macfarla** [comment]
Aborted attempt is here https://github.com/hyperledger/besu/pull/3970

**Comment by non-fungible-nelson** [comment]
@jflo I had heard this is completed, can it be closed?

**Comment by jflo** [comment]
Give it 48 hours till we see it run this week.

**Comment by non-fungible-nelson** [comment]
closing for analysis completion
