### ISSUE TITLE
Unable to process block because parent world state is not available

### ISSUE THREAD

**Issue by SeaMonkey82** [hyperledger/besu#4052]
I ran into this error with ropsten-lodestar-besu, with besu on a commit from the main branch pushed within the last few days, and besu was unable to recover until I deleted the besu database and resynced.

```
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:148)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:214)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:256)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:277)
        at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:137)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:185)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:62)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-07-03 06:46:59.794-04:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Unable to process block because parent world state 0xea0a5af970e850f4760cd610a4bc1f741654f37cee92b9b630a7a733338dbb53 is not available. Block 12515901 (0x59c7b67917e9cc703e2887c03b1228f0f8b41da634f2a61b35df0219309990d0)
2022-07-03 06:46:59.795-04:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Invalid new payload: number: 12515901, hash: 0x59c7b67917e9cc703e2887c03b1228f0f8b41da634f2a61b35df0219309990d0, parentHash: 0xc628202a04d296e51193571a60d786614014daaa4f30c492e9c2d1fd01d0f879, latestValidHash: 0xc628202a04d296e51193571a60d786614014daaa4f30c492e9c2d1fd01d0f879, status: INVALID, validationError: Unable to process block because parent world state 0xea0a5af970e850f4760cd610a4bc1f741654f37cee92b9b630a7a733338dbb53 is not available
```

**Comment by parithosh** [comment]
Are you running Besu in a docker container by any chance?

**Comment by SeaMonkey82** [comment]
Encountered this again on 93b877002272e76b24571eec8996ed595f52c905

```
java.lang.RuntimeException: java.lang.IllegalStateException: Address=0x134e62bd2ee247d4186a1fdbaa9e076cb26c1355 Prior Value in Rolling Change: Storage Roots differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:254)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:256)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:277)
        at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:137)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:188)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:62)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Address=0x134e62bd2ee247d4186a1fdbaa9e076cb26c1355 Prior Value in Rolling Change: Storage Roots differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.assertCloseEnoughForDiffing(BonsaiAccount.java:309)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollAccountChange(BonsaiWorldStateUpdater.java:497)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.lambda$rollForward$9(BonsaiWorldStateUpdater.java:422)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollForward(BonsaiWorldStateUpdater.java:420)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:243)
        ... 14 more
2022-07-08 16:21:44.624-04:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Unable to process block because parent world state 0xad3c4abf128722b6ee0242b82a90fa050415787cab407953708309a076e678ab is not available. Block 12552253 (0x3426773b49d87c36f73730ffe57a638d14d7f440d038cbceec1ac38370384e6d)
2022-07-08 16:21:44.624-04:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Invalid new payload: number: 12552253, hash: 0x3426773b49d87c36f73730ffe57a638d14d7f440d038cbceec1ac38370384e6d, parentHash: 0x95935a615a7e04a5d7cbd4151a6807fb516763a81a427fa8f244ec9e0c876c7f, latestValidHash: 0x95935a615a7e04a5d7cbd4151a6807fb516763a81a427fa8f244ec9e0c876c7f, status: INVALID, validationError: Unable to process block because parent world state 0xad3c4abf128722b6ee0242b82a90fa050415787cab407953708309a076e678ab is not available
```

**Comment by matkt** [comment]
was it a new node or an old node? was it not long after the reboot with the update or long after?

**Comment by matkt** [comment]
I say that because if it is a node that has been Synced before it is possible that it was already corrupted before. This fix does not fix an already corrupted node but it prevents a new node from becoming corrupted. If you have with a node that has been fully synced with this fix. So I will Say that this fix is ​​not enough

**Comment by mcdee** [comment]
>  I say that because if it is a node that has been Synced before it is possible that it was already corrupted before.

Is it possible to know if a node is corrupted, or is this basically saying "you need to resync from scratch" in case the node has this issue but not currently showing problems?

**Comment by matkt** [comment]
to know if a node is corrupted it would be necessary to look at the state of the last trielog and to see if they are valid. it is technically feasible but it is not currently available. if the problem persists we can implement an RPC method to replace a trielog with a valid trielog to avoid having to resync. But I prefer for the moment to not implement a feature for a bug. Knowing that we normally fixed it . But I am aware that this has an impact and if the problem persists we will certainly implement a method to avoid resync while trying to fix it (like RPC). But I'm very confident on our last fix regarding this

**Comment by matkt** [comment]
After knowing that the depth of reorgs is limited on the mainnet. If a node works for a day with the new version I would say there is normally no risk. Unless we have a very deep reorg which is not normally possible

**Comment by SeaMonkey82** [comment]
This was supposedly fixed in 22.4.4, but I have since done a completely fresh sync with that version and encountered the same error.

**Comment by SeaMonkey82** [comment]
Same error.  Different stacktrace. Commit f885c4671333168089a7b86ffedf985fce81954b
```
java.lang.RuntimeException: java.lang.IllegalStateException: Expected to create account, but the account exists.  Address=0xd48290f90578bf460e34bf33cac3d949d94e0237
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:254)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:265)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:281)
        at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:137)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:195)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:62)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Expected to create account, but the account exists.  Address=0xd48290f90578bf460e34bf33cac3d949d94e0237
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollAccountChange(BonsaiWorldStateUpdater.java:493)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.lambda$rollForward$9(BonsaiWorldStateUpdater.java:422)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollForward(BonsaiWorldStateUpdater.java:420)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:243)
        ... 14 more
2022-07-17 15:16:22.621-04:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Unable to process block because parent world state 0x71f74b0e284276cf98ddbb58cd7eec545009d9ac394f744ef65f81b2acb7b7b0 is not available. Block 12611764 (0xcc4f02a668683f996f2976af7c96afab303b4752e56dc631f09a36f1c9a6134e)
2022-07-17 15:16:22.621-04:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Invalid new payload: number: 12611764, hash: 0xcc4f02a668683f996f2976af7c96afab303b4752e56dc631f09a36f1c9a6134e, parentHash: 0xd55f875abf05751639ef5141e58bec392b63ced48152d2e7eea4a1f5eee3bef5, latestValidHash: 0xd55f875abf05751639ef5141e58bec392b63ced48152d2e7eea4a1f5eee3bef5, status: INVALID, validationError: Unable to process block because parent world state 0x71f74b0e284276cf98ddbb58cd7eec545009d9ac394f744ef65f81b2acb7b7b0 is not available
```

**Comment by matkt** [comment]
we are trying a fix that normally fix these issues. We'll keep you informed

**Comment by SeaMonkey82** [comment]
Yet another unique stack trace for this error.
```
java.lang.RuntimeException: java.lang.IllegalStateException: Address=0xa2e1d8dff9b33d986aee4e812f5652afa8f4b820 Prior Value in Rolling Change: nonces differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:254)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:100)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:265)
        at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:281)
        at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:137)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:195)
        at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:62)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Address=0xa2e1d8dff9b33d986aee4e812f5652afa8f4b820 Prior Value in Rolling Change: nonces differ
        at org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.assertCloseEnoughForDiffing(BonsaiAccount.java:303)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollAccountChange(BonsaiWorldStateUpdater.java:497)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.lambda$rollBack$13(BonsaiWorldStateUpdater.java:447)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1764)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.rollBack(BonsaiWorldStateUpdater.java:445)
        at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateArchive.getMutable(BonsaiWorldStateArchive.java:239)
        ... 14 more
2022-07-18 10:11:14.603-04:00 | vert.x-worker-thread-0 | ERROR | MainnetBlockValidator | Unable to process block because parent world state 0x7e05b280e6fcb6f469f89df4d547e750eca25a2292a3804f7229e6ed9c9d5083 is not available. Block 12616596 (0x34ef8b3984f7f801a8aa48747997bf367126d0d80e9b1890c36b71ce6c90f48f)
2022-07-18 10:11:14.603-04:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Invalid new payload: number: 12616596, hash: 0x34ef8b3984f7f801a8aa48747997bf367126d0d80e9b1890c36b71ce6c90f48f, parentHash: 0xcc7ded52c5b1e70a20b6fd6f9405c468fc0497df9ded2f7eb701b9ea3dcfdbac, latestValidHash: 0xcc7ded52c5b1e70a20b6fd6f9405c468fc0497df9ded2f7eb701b9ea3dcfdbac, status: INVALID, validationError: Unable to process block because parent world state 0x7e05b280e6fcb6f469f89df4d547e750eca25a2292a3804f7229e6ed9c9d5083 is not available
```
