### ISSUE TITLE
StackOverflow on recursive call to MergeCoordinator.isDecendantOf()

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#4169]
Kiln is now old enough (over 200k blocks since TTD) that the recursive nature of this method will blow stack:

> issue on Kiln with ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_forkchoiceUpdatedV1. what could be the cause? the Besu node is connected to a lighthouse beacon. logs in the thread.

>   at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.isDescendantOf(MergeCoordinator.java:536)                                                                                         ││ 2022-07-22 14:16:23.052+00:00 | vert.x-eventloop-thread-2 | ERROR | ExecutionEngineJsonRpcMethod | failed to exec consensus method engine_forkchoiceUpdatedV1                                                │
│ java.lang.StackOverflowError                                                                                                                                                                                 ││     at org.hyperledger.besu.ethereum.rlp.RLPEncodingHelpers.isSingleRLPByte(RLPEncodingHelpers.java:28)                                                                                                      │
│     at ....
 
Method needs to be refactored into a non-recursive pattern, since the distance from TTD will only increase as long as the network is alive.

**Comment by jflo** [comment]
Example of recursion on kiln:

> 2022-07-26 13:57:51.786+00:00 | vert.x-worker-thread-0 | DEBUG | MergeCoordinator | checking if block 683190:0x724b715167e6e6bfcfd6bba72d4fe53eaaa9a713bb3019a9ffc4c86f1c75f7db is ancestor of ││  898383:0xc05624d989966c207cf8b65aa671263ecd6847829864ffdd9e4ace8abc15cb7b                                                                                                                               │
│ besu-node 2022-07-26 13:57:51.786+00:00 | vert.x-worker-thread-0 | DEBUG | MergeCoordinator | checking if block 683190:0x724b715167e6e6bfcfd6bba72d4fe53eaaa9a713bb3019a9ffc4c86f1c75f7db is ancestor of ││  898382:0xe942c75bf533e1d5f782f9609c3cd4ef3fdb8d4f48b08b8edaabde6d14bb7712                                                                                                                               │
│ besu-node 2022-07-26 13:57:51.786+00:00 | vert.x-worker-thread-0 | DEBUG | MergeCoordinator | checking if block 683190:0x724b715167e6e6bfcfd6bba72d4fe53eaaa9a713bb3019a9ffc4c86f1c75f7db is ancestor of ││  898381:0x9e7f27b1430ee7584d4f5bd09ef917392afd728f81df250f4589f5dff7132589                                                                                                                               │
│ besu-node     at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.lambda$isDescendantOf$23(MergeCoordinator.java:536)                                                                 ││ besu-node     at java.base/java.util.Optional.map(Optional.java:265)                                                                                                                                     │
│ besu-node     at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.isDescendantOf(MergeCoordinator.java:536)                                                                           ││ besu-node     at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.lambda$isDescendantOf$23(MergeCoordinator.java:536)

**Comment by jflo** [comment]
If you can reproduce this, I'm curious to see complete logs from startup to stack error for both Besu and whatever CL was used. I'm curious how besu tried to determine the descendant of a block that was 200k blocks past the finalized one.  Thats a weird edge case that I'm not entirely sure how to reproduce.
