### ISSUE TITLE
ConcurrentModificationException from reattemptPendingPeers

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#4188]
User reported an issue on Discord. See stack trace here: https://pastebin.com/2zaa4JEd
Logs: https://pastebin.com/64LBAv6s
Discord message: https://discord.com/channels/905194001349627914/938504958909747250/1001287161007571035

**Comment by macfarla** [comment]
```
eth1_1           | java.util.ConcurrentModificationException
eth1_1           |      at java.base/java.util.concurrent.CopyOnWriteArrayList.bulkRemove(CopyOnWriteArrayList.java:855)
eth1_1           |      at java.base/java.util.concurrent.CopyOnWriteArrayList.bulkRemove(CopyOnWriteArrayList.java:833)
eth1_1           |      at java.base/java.util.concurrent.CopyOnWriteArrayList.removeIf(CopyOnWriteArrayList.java:816)
eth1_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthPeers.reattemptPendingPeerRequests(EthPeers.java:171)
eth1_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthPeers.dispatchMessage(EthPeers.java:161)
eth1_1           |      at org.hyperledger.besu.ethereum.eth.manager.EthProtocolManager.processMessage(EthProtocolManager.java:282)
eth1_1           |      at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.lambda$setupHandlers$0(NetworkRunner.java:135)
eth1_1           |      at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.lambda$dispatchMessage$1(PeerConnectionEvents.java:64)
eth1_1           |      at org.hyperledger.besu.util.Subscribers.lambda$forEach$0(Subscribers.java:112)
eth1_1           |      at java.base/java.lang.Iterable.forEach(Iterable.java:75)
eth1_1           |      at org.hyperledger.besu.util.Subscribers.forEach(Subscribers.java:109)
eth1_1           |      at org.hyperledger.besu.ethereum.p2p.rlpx.connections.PeerConnectionEvents.dispatchMessage(PeerConnectionEvents.java:64)
```

**Comment by fab-10** [comment]
I think this a duplicate of https://github.com/hyperledger/besu/issues/3491

**Comment by iamhsk** [comment]
Closing this since it is a duplicate
