### ISSUE TITLE
Transaction has been reverted by the EVM

### ISSUE THREAD

**Issue by AndreAugusto11** [hyperledger/besu#4215]
### Description
I am trying to deploy a smart contract in a besu network but the transaction to do so is being reverted by the EVM. I would like to have the smart contract deployed successfully.

### Acceptance Criteria
* Smart contract being deployed successfully.

### Steps to Reproduce (Bug)
1. Step 1 – Run a node for testing following the [Besu docs](https://besu.hyperledger.org/en/stable/HowTo/Get-Started/Starting-node/#run-a-node-for-testing)
2. Step 2 – Create a directory contracts with a `contract.sol` file and compile it to generate a json file.
Contents of the `contract.sol` file:
```
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.15;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract MyContract is Ownable, ERC20 {
    constructor() ERC20("someName", "someToken") {
    }
    function mint(address account, uint256 amount) external onlyOwner {
        _mint(account, amount);
    }
    function burn(address account, uint256 amount) external onlyOwner {
        _burn(account, amount);
    }
}
```
3. Step 3 – Create an example.js file with the following content:
```
const path = require('path');
const fs = require('fs');
const Tx = require('ethereumjs-tx').Transaction;
const Web3 = require('web3');
const web3 = new Web3('HTTP://127.0.0.1:8545'); // besu network

const genAccountPubKey = "0x627306090abaB3A6e1400e9345bC60c78a8BEf57";
const genAccountPrivKey = "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3";

const contractJsonPath = path.resolve(__dirname, 'contracts', 'cbdc-contract.json');
const contractJson = JSON.parse(fs.readFileSync(contractJsonPath));
const contractABI = contractJson.abi;
const contractBytecode = contractJson.bytecode;

const contract = new web3.eth.Contract(contractABI);
// smart contract data
const data = contract.deploy({
  data: contractBytecode
}).encodeABI();

async function deploy() {
  const nonce = await web3.eth.getTransactionCount(genAccountPubKey);

  const tx = await web3.eth.accounts.signTransaction(
    {
      nonce: nonce,
      from: genAccountPubKey,
      data: data,
      gas: 1000000,
    },
    genAccountPrivKey,
  );
  
  if (!tx.rawTransaction) {
    throw new Error(`${fnTag} Signing transaction failed, reason unknown.`);
  }
  
  const receipt = await web3.eth.sendSignedTransaction(tx.rawTransaction);
  console.log(receipt);
}

deploy();
```

**Expected behavior:** The smart contract to be deployed successfully when running the example.js file.

**Actual behavior:**
```
(node:74542) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x07fd79f3baf7a546f7c0db15d090a4284c9c2a18537b14cbbc019eda985bf6d4",
  "blockNumber": 4636,
  "contractAddress": "0xdDA6327139485221633A1FcD65f4aC932E60A2e1",
  "cumulativeGasUsed": 1000000,
  "from": "0x627306090abab3a6e1400e9345bc60c78a8bef57",
  "gasUsed": 1000000,
  "effectiveGasPrice": 1000,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": null,
  "transactionHash": "0x97eba856dd0a5c73ba6526773581c84377724f1e5a672eabf9b08ff0fae41aa0",
  "transactionIndex": 0
}
    at Object.TransactionError (/Users/andre/Documents/GitHub/deploy-sc-with-web3/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (/Users/andre/Documents/GitHub/deploy-sc-with-web3/node_modules/web3-core-helpers/lib/errors.js:98:21)
    at /Users/andre/Documents/GitHub/deploy-sc-with-web3/node_modules/web3-core-method/lib/index.js:396:57
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Frequency:** Always

### Versions (Add all that apply)
* Besu version: [`besu --version`]: besu/v22.7.0-RC3/osx-x86_64/adoptopenjdk-java-11
* Java version: [`java -version`]: openjdk version "11.0.11" 2021-04-20

### package.json dependencies information
```
"dependencies": {
    "@openzeppelin/contracts": "^4.7.2",
    "ethereumjs-tx": "^2.1.2",
    "web3": "^1.7.5"
}
```

I have tried to deploy exactly the same way to Ganache, and it is successful, the contract is created.

**Comment by AndreAugusto11** [comment]
The problem is solved. It had to do with the gas not being properly set to the size of the smart contract.

**Comment by DevWonder01** [comment]
> The problem is solved. It had to do with the gas not being properly set to the size of the smart contract.

What was the gas you used ?

**Comment by AndreAugusto11** [comment]
Hi @DevWonder01 I was using `1000000` as gas limit. By looking at the logs I realized it was not enough, so I increased accordingly to that. Please do that, look at the logs, the math is there 😀.
