### ISSUE TITLE
Crash during full sync

### ISSUE THREAD

**Issue by iamhsk** [hyperledger/besu#4219]
**Actual behavior:** [What actually happens]
Besu crashed while doing full sync on a newer block `7342831` on Goerli.  it was running normally and synced. several other Besu nodes and all geth nodes are fine but this now is out of sync and looping. the node has 1 restart.

* Software version: [`22.7.0-snapshot`]

**Stack trace:**  
```
│ besu-node 2022-08-04 08:42:44.237+00:00 | EthScheduler-Services-274 (importBlock) | ERROR | MainnetBlockValidator | Unable to process block because parent world state 0x91b92cc7f11f8154b27a0fcfd864dd885485462e939b3859e7f47f16f5b6138f is no │
│ besu-node 2022-08-04 08:42:44.238+00:00 | EthScheduler-Services-274 (importBlock) | WARN  | PipelineChainDownloader | Invalid block detected. Disconnecting from sync target. Failed to import block: Invalid block at #7342831 (0xce16fd505288 │
│ besu-node 2022-08-04 08:42:44.238+00:00 | EthScheduler-Services-274 (importBlock) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.                                                                      │
│ besu-node java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #7342831 (0xce16fd505288a0d62061e8d85a78b8b3f1fc898436c29cb9f5132b0 │
│ besu-node     at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)                                                                                                                                       │
│ besu-node     at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)                                                                                                                                     │
│ besu-node     at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)                                                                                                                                 │
│ besu-node     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)                                                                                                                                      │
│ besu-node     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)                                                                                                                            │
│ besu-node     at org.hyperledger.besu.services.pipeline.Pipeline.abort(Pipeline.java:180)                                                                                                                                                       │
│ besu-node     at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:159)                                                                                                                               │
│ besu-node     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)                                                                                                                                              │
│ besu-node     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                                                                             │
│ besu-node     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                                                                      │
│ besu-node     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                                                      │
│ besu-node     at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                                                                                                │
│ besu-node Caused by: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #7342831 (0xce16fd505288a0d62061e8d85a78b8b3f1fc898436c29cb9f5132b00f35b1c56)                      │
│ besu-node     at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:62)                                                                                                                        │
│ besu-node     at org.hyperledger.besu.ethereum.eth.sync.fullsync.FullImportBlockStep.accept(FullImportBlockStep.java:31)                                                                                                                        │
│ besu-node     at org.hyperledger.besu.services.pipeline.CompleterStage.run(CompleterStage.java:37)                                                                                                                                              │
│ besu-node     at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)                                                                                                                               │
│ besu-node     ... 5 more
```

**Comment by garyschulte** [comment]
snapshot releases are a moving target, can we reproduce this with a specific release version or share the commit hash that the snapshot was built from? 🙏
