### ISSUE TITLE
BaseFeePendingTransactionsSorter encountering empty `maxPriorityFeePerGas`

### ISSUE THREAD

**Issue by shemnon** [hyperledger/besu#4343]
Saw this stack trace six times today - 

```
2022-09-04 11:15:22.298-06:00 | vert.x-eventloop-thread-1 | ERROR | ContextImpl | Unhandled exception
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.hyperledger.besu.ethereum.eth.transactions.sorter.BaseFeePendingTransactionsSorter.lambda$new$0(BaseFeePendingTransactionsSorter.java:84)
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
	at java.base/java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:221)
	at java.base/java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:220)
	at java.base/java.util.Collections$ReverseComparator2.compare(Collections.java:5397)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:344)
	at java.base/java.util.TreeMap.remove(TreeMap.java:881)
	at java.base/java.util.TreeSet.remove(TreeSet.java:276)
	at org.hyperledger.besu.ethereum.eth.transactions.sorter.BaseFeePendingTransactionsSorter.doRemoveTransaction(BaseFeePendingTransactionsSorter.java:115)
	at org.hyperledger.besu.ethereum.eth.transactions.sorter.AbstractPendingTransactionsSorter.removeTransaction(AbstractPendingTransactionsSorter.java:173)
	at org.hyperledger.besu.ethereum.eth.transactions.sorter.AbstractPendingTransactionsSorter.lambda$evictOldTransactions$1(AbstractPendingTransactionsSorter.java:140)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.hyperledger.besu.ethereum.eth.transactions.sorter.AbstractPendingTransactionsSorter.evictOldTransactions(AbstractPendingTransactionsSorter.java:137)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPoolEvictionService.lambda$start$0(TransactionPoolEvictionService.java:38)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:889)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It makes little sense because to get into the `prioritizedTransactionsStaticRange` set (lines 206 & 287) you have to be filtered via isInStaticRange, which requires said optional to no be null.

The safest fix is probably to `orElse` it to a value that will cause the promptest eviction (since something went wrong, like a mutable transaction, which I don't see in current code). 0 or 2^256-1?

**Comment by garyschulte** [comment]
This is actually a fairly benign error, but the stack trace is not a good look.  The worst of it is that we fail the 60 second periodic evictOldTransactions timer.

What is happening is `evictOldTransactions` is attempting to drop a transaction that has been kicked out concurrently.

1. evictOldTransactions identifies a non-EIP1559 transaction T1 to evict
2. T1 gets concurrently evicted by addTransactionToPool (or a newly imported block, or whatever)
3. BaseFeePendingTransactionSorter [tries to evict from the dynamic pool but does not find it](https://github.com/hyperledger/besu/blob/main/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/sorter/BaseFeePendingTransactionsSorter.java#L106-L107)
4. evictOldTransactions tries to evict T1 from the static range instead, and the comparator blows up because it isn't a 1559 txn

I am not certain why this seems to be happening more frequently than it did with 22.7.1(-) , but it is likely because we are evicting transactions from the senderAndNonce collection and that opens the concurrency window up a bit wider for this to happen more frequently.  

An `.orElse(Wei.ZERO)` can fix this, or we can check to see if the transaction is in the static range on 107 before we try to evict it from the static pool.
