### ISSUE TITLE
Intermittent spotless failure in unit test step

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4363]
Intermittent spotless failure in unit test step
Looks like something needs updating

eg https://app.circleci.com/pipelines/github/hyperledger/besu/16864/workflows/c6c39ffa-1207-442d-bc95-a88dca825cd9/jobs/101353
```
Task :acceptance-tests:spotlessGroovyGradle FAILED
Cannot format, probably due to compilation errors.  Please fix and try again.
Step 'eclipse groovy formatter' found problem in 'build.gradle':
You are not using latest version on JVM 11+.
Try to upgrade to eclipse groovy formatter 4.21.0, which may have fixed this problem.
java.lang.Exception: You are not using latest version on JVM 11+.
Try to upgrade to eclipse groovy formatter 4.21.0, which may have fixed this problem.
	at com.diffplug.spotless.Jvm$Support$1.apply(Jvm.java:181)
	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
	at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
```

**Comment by macfarla** [comment]
should be fixed by #4366
