### ISSUE TITLE
Besu crashed after request

### ISSUE THREAD

**Issue by githubswisschain** [hyperledger/besu#4371]
Hi. I'm trying to execute a request ``` curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceBlockByHash","params":["0x0111aa7b7eb394144fdb3dca7b1f72dab5c1e38e01a0b842d0814f4480eb3f75"], "id":1}' http://127.0.0.1:8545 ```
, but get the besu error:
```
ethereum_1  | 2022-09-08 14:36:30.879+00:00 | Timer-0 | INFO  | DNSTimerTask | Refreshing DNS records with enrtree://AKA3AM6LPBYEUDMVNU3BSVQJ5AD45Y7YPOHJLEF6W26QOE4VTUDPE@all.mainnet.ethdisco.net
ethereum_1  | 2022-09-08 14:36:37.685+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 15497150 (0x1eb8b37849007bf8285bc17cdd8aff20097ad02bd3b7421dc2803e9055312935) for future import
ethereum_1  | 2022-09-08 14:36:37.838+00:00 | nioEventLoopGroup-3-10 | INFO  | BlockPropagationManager | Saving announced block 15497151 (0x33cca876da52c5291c95b2d7eb1d7df0641107492c811590ca7d1d6ac9104013) for future import
ethereum_1  | 2022-09-08 14:36:40.944+00:00 | nioEventLoopGroup-3-7 | INFO  | BlockPropagationManager | Saving announced block 15497152 (0x92ab5181ce605580a030593eb53ac6d392c42c5dc6de4848a74105c2a4cf8b9d) for future import
ethereum_1  | 2022-09-08 14:36:40.948+00:00 | nioEventLoopGroup-3-9 | INFO  | BlockPropagationManager | Saving announced block 15497153 (0x5d686b5aeb794fcf15e7f7886acd91dfc12547767c5cb80c06c2f606b63e26cf) for future import
ethereum_1  | 2022-09-08 14:36:44.173+00:00 | nioEventLoopGroup-3-9 | INFO  | SyncTargetManager | Found common ancestor with peer Peer 0xadc5d4e480de09ffa7... PeerReputation 99, validated? true, disconnected? false at block 15497148
ethereum_1  | 2022-09-08 14:36:54.076+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-18,5,main] has been blocked for 61233 ms, time limit is 60000 ms
ethereum_1  | io.vertx.core.VertxException: Thread blocked
ethereum_1  | 	at app//org.apache.tuweni.bytes.Bytes.appendHexTo(Bytes.java:1410)
ethereum_1  | 	at app//org.apache.tuweni.bytes.Bytes.toUnprefixedHexString(Bytes.java:1553)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.StructLog$$Lambda$1667/0x00000008404c6c40.apply(Unknown Source)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
ethereum_1  | 	at java.base@11.0.15/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.StructLog.lambda$new$1(StructLog.java:49)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.StructLog$$Lambda$1666/0x00000008404c6840.apply(Unknown Source)
ethereum_1  | 	at java.base@11.0.15/java.util.Optional.map(Optional.java:265)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.StructLog.<init>(StructLog.java:49)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.DebugTraceTransactionResult.createStructLog(DebugTraceTransactionResult.java:53)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.DebugTraceTransactionResult$$Lambda$1664/0x00000008404c6040.apply(Unknown Source)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
ethereum_1  | 	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.DebugTraceTransactionResult.<init>(DebugTraceTransactionResult.java:41)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.DebugTraceTransactionResult$$Lambda$1663/0x00000008404c5c40.apply(Unknown Source)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
ethereum_1  | 	at java.base@11.0.15/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ethereum_1  | 	at java.base@11.0.15/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.DebugTraceTransactionResult.of(DebugTraceTransactionResult.java:47)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.DebugTraceBlockByHash$$Lambda$1662/0x00000008404c5840.apply(Unknown Source)
ethereum_1  | 	at java.base@11.0.15/java.util.Optional.map(Optional.java:265)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.DebugTraceBlockByHash.response(DebugTraceBlockByHash.java:59)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:42)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:91)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$6(JsonRpcExecutorHandler.java:76)
ethereum_1  | 	at app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler$$Lambda$672/0x00000008404a3440.handle(Unknown Source)
ethereum_1  | 	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
ethereum_1  | 	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$1265/0x00000008406e3040.handle(Unknown Source)
ethereum_1  | 	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
ethereum_1  | 	at app//io.vertx.core.impl.ContextImpl$$Lambda$812/0x000000084059f040.handle(Unknown Source)
ethereum_1  | 	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
ethereum_1  | 	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
ethereum_1  | 	at app//io.vertx.core.impl.ContextImpl$$Lambda$811/0x000000084059e840.run(Unknown Source)
ethereum_1  | 	at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
ethereum_1  | 	at app//io.vertx.core.impl.TaskQueue$$Lambda$606/0x000000084046d040.run(Unknown Source)
ethereum_1  | 	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
ethereum_1  | 	at java.base@11.0.15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
ethereum_1  | 	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
ethereum_1  | 	at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)
```

besu version is 22.7.1
config:
```
besu --network=mainnet --rpc-http-enabled --sync-mode=fast --host-allowlist=* --nat-method=upnp --Xdns-enabled=true --rpc-http-api=ETH,NET,CLIQUE,DEBUG,MINER,NET,PERM,ADMIN,EEA,TXPOOL,PRIV,WEB3
```
hardware:
4cpu/16ram, ssd

Could anyone help?

**Comment by macfarla** [comment]
Thanks @githubswisschain we are looking into this

**Comment by mark-terry** [comment]
@githubswisschain We've investigated, but haven't been able to replicate the issue you've logged or identify the cause.

Could you advise whether you've experienced this issue again?

**Comment by githubswisschain** [comment]
@mark-terry Now it works. I've added more RAM

**Comment by mark-terry** [comment]
Thanks for the update! 👍

**Comment by mark-terry** [comment]
Could you advise what RAM / JVM configuration resolved the issue?
