### ISSUE TITLE
Error on pruning with Besu 22.7.2 - StatePruning-0 | ERROR | Besu | Uncaught exception in thread "StatePruning-0"

### ISSUE THREAD

**Issue by tiagocmachado** [hyperledger/besu#4376]
### Description

Seeing the following error on node start while using Forest with pruning enabled.

```
Sep 08 10:44:46  besu[2399129]: org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Column family already dropped!
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDbSegmentIdentifier.lambda$reset$0(RocksDbSegmentIdentifier.java:50)
Sep 08 10:44:46  besu[2399129]:         at java.base/java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:188)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDbSegmentIdentifier.reset(RocksDbSegmentIdentifier.java:39)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.lambda$clear$3(RocksDBColumnarKeyValueStorage.java:224)
Sep 08 10:44:46  besu[2399129]:         at java.base/java.util.Optional.ifPresent(Optional.java:178)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:224)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.clear(RocksDBColumnarKeyValueStorage.java:64)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.clear(SegmentedKeyValueStorageAdapter.java:40)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.clearMarks(MarkSweepPruner.java:229)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.ethereum.worldstate.MarkSweepPruner.prepare(MarkSweepPruner.java:124)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.ethereum.worldstate.Pruner.lambda$start$0(Pruner.java:97)
Sep 08 10:44:46  besu[2399129]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Sep 08 10:44:46  besu[2399129]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Sep 08 10:44:46  besu[2399129]:         at java.base/java.lang.Thread.run(Thread.java:833)
Sep 08 10:44:46  besu[2399129]: Caused by: org.rocksdb.RocksDBException: Column family already dropped!
Sep 08 10:44:46  besu[2399129]:         at org.rocksdb.RocksDB.dropColumnFamily(Native Method)
Sep 08 10:44:46  besu[2399129]:         at org.rocksdb.RocksDB.dropColumnFamily(RocksDB.java:767)
Sep 08 10:44:46  besu[2399129]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDbSegmentIdentifier.lambda$reset$0(RocksDbSegmentIdentifier.java:45)
Sep 08 10:44:46  besu[2399129]:         ... 13 more
```

### Versions
* Software version: 22.7.2
* Java version: 17.0.4
* OS Name & Version: Ubuntu 20.04.5 LTS

**Comment by macfarla** [comment]
Does your node recover from this issue @tiagocmachado ?

**Comment by tiagocmachado** [comment]
@macfarla Yes, it only appears once on node start.
