### ISSUE TITLE
Error: Unable to load trie node value

### ISSUE THREAD

**Issue by estensen** [hyperledger/besu#4379]
Mainnet
v22.7.2
Checkpoint sync
Bonsai
Paired with Lighthouse

```
2022-09-10 07:28:42.488+02:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #15,507,058 / 177 tx / 0 om / 12,357,960 (41.2%) gas / (0xeb57cfb3a467b8d2fac4755ea307e0170cb9b7958c8e2e3867325a39d464aea3) in 0.810s. Peers: 37
2022-09-10 07:28:44.492+02:00 | EthScheduler-Transactions-0 | ERROR | Besu | Uncaught exception in thread "EthScheduler-Transactions-0"
org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xfa7c13692550ff6de7f9df083cf91b0064a88728009472fd9d1e24f3bcaf7244 location 0x
	at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:133)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:131)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:63)
	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:119)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage.getAccount(BonsaiWorldStateKeyValueStorage.java:110)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.get(BonsaiPersistedWorldState.java:340)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiLayeredWorldState.get(BonsaiLayeredWorldState.java:232)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.lambda$validateTransaction$2(TransactionPool.java:282)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateTransaction(TransactionPool.java:280)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateRemoteTransaction(TransactionPool.java:213)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.addRemoteTransactions(TransactionPool.java:153)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:111)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:85)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageHandler.lambda$exec$0(TransactionsMessageHandler.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-10 07:28:45.828+02:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #15,507,059 / 45 tx / 0 om / 4,967,503 (16.6%) gas / (0x2fbe25e412dd9725d8c49c2306e851b3c3c3000f59fcbb82b440cda9625f8912) in 0.319s. Peers: 36
...
2022-09-10 08:24:05.622+02:00 | EthScheduler-Workers-1 | INFO  | PersistBlockTask | Imported #15,507,283 / 204 tx / 0 om / 24,431,428 (81.6%) gas / (0x2864fc3c8e7b49a559c4aecf9f4c168cb7f2ffedb29c94e393429df508bed2a9) in 1.589s. Peers: 37
2022-09-10 08:24:06.664+02:00 | EthScheduler-Transactions-2 | ERROR | Besu | Uncaught exception in thread "EthScheduler-Transactions-2"
org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xd39037f7f5278f704960d8dbff99e2487e11696b55f36db135d5b145d5c056cc location 0x0b
	at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:133)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:131)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:63)
	at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46)
	at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
	at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:64)
	at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:119)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage.getAccount(BonsaiWorldStateKeyValueStorage.java:110)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.get(BonsaiPersistedWorldState.java:340)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiLayeredWorldState.get(BonsaiLayeredWorldState.java:232)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.lambda$validateTransaction$2(TransactionPool.java:282)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateTransaction(TransactionPool.java:280)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateRemoteTransaction(TransactionPool.java:213)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.addRemoteTransactions(TransactionPool.java:153)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:111)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:85)
	at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageHandler.lambda$exec$0(TransactionsMessageHandler.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-10 08:24:12.731+02:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #15,507,284 / 167 tx / 0 om / 14,253,970 (47.6%) gas / (0x1008dc24feb11c14bb1e81632e75f27e4538c386f69c93ffb7f3bc379e783e67) in 1.451s. Peers: 37

```

Related to https://github.com/hyperledger/besu/issues/4079, but not the same as it's able to recover.

**Comment by kayagoban** [comment]
`Sep 10 20:18:54 besu besu[1130]: 2022-09-10 20:18:54.643+02:00 | EthScheduler-Transactions-2 | ERROR | Besu | Uncaught exception in thread "EthScheduler-Transactions-2"
Sep 10 20:18:54 besu besu[1130]: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x81f76cccd2adacc5749c7fd45dd1c2c8c4eb6bb33d963a7f4088af6bde85f661 location 0x01
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:133)
Sep 10 20:18:54 besu besu[1130]: #011at java.base/java.util.Optional.orElseThrow(Optional.java:403)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:131)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:63)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.GetVisitor.visit(GetVisitor.java:46)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:64)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:119)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage.getAccount(BonsaiWorldStateKeyValueStorage.java:110)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.get(BonsaiPersistedWorldState.java:340)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.bonsai.BonsaiLayeredWorldState.get(BonsaiLayeredWorldState.java:232)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.lambda$validateTransaction$2(TransactionPool.java:282)
Sep 10 20:18:54 besu besu[1130]: #011at java.base/java.util.Optional.map(Optional.java:260)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateTransaction(TransactionPool.java:280)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.validateRemoteTransaction(TransactionPool.java:213)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionPool.addRemoteTransactions(TransactionPool.java:153)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:111)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageProcessor.processTransactionsMessage(TransactionsMessageProcessor.java:85)
Sep 10 20:18:54 besu besu[1130]: #011at org.hyperledger.besu.ethereum.eth.transactions.TransactionsMessageHandler.lambda$exec$0(TransactionsMessageHandler.java:48)
Sep 10 20:18:54 besu besu[1130]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Sep 10 20:18:54 besu besu[1130]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Sep 10 20:18:54 besu besu[1130]: #011at java.base/java.lang.Thread.run(Thread.java:833)
Sep 10 20:19:04 besu besu[1130]: 2022-09-10 20:19:04.274+02:00 | vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected
Sep 10 20:21:04 besu besu[1130]: 2022-09-10 20:21:04.374+02:00 | vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected
Sep 10 20:21:09 besu besu[1130]: 2022-09-10 20:21:09.750+02:00 | EthScheduler-Services-163 (importBlock) | INFO  | FullImportBlockStep | Import reached block 15508800 (0xf43725f9804582c7cac5863eb4c5ce361aba5f4c6ad7c3305ea34845cf9d481f), 8.170 Mg/s, Peers: 85
Sep 10 20:23:04 besu besu[1130]: 2022-09-10 20:23:04.475+02:00 | vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected
Sep 10 20:25:01 besu CRON[5489]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Sep 10 20:25:04 besu besu[1130]: 2022-09-10 20:25:04.575+02:00 | vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected
Sep 10 20:26:50 besu besu[1130]: 2022-09-10 20:26:50.844+02:00 | EthScheduler-Services-163 (importBlock) | INFO  | FullImportBlockStep | Import reached block 15509000 (0x2f8eb7716a21f130f5d3c75d7da30de170d7680677da9136ac1abc3875ea11ff), 9.239 Mg/s, Peers: 85`

Also seen here.

v22.7.2
X_SNAP sync
Bonsai
No consensus engine connected.

**Comment by matkt** [comment]
as long as Besu keeps importing blocks it doesn't matter. we have implemented mechanisms to make bonsai more robust and the side effect is the display of this type of log. we are going to make this stacktrace less scary

**Comment by totoCZ** [comment]
`Dec 06 11:08:59 eth-execution besu[66338]: 2022-12-06 11:08:59.389+00:00 | vert.x-worker-thread-0 | ERROR | AbstractBlockProcessor | failed persisting block
Dec 06 11:08:59 eth-execution besu[66338]: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xf91f6d2a97748199ae5d94748f5ca712e9397013aeecec42753e671a9961eba3 location 0x0d05010c02
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:133)
Dec 06 11:08:59 eth-execution besu[66338]:         at java.base/java.util.Optional.orElseThrow(Optional.java:403)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:131)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:63)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.PutVisitor.visit(PutVisitor.java:68)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:64)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.PutVisitor.visit(PutVisitor.java:68)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:64)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.PutVisitor.visit(PutVisitor.java:68)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.PutVisitor.visit(PutVisitor.java:68)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.PutVisitor.visit(PutVisitor.java:68)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:80)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.put(StoredMerklePatriciaTrie.java:142)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.addTheAccounts(BonsaiPersistedWorldState.java:167)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.calculateRootHash(BonsaiPersistedWorldState.java:139)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.persist(BonsaiPersistedWorldState.java:287)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:146)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:76)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:205)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:135)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:440)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:454)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:141)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:217)
Dec 06 11:08:59 eth-execution besu[66338]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:73)
Dec 06 11:08:59 eth-execution besu[66338]:         at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
Dec 06 11:08:59 eth-execution besu[66338]:         at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
Dec 06 11:08:59 eth-execution besu[66338]:         at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
Dec 06 11:08:59 eth-execution besu[66338]:         at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
Dec 06 11:08:59 eth-execution besu[66338]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Dec 06 11:08:59 eth-execution besu[66338]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Dec 06 11:08:59 eth-execution besu[66338]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Dec 06 11:08:59 eth-execution besu[66338]:         at java.base/java.lang.Thread.run(Thread.java:833)
Dec 06 11:08:59 eth-execution besu[66338]: 2022-12-06 11:08:59.390+00:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Unable to load trie node value for hash 0xf91f6d2a97748199ae5d94748f5ca712e9397013aeecec42753e671a9961eba3 location 0x0d05010c02]. Block 16120820 (0xf47c2076cc987771366baf838497f277cb4b13c08694f6a3cad66fd9021a1116), caused by org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0xf91f6d2a97748199ae5d94748f5ca712e9397013aeecec42753e671a9961eba3 location 0x0d05010c02`

**Comment by non-fungible-nelson** [comment]
Handling/handled this in many other bonsai related issues.
