### ISSUE TITLE
Error importing pending blocks

### ISSUE THREAD

**Issue by estensen** [hyperledger/besu#4382]
Mainnet
v22.7.2
Checkpoint sync
Bonsai
Paired with Lighthouse

```
2022-09-12 10:22:50.923+02:00 | nioEventLoopGroup-3-5 | INFO  | BlockPropagationManager | Saved announced block for future import 15519890 (0x4f3822d9483620ac0d5d937a6c7e171159dea5bfd4f63b0a5f3ada6b789c1f50) - 2 saved block(s)
2022-09-12 10:22:50.937+02:00 | EthScheduler-Workers-1 | ERROR | MainnetBlockValidator | Parent block with hash 0xfd0b06fbb4f74a1caea67396721d833a4bea597b4ea9949b051b3cfca47af02a not present. Block 15519890 (0x4f3822d9483620ac0d5d937a6c7e171159dea5bfd4f63b0a5f3ada6b789c1f50)
2022-09-12 10:22:50.939+02:00 | EthScheduler-Workers-1 | ERROR | BlockPropagationManager | Error importing pending blocks
org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #15519890 (0x4f3822d9483620ac0d5d937a6c7e171159dea5bfd4f63b0a5f3ada6b789c1f50)
	at org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.executeTask(PersistBlockTask.java:205)
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.run(AbstractEthTask.java:75)
	at org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.lambda$forUnorderedBlocks$8(PersistBlockTask.java:164)
	at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:97)
	at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleSyncWorkerTask$0(EthScheduler.java:108)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-12 10:22:58.623+02:00 | EthScheduler-Workers-3 | INFO  | PersistBlockTask | Imported #15,519,890 / 87 tx / 0 om / 4,245,257 (14.2%) gas / (0x4f3822d9483620ac0d5d937a6c7e171159dea5bfd4f63b0a5f3ada6b789c1f50) in 0.482s. Peers: 73
```

**Comment by macfarla** [comment]
Does your node stop syncing at that block @estensen or does it recover?

**Comment by estensen** [comment]
It does recover and keep syncing
