### ISSUE TITLE
besu failing to start

### ISSUE THREAD

**Issue by mwampetaipyana** [hyperledger/besu#4428]
2022-09-23 10:58:00.895+03:00 | main | INFO  | Besu | Using LibEthPairings native alt bn128
2022-09-23 10:58:00.901+03:00 | main | INFO  | Besu | Using the native implementation of the signature algorithm
2022-09-23 10:58:00.904+03:00 | main | INFO  | Besu | Starting Besu version: besu/v22.7.1/linux-x86_64/oracle-java-18
2022-09-23 10:58:01.638+03:00 | main | WARN  | Besu | --rpc-http-tls-client-auth-enabled and --rpc-http-tls-cipher-suite has been ignored because --rpc-http-tls-enabled was not defined on the command line.
2022-09-23 10:58:01.641+03:00 | main | INFO  | Besu | Static Nodes file = /home/egovridc/QBFT-Network/Node1/data/static-nodes.json
2022-09-23 10:58:01.642+03:00 | main | INFO  | StaticNodesParser | StaticNodes file /home/egovridc/QBFT-Network/Node1/data/static-nodes.json does not exist, no static connections will be created.
2022-09-23 10:58:01.642+03:00 | main | INFO  | Besu | Connecting to 0 static nodes.
2022-09-23 10:58:01.644+03:00 | main | INFO  | Besu | Security Module: localfile
2022-09-23 10:58:01.669+03:00 | main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /home/egovridc/QBFT-Network/Node1/data
2022-09-23 10:58:01.730+03:00 | main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /home/egovridc/QBFT-Network/Node1/data. Version 1
2022-09-23 10:58:04.679+03:00 | main | INFO  | KeyPairUtil | Loaded public key 0x4b34190f58faf362056ebaf927925ca17f004ea0f72a112354597997699f7a3b717f7759a93a4397c0e1cdcc1874e77b2656dc7ad8d9312efc24a7ddcee4a0c3 from /home/egovridc/QBFT-Network/Node1/data/key
2022-09-23 10:58:04.882+03:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Berlin: 0]
2022-09-23 10:58:05.014+03:00 | main | INFO  | BesuControllerBuilder | TTD difficulty is not present, creating initial sync phase for PoW
2022-09-23 10:58:05.042+03:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2022-09-23 10:58:05.489+03:00 | main | INFO  | Runner | Starting external services ... 
2022-09-23 10:58:05.490+03:00 | main | INFO  | MetricsHttpService | Starting metrics http service on 172.17.17.108:9545
2022-09-23 10:58:05.696+03:00 | vert.x-eventloop-thread-3 | INFO  | MetricsHttpService | Metrics service started and listening on 172.17.17.108:9545
2022-09-23 10:58:05.696+03:00 | main | INFO  | JsonRpcHttpService | Starting JSON-RPC service on 172.17.17.108:8545
2022-09-23 10:58:05.710+03:00 | vert.x-eventloop-thread-3 | INFO  | JsonRpcHttpService | JSON-RPC service started and listening on 172.17.17.108:8545
2022-09-23 10:58:05.712+03:00 | vert.x-eventloop-thread-3 | ERROR | ContextImpl | Unhandled exception
java.lang.IllegalStateException: Cannot call requestPortForward() when in stopped state
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at org.hyperledger.besu.nat.upnp.UpnpNatManager.requestPortForward(UpnpNatManager.java:283)
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$start$0(JsonRpcHttpService.java:243)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.hyperledger.besu.nat.NatService.ifNatEnvironment(NatService.java:70)
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$start$1(JsonRpcHttpService.java:239)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
	at io.vertx.core.impl.future.FixedMapping.onSuccess(FixedMapping.java:31)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-09-23 10:58:05.713+03:00 | main | INFO  | AutoTransactionLogBloomCachingService | Starting auto transaction log bloom caching service.
2022-09-23 10:58:05.714+03:00 | main | INFO  | LogBloomCacheMetadata | Lookup cache metadata file in data directory: /home/egovridc/QBFT-Network/Node1/data/caches
2022-09-23 10:58:05.731+03:00 | main | INFO  | Runner | Starting Ethereum main loop ... 
2022-09-23 10:58:05.732+03:00 | main | INFO  | UpnpNatManager | Starting UPnP Service
2022-09-23 10:58:05.732+03:00 | main | INFO  | UpnpServiceImpl | Starting UPnP service...
2022-09-23 10:58:05.776+03:00 | main | INFO  | Router | Configuration did not create a StreamServer for: /172.17.17.108
2022-09-23 10:58:06.126+03:00 | main | INFO  | NetworkRunner | Starting Network.
2022-09-23 10:58:06.133+03:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /172.17.17.108:1234.
2022-09-23 10:58:06.134+03:00 | main | ERROR | Runner | unable to start main loop
java.lang.IllegalArgumentException: Cannot map to internal port zero.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.hyperledger.besu.nat.upnp.UpnpNatManager.requestPortForward(UpnpNatManager.java:284)
	at org.hyperledger.besu.ethereum.p2p.network.DefaultP2PNetwork.lambda$start$3(DefaultP2PNetwork.java:249)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.hyperledger.besu.nat.NatService.ifNatEnvironment(NatService.java:70)
	at org.hyperledger.besu.ethereum.p2p.network.DefaultP2PNetwork.start(DefaultP2PNetwork.java:255)
	at org.hyperledger.besu.ethereum.p2p.network.NetworkRunner.start(NetworkRunner.java:80)
	at org.hyperledger.besu.Runner.startEthereumMainLoop(Runner.java:139)
	at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1436)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2559)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:54)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:31)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2559)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1591)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1393)
	at org.hyperledger.besu.Besu.main(Besu.java:49)
Startup failed

To display full help:
besu [COMMAND] --help
2022-09-23 10:58:06.141+03:00 | BesuCommand-Shutdown-Hook | ERROR | Besu | Failed to stop Besu

**Comment by daniellehrner** [comment]
Which config options are you using? It seems one of the ports is set to zero

```
 java.lang.IllegalArgumentException: Cannot map to internal port zero.
```

**Comment by mwampetaipyana** [comment]
here are my configurations 
# Valid TOML config file
data-path="/home/user/QBFT-Network/Node1/data" # Path

# Network

nat-method="UPNP" 

discovery-enabled=false

p2p-enabled=true

p2p-host="172.17.17.108"

p2p-interface="172.17.17.108"

p2p-port=1234

max-peers=42

rpc-http-host="172.17.17.108"

rpc-http-enabled=true

rpc-http-api=["ETH","NET","QBFT"]

host-allowlist=["172.17.17.165","172.17.17.108","172.17.17.55","172.17.17.83","172.17.17.88"]

rpc-http-cors-origins=["172.17.17.165","172.17.17.108","172.17.17.55","chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn","http://remix.ethereum.org","172.17.17.83","172.17.17.88"]

rpc-http-max-active-connections=10

rpc-http-port=8545

rpc-http-tls-client-auth-enabled=true

rpc-http-tls-cipher-suite=["TLS_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]

rpc-http-tls-enabled=false

rpc-ws-enabled=false

sync-mode="FULL"

metrics-host="172.17.17.108"

metrics-port="9545"

metrics-protocol="PROMETHEUS"

metrics-enabled=true

metrics-category=["BLOCKCHAIN","PEERS","PROCESS"]

# Chain
genesis-file="/home/user/QBFT-Network/genesis.json" # Path to the custom genesis file

# Mining
miner-enabled=true
miner-coinbase="0x0000000000000000000000000000000000000000"
min-gas-price=0

**Comment by EdwardPrentice** [comment]
Can you try with
`metrics-port="9545"` changed to `metrics-port=9545`?

I'm suspicious that setting the port value to a string makes it equal to 0. If this is the case perhaps Besu could make an attempt to do a string -> int conversion if the value is a number.

**Comment by mwampetaipyana** [comment]
thank you very much its currently working smoothly
regards

**Comment by macfarla** [comment]
good to hear!
