### ISSUE TITLE
The provided --p2p-interface is not available

### ISSUE THREAD

**Issue by binny1024** [hyperledger/besu#4609]
### Description
As an [Actor], I want [feature] so that [why]. 
picocli.CommandLine$ParameterException: The provided --p2p-interface is not available:[public ip]
	at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1439)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:54)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:32)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1609)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1388)
	at org.hyperledger.besu.Besu.main(Besu.java:48)
Caused by: picocli.CommandLine$ParameterException: The provided --p2p-interface is not available: [public ip]
	at org.hyperledger.besu.cli.BesuCommand.validateP2PInterface(BesuCommand.java:1790)
	at org.hyperledger.besu.cli.BesuCommand.validateOptions(BesuCommand.java:1751)
	at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1421)
	... 16 more

To display full help:
besu [COMMAND] --help
### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

**Comment by gfukushima** [comment]
Hi @heifuni would be able to share the configuration or cli parameters you're using?

**Comment by binny1024** [comment]
Sorry, it's been a little long in the past, next time I meet, I'll send it to you again, thank you

**Comment by non-fungible-nelson** [comment]
Will close this for now - @binny1024 please re-open the issue if its still occuring.
