### ISSUE TITLE
P2P MTLS not able to connect to chain certificates (without root in truststore)

### ISSUE THREAD

**Issue by daragao** [hyperledger/besu#4695]
### Description
I am creating a Besu private network with uses the P2P MTLS.

I have been able to connect nodes in the following situations:
- Self signed certificates are used in the keystore and truststore
- Chain Certificates are used in the keystore and Root Certificates are used in the truststore

I am unable to setup the following:
- Chain Certificate in keystore. Only Sender Certificate on the truststore (no root certificate).

The reason why I don't want to use the root certificate in the truststore is because that will allow P2P connections  from any certificate signed by that root. I have tested this behavior.

To be clear, I am using a chain that has a Sender Certificate + Intermediate Certificate + Root Certificate.

### Steps to Reproduce (Bug)
1. Setup Network with MTLS P2P
2. Use a chain certificate on the keystore
3. Use a single certificate on the truststore

**Expected behavior:**
Connection without errors.

**Actual behavior:**
There is an SSLHandshake Exception between the nodes, pasting logs bellow:

```
2022-11-16 23:12:29.909+00:00 | nioEventLoopGroup-3-6 | INFO  | TLSContextFactory | Initializing SSL Context using PKCS12 keystore.
2022-11-16 23:12:29.909+00:00 | nioEventLoopGroup-3-8 | INFO  | TLSContextFactory | Initializing SSL Context using PKCS12 keystore.
2022-11-16 23:12:29.909+00:00 | nioEventLoopGroup-3-7 | INFO  | TLSContextFactory | Initializing SSL Context using PKCS12 keystore.
2022-11-16 23:12:30.029+00:00 | nioEventLoopGroup-3-6 | DEBUG | SslHandler | [id: 0x05b1512f, L:/10.88.153.89:35048 - R:/10.88.109.1:30303] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
2022-11-16 23:12:30.029+00:00 | nioEventLoopGroup-3-6 | DEBUG | HandshakeHandlerOutbound | Wrote initial crypto handshake message to /10.88.109.1:30303.
2022-11-16 23:12:30.030+00:00 | nioEventLoopGroup-3-6 | DEBUG | AbstractHandshakeHandler | Handshake error:
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
 at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
 at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
 at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:688)
 at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:643)
 at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:461)
 at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:440)
 at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
 at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295)
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
 ... 17 more
2022-11-16 23:12:30.030+00:00 | nioEventLoopGroup-3-6 | DEBUG | RlpxAgent | Failed to connect to peer 0x832e45315e98a7641cf139be160734ffd1899714c2855e89b4a209dc216226d88e46ed7c48203b65289a15c75194cacef5b3715d35d488bd73c84faaea4b326f: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
2022-11-16 23:12:30.071+00:00 | nioEventLoopGroup-3-8 | DEBUG | SslHandler | [id: 0x7556f4f2, L:/10.88.153.89:60576 - R:/10.88.144.48:30303] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
2022-11-16 23:12:30.071+00:00 | nioEventLoopGroup-3-8 | DEBUG | HandshakeHandlerOutbound | Wrote initial crypto handshake message to /10.88.144.48:30303.
2022-11-16 23:12:30.071+00:00 | nioEventLoopGroup-3-8 | DEBUG | AbstractHandshakeHandler | Handshake error:
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
 at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
 at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
 at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:688)
 at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:643)
 at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:461)
 at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:440)
 at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
 at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295)
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
 ... 17 more
2022-11-16 23:12:30.072+00:00 | nioEventLoopGroup-3-8 | DEBUG | RlpxAgent | Failed to connect to peer 0x064f2765641c0dc6c4e8e9a433ada36e01b001ae93be142aa94d7286e97217dcf90cc0b5e5471f6ade0a11285ee04627d97fbbb17a28d76eb66cbada937c0eb0: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
2022-11-16 23:12:30.077+00:00 | nioEventLoopGroup-3-7 | DEBUG | SslHandler | [id: 0x3eabd8a9, L:/10.88.153.89:43672 - R:/10.88.163.0:30303] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
2022-11-16 23:12:30.077+00:00 | nioEventLoopGroup-3-7 | DEBUG | HandshakeHandlerOutbound | Wrote initial crypto handshake message to /10.88.163.0:30303.
2022-11-16 23:12:30.078+00:00 | nioEventLoopGroup-3-7 | DEBUG | AbstractHandshakeHandler | Handshake error:
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
 at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
 at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
 at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:688)
 at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:643)
 at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:461)
 at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:440)
 at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
 at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295)
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
 ... 17 more
2022-11-16 23:12:30.078+00:00 | nioEventLoopGroup-3-7 | DEBUG | RlpxAgent | Failed to connect to peer 0xef07c06ba62fde3d2bc4671310f9dc4ec68a51bd83a1635c414146c2428ed5aec57a36cba48f9249cf7a2929393979eb411a0c6ef0bed77914860f29a5f0bcdb: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
2022-11-16 23:12:30.674+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 0
2022-11-16 23:12:30.674+00:00 | EthScheduler-Timer-0 | DEBUG | WaitForPeerTask | Waiting for new peer connection. 0 peers currently connected.
```

**Frequency:** 
Always happens

### Versions (Add all that apply)
* Software version: `besu-22.1.3`
* Java version: JDK 11
* OS Name & Version: AWS ECS Linux

### Additional Information (Add any of the following or anything else that may be relevant)
I am using an old version of Besu, but really need that version.

**Comment by macfarla** [comment]
if you really need a fix in an old version, you're welcome to fork, fix and maintain - this is an open source project!
