### ISSUE TITLE
OpenTelemetry double-init error

### ISSUE THREAD

**Issue by holiman** [hyperledger/besu#4714]
commit 1fa65fb944db18e486145f3a67886679b124bb6c
```
$ ./besu/ethereum/evmtool/build/install/evmtool/bin/evm --version
Hyperledger Besu EvmTool
besu/v22.10.1-dev-1fa65fb9/linux-x86_64/openjdk-java-17
```
```
$ ./besu/ethereum/evmtool/build/install/evmtool/bin/evm --code 6001 
java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead. Previous invocation set to cause of this exception.
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:99)
	at org.hyperledger.besu.metrics.MetricsSystemFactory.disableGlobalOpenTelemetry(MetricsSystemFactory.java:38)
	at org.hyperledger.besu.metrics.MetricsSystemFactory.create(MetricsSystemFactory.java:50)
	at org.hyperledger.besu.evmtool.MetricsSystemModule.getMetricsSystem(MetricsSystemModule.java:32)
	at org.hyperledger.besu.evmtool.MetricsSystemModule_GetMetricsSystemFactory.getMetricsSystem(MetricsSystemModule_GetMetricsSystemFactory.java:39)
	at org.hyperledger.besu.evmtool.MetricsSystemModule_GetMetricsSystemFactory.get(MetricsSystemModule_GetMetricsSystemFactory.java:31)
	at org.hyperledger.besu.evmtool.MetricsSystemModule_GetMetricsSystemFactory.get(MetricsSystemModule_GetMetricsSystemFactory.java:11)
	at org.hyperledger.besu.evmtool.BlockchainModule_ProvideBlockchainFactory.get(BlockchainModule_ProvideBlockchainFactory.java:46)
	at org.hyperledger.besu.evmtool.BlockchainModule_ProvideBlockchainFactory.get(BlockchainModule_ProvideBlockchainFactory.java:15)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.hyperledger.besu.evmtool.BlockchainModule_ProvideStateRootFactory.get(BlockchainModule_ProvideStateRootFactory.java:41)
	at org.hyperledger.besu.evmtool.BlockchainModule_ProvideStateRootFactory.get(BlockchainModule_ProvideStateRootFactory.java:14)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.hyperledger.besu.evmtool.BlockchainModule_GetMutableWorldStateFactory.get(BlockchainModule_GetMutableWorldStateFactory.java:54)
	at org.hyperledger.besu.evmtool.BlockchainModule_GetMutableWorldStateFactory.get(BlockchainModule_GetMutableWorldStateFactory.java:16)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.hyperledger.besu.evmtool.BlockchainModule_ProvideWorldUpdaterFactory.get(BlockchainModule_ProvideWorldUpdaterFactory.java:37)
	at org.hyperledger.besu.evmtool.BlockchainModule_ProvideWorldUpdaterFactory.get(BlockchainModule_ProvideWorldUpdaterFactory.java:13)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.hyperledger.besu.evmtool.DaggerEvmToolComponent$EvmToolComponentImpl.getWorldUpdater(DaggerEvmToolComponent.java:206)
	at org.hyperledger.besu.evmtool.EvmToolCommand.run(EvmToolCommand.java:246)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.hyperledger.besu.evmtool.EvmToolCommand.parse(EvmToolCommand.java:164)
	at org.hyperledger.besu.evmtool.EvmTool.main(EvmTool.java:26)
Caused by: java.lang.Throwable
	at io.opentelemetry.api.GlobalOpenTelemetry.set(GlobalOpenTelemetry.java:107)
	at org.hyperledger.besu.metrics.MetricsSystemFactory.disableGlobalOpenTelemetry(MetricsSystemFactory.java:38)
	at org.hyperledger.besu.metrics.MetricsSystemFactory.create(MetricsSystemFactory.java:50)
	at org.hyperledger.besu.evmtool.MetricsSystemModule.getMetricsSystem(MetricsSystemModule.java:32)
	at org.hyperledger.besu.evmtool.MetricsSystemModule_GetMetricsSystemFactory.getMetricsSystem(MetricsSystemModule_GetMetricsSystemFactory.java:39)
	at org.hyperledger.besu.evmtool.MetricsSystemModule_GetMetricsSystemFactory.get(MetricsSystemModule_GetMetricsSystemFactory.java:31)
	at org.hyperledger.besu.evmtool.MetricsSystemModule_GetMetricsSystemFactory.get(MetricsSystemModule_GetMetricsSystemFactory.java:11)
	at org.hyperledger.besu.evmtool.DataStoreModule_ProvideBlockchainKeyValueStorageFactory.get(DataStoreModule_ProvideBlockchainKeyValueStorageFactory.java:46)
	at org.hyperledger.besu.evmtool.DataStoreModule_ProvideBlockchainKeyValueStorageFactory.get(DataStoreModule_ProvideBlockchainKeyValueStorageFactory.java:14)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at org.hyperledger.besu.evmtool.DataStoreModule_ProvideBlockchainStorageFactory.get(DataStoreModule_ProvideBlockchainStorageFactory.java:39)
	at org.hyperledger.besu.evmtool.DataStoreModule_ProvideBlockchainStorageFactory.get(DataStoreModule_ProvideBlockchainStorageFactory.java:14)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
```

**Comment by non-fungible-nelson** [comment]
Is this still open?

**Comment by atoulme** [comment]
This is now fixed. Closing.
