### ISSUE TITLE
Besu loses sync on Goerli, `Critical Exception Processing Transaction`

### ISSUE THREAD

**Issue by yorickdowne** [hyperledger/besu#4755]
### Description

Besu loses sync. It's an alpha version, this bug may already have been fixed.

teku/v22.10.2/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17

besu/v22.10.1-alpha/linux-x86_64/openjdk-java-17

### Logs

```
execution_1                  | 2022-11-19 12:26:01.247+00:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Imported #7,981,304 / 69 tx / base fee 5.75 gwei / 23,929,507 (79.8%) gas / (0xf8e8b5f234ee2fed7bf568aedabded749d99c0c6fc8030e49751abf41cebc208) in 0.687s. Peers: 25
execution_1                  | 2022-11-19 12:26:02.310+00:00 | vert.x-worker-thread-0 | INFO  | EngineNewPayload | Imported #7,981,304 / 101 tx / base fee 5.75 gwei / 27,237,156 (90.8%) gas / (0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1) in 1.060s. Peers: 25
execution_1                  | 2022-11-19 12:26:37.433+00:00 | vert.x-worker-thread-0 | ERROR | MainnetTransactionProcessor | Critical Exception Processing Transaction
execution_1                  | org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x44eeeb3c18b3d55d7b6788ff84496454fb42d1d8a09ce8d37aa80831f1f4314a location 0x
execution_1                  |  at org.hyperledger.besu.ethereum.trie.StoredNode.lambda$load$0(StoredNode.java:133)
execution_1                  |  at java.base/java.util.Optional.orElseThrow(Optional.java:403)
execution_1                  |  at org.hyperledger.besu.ethereum.trie.StoredNode.load(StoredNode.java:131)
execution_1                  |  at org.hyperledger.besu.ethereum.trie.StoredNode.accept(StoredNode.java:63)
execution_1                  |  at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.get(StoredMerklePatriciaTrie.java:119)
execution_1                  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateKeyValueStorage.getStorageValueBySlotHash(BonsaiWorldStateKeyValueStorage.java:200)
execution_1                  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiPersistedWorldState.getStorageValueBySlotHash(BonsaiPersistedWorldState.java:404)
execution_1                  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValueBySlotHash(BonsaiWorldStateUpdater.java:332)
execution_1                  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValue(BonsaiWorldStateUpdater.java:319)
execution_1                  |  at org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.getStorageValue(BonsaiAccount.java:208)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:213)
execution_1                  |  at org.hyperledger.besu.evm.operation.SLoadOperation.execute(SLoadOperation.java:58)
execution_1                  |  at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:282)
execution_1                  |  at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:161)
execution_1                  |  at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:173)
execution_1                  |  at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:492)
execution_1                  |  at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:404)
execution_1                  |  at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:104)
execution_1                  |  at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:76)
execution_1                  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:198)
execution_1                  |  at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:128)
execution_1                  |  at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:450)
execution_1                  |  at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:464)
execution_1                  |  at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:141)
execution_1                  |  at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.EngineNewPayload.syncResponse(EngineNewPayload.java:224)
execution_1                  |  at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:73)
execution_1                  |  at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
execution_1                  |  at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
execution_1                  |  at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
execution_1                  |  at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
execution_1                  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
execution_1                  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
execution_1                  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
execution_1                  |  at java.base/java.lang.Thread.run(Thread.java:833)
b6788ff84496454fb42d1d8a09ce8d37aa80831f1f4314a location 0x. Block 0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640 Transaction 0xfb25b05b2beb5b440848f4c2d555cc222244adfd033603457926890e72d56722
execution_1                  | 2022-11-19 12:26:37.436+00:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Optional[Block processing error: transaction invalid Internal Error in Besu - org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x44eeeb3c18b3d55d7b6788ff84496454fb42d1d8a09ce8d37aa80831f1f4314a location 0x. Block 0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640 Transaction 0xfb25b05b2beb5b440848f4c2d555cc222244adfd033603457926890e72d56722]. Block 7981305 (0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640)
execution_1                  | 2022-11-19 12:26:37.437+00:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 7981305, hash: 0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640, parentHash: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, latestValidHash: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, status: INVALID, validationError: Block processing error: transaction invalid Internal Error in Besu - org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x44eeeb3c18b3d55d7b6788ff84496454fb42d1d8a09ce8d37aa80831f1f4314a location 0x. Block 0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640 Transaction 0xfb25b05b2beb5b440848f4c2d555cc222244adfd033603457926890e72d56722
execution_1                  | 2022-11-19 12:26:40.095+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:27:52.071+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:29:04.067+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:30:16.071+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:31:28.063+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:32:40.061+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:33:49.566+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:34:00.163+00:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 7981305, hash: 0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640, parentHash: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, status: INVALID, validationError: Block already present in bad block manager.
execution_1                  | 2022-11-19 12:35:00.065+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | VALID for fork-choice-update: head: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, finalized: 0x9d53df136627cb12ac1f3288475f5a3e6a0745d9993c21a26bebedf9d1297dad, safeBlockHash: 0xfc1549145e18aa890d94d775ea23a454ed36b174af9c13dc4788879d21710cba
execution_1                  | 2022-11-19 12:35:18.986+00:00 | vert.x-worker-thread-0 | WARN  | EngineNewPayload | Invalid new payload: number: 7981305, hash: 0x3afbe413b21547733d807b02e2382448239c2687fd444d2cabaa3d488486d640, parentHash: 0xe77a098b0b7d64b027d45101964321dfd6de780a874140c2107e72ce736869c1, latestValidHash: 0x0000000000000000000000000000000000000000000000000000000000000000, status: INVALID, validationError: Block already present in bad block manager.
```

It recovered from this with a restart on 22.10.0. No debug logs alas. This is server hardware w/ ECC RAM, I am assuming a software issue.

**Comment by non-fungible-nelson** [comment]
Hey @yorickdowne - was this behavior with `--Xbonsai-use-snapshots=true` on 22.10.2?

**Comment by yorickdowne** [comment]
@non-fungible-nelson I want to say yes. I've removed that parameter by now.

**Comment by non-fungible-nelson** [comment]
Ok - thanks for the report. We are updating our messaging about this experimental flag to be only used in an attempt to recover a node in a bad state and not for normal operation until we can iron out the behavior. on 22.10.2 we are slowly porting over the parts from snapshots to our default behavior and with this flag it can conflict. Closing for now, as we are tracking this issue here - #4785
