### ISSUE TITLE
Investigate UpnpManager StreamServer message

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#483]
When running pantheon with `--nat-method=UPNP`, I'm seeing the following message printed: "2019-07-19 15:03:14.435-04:00 | main | INFO | Router | Configuration did not create a StreamServer for: /10.1.10.39 
". This message originates from the PantheonUpnpServiceConfiguration.createStreamServer().

The stack trace (retrieved by adding the line new RuntimeException()).printStackTrace(); to this method) from this method invocation is:

```
{{}}

java.lang.RuntimeException at tech.pegasys.pantheon.nat.upnp.PantheonUpnpServiceConfiguration.createStreamServer(PantheonUpnpServiceConfiguration.java:142) at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:416) at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:125) at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:258) at tech.pegasys.pantheon.nat.upnp.UpnpNatManager.start(UpnpNatManager.java:118) at tech.pegasys.pantheon.Runner.start(Runner.java:80) at tech.pegasys.pantheon.cli.PantheonCommand.synchronize(PantheonCommand.java:1205) at tech.pegasys.pantheon.cli.PantheonCommand.startSynchronization(PantheonCommand.java:753) at tech.pegasys.pantheon.cli.PantheonCommand.run(PantheonCommand.java:667) at picocli.CommandLine.execute(CommandLine.java:1160) at picocli.CommandLine.access$800(CommandLine.java:141) at picocli.CommandLine$RunLast.handle(CommandLine.java:1367) at picocli.CommandLine$RunLast.handle(CommandLine.java:1335) at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) at tech.pegasys.pantheon.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:59) at tech.pegasys.pantheon.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:29) at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:748) at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:659) at tech.pegasys.pantheon.Pantheon.main(Pantheon.java:45)

```

**Comment by timbeiko** [comment]
This has been stale for >1 year. Closing for now. Feel free to copy/paste in a new issue if relevant. cc: @sajz
