### ISSUE TITLE
CPU usage spikes on a synced node

### ISSUE THREAD

**Issue by ahamlat** [hyperledger/besu#4838]
### Description
Some users reported random CPU spikes on a Besu synced nodes.
Below some of the graphs shared by users :
<img width="514" alt="image" src="https://user-images.githubusercontent.com/5099602/208393906-e4a4eacf-16fc-46b8-b374-51014bb8baa6.png">

<img width="524" alt="image" src="https://user-images.githubusercontent.com/5099602/208394121-e5132f72-5a82-4f1f-aa6c-efc96ddb023e.png">

Two different users shared graphs that show a link between these CPU peaks and the increase of number of pooled transactions.
Analysing a thread dump during this CPU peak usage, I noticed that one of the threads is running this part of the code, and holding a lock making 3 other threads waiting for this lock. This could mean that this thread was running for some time.

```
java.lang.Thread.State: RUNNABLE
at java.util.stream.AbstractPipeline.evaluate(java.base@17.0.5/AbstractPipeline.java:234)
at java.util.stream.IntPipeline.reduce(java.base@17.0.5/IntPipeline.java:515)
at java.util.stream.IntPipeline.sum(java.base@17.0.5/IntPipeline.java:473)
at org.hyperledger.besu.ethereum.eth.manager.EthPeer.outstandingRequests(EthPeer.java:524)
at org.hyperledger.besu.ethereum.eth.manager.EthPeer.hasAvailableRequestCapacity(EthPeer.java:532)
```
This part of the code calculates (sum) the number of outstanding requests and it takes into account those from pooled transactions.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/5099602/208396916-3b2a7665-bd5c-4b70-8320-db90c0f7471b.png">

### Steps to Reproduce (Bug)
* It is hard to reproduce, it could be part of the resolution of this issue.

**Expected behavior:** [What you expect to happen]
* Besu has a stable CPU consumption on synced node.

**Actual behavior:** [What actually happens]
* Besu has some random spikes in CPU usage

**Frequency:** [What percentage of the time does it occur?]
This issue is not frequent but some users seem to reproduce more than others, may be related to the use case. 

### Versions (Add all that apply)
* Software version: 22.10.3
* Java version: OpenJDK 64-Bit Server VM (17.0.5+8-Ubuntu-2ubuntu122.04 mixed mode, sharing)
* OS Name & Version: ubuntu 22.04

**Comment by ahamlat** [comment]
Adding here some profiling metrics that confirm the first observation. We're analysing this to understand why it consumes a lot of CPU.

<img width="1717" alt="image" src="https://user-images.githubusercontent.com/5099602/208754687-35f02389-d2dd-4554-a2db-bc878bac39bb.png">
