### ISSUE TITLE
Flaky test - ChainDataPrunerTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#4856]
https://app.circleci.com/pipelines/github/hyperledger/besu/19175/workflows/6b25b9c3-39dc-4ab9-9f20-a1026fc2ca79/jobs/116796/tests#failed-test-0

```
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.hyperledger.besu.ethereum.chain.ChainDataPrunerTest that uses org.hyperledger.besu.ethereum.chain.MutableBlockchain, org.hyperledger.besu.ethereum.chain.MutableBlockchainjava.util.List, java.util.Listint was not fulfilled within 50 milliseconds.
	at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
	at app//org.hyperledger.besu.ethereum.chain.ChainDataPrunerTest.forkPruning(ChainDataPrunerTest.java:128)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
```

**Comment by macfarla** [comment]
closing this - have not seen it fail at all.
