### ISSUE TITLE
Investigate Decoder Exception found on Ropsten full sync node

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#506]
```
2019-09-04 19:21:34.520+00:00 | nioEventLoopGroup-3-1 | ERROR | DeFramer | Exception while processing incoming messageio.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid node id.  Expected id of length: 64 bytes.at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.34.Final.jar:4.1.34.Final]at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.34.Final.jar:4.1.34.Final]at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar:4.1.34.Final]at java.lang.Thread.run(Thread.java:834) [?:?]Caused by: java.lang.IllegalArgumentException: Invalid node id.  Expected id of length: 64 bytes.at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-28.0-jre.jar:?]at tech.pegasys.pantheon.ethereum.p2p.peers.EnodeURL.<init>(EnodeURL.java:49) ~[pantheon-p2p-1.2.2.jar:1.2.2]at tech.pegasys.pantheon.ethereum.p2p.peers.EnodeURL$Builder.build(EnodeURL.java:257) ~[pantheon-p2p-1.2.2.jar:1.2.2]at tech.pegasys.pantheon.ethereum.p2p.rlpx.connections.netty.DeFramer.createPeer(DeFramer.java:200) ~[pantheon-p2p-1.2.2.jar:1.2.2]at tech.pegasys.pantheon.ethereum.p2p.rlpx.connections.netty.DeFramer.decode(DeFramer.java:127) ~[pantheon-p2p-1.2.2.jar:1.2.2]at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.34.Final.jar:4.1.34.Final]... 16 more
```

Probability: Remote

Severity: Marginal

**Comment by timbeiko** [comment]
Can't reproduce
