### ISSUE TITLE
Unable to recover after worldstate database issue

### ISSUE THREAD

**Issue by tiagocmachado** [hyperledger/besu#5125]
### Description
```Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.044+00:00 | PoS-Block-Builder-0 | INFO  | DefaultSynchronizer |
Feb 22 17:40:02  besu[2293926]: ####################################################################################################
Feb 22 17:40:02  besu[2293926]: #                                                                                                  #
Feb 22 17:40:02  besu[2293926]: # Besu has identified a problem with its worldstate database.                                      #
Feb 22 17:40:02  besu[2293926]: # Your node will fetch the correct data from peers to repair the problem.                          #
Feb 22 17:40:02  besu[2293926]: # Starting the sync pipeline...                                                                    #
Feb 22 17:40:02  besu[2293926]: #                                                                                                  #
Feb 22 17:40:02  besu[2293926]: ####################################################################################################
Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.045+00:00 | PoS-Block-Builder-0 | INFO  | TransactionPoolFactory | Disabling transaction handling during re-sync
Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.048+00:00 | PoS-Block-Builder-0 | WARN  | BonsaiWorldStateArchive | Invalid node for account 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 at location 0x
Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.174+00:00 | PoS-Block-Builder-0 | INFO  | DefaultSynchronizer | Starting synchronizer.
Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.174+00:00 | PoS-Block-Builder-0 | INFO  | FastSyncDownloader | Starting sync
Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.201+00:00 | PoS-Block-Builder-0 | WARN  | MergeCoordinator | Block 0x79cc23a8748c1bc32a46de0756174a0623c06620791fb3db22575b4fce103d42 built for proposal identified by 0x0019b5d189a74885, is not valid reason Optional[Unable to load trie node value for hash 0x05378128769b8e4878cdca04aa5bff604a88306aab6afe970158591842391ca4 location 0x]
Feb 22 17:40:02  besu[2293926]: 2023-02-22 17:40:02.201+00:00 | PoS-Block-Builder-0 | WARN  | MergeCoordinator | caused by
Feb 22 17:40:02  besu[2293926]: org.hyperledger.besu.ethereum.trie.MerkleTrieException: Unable to load trie node value for hash 0x05378128769b8e4878cdca04aa5bff604a88306aab6afe970158591842391ca4 location 0x
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValueBySlotHash(BonsaiWorldStateUpdater.java:418)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateUpdater.getStorageValue(BonsaiWorldStateUpdater.java:375)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.bonsai.BonsaiAccount.getStorageValue(BonsaiAccount.java:208)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:231)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:231)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:231)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.worldstate.UpdateTrackingAccount.getStorageValue(UpdateTrackingAccount.java:231)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.operation.SLoadOperation.execute(SLoadOperation.java:64)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:307)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:174)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:192)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:495)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:405)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:110)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:78)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:218)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:135)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:477)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.evaluateNewBlock(MergeCoordinator.java:394)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.recoverableBlockCreation(MergeCoordinator.java:374)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.retryBlockCreationUntilUseful(MergeCoordinator.java:349)
Feb 22 17:40:02  besu[2293926]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.lambda$tryToBuildBetterBlock$5(MergeCoordinator.java:324)
Feb 22 17:40:02  besu[2293926]:         at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
Feb 22 17:40:02  besu[2293926]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Feb 22 17:40:02  besu[2293926]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Feb 22 17:40:02  besu[2293926]:         at java.base/java.lang.Thread.run(Thread.java:833)
Feb 22 17:40:05  besu[2293926]: 2023-02-22 17:40:05.992+00:00 | nioEventLoopGroup-3-5 | INFO  | SnapWorldStateDownloader | Downloading world state from peers for pivot block 16685482 (0x24621a3f3244fc8a56a3e43c64b473fb5d480f5f88a8e2b8f24787d0a03e7197). State root 0xe2832af17f9c6ecacbc2f007fcf0931596c65a56a90d23d06e67f4b4d8a8ce46 pending requests 0
Feb 22 17:40:06  besu[2293926]: pure virtual method called
Feb 22 17:40:06  besu[2293926]: terminate called without an active exception
```

After the message above the node got stuck with the following error Invalid Block:
```
Feb 22 18:01:00 besu[2332961]: 2023-02-22 18:01:00.521+00:00 | nioEventLoopGroup-3-6 | INFO  | MainnetBlockValidator | Invalid block 16685512 (0x4bc825d559d74804787bbac90ef9e2b8778b85d2c536d57c8eb3c9eeb53c251c): Optional[World State Root does not match expected value, header 0xc08f00d346865520c2790ded1b040b42d9be89a4c61c4d3dd9a8cb19f65703c0 calculated 0x484bf5f88155a3e162bf00d29bf4e256268ef3d7773f7e7dbb11c77b09f9ca18], caused by java.lang.RuntimeException: World State Root does not match expected value, header 0xc08f00d346865520c2790ded1b040b42d9be89a4c61c4d3dd9a8cb19f65703c0 calculated 0x484bf5f88155a3e162bf00d29bf4e256268ef3d7773f7e7dbb11c77b09f9ca18
```

### Versions (Add all that apply)
* Software version: v23.1.0
* Java version: 
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)
* OS Name & Version:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by matkt** [comment]
just to know did you tried to restart besu ?

and could you give the configuration of your Besu node ?

**Comment by matkt** [comment]
It maybe related to the fix I added recently in the main branch https://github.com/hyperledger/besu/commit/17455d62e9a8179eae775e66e51ef4c0e7b96882
I think running this commit can help you if you are ok to run a non released version

**Comment by tiagocmachado** [comment]
> just to know did you tried to restart besu ?
> 
> and could you give the configuration of your Besu node ?

Yes after restart I just got stuck with the following:
```Feb 22 18:01:00 besu[2332961]: 2023-02-22 18:01:00.521+00:00 | nioEventLoopGroup-3-6 | INFO  | MainnetBlockValidator | Invalid block 16685512 (0x4bc825d559d74804787bbac90ef9e2b8778b85d2c536d57c8eb3c9eeb53c251c): Optional[World State Root does not match expected value, header 0xc08f00d346865520c2790ded1b040b42d9be89a4c61c4d3dd9a8cb19f65703c0 calculated 0x484bf5f88155a3e162bf00d29bf4e256268ef3d7773f7e7dbb11c77b09f9ca18], caused by java.lang.RuntimeException: World State Root does not match expected value, header 0xc08f00d346865520c2790ded1b040b42d9be89a4c61c4d3dd9a8cb19f65703c0 calculated 0x484bf5f88155a3e162bf00d29bf4e256268ef3d7773f7e7dbb11c77b09f9ca18```


The relevant config is:

besu   --network=mainnet --sync-mode=X_CHECKPOINT  --data-storage-format=BONSAI  --metrics-enabled=true  --Xplugin-rocksdb-high-spec-enabled

**Comment by matkt** [comment]
closed this must be fixed in the last release

**Comment by aggcastro** [comment]
Hello, I am having the same issue on version 24.5.2 in a private network with 6 nodes using QBFT. Here are the version details:

- OpenJDK:

openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13-Ubuntu-123.10.1)
OpenJDK 64-Bit Server VM (build 21.0.2+13-Ubuntu-123.10.1, mixed mode, sharing)
besu/v24.5.2/linux-x86_64/openjdk-java-21

- Kernel version:
5.10.216-204.855.amzn2.x86_64

- SO:
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL=https://www.ubuntu.com
SUPPORT_URL=https://help.ubuntu.com
BUG_REPORT_URL=https://bugs.launchpad.net/ubuntu
PRIVACY_POLICY_URL=https://www.ubuntu.com/legal/terms-and-policies/privacy-policy
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo

Additionally, the node is deployed in a k8s cluster on AWS via a Docker container.

Thanks in advance.
