### ISSUE TITLE
Exception when calling RO contract methods with `23.1.0`

### ISSUE THREAD

**Issue by ibhagwan** [hyperledger/besu#5139]
### Description
Since the upgrade to `23.1.0` simple read-only contract calls fail with both JsonRpc and websocket provider (works perfectly when downgrading to `22.10.3`)

### Steps to Reproduce (Bug)
Using ethers.js (v5.7.2) for simplicity but this fails the same way using rust with ethers-rs, run this on a goerli connected node :

> For some reason the sushiswap fails more consistently but both would fail randomly (alot) which doesn't happen on the same node when downgrading to `22.10.3`
```js
  // const provider = new ethers.providers.WebSocketProvider("ws://localhost:8546");
  const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545");
  const get = async (addr) => {
    const contract = new ethers.Contract(
      addr,
      [ "function WETH() external pure returns (address)",
        "function factory() external view returns (address)" ],
      provider
    );
    let weth = await contract.WETH().catch((err) => { console.log("WETH err", err); });
    let factory = await contract.factory().catch((err) => { console.log("factory err", err); });
    console.log(addr, "WETH", weth);
    console.log(addr, "factory", factory);
  }
  get("0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"); // uniswap
  get("0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"); // sushiswap goerli
```

**Expected behavior:**

The calls should return the addresses of the router's WETH and factory.

**Actual behavior:** 

An exception is raised, one example of many, all fail with the same error:
> ethers.js error
```
WETH err Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="WETH()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at Logger.makeError (ethers.esm.min.js:1:61127)
    at Logger.throwError (ethers.esm.min.js:1:61305)
    at Interface.decodeFunctionResult (ethers.esm.min.js:1:197645)
    at Contract.<anonymous> (ethers.esm.min.js:1:298164)
    at Generator.next (<anonymous>)
    at fulfilled (ethers.esm.min.js:1:291378)
```

>ethers-rs error:
```
AbiError(
    DecodingError(
        InvalidName(
            "please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist",
        ),
    ),
)
```

**Frequency:**

Happens most of the time using the above code.

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
```
besu/v23.1.0/linux-x86_64/openjdk-java-17
2023-02-26 09:18:15.237-08:00 | main | INFO  | Besu | Using jemalloc
```
* OS Name & Version: [`cat /etc/*release`]:  `Void Linux`
* Kernel Version: [`uname -a`] : `6.1.13`

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)

Uniswap router on Goerli:
[0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D](https://goerli.etherscan.io/address/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D#readContract)

Sushiswap router on Goerli:
[0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506](https://goerli.etherscan.io/address/0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506#readContract)

**Comment by ibhagwan** [comment]
FYI, this issue seems to be solved with version `23.1.2`, I'll leave up to the team to close this issue as perhaps other tests need to be verified before closing.
