### ISSUE TITLE
Implement Disconnect Peers for Useless response in snapsync 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5178]
- snapsync which loops on bad peers

Partial implementation in the PR below. 

Context in #4651

**Comment by siladu** [comment]
Found an unhandled error in the debug logs that appears to be killing the snapsync thread:

```
{"@timestamp":"2023-03-09T02:22:36,703","level":"INFO","thread":"EthScheduler-Services-3 (batchPersistAccountData)","class":"SnapsyncMetricsManager","message":"Worldstate download progress: 9.70%, Peer count: 25","throwable":""}
{"@timestamp":"2023-03-09T02:22:51,042","level":"DEBUG","thread":"EthScheduler-Services-8 (batchPersistStorageData)","class":"Pipeline","message":"Unhandled exception in pipeline. Aborting.","throwable":" org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy\n\tat org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:408)\n\tat org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.java:59)\n\tat org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter$1.commit(SegmentedKeyValueStorageAdapter.java:137)\n\tat org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage$Updater.commit(WorldStateKeyValueStorage.java:216)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.request.StorageRangeDataRequest.lambda$doPersist$0(StorageRangeDataRequest.java:97)\n\tat org.hyperledger.besu.ethereum.trie.CommitVisitor.maybeStoreNode(CommitVisitor.java:72)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.StackTrie$1.maybeStoreNode(StackTrie.java:125)\n\tat org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:63)\n\tat org.hyperledger.besu.ethereum.trie.LeafNode.accept(LeafNode.java:79)\n\tat org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)\n\tat org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)\n\tat org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)\n\tat org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)\n\tat org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)\n\tat org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)\n\tat org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)\n\tat org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)\n\tat org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.commit(StoredMerklePatriciaTrie.java:170)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.StackTrie.commit(StackTrie.java:119)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.request.StorageRangeDataRequest.doPersist(StorageRangeDataRequest.java:102)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.request.SnapDataRequest.persist(SnapDataRequest.java:101)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.PersistDataStep.persist(PersistDataStep.java:59)\n\tat org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloadProcess$Builder.lambda$build$8(SnapWorldStateDownloadProcess.java:264)\n\tat org.hyperledger.besu.services.pipeline.MapProcessor.processNextInput(MapProcessor.java:31)\n\tat org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)\n\tat org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:167)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: org.rocksdb.RocksDBException: Busy\n\tat org.rocksdb.Transaction.commit(Native Method)\n\tat org.rocksdb.Transaction.commit(Transaction.java:208)\n\tat org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:402)\n\t... 30 more\n"}
```

```
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:408)
at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.java:59)
at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter$1.commit(SegmentedKeyValueStorageAdapter.java:137)
at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage$Updater.commit(WorldStateKeyValueStorage.java:216)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.request.StorageRangeDataRequest.lambda$doPersist$0(StorageRangeDataRequest.java:97)
at org.hyperledger.besu.ethereum.trie.CommitVisitor.maybeStoreNode(CommitVisitor.java:72)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.StackTrie$1.maybeStoreNode(StackTrie.java:125)
at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:63)
at org.hyperledger.besu.ethereum.trie.LeafNode.accept(LeafNode.java:79)
at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
at org.hyperledger.besu.ethereum.trie.CommitVisitor.visit(CommitVisitor.java:50)
at org.hyperledger.besu.ethereum.trie.BranchNode.accept(BranchNode.java:90)
at org.hyperledger.besu.ethereum.trie.StoredMerklePatriciaTrie.commit(StoredMerklePatriciaTrie.java:170)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.StackTrie.commit(StackTrie.java:119)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.request.StorageRangeDataRequest.doPersist(StorageRangeDataRequest.java:102)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.request.SnapDataRequest.persist(SnapDataRequest.java:101)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.PersistDataStep.persist(PersistDataStep.java:59)
at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloadProcess$Builder.lambda$build$8(SnapWorldStateDownloadProcess.java:264)
at org.hyperledger.besu.services.pipeline.MapProcessor.processNextInput(MapProcessor.java:31)
at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:167)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: org.rocksdb.RocksDBException: Busy
at org.rocksdb.Transaction.commit(Native Method)\n\tat org.rocksdb.Transaction.commit(Transaction.java:208)
at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:402)
... 30 more

**Comment by macfarla** [comment]
writing tests for #5220
