### ISSUE TITLE
Enabling TLS for privacy results in exception

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu#525]
### Steps to Reproduce (Bug)
1. Generate a client certificate and key for Besu
2. Generate PKCS12 keystore and set password
3. Add keystore password to a file
4. Configure the keystore using the --privacy-tls-keystore-file option.
5. Configure the file that contains the password to decrypt the keystore using the --privacy-tls-keystore-password-file option.
6. Configure a fingerprint file - containing fingerprinbt from Orion node configured for client connection TLS --privacy-tls-known-enclave-file
7. Enable TLS for privacy --privacy-tls-enabled=true
8. Start besu

**Expected behavior:** 
Server should start and should be able to 'communicate' over TLS to Orion.

**Actual behavior:** 
Server fails to start with following exception
picocli.CommandLine$ParameterException: java.io.IOException: keystore password was incorrect
	at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:928)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2322)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:61)
	at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:31)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2322)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1036)
	at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:911)
	at org.hyperledger.besu.Besu.main(Besu.java:49)
Caused by: picocli.CommandLine$ExecutionException: java.io.IOException: keystore password was incorrect
	at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:1205)
	at org.hyperledger.besu.cli.BesuCommand.controller(BesuCommand.java:1197)
	at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:922)
	... 13 more
Caused by: io.vertx.core.VertxException: java.io.IOException: keystore password was incorrect
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:303)
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:478)
	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:503)
	at io.vertx.core.http.impl.HttpClientImpl.<init>(HttpClientImpl.java:133)
	at io.vertx.core.impl.VertxImpl.createHttpClient(VertxImpl.java:317)
	at org.hyperledger.besu.enclave.EnclaveFactory.createVertxEnclave(EnclaveFactory.java:104)
	at org.hyperledger.besu.ethereum.core.PrivacyParameters$Builder.build(PrivacyParameters.java:259)
	at org.hyperledger.besu.cli.BesuCommand.privacyParameters(BesuCommand.java:1635)
	at org.hyperledger.besu.cli.BesuCommand.getControllerBuilder(BesuCommand.java:1230)
	at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:1203)
	... 15 more
Caused by: java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2108)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at io.vertx.core.net.impl.KeyStoreHelper.loadJKSOrPKCS12(KeyStoreHelper.java:286)
	at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:95)
	at io.vertx.core.net.KeyCertOptions.getKeyManagerFactory(KeyCertOptions.java:53)
	at io.vertx.core.net.impl.SSLHelper.getKeyMgrFactory(SSLHelper.java:308)
	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:253)
	... 24 more
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.lang.IllegalStateException: password has been cleared
	... 32 more

**Frequency:** 
Every time

### Versions
* Software version: besu/v1.4.1/linux-x86_64/oracle_openjdk-java-11
* Java version: openjdk 11.0.4 2019-07-16 LTS
* OS Name & Version: CentOS Linux release 7.7.1908 (Core)

### Additional Information

Looks like bug in EnclaveFactory.java in package org.hyperledger.besu.enclave 

The function readSecretFromFile is reading the password file as bytes not a line... so you get EOL characters 

Simple fix:
return Files.readAllLines(path, Charsets.UTF_8).get(0);

**Comment by arash009** [comment]
Thanks for raising this, we'll look into fixing this for the next minor release. In the meantime, you can use this workaround to set the password:

`echo -n "Type your password:";read -s password;echo -ne $password > passwordFile;`
