### ISSUE TITLE
Flaky test - OpenTelemetryAcceptanceTest traceReporting

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#5543]
Seems to have become more flaky recently

example failure
https://app.circleci.com/pipelines/github/hyperledger/besu/22506/workflows/d356b29f-164a-4388-bd58-2c31267ef076/jobs/139857

```
OpenTelemetryAcceptanceTest > traceReporting() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.hyperledger.besu.tests.acceptance.OpenTelemetryAcceptanceTest null within 1 minutes.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at app//org.hyperledger.besu.tests.acceptance.OpenTelemetryAcceptanceTest.traceReporting(OpenTelemetryAcceptanceTest.java:184)

        Caused by:
        java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
            at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
            at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
            at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
            at java.base/java.util.Objects.checkIndex(Objects.java:359)
            at java.base/java.util.ArrayList.get(ArrayList.java:427)
            at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1347)
            at io.opentelemetry.proto.trace.v1.ScopeSpans.getSpans(ScopeSpans.java:210)
            at org.hyperledger.besu.tests.acceptance.OpenTelemetryAcceptanceTest.lambda$traceReporting$1(OpenTelemetryAcceptanceTest.java:195
```

**Comment by macfarla** [comment]
haven't seen this one flake in months. closing.
