### ISSUE TITLE
Getting Response is closed error

### ISSUE THREAD

**Issue by ppoliani** [hyperledger/besu#558]
### Description
I was trying a script that sends 1000 txs in a concurrent way. I checked the logs and I realised that there are some issues with the RPC api

```
2020-03-22 16:41:50.904+00:00 | vert.x-eventloop-thread-2 | ERROR | ContextImpl | Unhandled exception
java.lang.IllegalStateException: Response is closed
at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:617) ~[vertx-core-3.8.0.jar:3.8.0]
at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:157) ~[vertx-core-3.8.0.jar:3.8.0]
at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:54) ~[vertx-core-3.8.0.jar:3.8.0]
at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$7(JsonRpcHttpService.java:387) ~[besu-api-1.3.8.jar:1.3.8]
at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[vertx-core-3.8.0.jar:3.8.0]
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[vertx-core-3.8.0.jar:3.8.0]
at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[vertx-core-3.8.0.jar:3.8.0]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.34.Final.jar:4.1.34.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) [netty-transport-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.34.Final.jar:4.1.34.Final]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
I wonder if I should ignore these errors or not.

**Frequency:** [What percentage of the time does it occur?]
It happens everytime I run the script with that sends 1000 transactions

### Versions (Add all that apply)
* Software version: 
`besu/v1.3.8/linux-x86_64/oracle_openjdk-java-11`

* Java version: [`java -version`]
```
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode, sharing
```

* OS Name & Version: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
```

* Kernel Version: 

`Linux staging1 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by timbeiko** [comment]
@ppoliani we have a tentative fix up: https://github.com/hyperledger/besu/pull/613

**Comment by timbeiko** [comment]
@ppoliani I will close this issue for now given the fix mentioned above. Let us know if you have any issues with it. There will be a new release for Besu out in the next 24hrs with the fix. If you want to try it sooner, you can also build directly from master :-)
