### ISSUE TITLE
Error retrieving matching logs

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#5596]
From a canary node...

```
{"@timestamp":"2023-06-13T22:30:12,501","level":"ERROR","thread":"vert.x-worker-thread-12","class":"BaseJsonRpcProcessor","message":"Error processing method: eth_getLogs [{"address":["0x00000000219ab540356cbb839cbe05303d7705fa"],"fromBlock":"0xaaa98c","toBlock":"0xaaad74","topics":null}]","throwable":" java.lang.IllegalStateException: Error retrieving matching logs
at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogs(BlockchainQueries.java:710)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.lambda$response$3(EthGetLogs.java:98)
at java.base/java.util.Optional.orElseGet(Optional.java:364)
at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetLogs.response(EthGetLogs.java:70)
at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44)
at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)
at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)
at org.hyperledger.besu.ethereum.api.jsonrpc.execution.AuthenticatedJsonRpcProcessor.process(AuthenticatedJsonRpcProcessor.java:51)
at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92)
at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87)
at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57)
at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57)
at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54)
at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.RuntimeException: java.util.NoSuchElementException: No value present
at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$matchingLogs$17(BlockchainQueries.java:696)
at java.base/java.util.Optional.map(Optional.java:260)
at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogs(BlockchainQueries.java:685)\n\t... 21 more\nCaused by: java.util.NoSuchElementException: No value present
at java.base/java.util.Optional.orElseThrow(Optional.java:377)
at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.matchingLogsCached(BlockchainQueries.java:759)
at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$matchingLogs$17(BlockchainQueries.java:688)\n\t... 23 more\n"}
```

Looks like we don't have a certain block number in the chain...
https://github.com/hyperledger/besu/blob/main/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java#L759

The symptom is that prysm-besu is struggling to stay in sync...
<img width="1614" alt="Screenshot 2023-06-14 at 3 25 52 pm" src="https://github.com/hyperledger/besu/assets/2893793/b3d2bff1-38a0-45ab-9888-557501a65219">

and we get this prysm log...
```
time="2023-06-14 05:10:28" level=error msg="Unable to process past deposit contract logs, perhaps your execution client is not fully synced" error="processPastLogs: Internal error" prefix=powchain
```

This started happening at the end of a long backwards sync, following a Tuweni regression on main that caused the node to fall behind by ~2 days.

```
####################################################################################################
#                                                                                                  #
# Besu version 23.4.2-dev-180c7519                                                                 #
#                                                                                                  #
# Configuration:                                                                                   #
# Network: Mainnet                                                                                 #
# Network Id: 1                                                                                    #
# Data storage: Bonsai                                                                             #
# Sync mode: Snap                                                                                  #
# RPC HTTP APIs: TRACE,ADMIN,DEBUG,NET,ETH,WEB3,TXPOOL                                             #
# RPC HTTP port: 8545                                                                              #
# Engine APIs: ENGINE,ETH                                                                          #
# Engine port: 8551                                                                                #
# Engine JWT: /etc/jwt-secret.hex                                                                  #
#                                                                                                  #
# Host:                                                                                            #
# Java: openjdk-java-17                                                                            #
# Maximum heap size: 4.00 GB                                                                       #
# OS: linux-x86_64                                                                                 #
# glibc: 2.35                                                                                      #
# Total memory: 15.28 GB                                                                           #
# CPU cores: 4                                                                                     #
#                                                                                                  #
####################################################################################################
```
Prysm version: "Prysm/v4.0.5/aa7d0df7ff5f74168bdaf93453c856f279ec1573. Built at: 2023-05-22 18:03:46+00:00"

**Comment by siladu** [comment]
Will try deleting the caches and restarting besu just in case

**Comment by siladu** [comment]
> Will try deleting the caches and restarting besu just in case

No error in besu yet, but now prysm has a slightly different one...
```
time="2023-06-14 05:51:23" level=error msg="Unable to process past deposit contract logs, perhaps your execution client is not fully synced" error="processPastLogs: Could not process deposit log: received incorrect merkle index: wanted 0 but got 568326" prefix=powchain
```

Maybe it will change again once besu caches are rebuilt

**Comment by siladu** [comment]
Non-issue. This was caused by this node being previously resynced using `--Xcheckpoint-post-merge-enabled` so it was missing the logs, and only started complaining after some other things went wrong!
