### ISSUE TITLE
Request for Contract verification fails with java.io.IOException: Size exceed allowed maximum capacity

### ISSUE THREAD

**Issue by cofinex** [hyperledger/besu#5614]
### Description
As an contract Writer, I want to verify my contract using hardhat verify comman so that I can send a request for verifying my smart contract code written using openzeppeline. 

### Acceptance Criteria
* I should be able to send a request to verify my contract 

### Steps to Reproduce (Bug)
1. Sent a verification request using hardhat node plugin 
npx hardhat verify --network mainnetCofinex 0xxxxx... --contract contracts/QUE.sol:QUE --show-stack-traces

**Expected behavior:** 
The contract verification request should get submitte successfully and the contract should get verified

**Actual behavior:**
I get the folowing error reported in the Node log file

2023-06-16 14:20:58.985 | ERROR | p-thread-3 | ?                   :      | Unhandled exception in router
java.io.IOException: Size exceed allowed maximum capacity
        at io.netty.handler.codec.http.multipart.AbstractHttpData.checkSize(AbstractHttpData.java:71) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.handler.codec.http.multipart.MemoryAttribute.addContent(MemoryAttribute.java:84) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:632) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:380) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:299) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:49) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223) ~[netty-codec-http-4.1.90.Final.jar:4.1.90.Final]
        at io.vertx.core.http.impl.Http1xServerRequest.onData(Http1xServerRequest.java:543) ~[vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:132) ~[vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:239) ~[vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:129) ~[vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.http.impl.Http1xServerRequest.handleContent(Http1xServerRequest.java:146) ~[vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76) [vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:153) [vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:178) [vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:161) [vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:149) [vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:157) [vertx-core-4.3.5.jar:4.3.5]
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153) [vertx-core-4.3.5.jar:4.3.5]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.90.Final.jar:4.1.90.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.90.Final.jar:4.1.90.Final]

**Frequency:** 

Every Time

### Logs (if a bug)
Please post relevant logs from Besu (and the consensus client, if running proof of stake) from before and after the issue. 

### Versions (Add all that apply)
* Software version: [`besu --version`]
besu/v22.10.3/linux-x86_64/openjdk-java-17
* Java version: [`java -version`]
openjdk version "17.0.7" 2023-04-18
* OS Name & Version: [`cat /etc/*release`]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
* Kernel Version: [`uname -a`]
Linux ip-172-31-91-43 5.19.0-1022-aws #23~22.04.1-Ubuntu SMP Fri Mar 17 15:38:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
Cloud AWS 
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

**Comment by non-fungible-nelson** [comment]
Hi there - have you tried reproducing this error on a more recent version of Besu?

**Comment by cofinex** [comment]
Yes

**Comment by cofinex** [comment]
I tried with besu-23.4.1

**Comment by non-fungible-nelson** [comment]
Have you tried deploying the contract a different way without Hardhat? Would you be comfortable sharing the contract code? We need a little more information to reproduce.
