### ISSUE TITLE
Increase in DNS Complaints in 23.7.0

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5725]
### Description
Running a mainnet node on latest has several noisy complaints from the DNS in logging. 

### Steps to Reproduce (Bug)
1. Run node with default network options
2. Review logs
```
2023-07-25 16:33:52.196-04:00 | vert.x-eventloop-thread-3 | WARN  | DNSResolver | DNS query error with AOFYQGR76ZSMC4CNP4BNR5.all.goerli.ethdisco.net
io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error
2023-07-25 16:33:52.489-04:00 | vert.x-eventloop-thread-3 | WARN  | DNSResolver | DNS query error with 4NCZUOSMW6MES6GWKSZJE2.all.goerli.ethdisco.net
io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error
2023-07-25 16:33:52.767-04:00 | vert.x-eventloop-thread-3 | WARN  | DNSResolver | DNS query error with PLVKB3VLCO5ONCLLAU7IE7.all.goerli.ethdisco.net
io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error
... continues
```

followed by...

```
2023-07-25 16:34:03.630-04:00 | vert.x-eventloop-thread-3 | ERROR | Besu | Uncaught exception in thread "vert.x-eventloop-thread-3"
io.vertx.core.VertxException: DNS query timeout for DWBQEO3YKOF433B2N67UOGOO7M.all.goerli.ethdisco.net.
	at io.vertx.core.dns.impl.DnsClientImpl$Query.lambda$null$0(DnsClientImpl.java:353)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:295)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@36724491, io.vertx.kotlin.coroutines.VertxCoroutineExecutor@cc319bf]
```
This repeats several times in normal operation, but without any consequences. Probably a logging clean up.

**Comment by JanKalin** [comment]
And in the latest version 23.10.2
```
Dec 13 18:30:55 rp besu[2257214]: 2023-12-13 18:30:55.928+01:00 | vert.x-eventloop-thread-1 | ERROR | Besu | Uncaught exception in thread "vert.x-eventloop-thread-1"
Dec 13 18:30:55 rp besu[2257214]: io.vertx.core.VertxException: DNS query timeout for SYDZEVIAOLGKB3UO27N46MMGQ4.all.mainnet.ethdisco.net.
Dec 13 18:30:55 rp besu[2257214]:         at io.vertx.core.dns.impl.DnsClientImpl$Query.lambda$null$0(DnsClientImpl.java:353)
Dec 13 18:30:55 rp besu[2257214]:         at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
Dec 13 18:30:55 rp besu[2257214]:         at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
Dec 13 18:30:55 rp besu[2257214]:         at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Dec 13 18:30:55 rp besu[2257214]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Dec 13 18:30:55 rp besu[2257214]:         at java.base/java.lang.Thread.run(Thread.java:840)
Dec 13 18:30:55 rp besu[2257214]:         Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@712b9747, io.vertx.kotlin.coroutines.VertxCoroutineExecutor@2229cf50]
```
