### ISSUE TITLE
SnapSync pipeline halting on RocksDB Busy exception during flat db heal

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#5911]
### Description
During snap-sync, especially on a low IO instance, a deadlock can occur that will halt the snap sync pipeline.  See stack trace in logs below.

Besu should implement a retry policy that will catch the exception and retry the commit before throwing, rather than allowing the exception to abend the pipeline.

### Acceptance Criteria
* Snap sync pipeline is more tolerant of IO saturated machines

### Steps to Reproduce (Bug)
1. start snap sync of mainnet with flat db healing, on an IO restricted instance

**Expected behavior:** [What you expect to happen]
snap sync to finish with full flat db heal

**Actual behavior:** [What actually happens]
When IO contention is too high, a RocksDB Busy exception will be thrown and abend the sync pipeline

**Frequency:** [What percentage of the time does it occur?]

### Logs (if a bug)

```
{“@timestamp”:“2023-09-19T13:05:45,780",“level”:“INFO”,“thread”:“EthScheduler-Services-26 (batchPersistTrieNodeData)“,”class”:“SnapsyncMetricsManager”,“message”:“Healed 74500 world state trie nodes, Peer count: 25”,“throwable”:“”}
{“@timestamp”:“2023-09-19T13:05:55,384”,“level”:“INFO”,“thread”:“EthScheduler-Services-26 (batchPersistTrieNodeData)“,”class”:“Pipeline”,“message”:“Unexpected exception in pipeline. Aborting.“,”throwable”:” org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
	at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBTransaction.commit(RocksDBTransaction.java:95)
	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionValidatorDecorator.java:65)
	at org.hyperledger.besu.ethereum.bonsai.storage.BonsaiWorldStateKeyValueStorage$Updater.commit(BonsaiWorldStateKeyValueStorage.java:472)
	at org.hyperledger.besu.ethereum.eth.sync.snapsync.PersistDataStep.persist(PersistDataStep.java:80)
	at org.hyperledger.besu.ethereum.eth.sync.snapsync.SnapWorldStateDownloadProcess$Builder.lambda$build$27(SnapWorldStateDownloadProcess.java:392)
	at org.hyperledger.besu.services.pipeline.MapProcessor.processNextInput(MapProcessor.java:31)
	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:169)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.rocksdb.RocksDBException: Busy
	at org.rocksdb.Transaction.commit(Native Method)
	at org.rocksdb.Transaction.commit(Transaction.java:207)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBTransaction.commit(RocksDBTransaction.java:89)
	... 12 more
”}
```

### Versions (Add all that apply)
* Software version: 23.7.x
* Cloud VM, type, size: Azure d4s

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - mainnet, --Xsnapsync-synchronizer-flat-db-healing-enabled=true
* System info - IO constrained

**Comment by garyschulte** [comment]
fixed by #6004
