### ISSUE TITLE
The JSON-RPC trace_filter method can cause a Thread block

### ISSUE THREAD

**Issue by vitor-fernandes** [hyperledger/besu#5971]
### Description
Hi, while I was testing the JSON-RPC API I noticed that the _filter_ method of _TRACE_ API accepts a large block range which can cause a Thread block exception and possible leads to DoS the node.

I'm receiving the exception when sending a block range like 0 - 100000000

### Steps to Reproduce (Bug)
1. Enable the JSON-RPC and TRACE API on the Node
2. Call the trace_filter method with a large block range
3. curl -X POST --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"1","toBlock":"1000000000","after":2,"count":2,"fromAddress":["0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"]}],"id":415}' http://127.0.0.1:8548
4. Checking the logs, there will be a lot of Thread blocked exceptions, which will need to reboot the node to stop it from spawn

**Expected behavior:** An error message when the supplied block range is too large

**Actual behavior:** The node will fetch the traces between the entire block range causing a Thread exception, and keeping the client waiting until timeout the request

**Frequency:** Every time when a large block range is supplied.

#### Short Fix

A limit for the block range can be applied as occurred on the [eth_getLogs](https://besu.hyperledger.org/23.4.0/public-networks/reference/api#eth_getlogs)

### Logs (if a bug)
```
2023-09-28 15:49:54.013-03:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #16,997 / 0 tx / 0 pending / 0 (0.0%) gas / (0xf4749789dab086b9701de03979fab0bb79809b3fdebf7300b78e67d07298a01c)
2023-09-28 15:49:54.013-03:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Produced #16,997 / 0 tx / 0 pending / 0 (0.0%) gas / (0xf4749789dab086b9701de03979fab0bb79809b3fdebf7300b78e67d07298a01c)
2023-09-28 15:49:54.013-03:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #16,997 / 0 tx / 0 pending / 0 (0.0%) gas / (0xf4749789dab086b9701de03979fab0bb79809b3fdebf7300b78e67d07298a01c)
2023-09-28 15:49:54.015-03:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #16,997 / 0 tx / 0 pending / 0 (0.0%) gas / (0xf4749789dab086b9701de03979fab0bb79809b3fdebf7300b78e67d07298a01c)
2023-09-28 15:49:54.037-03:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[#67,vert.x-worker-thread-17,5,main] has been blocked for 62529 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at org.rocksdb.RocksDB.get(Native Method)
	at org.rocksdb.RocksDB.get(RocksDB.java:2096)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:253)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.get(RocksDBColumnarKeyValueStorage.java:69)
	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter.get(SegmentedKeyValueStorageAdapter.java:70)
	at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage.get(KeyValueStoragePrefixedKeyBlockchainStorage.java:140)
	at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStoragePrefixedKeyBlockchainStorage.getBlockHash(KeyValueStoragePrefixedKeyBlockchainStorage.java:112)
	at org.hyperledger.besu.ethereum.chain.DefaultBlockchain.getBlockHashByNumber(DefaultBlockchain.java:250)
	at org.hyperledger.besu.ethereum.chain.Blockchain.getBlockByNumber(Blockchain.java:108)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceFilter.getBlockList(TraceFilter.java:207)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceFilter.traceFilterWithPipeline(TraceFilter.java:124)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceFilter.response(TraceFilter.java:99)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92)
	at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87)
	at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57)
	at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Versions (Add all that apply)
* Software version: besu/v23.4.4/osx-aarch_64/openjdk-java-20

**Comment by non-fungible-nelson** [comment]
@macfarla this seems like a similar issue to the RPC range limits we added to other methods. Do you have any insight here or maybe a good suggestion on a reasonable limit? either by block range or response size.

**Comment by non-fungible-nelson** [comment]
May be more of a feature request - we would need tune-able values for what is a reasonable range in private networks that would want to provide access to this API to their users or developers...

**Comment by non-fungible-nelson** [comment]
Great @alyokaz - let us know if you have questions or reach out in Besu discord at #besu-contributors with more specific questions and devs can help out! I look forward to your PR.
