### ISSUE TITLE
besu t8n require post state to be provided still

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#5979]
still getting this issue 

```
.retesteth/besu/setup.sh WARNING: Besu daemon failed to start, will use besu evm t8n instead
/home/ubuntu/.retesteth/besu/start.sh --state.fork Berlin --state.reward 0 --state.chainid 1 --input.alloc /dev/shm/4a92005a-d5cb-4287-b4fe-2d286b62b0dc/alloc.json --input.txs /dev/shm/4a92005a-d5cb-4287-b4fe-2d286b62b0dc/txs.rlp --input.env /dev/shm/4a92005a-d5cb-4287-b4fe-2d286b62b0dc/env.json --output.basedir /dev/shm/4a92005a-d5cb-4287-b4fe-2d286b62b0dc --output.result out.json --output.alloc outAlloc.json --output.errorlog /dev/shm/4a92005a-d5cb-4287-b4fe-2d286b62b0dc/error.json

Res:

RAlloc:

Tool log: 
java.lang.RuntimeException: World State Root does not match expected value, header 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 calculated 0xcd39e0cdd18f8f811911222ae6779341663d0293e1a3d9501da7ac2f4da9b277
	at org.hyperledger.besu.ethereum.bonsai.worldview.BonsaiWorldState.verifyWorldStateRoot(BonsaiWorldState.java:435)
	at org.hyperledger.besu.ethereum.referencetests.BonsaiReferenceTestWorldState.verifyWorldStateRoot(BonsaiReferenceTestWorldState.java:91)
	at org.hyperledger.besu.ethereum.bonsai.worldview.BonsaiWorldState.persist(BonsaiWorldState.java:393)
	at org.hyperledger.besu.evmtool.T8nExecutor.runTest(T8nExecutor.java:380)
	at org.hyperledger.besu.evmtool.T8nSubCommand.run(T8nSubCommand.java:285)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.hyperledger.besu.evmtool.EvmToolCommand.execute(EvmToolCommand.java:271)
	at org.hyperledger.besu.evmtool.EvmToolCommand.execute(EvmToolCommand.java:237)
	at org.hyperledger.besu.evmtool.EvmTool.main(EvmTool.java:23)

Tests finished: 1
stExample time: 10.59, cputime: 0.02 (0%), t8ntime: 10.51 (99%)
Error: Tool returned empty file: /dev/shm/4a92005a-d5cb-4287-b4fe-2d286b62b0dc/out.json
```

**Comment by winsvega** [comment]
and if I run through the daemon it returns null output
```
.retesteth/besu/setup.sh Besu daemon is listening on port 3000
/home/ubuntu/.retesteth/besu/start.sh --state.fork Berlin --state.reward 0 --state.chainid 1 --input.alloc /dev/shm/46d53a32-38ba-409f-8495-0d7ae07c5749/alloc.json --input.txs /dev/shm/46d53a32-38ba-409f-8495-0d7ae07c5749/txs.rlp --input.env /dev/shm/46d53a32-38ba-409f-8495-0d7ae07c5749/env.json --output.basedir /dev/shm/46d53a32-38ba-409f-8495-0d7ae07c5749 --output.result out.json --output.alloc outAlloc.json --output.errorlog /dev/shm/46d53a32-38ba-409f-8495-0d7ae07c5749/error.json

Res:
null

RAlloc:
null

```

using the same script

**Comment by winsvega** [comment]
https://github.com/hyperledger/besu/issues/5934

**Comment by matkt** [comment]
Yes I describe the reason here https://github.com/hyperledger/besu/issues/5934#issuecomment-1735152307
@garyschulte   normally made a PR to not check the state root in this mode . Obviously we have forgotten a path which means that the stateroot is still verified. I will check this on Monday

**Comment by matkt** [comment]
I created a PR to fix that https://github.com/hyperledger/besu/pull/6013 
@winsvega could you validate that it's for you ? 
@garyschulte could you do a review of that ? Just added a method to disable root hash verification for T8n and not reference tests

**Comment by winsvega** [comment]
yes it works now! 
daemon t8n works as all the other t8ns.
