### ISSUE TITLE
Bonsai: SnapSync/FullSync and BlockPropagation race error

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu#5987]
### Description
On Bonsai on non-PoS networks, when completing snap sync a race exists that can corrupt the state.  

When the snapsync pipeline completes, the full sync process starts to catch up to head.  If the BlockPropagation manager reacts to a gossip'd block during this time, trie log rolling fails due to a missing trielog:

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. snap sync a non-PoS network using Bonsai storage format
2. once the snap sync completes, especially on networks with a short block time, the block propagation manager attempts to import blocks ahead of the trielog for the current pivot being available.

**Expected behavior:** [What you expect to happen]
no issue post sync

**Actual behavior:** [What actually happens]
trie log rolling fails at the tip of the synced chain due to missing trielog

**Frequency:** [What percentage of the time does it occur?]
varies based on network and block time.  Testing locally with clique and 5 second block time this happens about 33% of the time

### Logs (if a bug)
```
2023-10-04 18:22:30.070-07:00 | EthScheduler-Services-42 (importBlock) | INFO  | SnapWorldDownloadState | Running world state heal process from peers with pivot block 17083
2023-10-04 18:22:30.073-07:00 | EthScheduler-Services-36 (requestCompleteTask) | INFO  | SnapWorldDownloadState | Initiating the healing process for the flat database
2023-10-04 18:22:30.078-07:00 | EthScheduler-Services-36 (requestCompleteTask) | INFO  | SnapsyncMetricsManager | Finished worldstate snapsync with nodes 15 (healed=0) duration 0:2,418.
2023-10-04 18:22:31.009-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17095 (0xba970ed3247b9f2faefa462e0f6bbac711801158f19b56c8fa43c18c9b79033c) - 1 saved block(s)
2023-10-04 18:22:31.010-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0xf9bc52fdc7ee314f5ea3e955f95319263a8fe330da466dd422dac60b1855eba3 of block 17095 (0xba970ed3247b9f2faefa462e0f6bbac711801158f19b56c8fa43c18c9b79033c)
2023-10-04 18:22:31.021-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17094 (0xf9bc52fdc7ee314f5ea3e955f95319263a8fe330da466dd422dac60b1855eba3) - 2 saved block(s)
2023-10-04 18:22:31.021-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x88771787c2d41cadac5ec845badd71da6d6632d03544798ee15a70966c826f0e of block 17094 (0xf9bc52fdc7ee314f5ea3e955f95319263a8fe330da466dd422dac60b1855eba3)
2023-10-04 18:22:31.023-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17093 (0x88771787c2d41cadac5ec845badd71da6d6632d03544798ee15a70966c826f0e) - 3 saved block(s)
2023-10-04 18:22:31.023-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x9d8962b55b4f2ff02e69558e8ef52b3f69dfd79533075b3b888417a84f1d1cb9 of block 17093 (0x88771787c2d41cadac5ec845badd71da6d6632d03544798ee15a70966c826f0e)
2023-10-04 18:22:31.024-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17092 (0x9d8962b55b4f2ff02e69558e8ef52b3f69dfd79533075b3b888417a84f1d1cb9) - 4 saved block(s)
2023-10-04 18:22:31.025-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x171e9e81cd65b16e0dbdd2e866aa72d5a670d8ec8532e8db184f43ade9efdcc9 of block 17092 (0x9d8962b55b4f2ff02e69558e8ef52b3f69dfd79533075b3b888417a84f1d1cb9)
2023-10-04 18:22:31.026-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17091 (0x171e9e81cd65b16e0dbdd2e866aa72d5a670d8ec8532e8db184f43ade9efdcc9) - 5 saved block(s)
2023-10-04 18:22:31.026-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x25bd079593c700b80250e05eace2556c89fd3c45bfd407a40b4b6c92c3230752 of block 17091 (0x171e9e81cd65b16e0dbdd2e866aa72d5a670d8ec8532e8db184f43ade9efdcc9)
2023-10-04 18:22:31.028-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17090 (0x25bd079593c700b80250e05eace2556c89fd3c45bfd407a40b4b6c92c3230752) - 6 saved block(s)
2023-10-04 18:22:31.028-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x38b65af81633f8b029ce35ee48ef7a2eddbd0e5bf55449196c7c449f6cdc533d of block 17090 (0x25bd079593c700b80250e05eace2556c89fd3c45bfd407a40b4b6c92c3230752)
2023-10-04 18:22:31.030-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17089 (0x38b65af81633f8b029ce35ee48ef7a2eddbd0e5bf55449196c7c449f6cdc533d) - 7 saved block(s)
2023-10-04 18:22:31.030-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0xdb3ccc878c8f3653ee3c9f897bb585d75e97c007fb8ccad8a07d04c45cb3a036 of block 17089 (0x38b65af81633f8b029ce35ee48ef7a2eddbd0e5bf55449196c7c449f6cdc533d)
2023-10-04 18:22:31.032-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17088 (0xdb3ccc878c8f3653ee3c9f897bb585d75e97c007fb8ccad8a07d04c45cb3a036) - 8 saved block(s)
2023-10-04 18:22:31.033-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x97f4f5357046fdc0e170f96f0ad1c137e3c093e59f3588ebdf0dedf4e252ffa8 of block 17088 (0xdb3ccc878c8f3653ee3c9f897bb585d75e97c007fb8ccad8a07d04c45cb3a036)
2023-10-04 18:22:31.035-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17087 (0x97f4f5357046fdc0e170f96f0ad1c137e3c093e59f3588ebdf0dedf4e252ffa8) - 9 saved block(s)
2023-10-04 18:22:31.035-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x92954f4e479d37c0711169ece926fdabd3f3bf66c8a407a57b9c2ede1de0d1df of block 17087 (0x97f4f5357046fdc0e170f96f0ad1c137e3c093e59f3588ebdf0dedf4e252ffa8)
2023-10-04 18:22:31.038-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17086 (0x92954f4e479d37c0711169ece926fdabd3f3bf66c8a407a57b9c2ede1de0d1df) - 10 saved block(s)
2023-10-04 18:22:31.038-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x2cdc4f1edd62d3d8e70db61f1ba3bae2b00530d0895cde423487ef05a0d9fb49 of block 17086 (0x92954f4e479d37c0711169ece926fdabd3f3bf66c8a407a57b9c2ede1de0d1df)
2023-10-04 18:22:31.041-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 17085 (0x2cdc4f1edd62d3d8e70db61f1ba3bae2b00530d0895cde423487ef05a0d9fb49) - 11 saved block(s)
2023-10-04 18:22:31.041-07:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x49454ea5798a66d744663d789c709f31516eda3c19001c72a556ea11e0103c6f of block 17085 (0x2cdc4f1edd62d3d8e70db61f1ba3bae2b00530d0895cde423487ef05a0d9fb49)
2023-10-04 18:22:31.046-07:00 | EthScheduler-Workers-0 | INFO  | BonsaiWorldStateProvider | rolling mutableState blockHash 0x28b1d6e36173a75b905391390022f13eafff0522cd2909dbdc563cb36c2ecd26 to blockhash 0x6755091b4bd81ef4994b1b6256ceb01a3fccce8f1626baffcdfb54569f113f3c
2023-10-04 18:22:31.046-07:00 | EthScheduler-Workers-0 | INFO  | BonsaiWorldStateProvider | Rollforward 0x6755091b4bd81ef4994b1b6256ceb01a3fccce8f1626baffcdfb54569f113f3c
2023-10-04 18:22:31.046-07:00 | EthScheduler-Workers-0 | INFO  | BonsaiWorldStateProvider | Archive rolling failed for block hash 0x6755091b4bd81ef4994b1b6256ceb01a3fccce8f1626baffcdfb54569f113f3c
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateProvider.rollMutableStateToBlockHash(BonsaiWorldStateProvider.java:218)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateProvider.getMutable(BonsaiWorldStateProvider.java:184)
	at org.hyperledger.besu.ethereum.bonsai.BonsaiWorldStateProvider.getMutable(BonsaiWorldStateProvider.java:160)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:124)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:72)
	at org.hyperledger.besu.ethereum.mainnet.MainnetBlockImporter.importBlock(MainnetBlockImporter.java:45)
	at org.hyperledger.besu.ethereum.core.BlockImporter.importBlock(BlockImporter.java:45)
	at org.hyperledger.besu.ethereum.eth.sync.tasks.PersistBlockTask.executeTask(PersistBlockTask.java:203)
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.executeTaskTimed(AbstractEthTask.java:150)
	at org.hyperledger.besu.ethereum.eth.manager.task.AbstractEthTask.run(AbstractEthTask.java:75)
	at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.runImportTask(BlockPropagationManager.java:692)
	at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.validateAndProcessPendingBlock(BlockPropagationManager.java:671)
	at org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.lambda$importOrSavePendingBlock$21(BlockPropagationManager.java:617)
	at org.hyperledger.besu.util.FutureUtils.propagateResult(FutureUtils.java:98)
	at org.hyperledger.besu.ethereum.eth.manager.EthScheduler.lambda$scheduleSyncWorkerTask$0(EthScheduler.java:110)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-10-04 18:22:31.048-07:00 | EthScheduler-Workers-0 | INFO  | DefaultSynchronizer | Stopping synchronizer
2023-10-04 18:22:31.048-07:00 | EthScheduler-Workers-0 | INFO  | FastSyncDownloader | Stopping fast sync
2023-10-04 18:22:31.056-07:00 | EthScheduler-Workers-0 | INFO  | DefaultSynchronizer |
####################################################################################################
#                                                                                                  #
# Besu has identified a problem with its worldstate database.                                      #
# Your node will fetch the correct data from peers to repair the problem.                          #
# Starting the sync pipeline...                                                                    #
#                                                                                                  #
####################################################################################################
2023-10-04 18:22:31.057-07:00 | EthScheduler-Workers-0 | INFO  | TransactionPoolFactory | Disabling transaction handling during re-sync
```
### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]
* Consensus Client & Version if using Proof of Stake: [e.g. Teku, Lighthouse, Prysm, Nimbus, Lodestar]

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version [`solc --version`]
* Repo with minimal set of deployable/reproducible contract code - please provide a link
* Please include specifics on how you are deploying/calling the contract 
* Have you reproduced the issue on other eth clients

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

**Comment by garyschulte** [comment]
incidentally, the trie repair/healing process that is triggered fails also due to a missing trielog

**Comment by gfukushima** [comment]
I've tried to replicate this issue using the follwoing approaches, neither has reuslted in the same issue reported here:

- Using a Geth (clique) to start a network and sync besu from it.
Result: Snapsynced successfully as shown in the logs
`2023-11-16 15:52:35.157-03:00 | main | INFO  | Runner | Ethereum main loop is up.
2023-11-16 15:52:40.171-03:00 | EthScheduler-Timer-0 | INFO  | PivotSelectorFromPeers | Selecting block number 8310 as fast sync pivot block.
2023-11-16 15:52:40.177-03:00 | EthScheduler-Timer-0 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 1 peers.
2023-11-16 15:52:40.182-03:00 | EthScheduler-Timer-0 | INFO  | PivotBlockConfirmer | Confirm pivot block 8310 with at least 1 peers.
2023-11-16 15:52:40.189-03:00 | nioEventLoopGroup-3-1 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 8310: 0x4002bb511c9aaafcef4694aeb4220e211be1556cb6529318fb4bdef82d935bea
2023-11-16 15:52:40.193-03:00 | nioEventLoopGroup-3-1 | INFO  | SnapWorldStateDownloader | Downloading world state from peers for pivot block 8310 (0x4002bb511c9aaafcef4694aeb4220e211be1556cb6529318fb4bdef82d935bea). State root 0x66197c7179ac580b5e9888a5926ec9877f2a33a8fb27093327cf507c17426f38 pending requests 0
2023-11-16 15:52:40.390-03:00 | nioEventLoopGroup-3-1 | INFO  | BonsaiWorldStateKeyValueStorage | Bonsai flat db mode found PARTIAL
2023-11-16 15:52:40.391-03:00 | nioEventLoopGroup-3-1 | INFO  | BonsaiWorldStateKeyValueStorage | Bonsai flat db mode found FULL
2023-11-16 15:52:40.508-03:00 | EthScheduler-Services-36 (requestCompleteTask) | INFO  | SnapWorldDownloadState | Running world state heal process from peers with pivot block 8310
2023-11-16 15:52:40.536-03:00 | EthScheduler-Services-36 (requestCompleteTask) | INFO  | SnapWorldDownloadState | Pausing world state download while waiting for sync to complete
2023-11-16 15:52:42.181-03:00 | EthScheduler-Services-42 (importBlock) | INFO  | SnapWorldDownloadState | Running world state heal process from peers with pivot block 8310
2023-11-16 15:52:42.183-03:00 | EthScheduler-Services-36 (requestCompleteTask) | INFO  | SnapWorldDownloadState | Initiating the healing process for the flat database
2023-11-16 15:52:42.190-03:00 | EthScheduler-Services-36 (requestCompleteTask) | INFO  | SnapsyncMetricsManager | Finished worldstate snapsync with nodes 12 (healed=0) duration 0:1,993.
2023-11-16 15:52:44.197-03:00 | EthScheduler-Services-37 (importBlock) | INFO  | PipelineChainDownloader | PipelineChain download complete
2023-11-16 15:52:44.211-03:00 | EthScheduler-Services-37 (importBlock) | INFO  | DefaultSynchronizer | Sync completed successfully with pivot block 8310
2023-11-16 15:52:44.212-03:00 | EthScheduler-Services-37 (importBlock) | INFO  | TransactionPoolFactory | Enabling transaction handling following initial sync
2023-11-16 15:52:44.229-03:00 | EthScheduler-Services-37 (importBlock) | INFO  | FullSyncDownloader | Starting full sync.
2023-11-16 15:52:47.030-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #8,363 / 0 tx / 0 om / 0 (0.0%) gas / (0xa573237cd839d4bc6b5a9189e168989bf5fc5c1ce794f05c40a9d5ab44f9406c) in 0.002s. Peers: 1
`

- Using the follwoing PR [#5887](https://github.com/hyperledger/besu/pull/5887) using both DB provided (client and server)
Result is also a successfull sync (note that no snap was triggered only a quick fullsync to catch up with the chain).
`2023-11-16 16:00:21.385-03:00 | main | INFO  | Runner | Ethereum main loop is up.
2023-11-16 16:00:22.120-03:00 | nioEventLoopGroup-3-2 | INFO  | FullSyncTargetManager | Unable to find sync target. Currently checking 1 peers for usefulness
2023-11-16 16:00:23.042-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 36563 (0x31e5f39f7c51a09f9524a6d5c6c5b90ce1513c1a38861b0ff9347d0a90437654) - 1 saved block(s)
2023-11-16 16:00:23.042-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x2224d3ba3e4c14cdd85d03635c192cee5a6921b564515c8221bd6854cd94c17a of block 36563 (0x31e5f39f7c51a09f9524a6d5c6c5b90ce1513c1a38861b0ff9347d0a90437654)
2023-11-16 16:00:23.068-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 36562 (0x2224d3ba3e4c14cdd85d03635c192cee5a6921b564515c8221bd6854cd94c17a) - 2 saved block(s)
2023-11-16 16:00:23.069-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0x5eeff53e65691af3726a76fbf50864123b5e8c583bcaa3ffdc489250b3181104 of block 36562 (0x2224d3ba3e4c14cdd85d03635c192cee5a6921b564515c8221bd6854cd94c17a)
2023-11-16 16:00:23.079-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 36561 (0x5eeff53e65691af3726a76fbf50864123b5e8c583bcaa3ffdc489250b3181104) - 3 saved block(s)
2023-11-16 16:00:23.079-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0xce9668b8487c9490d968f6fbcd273ab6b9dfa30dbbcd7f551516b17c515b8f1a of block 36561 (0x5eeff53e65691af3726a76fbf50864123b5e8c583bcaa3ffdc489250b3181104)
2023-11-16 16:00:23.083-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Saved announced block for future import 36560 (0xce9668b8487c9490d968f6fbcd273ab6b9dfa30dbbcd7f551516b17c515b8f1a) - 4 saved block(s)
2023-11-16 16:00:23.083-03:00 | nioEventLoopGroup-3-2 | INFO  | BlockPropagationManager | Retrieving parent 0xd77c94985cb4f65f49d395b212c68c38094a75e47489ec688a156f8668be435e of block 36560 (0xce9668b8487c9490d968f6fbcd273ab6b9dfa30dbbcd7f551516b17c515b8f1a)
2023-11-16 16:00:23.124-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,559 / 0 tx / 0 om / 0 (0.0%) gas / (0xd77c94985cb4f65f49d395b212c68c38094a75e47489ec688a156f8668be435e) in 0.014s. Peers: 1
2023-11-16 16:00:23.128-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,560 / 0 tx / 0 om / 0 (0.0%) gas / (0xce9668b8487c9490d968f6fbcd273ab6b9dfa30dbbcd7f551516b17c515b8f1a) in 0.001s. Peers: 1
2023-11-16 16:00:23.129-03:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [36560]
2023-11-16 16:00:23.144-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,561 / 0 tx / 0 om / 0 (0.0%) gas / (0x5eeff53e65691af3726a76fbf50864123b5e8c583bcaa3ffdc489250b3181104) in 0.001s. Peers: 1
2023-11-16 16:00:23.144-03:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [36561]
2023-11-16 16:00:23.151-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,562 / 0 tx / 0 om / 0 (0.0%) gas / (0x2224d3ba3e4c14cdd85d03635c192cee5a6921b564515c8221bd6854cd94c17a) in 0.006s. Peers: 1
2023-11-16 16:00:23.151-03:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [36562]
2023-11-16 16:00:23.151-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 36562 (0x2224d3ba3e4c14cdd85d03635c192cee5a6921b564515c8221bd6854cd94c17a) is already imported
2023-11-16 16:00:23.156-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,563 / 0 tx / 0 om / 0 (0.0%) gas / (0x31e5f39f7c51a09f9524a6d5c6c5b90ce1513c1a38861b0ff9347d0a90437654) in 0.004s. Peers: 1
2023-11-16 16:00:23.156-03:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [36563]
2023-11-16 16:00:28.063-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,564 / 0 tx / 0 om / 0 (0.0%) gas / (0x679b66916d506722d21853b5d4e1147add6f7cd3ff4c66809b5f21cfe19cf023) in 0.005s. Peers: 1
2023-11-16 16:00:33.029-03:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #36,565 / 0 tx / 0 om / 0 (0.0%) gas / (0xc6bc7eea6eaac6ce8348bcc9454f0eb78edc3da0112de36efd80734013cdfb1e) in 0.001s. Peers: 1
`

- Using the follwoing PR [#5887](https://github.com/hyperledger/besu/pull/5887) trying to sync the client from scratch
Result is a snapsync that doesn't seem to progress.
`023-11-16 16:03:17.727-03:00 | main | INFO  | Runner | Ethereum main loop is up.
2023-11-16 16:03:22.733-03:00 | EthScheduler-Timer-0 | INFO  | PivotSelectorFromPeers | Selecting block number 36528 as fast sync pivot block.
2023-11-16 16:03:22.736-03:00 | EthScheduler-Timer-0 | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 1 peers.
2023-11-16 16:03:22.738-03:00 | EthScheduler-Timer-0 | INFO  | PivotBlockConfirmer | Confirm pivot block 36528 with at least 1 peers.
2023-11-16 16:03:22.752-03:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 36528: 0xfde79e32c353bc7ccb343900dca217c0ad809d066050817db8a0f69807eef4ff
2023-11-16 16:03:22.758-03:00 | nioEventLoopGroup-3-2 | INFO  | SnapWorldStateDownloader | Downloading world state from peers for pivot block 36528 (0xfde79e32c353bc7ccb343900dca217c0ad809d066050817db8a0f69807eef4ff). State root 0x286e0d7eeb31a7e6377c350fdc2a27f78fa61b97a0f7f4c7245fd834079424fd pending requests 0
2023-11-16 16:03:22.948-03:00 | nioEventLoopGroup-3-2 | INFO  | BonsaiWorldStateKeyValueStorage | Bonsai flat db mode found PARTIAL
2023-11-16 16:03:22.949-03:00 | nioEventLoopGroup-3-2 | INFO  | BonsaiWorldStateKeyValueStorage | Bonsai flat db mode found FULL
2023-11-16 16:04:22.972-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotSelectorFromPeers | Selecting block number 36540 as fast sync pivot block.
2023-11-16 16:04:22.973-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 1 peers.
2023-11-16 16:04:22.973-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockConfirmer | Confirm pivot block 36540 with at least 1 peers.
2023-11-16 16:04:22.975-03:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 36540: 0x9bdf0ba738fbcd32523439b6e645c3555f40f610bd5c7db1200e0b9d1b149008
2023-11-16 16:05:22.975-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotSelectorFromPeers | Selecting block number 36552 as fast sync pivot block.
2023-11-16 16:05:22.976-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 1 peers.
2023-11-16 16:05:22.976-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockConfirmer | Confirm pivot block 36552 with at least 1 peers.
2023-11-16 16:05:22.976-03:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 36552: 0xfbfb6521f8ec962cfa8c398cb028daf2863e8bfd5697b3b2052012fa61767795
2023-11-16 16:06:22.977-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotSelectorFromPeers | Selecting block number 36564 as fast sync pivot block.
2023-11-16 16:06:22.978-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 1 peers.
2023-11-16 16:06:22.978-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockConfirmer | Confirm pivot block 36564 with at least 1 peers.
2023-11-16 16:06:22.979-03:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 36564: 0x679b66916d506722d21853b5d4e1147add6f7cd3ff4c66809b5f21cfe19cf023
2023-11-16 16:07:22.987-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotSelectorFromPeers | Selecting block number 36576 as fast sync pivot block.
2023-11-16 16:07:22.992-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockRetriever | Retrieve a pivot block that can be confirmed by at least 1 peers.
2023-11-16 16:07:22.992-03:00 | EthScheduler-Services-1 (checkNewPivotBlock-Account) | INFO  | PivotBlockConfirmer | Confirm pivot block 36576 with at least 1 peers.
2023-11-16 16:07:22.997-03:00 | nioEventLoopGroup-3-2 | INFO  | PivotBlockConfirmer | Confirmed pivot block at 36576: 0x9248dd1df036e9c91bba23422b27382cc153d8f8c050bb40fe8877612ad84a9e
`

**Comment by non-fungible-nelson** [comment]
@garyschulte if this is dependent upon snapserver implementation, should we close this ticket ? Or keep open in presumption of fixing it on your feature branch... 

Happy to decide with you

**Comment by usmansaleem** [comment]
Removed P2 label. Need to reevaluate the bug priority.

**Comment by jflo** [comment]
Please retest to see if this hasn't been fixed by other improvements.
