### ISSUE TITLE
BftProcessorExecutor-QBFT-0 | ERROR | AbstractBlockProcessor | failed persisting block org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy

### ISSUE THREAD

**Issue by kkeaton-rcp** [hyperledger/besu#6053]
### Description
I have a private blockchain where all the validator nodes crashed and stopped processing blocks. They all seemed to have the error(s) attached below. This is extremely similar to [https://github.com/hyperledger/besu/issues/5441] which happened on besu version 23.4.0. However, the solution says it was an underlying hardware issue which I feel is unlikely as this happened to my nodes running on AWS. Any further discussion on this issue would be greatly appreciated, thank you!

### Steps to Reproduce
I am unsure how to reproduce this error as it seems to be an error with rocksdb. Using v23.1.2, ubuntu 22.04 running on t2.large aws instances.

**Expected behavior:** 
Expected the system to fix the error and start processing blocks again. 

**Actual behavior:** 
Error continues and seems to cause additional errors for the blockchain that cause the blockchain to stop processing blocks.

**Frequency:** 
This has only happened once so far on October 12th. 

### Versions 
Software version: besu v23.1.2
Java version: 17.0.8.1
OS Name & Version: Ubuntu 22.04.2 LTS
Kernel Version: x86_64
Cloud VM, type, size: AWS t2-large

### Logs
```
2023-10-12 00:13:21.013+00:00 | BftProcessorExecutor-QBFT-0 | ERROR | AbstractBlockProcessor | failed persisting block
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:408)
        at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionTransitionValidatorDecorator.java:59)
        at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter$1.commit(SegmentedKeyValueStorageAdapter.java:137)
        at org.hyperledger.besu.ethereum.storage.keyvalue.WorldStateKeyValueStorage$Updater.commit(WorldStateKeyValueStorage.java:216)
        at org.hyperledger.besu.ethereum.worldstate.DefaultMutableWorldState.persist(DefaultMutableWorldState.java:198)
        at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:179)
        at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:78)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:228)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:137)
        at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:74)
        at org.hyperledger.besu.consensus.qbft.validation.ProposalPayloadValidator.validateBlock(ProposalPayloadValidator.java:148)
        at org.hyperledger.besu.consensus.qbft.validation.ProposalPayloadValidator.validate(ProposalPayloadValidator.java:127)
        at org.hyperledger.besu.consensus.qbft.validation.ProposalValidator.validate(ProposalValidator.java:100)
        at org.hyperledger.besu.consensus.qbft.validation.MessageValidator.validateProposal(MessageValidator.java:133)
        at org.hyperledger.besu.consensus.qbft.statemachine.RoundState.setProposedBlock(RoundState.java:87)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.updateStateWithProposedBlock(QbftRound.java:258)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.handleProposalMessage(QbftRound.java:202)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.lambda$handleProposalPayload$1(QbftBlockHeightManager.java:207)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.handleProposalPayload(QbftBlockHeightManager.java:207)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.consumeMessage(BaseBftController.java:126)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftController.handleMessage(QbftController.java:81)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.handleMessageEvent(BaseBftController.java:88)
        at org.hyperledger.besu.consensus.common.bft.EventMultiplexer.handleBftEvent(EventMultiplexer.java:53)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.hyperledger.besu.consensus.common.bft.BftProcessor.run(BftProcessor.java:65)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.rocksdb.RocksDBException: Busy
        at org.rocksdb.Transaction.commit(Native Method)
        at org.rocksdb.Transaction.commit(Transaction.java:208)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage$RocksDbTransaction.commit(RocksDBColumnarKeyValueStorage.java:402)
        ... 28 more
2023-10-12 00:13:21.014+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | MainnetBlockValidator | Invalid block <block number> (0x5...): Optional[org.rocksdb.RocksDBException: Busy], caused by org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
2023-10-12 00:13:21.014+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalPayloadValidator | Invalid Proposal Payload: block did not pass validation. Reason Optional[org.rocksdb.RocksDBException: Busy]
2023-10-12 00:13:21.014+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: invalid proposal payload in proposal message
2023-10-12 00:13:21.036+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,038 / 2 tx / 0 om / 11,175,311 (0.0%) gas / (0x5...) in 2.921s. Peers: 11
2023-10-12 00:13:21.067+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 7213039 (0x1...) is already imported
2023-10-12 00:13:21.067+00:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [7213039]
2023-10-12 00:13:30.506+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftRound | Importing proposed block to chain. round=ConsensusRoundIdentifier{Sequence=7213040, Round=1}, hash=0x1...
2023-10-12 00:13:30.760+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #7,213,040 / 2 tx / 2 pending / 11,175,311 (0.0%) gas / (0x1...)
2023-10-12 00:13:30.770+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,040 / 2 tx / 0 om / 11,175,311 (0.0%) gas / (0x1...) in 0.784s. Peers: 11
2023-10-12 00:13:38.923+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftRound | Importing proposed block to chain. round=ConsensusRoundIdentifier{Sequence=7213041, Round=1}, hash=0xc...
2023-10-12 00:13:39.955+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 7213041 (0xc...) is already imported
2023-10-12 00:13:39.958+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Produced #7,213,041 / 2 tx / 2 pending / 11,175,299 (0.0%) gas / (0xc...)
2023-10-12 00:13:40.070+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,042 / 0 tx / 0 om / 0 (0.0%) gas / (0x13...) in 0.001s. Peers: 11
2023-10-12 00:13:52.327+00:00 | nioEventLoopGroup-3-7 | INFO  | BlockPropagationManager | Saved announced block for future import 7213044 (0x98...) - 1 saved block(s)
2023-10-12 00:13:52.327+00:00 | nioEventLoopGroup-3-7 | INFO  | BlockPropagationManager | Retrieving parent 0x92... of block 7213044 (0x98...)
2023-10-12 00:13:52.339+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftRound | Importing proposed block to chain. round=ConsensusRoundIdentifier{Sequence=7213043, Round=1}, hash=0x92...
2023-10-12 00:13:52.747+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #7,213,043 / 2 tx / 2 pending / 11,175,287 (0.0%) gas / (0x92...)
2023-10-12 00:13:52.821+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,043 / 2 tx / 0 om / 11,175,287 (0.0%) gas / (0x92...) in 1.723s. Peers: 11
2023-10-12 00:13:52.823+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,044 / 0 tx / 0 om / 0 (0.0%) gas / (0x98...) in 0.001s. Peers: 11
2023-10-12 00:13:52.823+00:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [7213044]
2023-10-12 00:14:02.543+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftRound | Importing proposed block to chain. round=ConsensusRoundIdentifier{Sequence=7213045, Round=1}, hash=0xec...
2023-10-12 00:14:03.218+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBesuControllerBuilder | Imported #7,213,045 / 2 tx / 1 pending / 11,175,299 (0.0%) gas / (0xec...)
2023-10-12 00:14:03.219+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,045 / 2 tx / 0 om / 11,175,299 (0.0%) gas / (0xec...) in 1.330s. Peers: 11
2023-10-12 00:14:18.582+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:14:35.468+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:15:07.559+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:15:07.559+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBlockHeightManager | Received future Proposal which is illegal, no round change triggered.
2023-10-12 00:16:08.620+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:18:16.978+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:22:33.139+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:31:04.671+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 00:48:08.598+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 01:22:16.671+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 02:30:32.530+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 02:30:32.530+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | QbftBlockHeightManager | Received future Proposal which is illegal, no round change triggered.
2023-10-12 04:47:04.668+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 09:20:08.665+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
2023-10-12 18:26:16.710+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
```

### Additional Information 
Besu setup info 

```
besu --data-path=<path> \
    --miner-enabled \
    --miner-coinbase=0x0000000000000000000000000000000000000000 \
    --min-gas-price=0 \
    --genesis-file=<path> \
    --rpc-http-enabled \
    --rpc-http-api=ETH,NET,QBFT,WEB3,ADMIN,TXPOOL \
    --host-allowlist="*" \
    --rpc-http-cors-origins="all" \
    --discovery-enabled=false \
    --Xdns-enabled=true \
    --rpc-http-port=23000 \
    --rpc-http-host=$IP \
    --p2p-port=54000 \
    --p2p-host=$IP \
    --p2p-interface=$IP \
    --sync-mode=FULL \
    --metrics-enabled \
    --static-nodes-file=<path>  > /tmp/besu-$(date '+%s').out 2>&1
```

**Comment by garyschulte** [comment]
what is your storage layer configuration on this aws instance?  Besu requires reasonably fast storage, something like attached nvme or EBS volume with IOPS configured in relation to the size of the storage the chain is using.  

`fio` tool can give you concrete numbers on IO performance.  Install that and run this test from the data partition you are using:

`sudo fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75`

FYI, for our dev-test nodes we have machines spec'd fairly lean, and their IO perf on this test is:

```
sudo fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=test --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75
test: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.28
Starting 1 process
test: Laying out IO file (1 file / 4096MiB)
Jobs: 1 (f=1): [m(1)][100.0%][r=10.4MiB/s,w=3523KiB/s][r=2658,w=880 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=1614888: Mon Oct 23 22:35:53 2023
  read: IOPS=2644, BW=10.3MiB/s (10.8MB/s)(3070MiB/297185msec)
   bw (  KiB/s): min= 8192, max=13242, per=100.00%, avg=10583.55, stdev=817.53, samples=594
   iops        : min= 2048, max= 3310, avg=2645.84, stdev=204.37, samples=594
  write: IOPS=883, BW=3535KiB/s (3620kB/s)(1026MiB/297185msec); 0 zone resets
   bw (  KiB/s): min= 2336, max= 3952, per=100.00%, avg=3537.14, stdev=199.26, samples=594
   iops        : min=  584, max=  988, avg=884.20, stdev=49.80, samples=594
  cpu          : usr=0.49%, sys=1.76%, ctx=327358, majf=0, minf=7
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=785920,262656,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=10.3MiB/s (10.8MB/s), 10.3MiB/s-10.3MiB/s (10.8MB/s-10.8MB/s), io=3070MiB (3219MB), run=297185-297185msec
  WRITE: bw=3535KiB/s (3620kB/s), 3535KiB/s-3535KiB/s (3620kB/s-3620kB/s), io=1026MiB (1076MB), run=297185-297185msec

Disk stats (read/write):
  sda: ios=785917/263364, merge=0/53, ticks=13807664/5245717, in_queue=19053382, util=99.62%
```

**Comment by garyschulte** [comment]
@siladu @jframe - are you aware of any qbft-specific concurrency that might cause rocksdb busy errors during block processing and/or reorgs?  The logs seem to show either a reorg or out-of-order block processing:

```
2023-10-12 00:13:21.014+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | MainnetBlockValidator | Invalid block <block number> (0x5...): Optional[org.rocksdb.RocksDBException: Busy], caused by org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
2023-10-12 00:13:21.014+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalPayloadValidator | Invalid Proposal Payload: block did not pass validation. Reason Optional[org.rocksdb.RocksDBException: Busy]
2023-10-12 00:13:21.014+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: invalid proposal payload in proposal message
2023-10-12 00:13:21.036+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #7,213,038 / 2 tx / 0 om / 11,175,311 (0.0%) gas / (0x5...) in 2.921s. Peers: 11
2023-10-12 00:13:21.067+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 7213039 (0x1...) is already imported
2023-10-12 00:13:21.067+00:00 | EthScheduler-Workers-0 | INFO  | BlockPropagationManager | Imported 1 pending blocks: [7213039]
```

**Comment by matthew1001** [comment]
Afraid I'm not familiar enough with the QBFT logic to know whether it does anything that might cause this.

**Comment by pullurib** [comment]
@kkeaton-rcp @matthew1001  Here's what I think happened here and a probable fix : 
From the log timing , looks like the storage exception was thrown only once and then besu recovered from it given it went on to mine other blocks . That way , it's different from #5441 as the storage exception there was thrown every time there was an attempt to persist the block. In this case, the problem is QBFT getting stuck  with following log 
```
 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: Latest Prepared Metadata blockhash does not align with proposed block
```
This is same as the bug in #6732 which stalls consensus and increments rounds with exponential increase in round times. In this case round time went upto 8 hours . I raised a PR for fixing this stall - #7875 which I believe would serve as a fix for this issue too.
