### ISSUE TITLE
besu t8n fails pyspec generated test

### ISSUE THREAD

**Issue by winsvega** [hyperledger/besu#6104]
Get this strange failure on a pyspec test by besu

```
Response test_importRawBlock: 0xe8f86f237690ec4a5a2fe437b0780abd3ef86265e3a6fce1c3047a8af6befb5d

Request: test_setChainParams 
{
    "params" : {
        "fork" : "Cancun",
        "terminalTotalDifficulty" : "0x00",
        "constantinopleForkBlock" : "0x00",
        "byzantiumForkBlock" : "0x00",
        "homesteadForkBlock" : "0x00",
        "chainID" : "0x01"
    },
    "accounts" : {
        "0x00000000000000000000000000000000000000aa" : {
            "balance" : "0x00",
            "code" : "0x61001c600081600b8239f334600014601857346001146010575b005b47600055600e565b60aaff",
            "nonce" : "0x00",
            "storage" : {
            }
        },
        "0x00000000000000000000000000000000000000cc" : {
            "balance" : "0x3b9aca00",
            "code" : "0x60aa3b6000600060aa3c60aa3b60006003f06000600060006000600073864bbda5c698ac34b47a9ea3bd4228802cc5ce3b620186a0f162ca1101556000600060006000600173864bbda5c698ac34b47a9ea3bd4228802cc5ce3b620186a0f1",
            "nonce" : "0x01",
            "storage" : {
            }
        },
        "0x000000000000000000000000000000000000ba11" : {
            "balance" : "0x00",
            "code" : "0x73864bbda5c698ac34b47a9ea3bd4228802cc5ce3b31620ba1aa55",
            "nonce" : "0x00",
            "storage" : {
            }
        },
        "0x000000000000000000000000000000000000ba12" : {
            "balance" : "0x00",
            "code" : "0x73864bbda5c698ac34b47a9ea3bd4228802cc5ce3b31620ba1aa55",
            "nonce" : "0x00",
            "storage" : {
            }
        },
        "0x000f3df6d732807ef1319fb7b8bb8522d0beac02" : {
            "balance" : "0x00",
            "code" : "0x3373fffffffffffffffffffffffffffffffffffffffe14604d57602036146024575f5ffd5b5f35801560495762001fff810690815414603c575f5ffd5b62001fff01545f5260205ff35b5f5ffd5b62001fff42064281555f359062001fff015500",
            "nonce" : "0x01",
            "storage" : {
            }
        },
        "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
            "balance" : "0x3b9aca00",
            "code" : "0x",
            "nonce" : "0x00",
            "storage" : {
            }
        }
    },
    "sealEngine" : "NoProof",
    "genesis" : {
        "author" : "0x0000000000000000000000000000000000000000",
        "difficulty" : "0x00",
        "gasLimit" : "0x016345785d8a0000",
        "baseFeePerGas" : "0x07",
        "withdrawalsRoot" : "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        "currentExcessBlobGas" : "0x00",
        "currentBlobGasUsed" : "0x00",
        "currentBeaconRoot" : "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData" : "0x00",
        "timestamp" : "0x00",
        "nonce" : "0x0000000000000000",
        "mixHash" : "0x0000000000000000000000000000000000000000000000000000000000000000"
    }
}
Alloc:
{
    "0x00000000000000000000000000000000000000aa" : {
        "balance" : "0x00",
        "code" : "0x61001c600081600b8239f334600014601857346001146010575b005b47600055600e565b60aaff",
        "nonce" : "0x00",
        "storage" : {
        }
    },
    "0x00000000000000000000000000000000000000cc" : {
        "balance" : "0x3b9aca00",
        "code" : "0x60aa3b6000600060aa3c60aa3b60006003f06000600060006000600073864bbda5c698ac34b47a9ea3bd4228802cc5ce3b620186a0f162ca1101556000600060006000600173864bbda5c698ac34b47a9ea3bd4228802cc5ce3b620186a0f1",
        "nonce" : "0x01",
        "storage" : {
        }
    },
    "0x000000000000000000000000000000000000ba11" : {
        "balance" : "0x00",
        "code" : "0x73864bbda5c698ac34b47a9ea3bd4228802cc5ce3b31620ba1aa55",
        "nonce" : "0x00",
        "storage" : {
        }
    },
    "0x000000000000000000000000000000000000ba12" : {
        "balance" : "0x00",
        "code" : "0x73864bbda5c698ac34b47a9ea3bd4228802cc5ce3b31620ba1aa55",
        "nonce" : "0x00",
        "storage" : {
        }
    },
    "0x000f3df6d732807ef1319fb7b8bb8522d0beac02" : {
        "balance" : "0x00",
        "code" : "0x3373fffffffffffffffffffffffffffffffffffffffe14604d57602036146024575f5ffd5b5f35801560495762001fff810690815414603c575f5ffd5b62001fff01545f5260205ff35b5f5ffd5b62001fff42064281555f359062001fff015500",
        "nonce" : "0x01",
        "storage" : {
        }
    },
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
        "balance" : "0x3b9aca00",
        "code" : "0x",
        "nonce" : "0x00",
        "storage" : {
        }
    }
}
Env:
{
    "currentCoinbase" : "0x0000000000000000000000000000000000000000",
    "currentDifficulty" : "0x00",
    "currentNumber" : "0x00",
    "currentTimestamp" : "0x00",
    "currentGasLimit" : "0x016345785d8a0000",
    "previousHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
    "currentBaseFee" : "0x07",
    "parentExcessBlobGas" : "0x00",
    "parentBlobGasUsed" : "0x00",
    "currentBeaconRoot" : "0x0000000000000000000000000000000000000000000000000000000000000000",
    "currentRandom" : "0x0000000000000000000000000000000000000000000000000000000000000000",
    "withdrawals" : [
    ],
    "parentBeaconBlockRoot" : "0x0000000000000000000000000000000000000000000000000000000000000000"
}
/home/wins/.retesteth/besu/start.sh --state.fork Cancun --state.reward -1 --state.chainid 1 --input.alloc /dev/shm/1e3b17f1-36bc-4027-baaf-76971af5e7f2/alloc.json --input.txs /dev/shm/1e3b17f1-36bc-4027-baaf-76971af5e7f2/txs.rlp --input.env /dev/shm/1e3b17f1-36bc-4027-baaf-76971af5e7f2/env.json --output.basedir /dev/shm/1e3b17f1-36bc-4027-baaf-76971af5e7f2 --output.result out.json --output.alloc outAlloc.json --output.errorlog /dev/shm/1e3b17f1-36bc-4027-baaf-76971af5e7f2/error.json

Res:

RAlloc:

Error: Tool returned empty file: /dev/shm/1e3b17f1-36bc-4027-baaf-76971af5e7f2/out.json
Tool log: 

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "nm" is null
	at java.base/java.lang.Long.decode(Long.java:1263)
	at org.hyperledger.besu.ethereum.referencetests.ReferenceTestEnv.updateFromParentValues(ReferenceTestEnv.java:236)
	at org.hyperledger.besu.evmtool.T8nExecutor.runTest(T8nExecutor.java:251)
	at org.hyperledger.besu.evmtool.T8nSubCommand.run(T8nSubCommand.java:285)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.hyperledger.besu.evmtool.EvmToolCommand.execute(EvmToolCommand.java:277)
	at org.hyperledger.besu.evmtool.EvmToolCommand.execute(EvmToolCommand.java:243)
	at org.hyperledger.besu.evmtool.EvmTool.main(EvmTool.java:23)
 (merge/security/007-fork=Cancun, fork: Cancun, block: 0)
```

**Comment by winsvega** [comment]
fixed
