### ISSUE TITLE
privacy ATs failing because tx pool not enabled during sync

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6402]
think we need a similar fix as was done here for permissioning ATs https://github.com/hyperledger/besu/pull/6384

Note privacy ATs currently running on nightly CI only (not on PRs)

example failure here https://app.circleci.com/pipelines/github/hyperledger/besu/26334/workflows/9ca2d46b-92df-4646-9e7d-fe9153826766/jobs/173226 with error "Transaction pool not enabled"

**Comment by macfarla** [comment]
cc @gtebrean this flakiness may impact you on #5968

**Comment by macfarla** [comment]
reopening this since we're still seeing occasional failures - flakiness with "Invalid params" or sometimes "tx pool not enabled" - so we think something is missing with the sync checks, getting receipts, web3j and the transaction pool

**Comment by macfarla** [comment]
example failure
```
PrivacyClusterAcceptanceTest > [TESSERA enclave type with EC encryptor] > org.hyperledger.besu.tests.acceptance.privacy.PrivacyClusterAcceptanceTest.canInteractWithMultiplePrivacyGroups[TESSERA enclave type with EC encryptor] FAILED
    java.lang.RuntimeException: org.web3j.protocol.exceptions.TransactionException: Error processing request: Invalid params
        at org.hyperledger.besu.tests.acceptance.dsl.privacy.condition.PrivGetTransactionReceiptTransaction.execute(PrivGetTransactionReceiptTransaction.java:49)
        at org.hyperledger.besu.tests.acceptance.dsl.privacy.condition.PrivGetTransactionReceiptTransaction.execute(PrivGetTransactionReceiptTransaction.java:29)
        at org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.execute(BesuNode.java:810)
        at org.hyperledger.besu.tests.acceptance.dsl.privacy.PrivacyNode.execute(PrivacyNode.java:247)
        at org.hyperledger.besu.tests.acceptance.privacy.PrivacyClusterAcceptanceTest.canInteractWithMultiplePrivacyGroups(PrivacyClusterAcceptanceTest.java:350)

        Caused by:
        org.web3j.protocol.exceptions.TransactionException: Error processing request: Invalid params
            at app//org.web3j.tx.response.PrivateTransactionReceiptProcessor.sendTransactionReceiptRequest(PrivateTransactionReceiptProcessor.java:38)
            at app//org.web3j.tx.response.PollingPrivateTransactionReceiptProcessor.getTransactionReceipt(PollingPrivateTransactionReceiptProcessor.java:45)
            at app//org.web3j.tx.response.PollingPrivateTransactionReceiptProcessor.waitForTransactionReceipt(PollingPrivateTransactionReceiptProcessor.java:36)
            at app//org.hyperledger.besu.tests.acceptance.dsl.privacy.condition.PrivGetTransactionReceiptTransaction.execute(PrivGetTransactionReceiptTransaction.java:45)
            ... 4 more
```
