### ISSUE TITLE
add FreeBSD support

### ISSUE THREAD

**Issue by airflow2010** [hyperledger/besu#6495]
### Description
From my limited understanding, besu should be able to be compiled (and run) on FreeBSD quite easily. If I try to compile it however, it fails with the following messages.

```
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalArgumentException: Unknown os.name 'freebsd'.
        at com.diffplug.common.swt.os.OS.calculateNative(OS.java:153)
        at com.diffplug.common.swt.os.OS.detectPlatform(OS.java:116)
        at com.diffplug.common.swt.os.OS.detectPlatform(OS.java:123)
        at com.diffplug.common.swt.os.OS.getRunning(OS.java:109)
        at com.diffplug.common.swt.os.SwtPlatform.getRunning(SwtPlatform.java:124)
        at dev.equo.solstice.BundleContextShim.getProperty(BundleContextShim.java:264)
        at dev.equo.solstice.BundleContextDelegate.getProperty(BundleContextDelegate.java:40)
        at org.eclipse.core.internal.runtime.InternalPlatform.getOS(InternalPlatform.java:396)
        at org.eclipse.core.runtime.Platform.getOS(Platform.java:1192)
        at org.eclipse.core.internal.resources.Workspace.<clinit>(Workspace.java:89)
        ... 148 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessGroovyGradle'.
> java.lang.ExceptionInInitializerError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 36s
107 actionable tasks: 105 executed, 2 up-to-date
```
I think the relevant info is at the beginning at line "Caused by: java.lang.IllegalArgumentException: Unknown os.name 'freebsd'.", which seems to indicate that freebsd is not included in a list of known OS. Could it be as simple as adding this OS to the list?

### Acceptance Criteria
* make besu compilable and executable on FreeBSD

### Versions (Add all that apply)
* Software version: 24.1.1
* Java version: OpenJDK 17.0.9
* OS Name & Version: FreeBSD 13.1-RELEASE-p9

**Comment by siladu** [comment]
Hi @airflow2010 we're using the spotless plugin for code formatting: https://plugins.gradle.org/plugin/com.diffplug.gradle.spotless
Not sure about their support for freebsd, but besu won't be doing anything too unusual in the configuration of spotless.

A workaround for now is to use gradle to skip the spotless tasks...
e.g. `./gradlew build -x spotlessGroovyGradle`

You might find other tasks fail for similar reason along the way.

If you just want to build the besu distribution binaries, you can skip all the formatting, tests, etc and try 
`./gradlew installDist`

**Comment by non-fungible-nelson** [comment]
Closing for @siladu's suggestions - if these suggestions do not help, please re-open with more detail. Thank you!

**Comment by airflow2010** [comment]
Hi! Thanks for your comment!

> If you just want to build the besu distribution binaries, you can skip all the formatting, tests, etc and try `./gradlew installDist`

That was a helpful advice - as I tried to build with just "./gradlew installDist" the compilation run through without errors.

```
BUILD SUCCESSFUL in 3s
98 actionable tasks: 2 executed, 96 up-to-date
```

When I startup the daemon, it crashes with information about librocksdbjni missing:

```
2024-02-06 15:49:20.936+00:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Paris:0, Paris:1150000, Paris:1920000, Paris:1920001, Paris:1920010, Paris:2463000, Paris:2675000, Paris:4370000, Paris:7280000, Paris:9069000, Paris:9200000, Paris:12244000, Paris:12965000, Paris:13773000, Paris:15050000, Shanghai:1681338455]
2024-02-06 15:49:21.385+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | No existing database detected at /usr/local/share/besu-24.1.1/build/install/besu. Using version 1
2024-02-06 15:49:21.459+00:00 | main | ERROR | Besu | Uncaught exception in thread "main"
java.lang.ExceptionInInitializerError
        at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDbUtil.loadNativeLibrary(RocksDbUtil.java:32)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.<clinit>(RocksDBColumnarKeyValueStorage.java:91)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBKeyValueStorageFactory.create(RocksDBKeyValueStorageFactory.java:197)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProviderBuilder.lambda$build$0(KeyValueStorageProviderBuilder.java:62)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProvider.getStorageBySegmentIdentifier(KeyValueStorageProvider.java:97)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProvider.createVariablesStorage(KeyValueStorageProvider.java:66)
        at org.hyperledger.besu.controller.BesuControllerBuilder.build(BesuControllerBuilder.java:598)
        at org.hyperledger.besu.controller.TransitionBesuControllerBuilder.build(TransitionBesuControllerBuilder.java:295)
        at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:2156)
        at org.hyperledger.besu.cli.BesuCommand.initController(BesuCommand.java:2144)
        at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1456)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:61)
        at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:33)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1621)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1417)
        at org.hyperledger.besu.Besu.main(Besu.java:39)
Caused by: java.lang.RuntimeException: librocksdbjni-freebsd64.so was not found inside JAR.
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:118)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:36)
        ... 28 more
```

I then searched if "rocksdb" could be installed as a dependency of besu, and I installed rocksdb-8.9.1 on the system. The besu executable however still crashes missing that libraries. It seems this specific library is not included or not available on FreeBSD. Would you agree, is there some direction I could investigate or something I should try?
