### ISSUE TITLE
add FreeBSD support (2)

### ISSUE THREAD

**Issue by airflow2010** [hyperledger/besu#6535]
Hi! Thanks for your comment! Sorry, I had to open another issue, as it was not possible to re-open the existing one, which has been closed.

> If you just want to build the besu distribution binaries, you can skip all the formatting, tests, etc and try `./gradlew installDist`

That was a helpful advice - as I tried to build with just "./gradlew installDist" the compilation run through without errors.

```
BUILD SUCCESSFUL in 3s
98 actionable tasks: 2 executed, 96 up-to-date
```

When I startup the daemon, it crashes with information about librocksdbjni missing:

```
2024-02-06 15:49:20.936+00:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Paris:0, Paris:1150000, Paris:1920000, Paris:1920001, Paris:1920010, Paris:2463000, Paris:2675000, Paris:4370000, Paris:7280000, Paris:9069000, Paris:9200000, Paris:12244000, Paris:12965000, Paris:13773000, Paris:15050000, Shanghai:1681338455]
2024-02-06 15:49:21.385+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | No existing database detected at /usr/local/share/besu-24.1.1/build/install/besu. Using version 1
2024-02-06 15:49:21.459+00:00 | main | ERROR | Besu | Uncaught exception in thread "main"
java.lang.ExceptionInInitializerError
        at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDbUtil.loadNativeLibrary(RocksDbUtil.java:32)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.segmented.RocksDBColumnarKeyValueStorage.<clinit>(RocksDBColumnarKeyValueStorage.java:91)
        at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBKeyValueStorageFactory.create(RocksDBKeyValueStorageFactory.java:197)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProviderBuilder.lambda$build$0(KeyValueStorageProviderBuilder.java:62)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProvider.getStorageBySegmentIdentifier(KeyValueStorageProvider.java:97)
        at org.hyperledger.besu.ethereum.storage.keyvalue.KeyValueStorageProvider.createVariablesStorage(KeyValueStorageProvider.java:66)
        at org.hyperledger.besu.controller.BesuControllerBuilder.build(BesuControllerBuilder.java:598)
        at org.hyperledger.besu.controller.TransitionBesuControllerBuilder.build(TransitionBesuControllerBuilder.java:295)
        at org.hyperledger.besu.cli.BesuCommand.buildController(BesuCommand.java:2156)
        at org.hyperledger.besu.cli.BesuCommand.initController(BesuCommand.java:2144)
        at org.hyperledger.besu.cli.BesuCommand.run(BesuCommand.java:1456)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:61)
        at org.hyperledger.besu.cli.util.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:33)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1621)
        at org.hyperledger.besu.cli.BesuCommand.parse(BesuCommand.java:1417)
        at org.hyperledger.besu.Besu.main(Besu.java:39)
Caused by: java.lang.RuntimeException: librocksdbjni-freebsd64.so was not found inside JAR.
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:118)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:102)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:82)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:36)
        ... 28 more
```

I then searched if "rocksdb" could be installed as a dependency of besu, and I installed rocksdb-8.9.1 on the system. The besu executable however still crashes missing that libraries. It seems this specific library is not included or not available on FreeBSD. Would you agree, is there some direction I could investigate or something I should try?

_Originally posted by @airflow2010 in https://github.com/hyperledger/besu/issues/6495#issuecomment-1930121834_

**Comment by siladu** [comment]
Thanks for opening the new issue.

Besu has RocksDB as a dependency, specifically it needs to use `rocksdbjni` to talk to rocksdb as a native library via JNI because RocksDB is written in C++.

Looking into RocksDB java support, it unfortunately appears that it isn't compiled for FreeBSD

https://github.com/facebook/rocksdb/blob/main/java/RELEASE.md
> The cross-platform jar can be used on any 64-bit OSX system, 32-bit Linux system, or 64-bit Linux system.

I'm no RocksDB or FreeBSD expert, but I think a way around this might be to build your own version of rocksdbjni compiled for FreeBSD, and then modify Besu to use that. 
Ideally, this would be written as a Besu plugin https://besu.hyperledger.org/23.10.2/private-networks/concepts/plugins
(which is actually how the current besu rocksdb integration works anyway: https://github.com/hyperledger/besu/tree/main/plugins/rocksdb)

Hopefully I can get a second opinion from @ahamlat in case I've missed something

**Comment by siladu** [comment]
>  Couldn't I use just the existing plugin for rocksdb and just replace the rocksdbjni-file?

@airflow2010 yes it's possible but you will be using a forked version of besu which you'd have to maintain, i.e. update and recompile every time you want to deploy...whereas with a plugin you can use the official besu release in conjunction with it.

**Comment by siladu** [comment]
I will close this issue for now, feel free to open another or get in touch on the Hyperledger Discord if you have any further issues.
