### ISSUE TITLE
Invalid block detected (BREACH_OF_PROTOCOL) | IBFT 2.0 

### ISSUE THREAD

**Issue by avenbreaks** [hyperledger/besu#6680]
### Description
After the node stop and then tries to re-run it seems to get an `invalid block detected `error and then the peer disconnects. We build blockchain using besu for private networks. 

### Config 
```
besu/bin/besu \
     --api-gas-price-max=1000000000000000 \
     --min-gas-price=1000000000 \
     --data-path=Node-1/data \
     --data-storage-format=BONSAI \
     --network-id=6666 \
     --rpc-http-enabled=true \
     --rpc-http-host=0.0.0.0 \
     --rpc-http-port=8545 \
     --rpc-http-cors-origins="*" \
     --rpc-http-api=NET,WEB3,ETH,IBFT,ENGINE,TXPOOL,TRACE \
     --rpc-http-authentication-jwt-algorithm=RS256 \
     --rpc-ws-enabled=true \
     --rpc-ws-api=NET,WEB3,ETH,IBFT,ENGINE,TXPOOL,TRACE \
     --rpc-ws-host=0.0.0.0 \
     --rpc-ws-port=8546 \
     --rpc-ws-max-active-connections=100 \
     --rpc-ws-max-frame-size=1048576 \
     --genesis-file=genesis.json \
     --host-allowlist="*" \
     --engine-rpc-enabled=true \
     --engine-host-allowlist="*" \
     --engine-jwt-secret=jwtsecret.hex \
     --engine-rpc-port=8551 \
     --node-private-key-file=/Node-1/data/key \
     --max-peers=4 \
     --Xp2p-peer-lower-bound=4 \
     --sync-mode=FULL \
     --p2p-enabled=true \
     --p2p-host=XXX.XXX.XXX.XXX \
     --p2p-port=30303 \
     --logging=INFO \
     --metrics-enabled=true \
     --metrics-host=0.0.0.0 \
     --metrics-port=9545 \
     --metrics-protocol=PROMETHEUS \
     --metrics-category=BLOCKCHAIN,ETHEREUM,EXECUTORS,NETWORK,PEERS,PERMISSIONING,PRUNER,RPC,SYNCHRONIZER,TRANSACTION_POOL,STRATUM,JVM,PROCESS 

```
### Logs (if a bug)

```
2024-03-05 02:05:41.425+00:00 | BftProcessorExecutor-IBFT-0 | ERROR | AbstractBlockProcessor | failed persisting block
org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
	at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBTransaction.commit(RocksDBTransaction.java:95)
	at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionValidatorDecorator.java:65)
	at org.hyperledger.besu.ethereum.bonsai.storage.BonsaiWorldStateKeyValueStorage$Updater.commit(BonsaiWorldStateKeyValueStorage.java:466)
	at org.hyperledger.besu.ethereum.bonsai.worldview.BonsaiWorldState.persist(BonsaiWorldState.java:432)
	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:194)
	at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:79)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:207)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:135)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:72)
	at org.hyperledger.besu.consensus.ibft.validation.MessageValidator.validateBlock(MessageValidator.java:97)
	at org.hyperledger.besu.consensus.ibft.validation.MessageValidator.validateProposal(MessageValidator.java:80)
	at org.hyperledger.besu.consensus.ibft.statemachine.RoundState.setProposedBlock(RoundState.java:88)
	at org.hyperledger.besu.consensus.ibft.statemachine.IbftRound.updateStateWithProposedBlock(IbftRound.java:228)
	at org.hyperledger.besu.consensus.ibft.statemachine.IbftRound.updateStateWithProposalAndTransmit(IbftRound.java:170)
	at org.hyperledger.besu.consensus.ibft.statemachine.IbftRound.createAndSendProposalMessage(IbftRound.java:123)
	at org.hyperledger.besu.consensus.ibft.statemachine.IbftBlockHeightManager.handleBlockTimerExpiry(IbftBlockHeightManager.java:127)
	at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.handleBlockTimerExpiry(BaseBftController.java:167)
	at org.hyperledger.besu.consensus.common.bft.EventMultiplexer.handleBftEvent(EventMultiplexer.java:65)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.hyperledger.besu.consensus.common.bft.BftProcessor.run(BftProcessor.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.rocksdb.RocksDBException: Busy
	at org.rocksdb.Transaction.commit(Native Method)
	at org.rocksdb.Transaction.commit(Transaction.java:208)
	at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBTransaction.commit(RocksDBTransaction.java:89)
	... 22 more
2024-03-05 02:05:41.428+00:00 | BftProcessorExecutor-IBFT-0 | INFO  | MainnetBlockValidator | Invalid block 2704803 (0x0743edf2e2fd0a61c11ff76cdc1dd82d09e675fc1c4c7c78235af506a2178d3b): Optional[org.rocksdb.RocksDBException: Busy], caused by org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
2024-03-05 02:05:41.428+00:00 | BftProcessorExecutor-IBFT-0 | INFO  | MessageValidator | Invalid Proposal message, block did not pass validation. Reason Optional[org.rocksdb.RocksDBException: Busy]
2024-03-05 02:05:41.601+00:00 | BftProcessorExecutor-IBFT-0 | ERROR | AbstractBlockProcessor | failed persisting block
```

```
2024-03-05 02:05:41.602+00:00 | BftProcessorExecutor-IBFT-0 | INFO  | MainnetBlockValidator | Invalid block 2704878 (0xf8f7026f524b33db9bb0115c4053e5b3f4141de166617f6e51c6c5ff47731cc5): Optional[org.rocksdb.RocksDBException: Busy], caused by org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: Busy
2024-03-05 02:05:41.602+00:00 | BftProcessorExecutor-IBFT-0 | INFO  | MessageValidator | Invalid Proposal message, block did not pass validation. Reason Optional[org.rocksdb.RocksDBException: Busy]
2024-03-05 02:05:41.663+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | MainnetBlockValidator | Invalid block 2704921 (0x5758b561fa7b427883ed71e4975cbe72836fa21d52b6196f8262d048f86c51e8): Optional[Unable to process block because parent world state 0x964e562dbcd2113159cda36946fac806e5ef48e3f10a7289d3c34b84a6635501 is not available]
2024-03-05 02:05:41.666+00:00 | EthScheduler-Services-5 (importBlock) | INFO  | Pipeline | Unexpected exception in pipeline. Aborting.
org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #2704921 (0x5758b561fa7b427883ed71e4975cbe72836fa21d52b6196f8262d048f86c51e8)

```

```
2024-03-05 02:05:41.668+00:00 | EthScheduler-Services-5 (importBlock) | WARN  | PipelineChainDownloader | Invalid block detected (BREACH_OF_PROTOCOL). Disconnecting from sync target. Failed to import block: Invalid block at #2704921 (0x5758b561fa7b427883ed71e4975cbe72836fa21d52b6196f8262d048f86c51e8)
2024-03-05 02:05:41.675+00:00 | EthScheduler-Services-5 (importBlock) | WARN  | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: org.hyperledger.besu.ethereum.eth.sync.tasks.exceptions.InvalidBlockException: Failed to import block: Invalid block at #2704921 (0x5758b561fa7b427883ed71e4975cbe72836fa21d52b6196f8262d048f86c51e8)

```

**Comment by non-fungible-nelson** [comment]
This looks like improper error handling in Besu. Need an exception for rocksDB exception (or wrap with storage exception). Or treat storage exception as separate for a retry. 

@matthew1001 - might be a nice area for cleanup?

**Comment by non-fungible-nelson** [comment]
Hi there @avenbreaks - can you provide your hardware specs here and machine configuration?

**Comment by matthew1001** [comment]
There have been various issues & discussions about the `RocksDBException: Busy` errors:

- https://github.com/hyperledger/besu/pull/5976 
- https://github.com/hyperledger/besu/pull/6004
- https://discord.com/channels/905194001349627914/1204343645847687199/1205121949337133098

I'm not an expert on the DB layer in Besu but retrying operations seems to be the preferred way to resolve these. It would seem to make most sense for it to be handled down in the RocksDB layer so individual places in the codebase don't need to handle it themselves. However for now I've raised a draft PR to use retries for BFT block validation paths:

- https://github.com/hyperledger/besu/pull/6715

I'll try running with it in the scenarios I've hit the `Busy` error to see if it resolves them. If anyone else is able to give it a try (@avenbreaks are you able to see if it resolves your errors?) that would help validate the fix.

**Comment by non-fungible-nelson** [comment]
Sorry @matthew1001, I erroneously tagged you. However, if you want to work on it with @daniellehrner, we can collaborate on discord !

**Comment by avenbreaks** [comment]
> This looks like improper error handling in Besu. Need an exception for rocksDB exception (or wrap with storage exception). We do not have retry logic for a storage exception in IBFT, can be added in the block validator (we can mirror mainnet).

Hi, this is a private blockchain and I have tried to add a new validator but it only synchronizes the old block, to add a new block it does not work at all. for specifications 

```
Digital Ocean VM
16GB RAM 
4 vCPU
1TB SSD 
```

**Comment by matthew1001** [comment]
> Sorry @matthew1001, I erroneously tagged you. However, if you want to work on it with @daniellehrner, we can collaborate on discord !

No problem - it's something I've been involved in various chats about, so thought I might at least try to prove out a fix for another of the code paths. I'll leave my PR in draft for a while until I have time to test it for a longer period of time. I don't mind at all if someone else picks this issue up.

**Comment by avenbreaks** [comment]
Good morning sir, its already solved?

**Comment by sereyvathanatum** [comment]
I faced same issues with QBFT, rollback to version 24.1.0, issue resolved.

**Comment by non-fungible-nelson** [comment]
@daniellehrner - can we status this please?

**Comment by jmc000** [comment]
Facing similar `Invalid block` error here

Last week, I had an issue with Holesky running `24.3.0`. I resynced and upgraded to `24.3.3`, which fixed it until today, but now I am facing a similar error again


here are our logs
```
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]: 2024-04-22 17:42:39.776+02:00 | vert.x-worker-thread-0 | ERROR | AbstractBlockProcessor | failed persisting block
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]: org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: block checksum mismatch: stored = 2102455641, computed = 1576578973, type = 1  in /home/ethereum/var/lib/besu/database/012104.sst offset 8254017 size 32665
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBTransaction.commit(RocksDBTransaction.java:95)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageTransactionValidatorDecorator.commit(SegmentedKeyValueStorageTransactionValidatorDecorator.java:65)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.services.kvstore.SegmentedKeyValueStorageAdapter$KeyValueStorageTransactionAdapter.commit(SegmentedKeyValueStorageAdapter.java:168)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.trie.bonsai.storage.BonsaiWorldStateKeyValueStorage$Updater.commit(BonsaiWorldStateKeyValueStorage.java:462)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.trie.bonsai.worldview.BonsaiWorldState.persist(BonsaiWorldState.java:460)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:209)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:79)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:207)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:135)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:83)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.validateBlock(MergeCoordinator.java:551)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.consensus.merge.blockcreation.MergeCoordinator.rememberBlock(MergeCoordinator.java:581)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.consensus.merge.blockcreation.TransitionCoordinator.rememberBlock(TransitionCoordinator.java:164)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.engine.AbstractEngineNewPayload.syncResponse(AbstractEngineNewPayload.java:319)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.ExecutionEngineJsonRpcMethod.lambda$response$0(ExecutionEngineJsonRpcMethod.java:90)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at java.base/java.lang.Thread.run(Thread.java:840)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]: Caused by: org.rocksdb.RocksDBException: block checksum mismatch: stored = 2102455641, computed = 1576578973, type = 1  in /home/ethereum/var/lib/besu/database/012104.sst offset 8254017 size 32665
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.rocksdb.Transaction.commit(Native Method)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.rocksdb.Transaction.commit(Transaction.java:207)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         at org.hyperledger.besu.plugin.services.storage.rocksdb.RocksDBTransaction.commit(RocksDBTransaction.java:89)
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]:         ... 22 more
Apr 22 17:42:39 ethereum-holesky-02 besu[263501]: 2024-04-22 17:42:39.776+02:00 | vert.x-worker-thread-0 | INFO  | MainnetBlockValidator | Invalid block 1397638 (0xd81f964406264f7a7c4cfa0b9eef957aee1eae2e3499dfec35583038b443ad9b): Optional[org.rocksdb.RocksDBException] block checksum mismatch: stored = 2102455641, computed = 1576578973, type = 1  in /home/ethereum/var/lib/besu/database/012104.sst offset 8254017 size 32665], caused by org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: block checksum mismatch: stored = 2102455641, computed = 1576578973, type = 1  in /home/ethereum/var/lib/besu/database/012104.sst offset 8254017 size 32665
Apr 22 17:42:45 ethereum-holesky-02 besu[263501]: 2024-04-22 17:42:45.041+02:00 | vert.x-worker-thread-0 | ERROR | AbstractBlockProcessor | failed persisting block
Apr 22 17:42:45 ethereum-holesky-02 besu[263501]: org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: block checksum mismatch: stored = 2102455641, computed = 1576578973, type = 1  in /home/ethereum/var/lib/besu/database/012104.sst offset 8254017 size 32665
```

Server specs:
```
63Go RAM
6 CPU
1.9T NVME (1.7T free)
```

binary configuration:
```
besu \
  --network=holesky \
  --logging=INFO \
  --host-allowlist=localhost,127.0.0.1 \
  --metrics-enabled=true \
  --metrics-port=6061 \
  --metrics-host=0.0.0.0 \
  --rpc-http-enabled=true \
  --rpc-http-port=8545 \
  --rpc-ws-enabled=True \
  --rpc-ws-host=0.0.0.0 \
  --rpc-ws-port=8554 \
  --max-peers=10 \
  --sync-mode=X_CHECKPOINT \
  --data-storage-format=BONSAI \
  --data-path=/home/ethereum/var/lib/besu \
  --Xplugin-rocksdb-high-spec-enabled \
  --engine-jwt-secret=/home/ethereum/secrets/jwtsecret
```

**Comment by shubham-edx** [comment]
@matthew1001 any workaround with this issue?
we are facing this issue in our blockchain.
![image](https://github.com/hyperledger/besu/assets/53253101/c2765bb6-bf04-47e9-82c2-055e34e28c25)

**Comment by shubham-edx** [comment]
@avenbreaks were you able to resolve this issue?

**Comment by macfarla** [comment]
@daniellehrner has been working on this - can you give an update?

**Comment by daniellehrner** [comment]
I am working on it, but there are several different issues causing this error. The initial one was a RocksDB busy exception, but we have also seen block checksum mismatch errors and world state root mismatch. All of those can cause the block import to fail and cause a breach of protocol error. But all of those have different root causes. 

We might want to include a retry mechanism for block imports an private chains. Getting Bonsai working with private chains should fix some of the issues mentioned as well.

**Comment by matthew1001** [comment]
Starting some more testing of `BONSAI` + `QBFT` and found it easy to hit the `World State Root does not match expected value` bug:

```
2024-05-21 08:38:23.353+00:00 | EthScheduler-Workers-0 | INFO  | AbstractBlockProcessor | Block processing error: transaction invalid transaction nonce 1 below sender account nonce 2. Block 0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68 Transaction 0x88ea452a77fb685d0d7fd2d0cc55d9aa49fa49cb59cb5d5f2d3ad613a6b194d7
2024-05-21 08:38:23.354+00:00 | EthScheduler-Workers-0 | INFO  | MainnetBlockValidator | Invalid block 21705 (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68): Optional[Block processing error: transaction invalid transaction nonce 1 below sender account nonce 2. Block 0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68 Transaction 0x88ea452a77fb685d0d7fd2d0cc55d9aa49fa49cb59cb5d5f2d3ad613a6b194d7]
2024-05-21 08:38:23.355+00:00 | EthScheduler-Workers-0 | WARN  | BlockPropagationManager | Failed to import announced block 21705 (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68)
2024-05-21 08:38:23.377+00:00 | EthScheduler-Workers-0 | INFO  | AbstractBlockProcessor | Block processing error: transaction invalid transaction nonce 1 below sender account nonce 2. Block 0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68 Transaction 0x88ea452a77fb685d0d7fd2d0cc55d9aa49fa49cb59cb5d5f2d3ad613a6b194d7
2024-05-21 08:38:23.385+00:00 | EthScheduler-Workers-0 | INFO  | MainnetBlockValidator | Invalid block 21705 (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68): Optional[Block processing error: transaction invalid transaction nonce 1 below sender account nonce 2. Block 0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68 Transaction 0x88ea452a77fb685d0d7fd2d0cc55d9aa49fa49cb59cb5d5f2d3ad613a6b194d7]
2024-05-21 08:38:23.386+00:00 | EthScheduler-Workers-0 | WARN  | BlockPropagationManager | Failed to import announced block 21705 (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68)
2024-05-21 08:38:23.395+00:00 | BftProcessorExecutor-QBFT-0 | ERROR | AbstractBlockProcessor | failed persisting block
java.lang.RuntimeException: World State Root does not match expected value, header 0x04a4e0109f2946a13fb4ddf9996dd418de36101b0375a794e3f8fdff8649a801 calculated 0x798ae33cd647de60decf98a9510c20ac509070fe4ed756eb870cb9d7d08790a9
	at org.hyperledger.besu.ethereum.trie.diffbased.common.worldview.DiffBasedWorldState.verifyWorldStateRoot(DiffBasedWorldState.java:203)
	at org.hyperledger.besu.ethereum.trie.diffbased.common.worldview.DiffBasedWorldState.persist(DiffBasedWorldState.java:161)
	at org.hyperledger.besu.ethereum.mainnet.AbstractBlockProcessor.processBlock(AbstractBlockProcessor.java:214)
	at org.hyperledger.besu.ethereum.mainnet.BlockProcessor.processBlock(BlockProcessor.java:79)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.processBlock(MainnetBlockValidator.java:221)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:140)
	at org.hyperledger.besu.ethereum.MainnetBlockValidator.validateAndProcessBlock(MainnetBlockValidator.java:73)
	at org.hyperledger.besu.consensus.qbft.validation.ProposalPayloadValidator.validateBlock(ProposalPayloadValidator.java:152)
	at org.hyperledger.besu.consensus.qbft.validation.ProposalPayloadValidator.validate(ProposalPayloadValidator.java:129)
	at org.hyperledger.besu.consensus.qbft.validation.ProposalValidator.validate(ProposalValidator.java:103)
	at org.hyperledger.besu.consensus.qbft.validation.MessageValidator.validateProposal(MessageValidator.java:133)
	at org.hyperledger.besu.consensus.qbft.statemachine.RoundState.setProposedBlock(RoundState.java:87)
	at org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.updateStateWithProposedBlock(QbftRound.java:265)
	at org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.handleProposalMessage(QbftRound.java:209)
	at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.lambda$handleProposalPayload$1(QbftBlockHeightManager.java:235)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.handleProposalPayload(QbftBlockHeightManager.java:235)
	at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.consumeMessage(BaseBftController.java:126)
	at org.hyperledger.besu.consensus.qbft.statemachine.QbftController.handleMessage(QbftController.java:81)
	at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.handleMessageEvent(BaseBftController.java:88)
	at org.hyperledger.besu.consensus.common.bft.EventMultiplexer.handleBftEvent(EventMultiplexer.java:53)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.hyperledger.besu.consensus.common.bft.BftProcessor.run(BftProcessor.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-05-21 08:38:23.405+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | MainnetBlockValidator | Failed to process block 21705 (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68): Optional[World State Root does not match expected value, header 0x04a4e0109f2946a13fb4ddf9996dd418de36101b0375a794e3f8fdff8649a801 calculated 0x798ae33cd647de60decf98a9510c20ac509070fe4ed756eb870cb9d7d08790a9], caused by java.lang.RuntimeException: World State Root does not match expected value, header 0x04a4e0109f2946a13fb4ddf9996dd418de36101b0375a794e3f8fdff8649a801 calculated 0x798ae33cd647de60decf98a9510c20ac509070fe4ed756eb870cb9d7d08790a9
2024-05-21 08:38:23.406+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalPayloadValidator | Invalid Proposal Payload: block did not pass validation. Reason Optional[World State Root does not match expected value, header 0x04a4e0109f2946a13fb4ddf9996dd418de36101b0375a794e3f8fdff8649a801 calculated 0x798ae33cd647de60decf98a9510c20ac509070fe4ed756eb870cb9d7d08790a9]
2024-05-21 08:38:23.425+00:00 | BftProcessorExecutor-QBFT-0 | INFO  | ProposalValidator | Invalid Proposal Payload: invalid proposal payload in proposal message
2024-05-21 08:38:25.028+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Saved announced block for future import 21706 (0x82fc66577696322bd5a0efd06f1c5c969eebc5dbc9cff2ad0a287869cf5d11ff) - 1 saved block(s)
2024-05-21 08:38:25.028+00:00 | nioEventLoopGroup-3-3 | INFO  | BlockPropagationManager | Retrieving parent 0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68 of block 21706 (0x82fc66577696322bd5a0efd06f1c5c969eebc5dbc9cff2ad0a287869cf5d11ff)
2024-05-21 08:38:25.119+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #21,705 / 1 tx / 0 om / 1,343,717 (0.2%) gas / (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68) in 0.060s. Peers: 3
2024-05-21 08:38:25.128+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Block 21706 (0x82fc66577696322bd5a0efd06f1c5c969eebc5dbc9cff2ad0a287869cf5d11ff) is already imported
```

In my particular case all I did was leave the nodes mining empty blocks, then submit a new transaction. Interestingly the block complained about above, `21705`, did eventually get included in the chain:

```
2024-05-21 08:38:25.119+00:00 | EthScheduler-Workers-0 | INFO  | PersistBlockTask | Imported #21,705 / 1 tx / 0 om / 1,343,717 (0.2%) gas / (0x9af85cd9c4c1d9c1b0cfd4decf6c26b018c553ac615642e30c3dff930c4b6e68) in 0.060s. Peers: 3
```

and the transaction has a receipt. So the transaction eventually got mined correctly, but after lots of errors being reported.

**Comment by matthew1001** [comment]
Putting more findings here as I'm looking into this again. The recreate I have locally shows the in most cases (i.e. where there's no block import error) the node validates each block twice:

```
org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.handleProposalMessage
```

and

```
org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManager.handleCommitPayload
```

Note that both of these paths are QBFT block handling. Occasionally Besu throws the `Invalid block` error and when that happens the block is again being validated twice:

```
org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.handleProposalMessage
```

and

```
org.hyperledger.besu.ethereum.eth.sync.BlockPropagationManager.validateAndProcessPendingBlock
```

Note that in this case, the second block validation step is in the ethereum block propagation code path, not the QBFT code path. I'm guessing there might be a race condition between a node receiving a QBFT commit message and it receiving a `NewBlock` via the ethereum protocol. Possibly the `NewBlock` message is a no-op if the block has already been imported by a QBFT commit.

The initial `org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.handleProposalMessage` validation is persisting the validated block in both cases, something which should only be done at QBFT commit or Ethereum `NewBlock` time. I'm going to change `org.hyperledger.besu.consensus.qbft.statemachine.QbftRound.handleProposalMessage` to not persist state.
