### ISSUE TITLE
Flaky test - EthSendRawTransactionAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6718]
eg https://github.com/hyperledger/besu/actions/runs/8256202429/job/22584394562?pr=6665

```
> Task :acceptance-tests:tests:acceptanceTestNotPrivacy

EthSendRawTransactionAcceptanceTest > shouldSendSuccessfullyToLenientNodeWithoutChainId() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.hyperledger.besu.tests.acceptance.dsl.condition.eth.ExpectSuccessfulEthGetTransactionReceipt 
    Expecting Optional to contain a value but it was empty within 1 minutes.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.eth.ExpectSuccessfulEthGetTransactionReceipt.verify(ExpectSuccessfulEthGetTransactionReceipt.java:35)
        at app//org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.verify(BesuNode.java:823)
        at app//org.hyperledger.besu.tests.acceptance.jsonrpc.EthSendRawTransactionAcceptanceTest.shouldSendSuccessfullyToLenientNodeWithoutChainId(EthSendRawTransactionAcceptanceTest.java:57)

        Caused by:
        java.lang.AssertionError: 
        Expecting Optional to contain a value but it was empty.
            at org.hyperledger.besu.tests.acceptance.dsl.condition.eth.ExpectSuccessfulEthGetTransactionReceipt.lambda$verify$0(ExpectSuccessfulEthGetTransactionReceipt.java:35)
            at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
            at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
            at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:[235](https://github.com/hyperledger/besu/actions/runs/8256202429/job/22584394562?pr=6665#step:9:236))
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by macfarla** [comment]
fixed by #6837
