### ISSUE TITLE
Flaky test - NewPendingTransactionAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6909]
NewPendingTransactionAcceptanceTest Disabled in  #6906

evidence of flakiness: https://github.com/hyperledger/besu/actions/runs/8596349136/job/23553493115?pr=6758

**Comment by macfarla** [comment]
this one is still flaky 
NewPendingTransactionAcceptanceTest > subscriptionToMinerNodeMustReceiveEveryPublishEvent() FAILED
eg https://github.com/hyperledger/besu/actions/runs/8769973760/job/24066042552
        at app//org.hyperledger.besu.tests.acceptance.pubsub.NewPendingTransactionAcceptanceTest.subscriptionToMinerNodeMustReceiveEveryPublishEvent(NewPendingTransactionAcceptanceTest.java:132)

**Comment by macfarla** [comment]
interesting because it's actually receiving one MORE event than expected

NewPendingTransactionAcceptanceTest > subscriptionToMinerNodeMustReceiveEveryPublishEvent() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.hyperledger.besu.tests.acceptance.dsl.pubsub.WebSocket 
    Expected size: 3 but was: 4

**Comment by macfarla** [comment]
flaked again here https://github.com/hyperledger/besu/actions/runs/9026109530/job/24802900146?pr=7054
```
2024-05-10T02:04:22.1956281Z NewPendingTransactionAcceptanceTest > subscriptionToMinerNodeMustReceiveEveryPublishEvent() FAILED
2024-05-10T02:04:22.1957732Z     java.lang.AssertionError: 
2024-05-10T02:04:22.1958395Z     Expected size: 3 but was: 4 in:
2024-05-10T02:04:22.1959301Z     [org.hyperledger.besu.tests.acceptance.dsl.pubsub.SubscriptionEvent@2017699,
2024-05-10T02:04:22.1960594Z         org.hyperledger.besu.tests.acceptance.dsl.pubsub.SubscriptionEvent@51405db0,
2024-05-10T02:04:22.2201384Z         org.hyperledger.besu.tests.acceptance.dsl.pubsub.SubscriptionEvent@5ba05c50,
2024-05-10T02:04:22.2202868Z         org.hyperledger.besu.tests.acceptance.dsl.pubsub.SubscriptionEvent@3cd73556]
2024-05-10T02:04:22.2204596Z         at org.hyperledger.besu.tests.acceptance.dsl.pubsub.WebSocket.lambda$verifyTotalEventsReceived$0(WebSocket.java:56)
2024-05-10T02:04:22.2206220Z         at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
2024-05-10T02:04:22.2651676Z         at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
2024-05-10T02:04:22.2653100Z         at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
2024-05-10T02:04:22.2654278Z         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-05-10T02:04:22.2656066Z         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-05-10T02:04:22.2657571Z         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-05-10T02:04:22.2658697Z         at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-10T02:06:07.7952031Z 
2024-05-10T02:06:07.7952574Z 38 tests completed, 1 failed, 4 skipped
2024-05-10T02:06:08.0944921Z 
2024-05-10T02:06:08.0946522Z > Task :acceptance-tests:tests:acceptanceTestNotPrivacy FAILED
```

**Comment by macfarla** [comment]
flaked again https://github.com/hyperledger/besu/actions/runs/13647208778/job/38148168140

```
NewPendingTransactionAcceptanceTest > subscriptionToArchiveNodeMustReceiveEveryPublishEvent() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 7000000000000000000
     but was: 2000000000000000000
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.account.ExpectAccountBalance.lambda$verify$0(ExpectAccountBalance.java:50)
        at app//org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
        at java.base@21.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.6/java.lang.Thread.run(Thread.java:1583)
```
