### ISSUE TITLE
Flaky test - PkiQbftAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6932]
example failure https://github.com/hyperledger/besu/actions/runs/8642678371/job/23694202529?pr=6931

PkiQbftAcceptanceTest > shouldMineWithIgnoringANodeInCRL(String, PkiQbftAcceptanceTestParameterization) > org.hyperledger.besu.tests.acceptance.bft.pki.PkiQbftAcceptanceTest.shouldMineWithIgnoringANodeInCRL(String, PkiQbftAcceptanceTestParameterization)[2] FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.hyperledger.besu.tests.acceptance.dsl.condition.net.AwaitNetPeerCount 
    expected: 3
     but was: 2 within 30 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:24)
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.net.AwaitNetPeerCount.verify(AwaitNetPeerCount.java:39)
        at app//org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.verify(BesuNode.java:842)
        at app//org.hyperledger.besu.tests.acceptance.dsl.node.BesuNode.awaitPeerDiscovery(BesuNode.java:560)
        at app//org.hyperledger.besu.tests.acceptance.dsl.node.cluster.Cluster.start(Cluster.java:99)
        at app//org.hyperledger.besu.tests.acceptance.dsl.node.cluster.Cluster.start(Cluster.java:67)
        at app//org.hyperledger.besu.tests.acceptance.bft.pki.PkiQbftAcceptanceTest.shouldMineWithIgnoringANodeInCRL(PkiQbftAcceptanceTest.java:92)

**Comment by macfarla** [comment]
I ran this test locally in my IDE and it took 41 minutes for the class (18 tests). but all passed.
