### ISSUE TITLE
Flaky test - Clique Mining

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6974]
line 95 fails

**Comment by macfarla** [comment]
example failure https://github.com/hyperledger/besu/actions/runs/8750124596/job/24013033313

CliqueMiningAcceptanceTest > shouldMineTransactionsOnMultipleNodes() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.hyperledger.besu.tests.acceptance.dsl.condition.account.ExpectAccountBalance 
    expected: 50000000000000000000
     but was: 0 within 30 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:24)
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.account.ExpectAccountBalance.verify(ExpectAccountBalance.java:49)
        at app//org.hyperledger.besu.tests.acceptance.dsl.node.cluster.Cluster.verify(Cluster.java:194)
        at app//org.hyperledger.besu.tests.acceptance.clique.CliqueMiningAcceptanceTest.shouldMineTransactionsOnMultipleNodes(CliqueMiningAcceptanceTest.java:95)
