### ISSUE TITLE
Flaky test - NodeSmartContractPermissioningOutOfSyncAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7108]
https://github.com/hyperledger/besu/actions/runs/8880830707/job/24382499661?pr=6161

```
NodeSmartContractPermissioningOutOfSyncAcceptanceTest > addNodeToClusterAndVerifyNonBootNodePeerConnectionWorksAfterSync() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.hyperledger.besu.tests.acceptance.dsl.AcceptanceTestBase 
    Expecting actual:
      20
    to be greater than or equal to:
      25
     within 2 minutes.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:769)
        at app//org.hyperledger.besu.tests.acceptance.dsl.WaitUtils.waitFor(WaitUtils.java:31)
        at app//org.hyperledger.besu.tests.acceptance.dsl.AcceptanceTestBase.waitForBlockHeight(AcceptanceTestBase.java:180)
        at 
```

**Comment by macfarla** [comment]
another failure at a different point

https://github.com/hyperledger/besu/actions/runs/9476552414/job/26109624319

NodeSmartContractPermissioningOutOfSyncAcceptanceTest > addNodeToClusterAndVerifyNonBootNodePeerConnectionWorksAfterSync() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at java.base@21.0.3/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.3/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.perm.WaitForTrueResponse.lambda$verify$0(WaitForTrueResponse.java:34)
        at app//org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
        at java.base@21.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
