### ISSUE TITLE
flaky test - SECP256R1AcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7217]
https://github.com/hyperledger/besu/actions/runs/9481044071/job/26122976659?pr=7204

SECP256R1AcceptanceTest > transactionShouldBeSuccessful() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 5000000000000000000
     but was: 0
        at java.base@21.0.3/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.3/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.account.ExpectAccountBalance.lambda$verify$0(ExpectAccountBalance.java:50)
        at app//org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
        at java.base@21.0.3/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)

**Comment by macfarla** [comment]
fixed by #7249
