### ISSUE TITLE
eth_gasPrice ERROR Could not retrieve block 

### ISSUE THREAD

**Issue by siladu** [hyperledger/besu#7287]
While retesting #6965, which involved running a QBFT node and throwing https://github.com/MariusVanDerWijden/tx-fuzz at it. I received a new error:

```
2024-07-01 16:08:56.279+10:00 | vert.x-worker-thread-8 | ERROR | BaseJsonRpcProcessor | Error processing method: eth_gasPrice null
java.lang.IllegalStateException: Could not retrieve block #10
	at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$gasPrice$25(BlockchainQueries.java:994)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.lambda$gasPrice$26(BlockchainQueries.java:993)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at java.base/java.util.stream.Streams$RangeLongSpliterator.forEachRemaining(Streams.java:232)
	at java.base/java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:777)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at org.hyperledger.besu.ethereum.api.query.BlockchainQueries.gasPrice(BlockchainQueries.java:999)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGasPrice.calculateGasPrice(EthGasPrice.java:49)
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGasPrice.response(EthGasPrice.java:45)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)
	at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92)
	at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87)
	at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57)
	at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

This PR had main pulled in recently. Previous test was based on May 21st main, that area of code had changed around May 2nd, in https://github.com/hyperledger/besu/commit/8df6bcadddc817fd8099c1849fe25b0ca7f66e3c#diff-2ef41086175ba1eea041526cfd1d92a80688eeeb8e4e1f17566b2f3d65ed7cae

Still trying to recreate it consistently.

**Comment by non-fungible-nelson** [comment]
@matthew1001 flagging this for you

**Comment by matthew1001** [comment]
Could this be similar to the issues fixed in https://github.com/hyperledger/besu/pull/6143 and https://github.com/hyperledger/besu/pull/6345?

Those stemmed from issues around `chainHead` being updated before blockchain storage had been committed. `DefaultBlockchain.appendBlockHelper(...)` updates the `chainHead` before committing the stored block to the DB. This means that any non-synchronized method on `DefaultBlockchain` (of which `DefaultBlockchain.getBlockHashByNumber(...)` is one) chain head could be new but storage could be yet to update.

If you look at `BlockchainQueries.gasPrice(...)` it calls `blockchain.getChainHeadHeader()` which gets the new chain head via an unsynchronized call to `DefaultBlockchain.getChainHeadHash(...)`. It then calls `blockchain.getBlockByNumber(...)` which ends up at the un-synchronized `blockchainStorage.getBlockHash(...)`. There's a timing window therefore where chain head has been updated but storage hasn't been committed.
