### ISSUE TITLE
OpenTelemetryAcceptanceTest > traceReporting() FAILED

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7529]
https://github.com/hyperledger/besu/actions/runs/10588842146/job/29342019497?pr=7516
```
OpenTelemetryAcceptanceTest > traceReporting() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: SPAN_KIND_INTERNAL
     but was: SPAN_KIND_SERVER
        at java.base@21.0.4/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base@21.0.4/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at app//org.hyperledger.besu.tests.acceptance.OpenTelemetryAcceptanceTest.lambda$traceReporting$1(OpenTelemetryAcceptanceTest.java:192)
```

**Comment by pr9t** [comment]
Hey, I am interested in this issue. Please assign this to me.

**Comment by jflo** [comment]
Assigned! please let me know if you have any issues.

**Comment by macfarla** [comment]
@pr9t I don't know if this test has been flaky lately? Maybe it isn't a problem any more - I think don't spend too long looking at it
