### ISSUE TITLE
java.util.NoSuchElementException: No value present, processing method: `eth_getBlockReceipts` 

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#7635]
### Description

It seems that something that could be assent is not handled the right way

```
2024-09-18 14:50:19.794	2024-09-18 12:50:19.788+00:00 | vert.x-worker-thread-0 | ERROR | BaseJsonRpcProcessor | Error processing method: eth_getBlockReceipts ["0x59ede5a197a89592387ba9a5f491692b66769be0a2ffffc88cbbe22f6af9a6b9"]
2024-09-18 14:50:19.794	java.util.NoSuchElementException: No value present
2024-09-18 14:50:19.794		at java.base/java.util.Optional.get(Optional.java:143) ~[?:?]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetBlockReceipts.lambda$getBlockReceiptsResult$0(EthGetBlockReceipts.java:98) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
2024-09-18 14:50:19.794		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
2024-09-18 14:50:19.794		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
2024-09-18 14:50:19.794		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
2024-09-18 14:50:19.794		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
2024-09-18 14:50:19.794		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
2024-09-18 14:50:19.794		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetBlockReceipts.lambda$getBlockReceiptsResult$1(EthGetBlockReceipts.java:99) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetBlockReceipts.getBlockReceiptsResult(EthGetBlockReceipts.java:95) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthGetBlockReceipts.resultByBlockHash(EthGetBlockReceipts.java:69) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterOrBlockHashMethod.handleParamTypes(AbstractBlockParameterOrBlockHashMethod.java:143) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterOrBlockHashMethod.response(AbstractBlockParameterOrBlockHashMethod.java:151) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:44) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:54) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.handlers.AbstractJsonRpcExecutor.executeRequest(AbstractJsonRpcExecutor.java:87) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.handlers.JsonRpcObjectExecutor.execute(JsonRpcObjectExecutor.java:57) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:57) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
2024-09-18 14:50:19.794		at org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$2(JsonRpcExecutorHandler.java:54) ~[besu-api-24.9-delivery32.jar:24.9-delivery32]
2024-09-18 14:50:19.794		at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.5.9.jar:4.5.9]
2024-09-18 14:50:19.794		at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:191) ~[vertx-core-4.5.9.jar:4.5.9]
2024-09-18 14:50:19.794		at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279) ~[vertx-core-4.5.9.jar:4.5.9]
2024-09-18 14:50:19.794		at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210) ~[vertx-core-4.5.9.jar:4.5.9]
2024-09-18 14:50:19.795		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
2024-09-18 14:50:19.795		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
2024-09-18 14:50:19.795		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.112.Final.jar:4.1.112.Final]
2024-09-18 14:50:19.795		at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by pr9t** [comment]
Hey, I am interested in this issue. Please assign this to me.

**Comment by fab-10** [comment]
assigned
