### ISSUE TITLE
Peers sync a while and would stop the connection

### ISSUE THREAD

**Issue by davidpang731** [hyperledger/besu#7865]
Hi all, I have a question about peers and sync. Here is the background.

Version: 21.10.0 official image, hyperledger/besu:21.10.0
Nodes: a FAST node and a FULL node. FAST and FULL means the sync-mode value.
Config: 2 nodes use the same static-nodes-file / genesis.json, but use different the data path and sync-mode
Machine: AWS i3en.3xlarge

The problem is that only FULL node could keep the successful peer sync, and FAST node could only sync for a while(maybe 20 minutes). After about 20 minutes, the FAST node would have no peers. Even I update the besu version to 24.10.0 and still got the same result. But if I restart the FAST node, it could sync 20 minutes again.

Could anybody help me to solve this problem?  And I would thank a million.

**Comment by zhengfengpang** [comment]
Here are some important logs about FAST node.

wyzth-besu  | 2024-11-06 07:36:13.831+00:00 | EthScheduler-Timer-0 | INFO  | AbstractRetryingPeerTask | No peers available, waiting for peers: 0
wyzth-besu  | 2024-11-06 07:36:13.831+00:00 | EthScheduler-Timer-0 | DEBUG | WaitForPeerTask | Waiting for new peer connection. 0 peers currently connected.
wyzth-besu  | 2024-11-06 07:36:13.829+00:00 | EthScheduler-Services-12 (downloadHeaders) | DEBUG | Pipeline | Unhandled exception in pipeline. Aborting.
wyzth-besu  | java.lang.RuntimeException: Async operation failed. org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
wyzth-besu  | 	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.outputNextCompletedTask(AsyncOperationProcessor.java:86)
wyzth-besu  | 	at org.hyperledger.besu.services.pipeline.AsyncOperationProcessor.processNextInput(AsyncOperationProcessor.java:64)
wyzth-besu  | 	at org.hyperledger.besu.services.pipeline.ProcessingStage.run(ProcessingStage.java:38)
wyzth-besu  | 	at org.hyperledger.besu.services.pipeline.Pipeline.lambda$runWithErrorHandling$3(Pipeline.java:152)
wyzth-besu  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
wyzth-besu  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
wyzth-besu  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
wyzth-besu  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
wyzth-besu  | 	at java.base/java.lang.Thread.run(Unknown Source)
wyzth-besu  | Caused by: java.util.concurrent.ExecutionException: org.hyperledger.besu.ethereum.eth.manager.exceptions.MaxRetriesReachedException: Task failed: MAX_RETRIES_REACHED
wyzth-besu  | 	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
wyzth-besu  | 	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)

**Comment by zhengfengpang** [comment]
wyzth-besu  | 2024-11-06 07:36:13.832+00:00 | EthScheduler-Services-10 (downloadBodies) | DEBUG | PipelineChainDownloader | Chain download failed. Restarting after short delay.

**Comment by zhengfengpang** [comment]
Wait.. It has similar issues in the KNOWN_ISSUES.md, but this does not show "block checksum mismatch".

## Fast sync when running Besu on cloud providers  

A known [RocksDB issue](https://github.com/facebook/rocksdb/issues/6435) causes fast sync to fail 
when running Besu on certain cloud providers. The following error is displayed repeatedly: 

```
...
EthScheduler-Services-1 (importBlock) | ERROR | PipelineChainDownloader | Chain download failed. Restarting after short delay.
java.util.concurrent.CompletionException: org.hyperledger.besu.plugin.services.exception.StorageException: org.rocksdb.RocksDBException: block checksum mismatch:
....
```

This behaviour has been seen on AWS and Digital Ocean. 

Workaround -> On AWS, a full restart of the AWS VM is required to restart the fast sync. 

Fast sync is not currently supported on Digital Ocean. We are investigating options to 
[add support for fast sync on Digital Ocean](https://github.com/hyperledger/besu/issues/591).

**Comment by siladu** [comment]
Hi @zhengfengpang FAST sync will soon be deprecated. Can you confirm if you're using this for a public or private network, e.g. QBFT?

If QBFT, then you could try it's successor sync-mode=SNAP but you will also need to use this flag: `--Xsnapsync-bft-enabled` - some comments about it here: https://besu.hyperledger.org/private-networks/how-to/configure/consensus/qbft 
and feel free to ask questions in the #besu-enterprise discord channel
