### ISSUE TITLE
IllegalArgumentException: Attempt to create a discovery endpoint for an enode with discovery disabled.

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#7887]
```
{"@timestamp":"2024-11-16T04:52:16,378","level":"ERROR","thread":"vert.x-virtual-thread-16139","class":"ContextImpl","message":"Unhandled exception","throwable":" java.lang.IllegalArgumentException: Attempt to create a discovery endpoint for an enode with discovery disabled.
at org.hyperledger.besu.ethereum.p2p.discovery.Endpoint.lambda$fromEnode$1(Endpoint.java:57)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.hyperledger.besu.ethereum.p2p.discovery.Endpoint.fromEnode(Endpoint.java:55)
at org.hyperledger.besu.ethereum.p2p.discovery.DiscoveryPeer.fromEnode(DiscoveryPeer.java:52)
at org.hyperledger.besu.ethereum.p2p.network.DefaultP2PNetwork.lambda$createDaemonListener$6(DefaultP2PNetwork.java:374)
at org.hyperledger.besu.ethereum.p2p.discovery.dns.DNSDaemon.lambda$refreshENRRecords$0(DNSDaemon.java:104)
at java.base/java.util.Optional.ifPresent(Optional.java:178)
at org.hyperledger.besu.ethereum.p2p.discovery.dns.DNSDaemon.refreshENRRecords(DNSDaemon.java:104)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1051)
at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1027)
at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:328)
at io.vertx.core.impl.ContextImpl.lambda$emit$5(ContextImpl.java:335)
at io.vertx.core.impl.WorkerExecutor.lambda$execute$0(WorkerExecutor.java:68)
at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
at io.vertx.core.impl.ThreadPerTaskExecutorService.lambda$execute$0(ThreadPerTaskExecutorService.java:82)
at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)\n"}
```

**Comment by fab-10** [comment]
low priority, it happens seldomly and there is no evident impact
