### ISSUE TITLE
Experimental `--Xchain-pruning-enabled=true` doesn't work with documented QBFT defaults

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu#7963]
When a Bonsai QBFT node with `--Xchain-pruning-enabled=true` is stopped and restarted, it errors with:

```
2024-11-29 15:26:30.120+00:00 | main | ERROR | Runner | unable to start main loop
com.google.common.util.concurrent.UncheckedExecutionException: java.util.NoSuchElementException: Supplied block was on a orphaned chain, unable to generate VoteTally.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2085)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4017)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4898)
        at org.hyperledger.besu.consensus.common.validator.blockbased.VoteTallyCache.getVoteTallyAfterBlock(VoteTallyCache.java:76)
        at org.hyperledger.besu.consensus.common.validator.blockbased.BlockValidatorProvider.getValidatorsAfterBlock(BlockValidatorProvider.java:97)
        at org.hyperledger.besu.consensus.qbft.validator.ForkingValidatorProvider.getValidatorsAfterBlock(ForkingValidatorProvider.java:66)
        at org.hyperledger.besu.consensus.qbft.validator.ForkingValidatorProvider.getValidatorsAtHead(ForkingValidatorProvider.java:60)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BftFinalState.getValidators(BftFinalState.java:93)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BftFinalState.isLocalNodeValidator(BftFinalState.java:130)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftBlockHeightManagerFactory.create(QbftBlockHeightManagerFactory.java:69)
        at org.hyperledger.besu.consensus.qbft.statemachine.QbftController.createNewHeightManager(QbftController.java:118)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.startNewHeightManager(BaseBftController.java:210)
        at org.hyperledger.besu.consensus.common.bft.statemachine.BaseBftController.start(BaseBftController.java:79)
        at org.hyperledger.besu.consensus.common.bft.blockcreation.BftMiningCoordinator.start(BftMiningCoordinator.java:101)
        at org.hyperledger.besu.controller.QbftBesuControllerBuilder$1.onInitialSyncCompleted(QbftBesuControllerBuilder.java:323)

```

### Steps to Reproduce
1. Create 4-node QBFT chain
   - I used a mix of FOREST and BONSAI nodes, all with `FULL` sync mode
2. Configure one of the BONSAI nodes to have `--Xchain-pruning-enabled`
3. Start the chain (2s block period) and leave it for long enough to produce `7200` blocks (the min default for pruning)
4. At e.g. `10k` blocks, stop all the nodes
5. Restart all the nodes
6. Nodes 1-3 start producing blocks again. Node 4 errors with above stack trace.

### Version
`24.11-develop-5596cbd`

**Comment by matthew1001** [comment]
It looks like this is due to the default `epochlength` in the docs being set to `30000` blocks, where pruning only retains the previous `7200` blocks. So changing config does fix the issue, but I think the flag should check if `epochlength > --Xchain-pruning-blocks-retained` and fail validation if it does. I'll leave this issue open and will maybe find time to fix it shortly.
