### ISSUE TITLE
Flaky test - CliqueProposeRpcAcceptanceTest

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7973]
example failure https://github.com/hyperledger/besu/actions/runs/12131035525/job/33822468361

```
CliqueProposeRpcAcceptanceTest > shouldNotAddValidatorWhenInsufficientVotes() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      1
    to be greater than or equal to:
      2
        at org.hyperledger.besu.tests.acceptance.dsl.condition.blockchain.ExpectBlockNumberAbove.lambda$verify$0(ExpectBlockNumberAbove.java:46)
        at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
        at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by macfarla** [comment]
another one https://github.com/hyperledger/besu/actions/runs/12149639539/job/33880752770?pr=7979

**Comment by macfarla** [comment]
should be fixed by #7993

**Comment by macfarla** [comment]
another one https://github.com/hyperledger/besu/actions/runs/12227197580/job/34103578101

**Comment by macfarla** [comment]
another one https://github.com/hyperledger/besu/actions/runs/12281573767/job/34270784699?pr=8018

**Comment by macfarla** [comment]
another one https://github.com/hyperledger/besu/actions/runs/12343809466/job/34445457215
different method though
CliqueProposeRpcAcceptanceTest > shouldAddValidators() FAILED

**Comment by macfarla** [comment]
should be fixed by #8226

**Comment by macfarla** [comment]
still flaky eg https://github.com/hyperledger/besu/actions/runs/13127634638/job/36626897888?pr=8236

```
CliqueProposeRpcAcceptanceTest > shouldAddValidators() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting actual:
      [0xedb95f16822b1e7b474fdeb2d5ddf6fdf2df7c64,
        0xf74e7ed4a7664dc85ad22fb423e509cea4f7d4bc]
    to contain exactly (and in same order):
      [0xedb95f16822b1e7b474fdeb2d5ddf6fdf2df7c64,
        0xf74e7ed4a7664dc85ad22fb423e509cea4f7d4bc,
        0xf794f22f9169600f5962d1f9dfe32ec68f4[207](https://github.com/hyperledger/besu/actions/runs/13127634638/job/36626897888?pr=8236#step:14:208)b5]
    but could not find the following elements:
      [0xf794f22f9169600f5962d1f9dfe32ec68f4207b5]
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.clique.ExpectValidators.lambda$verify$0(ExpectValidators.java:39)
        at app//org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
        at java.base@21.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.6/java.lang.Thread.run(Thread.java:1583)
```

**Comment by fab-10** [comment]
PR https://github.com/hyperledger/besu/pull/8324 to try to re-enable again after https://github.com/hyperledger/besu/pull/8306
