### ISSUE TITLE
Flaky CliqueProposeRpcAcceptanceTest

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#7992]
This test is flaky and so makes the CI less effective and time consuming
```
CliqueProposeRpcAcceptanceTest > shouldAddValidators() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting actual:
      [0x636ff1b9193e3e7d8d0e7969ff42797c4364b078,
        0xeca06bf15c8ec68dd376c31f5c8fc4a15b732e21]
    to contain exactly (and in same order):
      [0x636ff1b9193e3e7d8d0e7969ff42797c4364b078,
        0x8a7bb12189589fd26630d5c7d56beef840362cde,
        0xeca06bf15c8ec68dd376c31f5c8fc4a15b732e21]
    but could not find the following elements:
      [0x8a7bb12189589fd26630d5c7d56beef840362cde]
        at app//org.hyperledger.besu.tests.acceptance.dsl.condition.clique.ExpectValidators.lambda$verify$0(ExpectValidators.java:39)
        at app//org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
        at app//org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
        at java.base@21.0.5/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)
```

**Comment by macfarla** [comment]
should be fixed by #7993
