### ISSUE TITLE
state overrides - nonce should allow hex

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#7998]
It looks to me from those logs like the user has supplied a nonce as a hex value, and besu is trying to deserialize it to a long probably expecting it to be a decimal/int

```
2024-12-08 23:40:06.987+00:00 | vert.x-worker-thread-6 | ERROR | BaseJsonRpcProcessor | Error processing method: eth_call [{"from":"0x148c930352929bc4676214a6333ff3d60c14f3da","to":"0xb4ffef15daf4c02787bc533
2580b838ce39805f5","gas":"0x317ff4","data":"0x70a08231000000000000000000000000148c930352929bc4676214a6333ff3d60c14f3da"},"0xc77281",{"0x148c930352929bc4676214a6333ff3d60c14f3da":{"nonce":"0x9e","balance":"0x
215d7f2a0e82433","movePrecompileToAddress":null},"0x28f6899ff643261ca9766ddc251b359a2d00b945":{"stateDiff":{"0x4c3248b57289b773fb4b4d65000ea6e7586ec5f43b9368c3f5fbe242405ae278":"0x6774858067562e930000008ac72
30489e800000000000374922507579f36ea21","0x74f7ea035dfa10f304cf0b8e7e5d9c0f09e863cd8d54cd9bb93157d81cbf10aa":"0x000000000000000000000000000000000000000000000374922507579f36ea21","0xa8414727a6198ba40a2f5e89741
3cff87745aada8834a9dec6b30698cdd798eb":"0xa1ad504367562e9300000000000000000000000000004a6e6ce87410aa4b5006","0xbb1402ab158438f86c9f2b558da42f68d1d0ec92437cd2f7f075dfb8afecb02c":"0x000000000000000000001d528b6
4b92455e7410000000374922507579f36ea21"},"movePrecompileToAddress":null},"0x2f9bb73a8e98793e26cb2f6c4ad037bdf1c6b269":{"stateDiff":{"0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892b9f":"0x0000
0000000984c5005034e416ff086d0000000003563d3452ef16b32ef604b8","0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892ba0":"0x0000000000189c384b74901c987f0e3900000000036721ecedf5f2e10ab2412f","0x1fd8
4a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892ba1":"0x00000000000000000000020067562e9300000000002c6f7077d2986d050fe1c7","0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892ba6":"0x0000
0000000000000000000000000000000000000000000000120a58a469bd3a"},"movePrecompileToAddress":null},"0xb4ffef15daf4c02787bc5332580b838ce39805f5":{"stateDiff":{"0x00000000000000000000000000000000000000000000000000
00000000000036":"0x00000000000000000000000000000000000000000000023925601eac764778be","0x6ae29f6c72aa6fa7308c28d7d43c83524fa8c6631a476f705e12ff16dab745cb":"0x0000000003563d3452ef16b32ef604b8000000000000000001
c02dd25ac765a4","0xcaff7ca3c07ca5c9cde048b62c7cfae172a46c9085257f8e8a490f3662a5eb90":"0x0000000003563d3452ef16b32ef604b800000000000000000000000000000000","0xcbad9e80aa2f40218b77a8608899af04d15bd48f0c229d9c22
c9f0955dadc9da":"0x00000000000000000000000000000000000000000000000001ced6f2ea95bc58"},"movePrecompileToAddress":null},"0xe5d7c2a44ffddf6b295a15c148167daaaf5cf34f":{"balance":"0x43537bcbb01f0e039f2","stateDif
f":{"0xb0c6eca2f0dc82fff04395ff787d1ab4c55a8f88b9a85ba295da8a5e0e89f940":"0x0000000000000000000000000000000000000000000000ee0581bf089e16c06f"},"movePrecompileToAddress":null}},{"time":"0x67562e93"}]         
org.hyperledger.besu.ethereum.api.jsonrpc.internal.exception.InvalidJsonRpcRequestException: Invalid account overrides parameter (index 2)  
[9:53](https://consensys.slack.com/archives/C03957X9XKP/p1733702034988039?thread_ts=1733701966.061549&cid=C03957X9XKP)
Caused by: org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter$JsonRpcParameterException: Invalid json rpc parameter at index 2. Supplied value was: '{0x148c930352929bc4676214a6333
ff3d60c14f3da={nonce=0x9e, balance=0x215d7f2a0e82433, movePrecompileToAddress=null}, 0x28f6899ff643261ca9766ddc251b359a2d00b945={stateDiff={0x4c3248b57289b773fb4b4d65000ea6e7586ec5f43b9368c3f5fbe242405ae278=
0x6774858067562e930000008ac7230489e800000000000374922507579f36ea21, 0x74f7ea035dfa10f304cf0b8e7e5d9c0f09e863cd8d54cd9bb93157d81cbf10aa=0x000000000000000000000000000000000000000000000374922507579f36ea21, 0xa8
414727a6198ba40a2f5e897413cff87745aada8834a9dec6b30698cdd798eb=0xa1ad504367562e9300000000000000000000000000004a6e6ce87410aa4b5006, 0xbb1402ab158438f86c9f2b558da42f68d1d0ec92437cd2f7f075dfb8afecb02c=0x0000000
00000000000001d528b64b92455e7410000000374922507579f36ea21}, movePrecompileToAddress=null}, 0x2f9bb73a8e98793e26cb2f6c4ad037bdf1c6b269={stateDiff={0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e8
92b9f=0x00000000000984c5005034e416ff086d0000000003563d3452ef16b32ef604b8, 0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892ba0=0x0000000000189c384b74901c987f0e3900000000036721ecedf5f2e10ab2412f
, 0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892ba1=0x00000000000000000000020067562e9300000000002c6f7077d2986d050fe1c7, 0x1fd84a755d3a9c78ff8b3bd554246082782d06efd21cdf78c58b0ad75e892ba6=0x0
0000000000000000000000000000000000000000000000000120a58a469bd3a}, movePrecompileToAddress=null}, 0xb4ffef15daf4c02787bc5332580b838ce39805f5={stateDiff={0x00000000000000000000000000000000000000000000000000000
00000000036=0x00000000000000000000000000000000000000000000023925601eac764778be, 0x6ae29f6c72aa6fa7308c28d7d43c83524fa8c6631a476f705e12ff16dab745cb=0x0000000003563d3452ef16b32ef604b8000000000000000001c02dd25a
c765a4, 0xcaff7ca3c07ca5c9cde048b62c7cfae172a46c9085257f8e8a490f3662a5eb90=0x0000000003563d3452ef16b32ef604b800000000000000000000000000000000, 0xcbad9e80aa2f40218b77a8608899af04d15bd48f0c229d9c22c9f0955dadc9
da=0x00000000000000000000000000000000000000000000000001ced6f2ea95bc58}, movePrecompileToAddress=null}, 0xe5d7c2a44ffddf6b295a15c148167daaaf5cf34f={balance=0x43537bcbb01f0e039f2, stateDiff={0xb0c6eca2f0dc82ff
f04395ff787d1ab4c55a8f88b9a85ba295da8a5e0e89f940=0x0000000000000000000000000000000000000000000000ee0581bf089e16c06f}, movePrecompileToAddress=null}}' of type: 'java.util.LinkedHashMap' - expected type: 'org.
hyperledger.besu.ethereum.util.AccountOverrideMap'                                                                                                                                                             
    at org.hyperledger.besu.ethereum.api.jsonrpc.internal.parameters.JsonRpcParameter.optional(JsonRpcParameter.java:78) 
[9:54](https://consensys.slack.com/archives/C03957X9XKP/p1733702044994839?thread_ts=1733701966.061549&cid=C03957X9XKP)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "0x9e": not a valid `java.lang.Long` value                                 
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 56] (through reference chain: org.hyperledger.besu.ethereum.util.AccountOverrideMap["0x148c930352929bc4676214
a6333ff3d60c14f3da"]->org.hyperledger.besu.ethereum.util.AccountOverride$Builder["nonce"])                                                                                                                     
    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)  
```

**Comment by Gabriel-Trintinalia** [comment]
@macfarla  Use `UnsignedLongParameter` instead of Long, it will parse both correctly :)

**Comment by macfarla** [comment]
see #5788
