### ISSUE TITLE
Simulation - Implement movePrecompileToAddress for state override

### ISSUE THREAD

**Issue by Gabriel-Trintinalia** [hyperledger/besu#8023]
### Error Description:

When using the `state override` feature with the `eth_call` method in Besu, an error occurs due to the unrecognized `movePrecompileToAddress` field. This results in an `InvalidJsonRpcRequestException`.

#### Error Details:
```
org.hyperledger.besu.ethereum.api.jsonrpc.internal.exception.InvalidJsonRpcRequestException: Invalid account overrides parameter (index 2)
    at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthCall.getAddressAccountOverrideMap(EthCall.java:125)
    at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.EthCall.resultByBlockHeader(EthCall.java:89)
```

#### Suggested Solution:
Modify the `getAddressAccountOverrideMap` method to ignore unknown fields like `movePrecompileToAddress` until an implementation is available.

For reference, the Geth implementation for handling the `movePrecompileToAddress` field [here](https://github.com/ethereum/go-ethereum/blob/293a300d64be3d9a1c2cc92c26fcff4089deadcd/internal/ethapi/api.go#L665-L676).

**Comment by Gabriel-Trintinalia** [comment]
More on movePrecompileToAddress https://mirror.xyz/killaridev.eth/NXR9v4r8b4SWl-hbqJqRQyIAcE4GACobzMObREvL0fo
