### ISSUE TITLE
DebugOperationTracer throws an IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by brianmcgee** [hyperledger/besu#915]
### Description

Calling `trace_block` for block [#4063089](https://ropsten.etherscan.io/block/4063089) in Ropsten causes the DebugOperationTracer to throw an IndexOutOfBoundsException.

### Steps to Reproduce (Bug)
1. Ensure you have synced Ropsten until block #4063089
2. Execute the following call:

```
curl --location --request POST 'localhost:8545' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"trace_block",
	"params":[
		"0x3DFF71"
	],
	"id":1
}'
```

**Expected behavior:** A valid block trace

**Actual behavior:** 

```
WARNING: All illegal access operations will be denied in a future release
2020-05-13 07:44:11.290+01:00 | vert.x-worker-thread-0 | ERROR | JsonRpcHttpService | Error processing JSON-RPC requestBody
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
	at org.hyperledger.besu.ethereum.vm.DebugOperationTracer.tracePrecompileCall(DebugOperationTracer.java:111) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.executePrecompile(MainnetMessageCallProcessor.java:134) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.start(MainnetMessageCallProcessor.java:61) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:167) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:361) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:306) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:47) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.mainnet.TransactionProcessor.processTransaction(TransactionProcessor.java:169) ~[core-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.lambda$prepareReplayAction$0(BlockTracer.java:62) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$0(BlockReplay.java:60) ~[api-1.4.4.jar:1.4.4]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$1(BlockReplay.java:66) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.performActionWithBlock(BlockReplay.java:150) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.block(BlockReplay.java:52) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.trace(BlockTracer.java:47) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.traceBlock(TraceBlock.java:86) ~[api-1.4.4.jar:1.4.4]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceBlock.resultByBlockNumber(TraceBlock.java:73) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:64) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.response(AbstractBlockParameterMethod.java:78) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.process(JsonRpcHttpService.java:589) ~[api-1.4.4.jar:1.4.4]
	at org.hyperledger.besu.ethereum.api.jsonrpc.JsonRpcHttpService.lambda$handleJsonSingleRequest$9(JsonRpcHttpService.java:463) ~[api-1.4.4.jar:1.4.4]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316) ~[vertx-core-3.8.5.jar:3.8.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Frequency:** 100% of the time

### Versions (Add all that apply)
* Software version: 1.4.4
* Java version: 14

**Comment by shemnon** [comment]
Ohh... that's rich.  Someone *directly* called a precompiled contract: https://ropsten.etherscan.io/tx/0xcf8e0fedb6c87ec3317b07d3713f53d398fbac5fbcbc43f7a7911148dc145316

**Comment by brianmcgee** [comment]
Am I right in thinking that this bug is happening because the `tracePrecompileCall` assumes that a pre-compiled contract will only be called as a message that was spawned from the root of the transaction? 

And since pre-compiled calls do not generate their own `MessageCall` the gas associated with it's execution gets attributed to the parent, but in this instance there is none?

Assuming this is correct, the fix should then be something simple:

```java
  @Override
  public void tracePrecompileCall(
      final MessageFrame frame, final Gas gasRequirement, final Bytes output) {
    if(!traceFrames.isEmpty()) {
      traceFrames.get(traceFrames.size() - 1).setPrecompiledGasCost(Optional.of(gasRequirement));
    }
  }
```

Does the gas requirement for the pre-compiled call still need accounted for, or is that taken care of already in this instance?

**Comment by abdelhamidbakhta** [comment]
Actually if i run the same request i get a valid trace block response:
```json
{
  "jsonrpc": "2.0",
  "id": 415,
  "result": [
    {
      "action": {
        "author": "0x1bc1ee741b3d2047543f5971ad75340734c14413",
        "rewardType": "block",
        "value": "0x29a2241af62c0000"
      },
      "blockHash": "0x4f5e3472b558d9ee4f440f37895552340b1358c658630b1d0c184e52b8715349",
      "blockNumber": 4063089,
      "result": null,
      "subtraces": 0,
      "traceAddress": [],
      "transactionHash": null,
      "transactionPosition": null,
      "type": "reward"
    }
  ]
}
```

**Comment by abdelhamidbakhta** [comment]
> Am I right in thinking that this bug is happening because the `tracePrecompileCall` assumes that a pre-compiled contract will only be called as a message that was spawned from the root of the transaction?
> 
> And since pre-compiled calls do not generate their own `MessageCall` the gas associated with it's execution gets attributed to the parent, but in this instance there is none?
> 
> Assuming this is correct, the fix should then be something simple:
> 
> ```java
>   @Override
>   public void tracePrecompileCall(
>       final MessageFrame frame, final Gas gasRequirement, final Bytes output) {
>     if(!traceFrames.isEmpty()) {
>       traceFrames.get(traceFrames.size() - 1).setPrecompiledGasCost(Optional.of(gasRequirement));
>     }
>   }
> ```
> 

Yes you are totally right.

**Comment by abdelhamidbakhta** [comment]
> Does the gas requirement for the pre-compiled call still need accounted for, or is that taken care of already in this instance?

No, i don't think the pre-compiled call still need to be accounted for.
