### ISSUE TITLE
Build fails, java.lang.UnsatisfiedLinkError at BesuEventsImplTest

### ISSUE THREAD

**Issue by Tectract** [hyperledger/besu#991]
### Description
Build failing on linux machine

### Acceptance Criteria
build bug

### Steps to Reproduce (Bug)
1. gradlew build (fails)

**Expected behavior:** [What you expect to happen]
build success

**Actual behavior:** [What actually happens]

    > Task :besu:test

    org.hyperledger.besu.services.BesuEventsImplTest > additionWithoutSubscriptionsCompletes FAILED
    java.lang.UnsatisfiedLinkError at BesuEventsImplTest.java:470

    org.hyperledger.besu.services.BesuEventsImplTest > newBlockEventUselessUnsubscribesCompletes FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > logEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > syncStatusEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > syncStatusEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > transactionDroppedEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > reorgWithoutSubscriptionsCompletes FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > addedBlockEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > transactionAddedEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > newBlockEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > logEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > addedBlockEventUselessUnsubscribesCompletes FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > reorgedBlockEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > newBlockEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > addedBlockEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > reorgedBlockEventUselessUnsubscribesCompletes FAILED
    java.lang.NoClassDefFoundError at NativeConstructorAccessorImpl.java:-2

    org.hyperledger.besu.services.BesuEventsImplTest > transactionAddedEventUselessUnsubscribesCompletes FAILED
    java.lang.NoClassDefFoundError at null:-1

    org.hyperledger.besu.services.BesuEventsImplTest > transactionAddedEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at null:-1

    org.hyperledger.besu.services.BesuEventsImplTest > reorgedBlockEventDoesNotFireAfterUnsubscribe FAILED
    java.lang.NoClassDefFoundError at null:-1

    org.hyperledger.besu.services.BesuEventsImplTest > propagationWithoutSubscriptionsCompletes FAILED
    java.lang.NoClassDefFoundError at null:-1

    org.hyperledger.besu.services.BesuEventsImplTest > transactionDroppedEventFiresAfterSubscribe FAILED
    java.lang.NoClassDefFoundError at null:-1

    431 tests completed, 21 failed

**Frequency:** [What percentage of the time does it occur?]
(every time)

### Versions (Add all that apply)
* Software version: [`besu --version`]

(besu not installed yet)

* Java version: [`java -version`]

openjdk 13.0.3 2020-04-14
OpenJDK Runtime Environment Zulu13.31+11-CA (build 13.0.3+3-MTS)
OpenJDK 64-Bit Server VM Zulu13.31+11-CA (build 13.0.3+3-MTS, mixed mode, sharing)

* OS Name & Version: [`cat /etc/*release`]

Linux Mint 17 Qiana

* Kernel Version: [`uname -a`]

based on Ubuntu 14.04

(standalone machine)

### Additional Information

Looking at some weird java lib failures here, on a new machine install. Not sure how to debug / troubleshoot this one. 

Here's some output from the logs on the first failed test:

java.lang.NoClassDefFoundError: Could not initialize class org.hyperledger.besu.services.BesuEventsImplTest
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:77)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:83)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by atoulme** [comment]
You might want to attach the output of the first failed test:
```org.hyperledger.besu.services.BesuEventsImplTest > additionWithoutSubscriptionsCompletes FAILED
java.lang.UnsatisfiedLinkError at BesuEventsImplTest.java:470```

**Comment by Tectract** [comment]
Here's the first two.

I think this issue has something to do with java versions / libs. I'm not seeing it on my main servers...


org.hyperledger.besu.services.BesuEventsImplTest > additionWithoutSubscriptionsCompletes FAILED
    java.lang.UnsatisfiedLinkError: 'int org.hyperledger.besu.nativelib.secp256k1.LibSecp256k1.secp256k1_ecdsa_sign_recoverable(com.sun.jna.ptr.PointerByReference, org.hyperledger.besu.nativelib.secp256k1.LibSecp256k1$secp256k1_ecdsa_recoverable_signature, byte[], byte[], org.hyperledger.besu.nativelib.secp256k1.LibSecp256k1$secp256k1_nonce_function, com.sun.jna.Pointer)'
        at org.hyperledger.besu.nativelib.secp256k1.LibSecp256k1.secp256k1_ecdsa_sign_recoverable(Native Method)
        at org.hyperledger.besu.crypto.SECP256K1.signNative(SECP256K1.java:347)
        at org.hyperledger.besu.crypto.SECP256K1.sign(SECP256K1.java:116)
        at org.hyperledger.besu.ethereum.core.Transaction$Builder.computeSignature(Transaction.java:729)
        at org.hyperledger.besu.ethereum.core.Transaction$Builder.signAndBuild(Transaction.java:720)
        at org.hyperledger.besu.ethereum.core.TransactionTestFixture.createTransaction(TransactionTestFixture.java:54)
        at org.hyperledger.besu.services.BesuEventsImplTest.createTransaction(BesuEventsImplTest.java:470)
        at org.hyperledger.besu.services.BesuEventsImplTest.<clinit>(BesuEventsImplTest.java:80)

org.hyperledger.besu.services.BesuEventsImplTest > newBlockEventUselessUnsubscribesCompletes FAILED
    java.lang.NoClassDefFoundError: Could not initialize class org.hyperledger.besu.services.BesuEventsImplTest
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
        at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:77)
        at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:83)
        at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
        at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by RatanRSur** [comment]
What's the commit hash that you see this on?

**Comment by Tectract** [comment]
* master ffa8745 Add gate for multi-tenancy + onchain privacy groups (#990)

Still thinking this one has something to do with local java libs not being sorted by gradle properly... I was having a hard time getting JDK to install properly on this machine, so I just symlinked the executable to /usr/bin/java and updated the default_java symlink in /usr/lib/jvm...

**Comment by RatanRSur** [comment]
A shot in the dark but can you try deleting your maven cache? `~/.m2/repository`

**Comment by Tectract** [comment]
That folder doesn't exist on this system, I don't use maven in my stack, right now.

**Comment by shemnon** [comment]
Looks like the native libraries from besu-native are failing to completely load.  I was under the impression that JNA would check all the symbols on load, but I guess not :(. Or, it may be an azul thing.  Let me try and repro this tomorrow.

**Comment by shemnon** [comment]
a quick fix (at the cost of speed) is to add `--Xsecp256k1-native-enabled=false` and `--Xaltbn128-native-enabled=false` on the command line.  This disables the native libraries.

**Comment by shemnon** [comment]
Also, gradle keeps it's caches in `~/.gradle/caches`

**Comment by Tectract** [comment]
> ./gradlew build --Xsecp256k1-native-enabled=false --Xaltbn128-native-enabled=false

    FAILURE: Build failed with an exception.
    * What went wrong:
    Problem configuring task :build from command line.
    > Unknown command-line option '--Xsecp256k1-native-enabled'.

Hmmmmmm :) Thanks again for your help guys. I wonder if there is some dependency that's missing (or different) on this machine but not on my other servers, now, since this is the only machine that failed to build in this way.

**Comment by vmichalik** [comment]
@Tectract hey, just revisiting some old issues. Is this one still a problem for you?

**Comment by Tectract** [comment]
lol, no. I gave up on Besu long ago. Didn't Microsoft stop supporting development on it?

**Comment by vmichalik** [comment]
Microsoft help out from time to time, but have never been a primary contributor. Lots of Besu developers are employed by ConsenSys. The Besu team and community is bigger than ever, with lots more projects to be announced being built on it in 2021. In the private network space, projects like Fnality, Alastria and others are being built on Besu, and on the Ethereum mainnet side it's a leading client in EIP1559 and the Merge (fka Eth1<>Eth2). 👍

**Comment by vmichalik** [comment]
I'm going to close this as an issue for now as we haven't seen it replicated in the past year, if that's alright. You can still reply here, or join us over at https://chat.hyperledger.org/channel/besu if you have any more questions!
